autogluon/autogluon

autogluon/task/tabular_prediction/tabular_prediction.py
autogluon/utils/tabular/ml/learner/default_learner.py
autogluon/utils/tabular/ml/models/catboost/catboost_model.py
autogluon/utils/tabular/ml/models/catboost/catboost_utils.py
autogluon/utils/tabular/ml/models/ensemble/bagged_ensemble_model.py
autogluon/utils/tabular/ml/models/ensemble/stacker_ensemble_model.py
autogluon/utils/tabular/ml/models/lgb/callbacks.py
autogluon/utils/tabular/ml/models/lgb/lgb_model.py
autogluon/utils/tabular/ml/models/tabular_nn/tabular_nn_model.py
autogluon/utils/tabular/ml/trainer/abstract_trainer.py
autogluon/utils/tabular/ml/trainer/auto_trainer.py
autogluon/utils/tabular/ml/trainer/model_presets/presets.py
autogluon/utils/tabular/ml/utils.py
autogluon/utils/tabular/utils/exceptions.py

Added time_limit functionality to AutoGluon Tabular

Added time_limit functionality to AutoGluon Tabular

---

docs/config.ini

Add G analytics tracker

---

autogluon/task/tabular_prediction/predictor.py
autogluon/utils/tabular/ml/learner/abstract_learner.py
autogluon/utils/tabular/ml/models/ensemble/weighted_ensemble_model.py
autogluon/utils/tabular/ml/models/knn/knn_model.py

Added leaderboard functionality to Tabular

Added leaderboard functionality to Tabular

---

autogluon/task/image_classification/dataset.py
autogluon/task/image_classification/image_classification.py
autogluon/task/object_detection/object_detection.py
autogluon/task/tabular_prediction/__init__.py
autogluon/task/tabular_prediction/dataset.py
autogluon/task/tabular_prediction/predictor.py
autogluon/task/tabular_prediction/tabular_prediction.py
docs/api/autogluon.task.rst
docs/index.rst
docs/install-include.rst
docs/static/application.html

- clarified install instructions
- hyperlinks for tabular docs

website improvements

---

autogluon/task/object_detection/object_detection.py

[fix #104] log variables in logging

---

docs/install-include.rst

remove mac installation for now

---

autogluon/task/tabular_prediction/tabular_prediction.py
autogluon/utils/tabular/ml/learner/abstract_learner.py
autogluon/utils/tabular/ml/trainer/model_presets/presets.py

Disable Neural Network in Tabular by Default, currently causes frequent hanging

Disable Neural Network in Tabular by Default

---

autogluon/utils/files.py

@chongruo FYI
ag.unzip return foldername or a tuple of foldernames

ag.unzip return foldername or a tuple of foldernames

---

autogluon/task/tabular_prediction/tabular_prediction.py
setup.py

Fixed defect in tabular NN caused by pynvml introduced in #94 

Fixed defect in tabular NN caused by pynvml

---

autogluon/utils/tabular/ml/learner/abstract_learner.py
autogluon/utils/tabular/ml/trainer/abstract_trainer.py

Added functionality to choose best between weighted ensembles in Tabular

Added functionality to choose best between weighted ensembles in Tabular

---

autogluon/searcher/grid_searcher.py

fix searcher argument name patch

---

autogluon/scheduler/remote/ssh_helper.py
autogluon/searcher/grid_searcher.py
autogluon/task/image_classification/__init__.py
autogluon/task/image_classification/classifier.py
autogluon/task/image_classification/image_classification.py
autogluon/utils/files.py
autogluon/utils/pil_transforms.py
docs/api/autogluon.task.rst
docs/tutorials/nas/enas_mnist.md
setup.py

I am working on a challange and expand some relevant utils for CV in this PR.
1. Add RandomCrop Transformation

CV Utils and Docs Improvements

---

autogluon/task/tabular_prediction/tabular_prediction.py
autogluon/utils/tabular/ml/learner/abstract_learner.py
autogluon/utils/tabular/ml/learner/default_learner.py
autogluon/utils/tabular/ml/models/abstract/abstract_model.py
autogluon/utils/tabular/ml/models/catboost/catboost_model.py
autogluon/utils/tabular/ml/models/ensemble/bagged_ensemble_model.py
autogluon/utils/tabular/ml/models/ensemble/greedy_weighted_ensemble_model.py
autogluon/utils/tabular/ml/models/ensemble/stacker_ensemble_model.py
autogluon/utils/tabular/ml/models/ensemble/weighted_ensemble_model.py
autogluon/utils/tabular/ml/models/knn/knn_model.py
autogluon/utils/tabular/ml/models/lgb/lgb_model.py
autogluon/utils/tabular/ml/models/rf/rf_model.py
autogluon/utils/tabular/ml/models/tabular_nn/tabular_nn_model.py
autogluon/utils/tabular/ml/trainer/abstract_trainer.py
autogluon/utils/tabular/ml/trainer/auto_trainer.py
autogluon/utils/tabular/ml/trainer/model_presets/presets_rf.py
autogluon/utils/tabular/ml/tuning/ensemble_selection.py
autogluon/utils/tabular/ml/utils.py
autogluon/utils/tabular/utils/exceptions.py
setup.py
tests/unittests/test_tabular.py

Major Additions:
- Repeated KFold Bagging
- Stacker max_models hyperparameters
- Memory Optimization / Checks
- Improved Logging, Leaderboard, Info
- Various Bug Fixes

AutoGluon Tabular Improvements

---

autogluon/task/object_detection/dataset/__init__.py
autogluon/task/object_detection/dataset/voc.py
autogluon/task/object_detection/object_detection.py
autogluon/task/object_detection/pipeline.py
examples/object_detection/benchmark.py

support more datasets (clipart, watercolor, comic, voc) for object detection.
add running scripts

Support more datasets for object detection

---

autogluon/task/object_detection/object_detection.py
docs/tutorials/object_detection/beginner.md
examples/object_detection/benchmark.py
examples/object_detection/demo.py

[fix] typo for time_limits

---

autogluon/task/tabular_prediction/tabular_prediction.py
autogluon/utils/tabular/data/label_cleaner.py
autogluon/utils/tabular/ml/models/abstract/abstract_model.py
autogluon/utils/tabular/ml/models/catboost/catboost_model.py
autogluon/utils/tabular/ml/models/ensemble/bagged_ensemble_model.py
autogluon/utils/tabular/ml/models/ensemble/greedy_weighted_ensemble_model.py
autogluon/utils/tabular/ml/models/ensemble/stacker_ensemble_model.py
autogluon/utils/tabular/ml/models/ensemble/weighted_ensemble_model.py
autogluon/utils/tabular/ml/models/knn/knn_model.py
autogluon/utils/tabular/ml/models/lgb/lgb_model.py
autogluon/utils/tabular/ml/models/rf/rf_model.py
autogluon/utils/tabular/ml/models/tabular_nn/tabular_nn_model.py
autogluon/utils/tabular/ml/trainer/abstract_trainer.py
autogluon/utils/tabular/ml/trainer/auto_trainer.py
autogluon/utils/tabular/ml/trainer/model_presets/presets.py
setup.py
tests/unittests/test_tabularHPO_bagstack.py
tests/unittests/test_tabular_bagstack.py

Major Changes:
- Added fold-level fit control to bagged models
- Optimized HPO when bagging (speedup 10-20%)
- Optimized KNN memory usage during HPO (halved peak memory usage)
- Various code cleanup / refactoring to standardize model parameters

AutoGluon Tabular HPO Optimization + Refactoring

---

autogluon/task/image_classification/dataset.py
autogluon/task/image_classification/image_classification.py
autogluon/task/image_classification/nets.py
docs/tutorials/nas/enas_mnist.md
tests/unittests/test_image_classification.py

Add Ensemble for Image Classification

---

autogluon/task/tabular_prediction/tabular_prediction.py
autogluon/utils/tabular/data/cleaner.py
autogluon/utils/tabular/ml/learner/default_learner.py
autogluon/utils/tabular/ml/tuning/ensemble_selection.py

#201 
Clarified documentation and logging on tabular class thresholding.
Disabled enable_fit_continuation.

Tabular Doc Update

---

setup.py

bump up to 0.0.4

---

docs/index.rst

Fixes https://github.com/awslabs/autogluon/issues/217

fixed front page example bug

---

autogluon/task/base/base_task.py
autogluon/task/image_classification/classifier.py
autogluon/task/image_classification/dataset.py
autogluon/task/image_classification/image_classification.py
autogluon/task/image_classification/pipeline.py
tests/unittests/test_image_classification.py

fixes https://github.com/awslabs/autogluon/issues/207

fix classifier load/save

---

autogluon/model_zoo/model_store.py
autogluon/model_zoo/model_zoo.py
autogluon/model_zoo/models/standford_dog_models.py
autogluon/task/image_classification/nets.py
tests/unittests/test_model_zoo.py

fixes https://github.com/awslabs/autogluon/issues/158

add standford dog pretrained models

---

autogluon/task/image_classification/losses.py
autogluon/utils/tabular/features/abstract_feature_generator.py
autogluon/utils/tabular/ml/learner/default_learner.py
autogluon/utils/tabular/ml/models/abstract/abstract_model.py
autogluon/utils/tabular/ml/models/lgb/lgb_model.py
autogluon/utils/tabular/ml/models/tabular_nn/tabular_nn_model.py
autogluon/utils/tabular/utils/savers/save_pkl.py

Fixes data preprocessing for certain datasets with high-cardinality categorical features. The error fixed here previously only manifested when 'proc.embed_min_categories' exceeded 'proc.max_category_levels' (see: tabular_nn/hyperparameters/parameters.py)

[WIP] Fix one-hot issue when num category levels exceeds max allowed levels

---

autogluon/utils/tabular/ml/learner/default_learner.py

Fixed defect in tabular with tuning_data specified

Fixed defect in tabular with tuning_data specified

---

autogluon/task/tabular_prediction/tabular_prediction.py

Metric is not logged in %s placeholder, added placeholder value

Metric is not logged in %s placeholder

---

autogluon/task/tabular_prediction/tabular_prediction.py
autogluon/utils/tabular/features/abstract_feature_generator.py
autogluon/utils/tabular/ml/learner/default_learner.py
autogluon/utils/tabular/ml/models/ensemble/greedy_weighted_ensemble_model.py
autogluon/utils/tabular/ml/models/ensemble/stacker_ensemble_model.py
autogluon/utils/tabular/ml/models/rf/rf_model.py
autogluon/utils/tabular/ml/trainer/abstract_trainer.py
autogluon/utils/tabular/ml/trainer/model_presets/presets.py
autogluon/utils/tabular/ml/trainer/model_presets/presets_rf.py
autogluon/utils/tabular/ml/tuning/ensemble_selection.py

- Improved tabular memory management for random forest
- Improved tabular time limit management for random forest and weighted ensemble
- Improved tabular logging clarity

Tabular Memory and Time Limit Optimization

---

README.md

Seeing a python code block without color is weird.
Since other markdown files are tutorials linked to the document website, I will only change the README.md file.

README.md - add color to code block

---

autogluon/task/tabular_prediction/tabular_prediction.py
autogluon/utils/tabular/ml/models/catboost/catboost_model.py
autogluon/utils/tabular/ml/models/ensemble/bagged_ensemble_model.py
autogluon/utils/tabular/ml/models/ensemble/stacker_ensemble_model.py
autogluon/utils/tabular/ml/models/lgb/lgb_model.py
autogluon/utils/tabular/ml/trainer/model_presets/presets.py
setup.py

Major Changes:
- Optimized CatBoost memory usage, significantly reduced OOM error chance
- Optimized CatBoost early stopping logic on large datasets
- Optimized LightGBM early stopping logic on large datasets
- Fixed defect causing logging verbosity to be ignored in stacker models
- Fixed defect in time estimation on n_repeated bagging models
- Updated pandas version requirement

Tabular Memory and Early Stopping Optimization + Bug Fixes

---

autogluon/utils/tabular/data/label_cleaner.py
autogluon/utils/tabular/ml/models/tabular_nn/tabular_nn_model.py

- For binary classification with class labels [0,1], label cleaner was wrongly converting these to class labels [True, False].
-Also address issue of NN model potentially not saving to file during epoch 0.

Fix bug in label cleaner for booleans

---

autogluon/task/tabular_prediction/tabular_prediction.py
autogluon/utils/tabular/ml/learner/abstract_learner.py
autogluon/utils/tabular/ml/learner/default_learner.py
autogluon/utils/tabular/ml/models/abstract/abstract_model.py
autogluon/utils/tabular/ml/models/catboost/catboost_model.py
autogluon/utils/tabular/ml/models/ensemble/bagged_ensemble_model.py
autogluon/utils/tabular/ml/models/ensemble/greedy_weighted_ensemble_model.py
autogluon/utils/tabular/ml/models/ensemble/stacker_ensemble_model.py
autogluon/utils/tabular/ml/models/ensemble/weighted_ensemble_model.py
autogluon/utils/tabular/ml/models/lgb/lgb_model.py
autogluon/utils/tabular/ml/models/tabular_nn/tabular_nn_model.py
autogluon/utils/tabular/ml/trainer/abstract_trainer.py
autogluon/utils/tabular/ml/trainer/auto_trainer.py
autogluon/utils/tabular/ml/trainer/model_presets/presets.py

Major Changes:
- Added stopping_metric param to TabularPrediction
- stopping_metric changed to 'log_loss' by default when eval_metric is 'roc_auc'
- Added option for str type input to TabularPrediction train_data and tuning_data parameters

Tabular Stopping Metric + File Path Input

---

README.md

Updated readme to align with website ordering of tasks

Updated readme to align with website ordering of tasks

---

setup.py

Updated AutoGluon to version 0.0.5

Updated AutoGluon version to 0.0.5

---

autogluon/task/tabular_prediction/predictor.py
autogluon/task/tabular_prediction/tabular_prediction.py

TabularPredictor now accepts file path for dataset parameters

TabularPredictor now accepts file path for dataset parameters

---

autogluon/task/text_classification/text_classification.py
docs/tutorials/text_classification/beginner.md

Added warnings to TextClassification usage

Added warnings to TextClassification usage

---

autogluon/task/tabular_prediction/tabular_prediction.py

*Issue #271 *
- changing type checking for using `isinstance` 
- indentation correction
- replacing `set` creation from `list` to directly `set` creation

Type Checking correction, indentation correction

---

autogluon/task/base/base_predictor.py
autogluon/task/base/base_task.py
autogluon/task/tabular_prediction/tabular_prediction.py

Basic pep 8 corrections:
- imports optimisation - https://www.python.org/dev/peps/pep-0008/#imports
- surround top-level function and class definitions with two blank lines - https://www.python.org/dev/peps/pep-0008/#blank-lines
Bug fix in string formating.

Basic pep 8 corrections, bug fix in string formatting. 

---

autogluon/utils/tabular/features/abstract_feature_generator.py

#277 
Fixed defect when val_list == 0 in feature generator

Fixed defect when val_list == 0 in feature generator

---

autogluon/utils/tabular/ml/learner/abstract_learner.py
autogluon/utils/tabular/ml/models/abstract/abstract_model.py
autogluon/utils/tabular/ml/models/catboost/catboost_model.py
autogluon/utils/tabular/ml/trainer/abstract_trainer.py
autogluon/utils/tabular/ml/trainer/auto_trainer.py
autogluon/utils/tabular/ml/tuning/feature_pruner.py
autogluon/utils/tabular/ml/utils.py
autogluon/utils/tabular/utils/savers/save_pd.py

- Cleaned code
- Added model param to score function
- Updated FeaturePruner to have early stopping

Tabular Minor Cleanup + Add model option to score func

---

README.md
autogluon/model_zoo/models/efficientnet.py
tests/run_all.sh

Fix CI not catching errors when failing unit tests.

---

autogluon/task/tabular_prediction/tabular_prediction.py
autogluon/utils/tabular/metrics/__init__.py

Description of changes:
Performing basic PEP8 corrections.
Completing TODO in tabular_prediction.py for creation of functions for metrics.
Type checking correction.

Creating function for getting metric from its name.

---

autogluon/utils/tabular/ml/models/tabular_nn/embednet.py

[WIP] Accelerating Tabular NN

---

autogluon/task/tabular_prediction/tabular_prediction.py
autogluon/utils/tabular/ml/learner/abstract_learner.py
autogluon/utils/tabular/ml/models/abstract/abstract_model.py
autogluon/utils/tabular/ml/models/catboost/catboost_model.py
autogluon/utils/tabular/ml/models/ensemble/bagged_ensemble_model.py
autogluon/utils/tabular/ml/models/ensemble/stacker_ensemble_model.py
autogluon/utils/tabular/ml/models/lgb/lgb_model.py
autogluon/utils/tabular/ml/models/rf/rf_model.py
autogluon/utils/tabular/ml/models/tabular_nn/tabular_nn_model.py
autogluon/utils/tabular/ml/trainer/abstract_trainer.py
autogluon/utils/tabular/ml/trainer/model_presets/presets.py
autogluon/utils/tabular/ml/trainer/model_presets/presets_distill.py

Major Changes:
- Added prototype model compression
- Added prototype model distillation

Tabular Model Compression + Distillation

---

autogluon/utils/tabular/data/label_cleaner.py
autogluon/utils/tabular/features/abstract_feature_generator.py

Basi PEP8 corrections, 
Correction of Type checking, 
Vectorization of feature creations from text,
Removing duplicate len calculation from strings.

FIX: optimizing feature creation from text

---

autogluon/utils/tabular/ml/models/lgb/lgb_model.py

#292 
Updated seed to 0 from None for LGBM to ensure reproducible behavior

Updated default seed to 0 from None for LGBM

---

autogluon/utils/tabular/ml/models/tabular_nn/embednet.py

#302
Reverts #291 until performance evaluation can be more comprehensively tested.

Revert #291

---

autogluon/scheduler/fifo.py
autogluon/utils/tabular/ml/models/abstract/abstract_model.py
autogluon/utils/tabular/ml/models/abstract/model_trial.py

Basic pep8 corrections;
Type checking fixes;
String formatting simplification with using `f-string`;
Other small fixes.

FIX: type checking, pep8

---

autogluon/model_zoo/model_zoo.py
autogluon/task/image_classification/dataset.py
autogluon/task/image_classification/image_classification.py

Basic PEP 8 corrections, 
Making code more readable,
Small fixes.

General fixes

---

setup.py

Loosened version constraint on LightGBM

Loosened version constraint on LightGBM

---

autogluon/utils/tabular/ml/models/tabular_nn/tabular_nn_dataset.py
autogluon/utils/tabular/ml/models/tabular_nn/tabular_nn_model.py

Cleaned Tabular NN code

---

autogluon/task/image_classification/dataset.py
autogluon/task/image_classification/pipeline.py
autogluon/task/image_classification/processing_params.py
autogluon/task/image_classification/utils.py

Basic PEP8 fixes.
String formatting. 

FIX: basic pep8 fixes

---

autogluon/utils/tabular/ml/models/ensemble/weighted_ensemble_model.py

Fixed child type of weighted_ensemble_model

Fixed child type of weighted_ensemble_model

---

examples/image_classification/benchmark.py

fix typos according pep8 style

---

autogluon/utils/tabular/ml/learner/abstract_learner.py
autogluon/utils/tabular/ml/models/abstract/abstract_model.py
autogluon/utils/tabular/ml/models/ensemble/bagged_ensemble_model.py
autogluon/utils/tabular/ml/models/ensemble/stacker_ensemble_model.py
autogluon/utils/tabular/ml/trainer/abstract_trainer.py

…and loading from the new location, including new machines.
https://github.com/awslabs/autogluon/issues/125
Tabular uses relative paths, support for moving learner directory
- Haven't tested cross-machine, but fairly certain it will work.
- Haven't tested moving to S3 and loading from S3, but it might work.
- Haven't tested cross-OS, this is currently an unknown if it works.

Tabular uses relative paths, support for moving learner directory

---

autogluon/task/tabular_prediction/predictor.py
autogluon/task/tabular_prediction/tabular_prediction.py
autogluon/utils/plots.py

Updated fit_summary to pull info from leaderboard, and base plots around inference-time.
There still remain issues in how certain ensembles'/stackers' times are being computed. Once these are resolved, they should be updated in the leaderboard so the plots reflect the correct times for all models.

Updated tabular fit_summary 

---

autogluon/utils/tabular/features/abstract_feature_generator.py
autogluon/utils/tabular/metrics/__init__.py
autogluon/utils/tabular/ml/models/catboost/catboost_model.py
autogluon/utils/tabular/ml/models/ensemble/bagged_ensemble_model.py
autogluon/utils/tabular/ml/models/lgb/hyperparameters/lgb_trial.py
autogluon/utils/tabular/ml/models/lgb/lgb_model.py
autogluon/utils/tabular/ml/trainer/abstract_trainer.py
autogluon/utils/tabular/ml/tuning/ensemble_selection.py

Tabular: Updated type() checks to isinstance() checks

Tabular: Updated type() checks to isinstance() checks

---

autogluon/utils/tabular/ml/models/abstract/abstract_model.py
autogluon/utils/tabular/ml/models/ensemble/greedy_weighted_ensemble_model.py
autogluon/utils/tabular/ml/models/ensemble/stacker_ensemble_model.py
autogluon/utils/tabular/ml/models/knn/knn_model.py
autogluon/utils/tabular/ml/models/lgb/lgb_model.py
autogluon/utils/tabular/ml/models/rf/rf_model.py

Cleaned model code, removed unused functions, removed unused parameters.

Tabular: Cleaned model code, removed unused functions and parameters.

---

docs/tutorials/course/index.rst

Fix: Fix a broken link

---

docs/tutorials/tabular_prediction/tabular-indepth.md
docs/tutorials/tabular_prediction/tabular-kaggle.md
docs/tutorials/tabular_prediction/tabular-quickstart.md

Existing TabularPrediction tutorials were out of date and failed to reflect best practices and the important options to the user.

Updated tabular tutorials

---

autogluon/utils/tabular/features/add_datepart_helper.py
autogluon/utils/tabular/features/vectorizers.py
autogluon/utils/tabular/metrics/classification_metrics.py
autogluon/utils/tabular/ml/learner/abstract_learner.py

Basic PEP8 corrections and optimizations. 

FIX: basic PEP8 corrections, optimizations

---

autogluon/task/tabular_prediction/predictor.py
autogluon/utils/tabular/ml/models/abstract/abstract_model.py
autogluon/utils/tabular/ml/models/ensemble/bagged_ensemble_model.py
autogluon/utils/tabular/ml/models/ensemble/stacker_ensemble_model.py
autogluon/utils/tabular/ml/models/knn/knn_model.py
autogluon/utils/tabular/ml/models/lgb/hyperparameters/lgb_trial.py
autogluon/utils/tabular/ml/models/lgb/lgb_model.py
autogluon/utils/tabular/ml/models/rf/rf_model.py
autogluon/utils/tabular/ml/trainer/abstract_trainer.py

- Fixed validation time values for bagged models
- Added fit_time and predict_time variables to models
- Note: Validation time and fit time is not fixed for non-bagged HPO models, requires significant code refactor in model.hyperparameter_tune() that is beyond the scope of this PR.
- Note: Validation time reflects time for the model given its inputs, not the full stacked ensemble time including base models. This requires graph representation to change.

Tabular: Fixed validation time values for bagged models

---

autogluon/task/tabular_prediction/predictor.py
autogluon/utils/plots.py

Moved .fillna calls in fit_summary to a copy of leaderboard

Tabular: Moved .fillna calls in fit_summary to a copy of leaderboard

---

autogluon/utils/tabular/ml/models/abstract/abstract_model.py
autogluon/utils/tabular/ml/models/abstract/model_trial.py
autogluon/utils/tabular/ml/models/ensemble/bagged_ensemble_model.py
autogluon/utils/tabular/ml/models/ensemble/stacker_ensemble_model.py
autogluon/utils/tabular/ml/models/lgb/hyperparameters/lgb_trial.py
autogluon/utils/tabular/ml/models/lgb/lgb_model.py
autogluon/utils/tabular/ml/models/tabular_nn/tabular_nn_model.py
autogluon/utils/tabular/ml/trainer/abstract_trainer.py

Major Changes:
- Simplified AbstractModel HPO
- Added support for early stopping with time for AbstractModel HPO
- Unified various HPO code under a single method
- Fixed minor defects in AbstractModel HPO
- Added fit_time and predict_time recording to HPO models (Not utilized yet)
This PR is part 2 of HPO Cleanup/Improvements.
A future PR will address tabular_nn HPO and remaining defects.

Tabular AbstractModel HPO Improvements

---

autogluon/task/tabular_prediction/tabular_prediction.py
autogluon/utils/tabular/ml/models/tabular_nn/tabular_nn_model.py
autogluon/utils/tabular/ml/models/tabular_nn/tabular_nn_trial.py

#266 
Major Changes:
- Reworked TabularNN HPO to be consistent with other models, fixed various defects in TabularNN HPO.
- Reworked TabularNN to minimize unnecessary variables and avoid alteration of original self.params during .fit(). Simplified code structure.

Tabular: Refactored tabular_nn_model and tabular_nn_trial

---

autogluon/task/tabular_prediction/predictor.py
autogluon/utils/tabular/ml/learner/abstract_learner.py
autogluon/utils/tabular/ml/learner/default_learner.py
autogluon/utils/tabular/ml/models/abstract/abstract_model.py
autogluon/utils/tabular/ml/models/ensemble/bagged_ensemble_model.py
autogluon/utils/tabular/ml/models/ensemble/greedy_weighted_ensemble_model.py
autogluon/utils/tabular/ml/models/ensemble/stacker_ensemble_model.py
autogluon/utils/tabular/ml/models/tabular_nn/tabular_nn_model.py
autogluon/utils/tabular/ml/trainer/abstract_trainer.py
autogluon/utils/tabular/utils/savers/save_json.py

Added get_info() to models, trainer, and learner

Tabular: Added get_info() to models, trainer, and learner

---

autogluon/utils/tabular/ml/models/ensemble/greedy_weighted_ensemble_model.py

Fixed defect in greedy_weighted_ensemble_model

Fixed defect in greedy_weighted_ensemble_model

---

autogluon/scheduler/fifo.py
autogluon/scheduler/hyperband.py
autogluon/scheduler/remote/remote.py
autogluon/scheduler/remote/remote_manager.py
autogluon/scheduler/reporter.py
autogluon/scheduler/scheduler.py
autogluon/searcher/grid_searcher.py
autogluon/searcher/rl_controller.py
autogluon/searcher/skopt_searcher.py

Searcher and Scheduler cleanup

Searcher and Scheduler cleanup

---

autogluon/utils/tabular/metrics/classification_metrics.py
autogluon/utils/tabular/metrics/softclass_metrics.py
autogluon/utils/tabular/ml/learner/abstract_learner.py
autogluon/utils/tabular/ml/learner/default_learner.py
autogluon/utils/tabular/ml/models/ensemble/bagged_ensemble_model.py

Basic PEP8 corrections and improvements. 

FIX: basic PEP8 fixes and improvements

---

autogluon/utils/tabular/ml/models/abstract/model_trial.py
autogluon/utils/tabular/ml/models/lgb/hyperparameters/lgb_trial.py
autogluon/utils/tabular/ml/models/tabular_nn/tabular_nn_trial.py

Reduced code duplication in HPO code

Tabular: Reduced code duplication in HPO code

---

CONTRIBUTING.md

Provide more detailed tips to new contributors as suggested by @mseeger 
I think the more instructions & information we can provide the better.

Updated contribution instructions

---

autogluon/utils/tabular/ml/learner/abstract_learner.py
autogluon/utils/tabular/ml/models/abstract/abstract_model.py
autogluon/utils/tabular/ml/models/ensemble/bagged_ensemble_model.py
autogluon/utils/tabular/ml/models/ensemble/stacker_ensemble_model.py
autogluon/utils/tabular/ml/trainer/abstract_trainer.py
autogluon/utils/tabular/ml/utils.py

#304 
Major Changes:
- Added functionality to get raw feature importances as opposed to the specific model's features (Black Box method).
- Cleaned feature importance code
- Note: raw feature importance on training data in bagged mode is not implemented in this PR.
Code Example:
```
import datetime
import sklearn.datasets
from autogluon.utils.tabular.ml.utils import generate_train_test_split
from autogluon import TabularPrediction as task
LABEL = 'target'
utcnow = datetime.datetime.utcnow()
timestamp_str_now = utcnow.strftime("%Y%m%d_%H%M%S")
path_prefix = 'datasets/breast_cancer/'
path_model_prefix = path_prefix + 'learners/' + timestamp_str_now + '/'
cancer_data = …
```

Tabular: Feature Importance Raw

---

autogluon/utils/tabular/features/auto_ml_feature_generator.py
autogluon/utils/tabular/ml/models/lgb/lgb_model.py
autogluon/utils/tabular/ml/models/lgb/lgb_utils.py
autogluon/utils/tabular/ml/utils.py

Basic PEP8 corrections, performing some TODOs, minor bug fixes.

FIX: tabular utils and lgb clean up

---

autogluon/scheduler/fifo.py
autogluon/scheduler/hyperband.py
autogluon/scheduler/rl_scheduler.py

*Issue #329 , if available:*
Continuation of #345 for hyperband and rl.

Fix scheduler hpo

---

autogluon/utils/tabular/features/auto_ml_feature_generator.py

Adjusted ngram max_memory_percentage from 0.2 -> 0.15

Tabular: Improved ngram feature generation stability

---

README.md

Added AutoGluon Logo to README.md

Added AutoGluon Logo to README.md

---

autogluon/task/tabular_prediction/predictor.py
autogluon/task/tabular_prediction/tabular_prediction.py
autogluon/utils/tabular/ml/learner/abstract_learner.py
autogluon/utils/tabular/ml/models/abstract/abstract_model.py
autogluon/utils/tabular/ml/models/ensemble/bagged_ensemble_model.py
autogluon/utils/tabular/ml/models/ensemble/weighted_ensemble_model.py
autogluon/utils/tabular/ml/trainer/abstract_trainer.py

#304
Major Changes:
- Added feature_importance to tabular Predictor
- Fixed defects in feature importance calculations and made it memory safe.

Added feature_importance to Tabular Predictor

---

setup.py

Upgraded version from 0.0.5 -> 0.0.6
Note: I will merge this after #366 is merged. Then we can update the pypi.

Updated version to 0.0.6

---

autogluon/utils/tabular/ml/learner/abstract_learner.py
autogluon/utils/tabular/ml/learner/default_learner.py

Some optimizations, PEP8 corrections. 
Bug fix when removing missing labels. Old code was not working, when the labels are `pd.Series` with index different than `0, 1, 2, ...`.

FIX: optimizations and small bug fix

---

autogluon/utils/tabular/ml/models/abstract/abstract_model.py
autogluon/utils/tabular/ml/trainer/abstract_trainer.py

Making optimization of feature importance calculation according to TODOs.

Making optimization of feature importance calculation according to TODOs

---

CONTRIBUTING.md
autogluon/task/tabular_prediction/predictor.py
autogluon/utils/tabular/ml/learner/abstract_learner.py

Fixes this issue:
https://github.com/awslabs/autogluon/issues/381
Also updated Contribution instructions to reflect the new pytest unit-testing approach.

Fixed tabular predictor evaluate_predictions for certain metrics like F1

---

autogluon/scheduler/remote/remote.py
autogluon/utils/sync_remote.py

safe start and auto exit for distributed search on multiple nodes.

Fix auto exit

---

README.md

Updated readme to include links to articles and paper, plus code contribution guidelines.

Updated readme to include links to articles and paper

---

autogluon/scheduler/remote/remote.py
autogluon/task/object_detection/data_parallel.py
autogluon/utils/mxutils.py
autogluon/utils/sync_remote.py
setup.py

Many thanks to @tlienart !
Working with SageMaker example at https://github.com/zhanghang1989/AutoGluon-Docker
The change does not break any existing features.

Sagemaker Compatibility

---

autogluon/utils/augment.py
autogluon/utils/pil_transforms.py

Add Image Auto Augment

---

.github/workflows/pythonpublish.yml
setup.py

Pypi Nightly

---

autogluon/utils/tabular/ml/constants.py
autogluon/utils/tabular/ml/learner/abstract_learner.py
autogluon/utils/tabular/ml/models/ensemble/bagged_ensemble_model.py
autogluon/utils/tabular/ml/trainer/abstract_trainer.py

Added internal support for _FULL ensemble creation that only uses other _FULL ensembles during prediction. This results in 10-200x inference time speedup for most ensembles with minimal accuracy loss.
Once this PR is merged, the follow-up PR will introduce this to Tabular Predictor as a user-facing option. For that PR, I will also benchmark the functionality to ensure stability and demonstrate the difference in accuracy and inference time.

Tabular: Added internal support for _FULL ensembles

---

autogluon/task/image_classification/dataset.py

Fix #364: Fix num_class for RecordDataset

---

.github/workflows/pythonpublish.yml
README.md

Upload to pypi daily

---

autogluon/task/tabular_prediction/predictor.py
autogluon/task/tabular_prediction/tabular_prediction.py
autogluon/utils/tabular/ml/learner/abstract_learner.py
autogluon/utils/tabular/ml/trainer/abstract_trainer.py

Added refit_full functionality to user-facing layer.
Benchmarking is still running, will update with results tomorrow.

Tabular: Added refit_full user-facing functionality

---

autogluon/task/tabular_prediction/tabular_prediction.py
autogluon/utils/tabular/ml/models/lr/hyperparameters/parameters.py
autogluon/utils/tabular/ml/models/lr/hyperparameters/searchspaces.py
autogluon/utils/tabular/ml/models/lr/lr_model.py
autogluon/utils/tabular/ml/models/lr/lr_preprocessing_utils.py
autogluon/utils/tabular/ml/trainer/model_presets/presets.py

This code adds linear models capabilities to the framework. Models are fully-integrated, but disabled by default: uncomment `LR` section in `fit()` method in  `autogluon/task/tabular_prediction/tabular_prediction.py`
The model has 3 variations, which are different by how in-model pre-processing and feature selection is performed. All operations are performed in sparse matrix form via Sklearn pipelines. Text features are controlled via `handle_text` hyper-parameter:
* `ignore` handles continuous and categorical features; features marked as NLP-capable are dropped. Preprocessing is similar to NNTabular: imputation, scaling, skew correction; categorical variables are one-hot encoded with a limit on max number of values in category.
* `only` handles only text …

Linear models support

---

autogluon/scheduler/rl_scheduler.py

fix an error in rl_scheduler #421

[fix] RL scheduler

---

autogluon/utils/tabular/ml/models/tabular_nn/tabular_nn_model.py

#411 
Optimizes inference time on tabular NN by restricting data loading to 1-core and avoiding os.fork() calls. This results in a flat speedup of ~0.05 - 0.10 seconds per call to inference. For small datasets and online-inference situations, this can lead to a 400% or larger inference speedup, while using less overall CPU with no impact to training times. Additionally, it is suspected this uses far less memory and will resolve potential memory issues during validation and test inference observed in #411.
Benchmark results (_mixed represents this change):
```
framework  time_train_s  metric_error  time_infer_s       acc       auc   logloss  bestdiff  loss_rescaled      rank  rank=1_count  rank=2_count  rank=3_count  rank>3_count …
```

Optimized tabular neural network inference speed

---

autogluon/contrib/enas/enas_scheduler.py

Bug fix when warmup is enabled and self.baseline is None.

---

README.md

Added Tabular SageMaker tutorial link

Added Tabular SageMaker tutorial link

---

autogluon/task/tabular_prediction/tabular_prediction.py
autogluon/utils/tabular/ml/learner/abstract_learner.py
autogluon/utils/tabular/ml/learner/default_learner.py
autogluon/utils/tabular/ml/trainer/abstract_trainer.py
autogluon/utils/tabular/ml/trainer/auto_trainer.py
autogluon/utils/tabular/ml/utils.py

#425 
Added random_seed parameter to TabularPrediction. Functionality is identical to previous if random_seed is kept as default value.

Tabular: Added random_seed parameter

---

autogluon/utils/tabular/features/abstract_feature_generator.py
autogluon/utils/tabular/features/vectorizers.py
autogluon/utils/tabular/ml/models/tabular_nn/hyperparameters/parameters.py
autogluon/utils/tabular/ml/models/tabular_nn/tabular_nn_model.py

#401 -> Should remove the NN bottleneck
Changes:
- Max n for ngrams changed from 5 to 3
- Disabled text feature usage by default in NN, added hyperparameter toggle
- Added automated removal of near unique features (Handles categorical ID's and raw text columns after ngram generation)

Tabular: Optimize Text Handling

---

autogluon/task/image_classification/image_classification.py
autogluon/task/image_classification/nets.py

#218
FIx potential usage issue similar to #218 

Fix #218: fix arg names and orders

---

autogluon/task/object_detection/detector.py
autogluon/task/object_detection/nets.py
autogluon/task/object_detection/object_detection.py
autogluon/task/object_detection/pipeline.py
autogluon/task/object_detection/utils.py
examples/object_detection/benchmark.py

Make changes to object detection benchmark, so that different hyper-parameters are used for yolo v3 and faster rcnn.

faster rcnn benchmark [WIP]

---

autogluon/task/tabular_prediction/predictor.py

Added experimental preview .info function to predictor.
Note that this is fully functional, but due to the quantity of fields this returns (>50) it has not been fully documented.

Tabular: Added experimental preview .info function to predictor

---

autogluon/contrib/enas/enas_scheduler.py
autogluon/core/task.py
autogluon/scheduler/fifo.py
autogluon/scheduler/hyperband.py
autogluon/scheduler/hyperband_promotion.py
autogluon/scheduler/hyperband_stopping.py
autogluon/scheduler/reporter.py
autogluon/scheduler/rl_scheduler.py
autogluon/scheduler/scheduler.py
autogluon/searcher/grid_searcher.py
autogluon/searcher/rl_controller.py
autogluon/searcher/searcher.py
autogluon/searcher/searcher_factory.py
autogluon/searcher/skopt_searcher.py
autogluon/task/base/base_task.py
autogluon/task/image_classification/image_classification.py
autogluon/task/object_detection/object_detection.py
autogluon/task/tabular_prediction/tabular_prediction.py
autogluon/task/text_classification/text_classification.py
autogluon/utils/tabular/utils/savers/save_json.py
docs/api/autogluon.scheduler.rst
docs/api/autogluon.searcher.rst
docs/tutorials/course/algorithm.md
tests/unittests/test_skoptsearcher.py

- Cleanup of BaseSearcher API, in particular update
- Improve checkpoint/resume, support searcher objects which cannot be pickled
- Improved documentation of FIFOScheduler, HyperbandScheduler

Refactoring of schedulers and searchers

---

autogluon/utils/tabular/ml/models/abstract/abstract_model.py
autogluon/utils/tabular/ml/models/lgb/lgb_model.py

#399 
Fixed crash in LightGBM with special characters in column names.
This fix makes LightGBM work for problems with text features, as previously the feature engineered column names from AutoGluon when text was present contained these special characters and crashed LightGBM.

Tabular: Fixed crash in LightGBM with special characters in column names

---

.github/workflows/pypi_release.yml
setup.py

Fix Version File and Auto Upload to PyPi

---

setup.py

Updated version to 0.0.10 to enable daily pre-releases

Updated version to 0.0.10

---

autogluon/task/tabular_prediction/tabular_prediction.py
autogluon/utils/tabular/metrics/__init__.py

Fixed root_mean_squared_error metric unavailable during fit()

Tabular: Fixed root_mean_squared_error metric unavailable during fit()

---

autogluon/utils/tabular/ml/learner/abstract_learner.py

Removed unused sample parameter from learner

Tabular: Removed unused sample parameter

---

autogluon/task/tabular_prediction/dataset.py
autogluon/task/tabular_prediction/predictor.py
autogluon/task/tabular_prediction/tabular_prediction.py
autogluon/utils/tabular/features/abstract_feature_generator.py
autogluon/utils/tabular/ml/learner/abstract_learner.py
docs/api/autogluon.task.rst
examples/tabular/example_advanced_tabular.py
examples/tabular/example_simple_tabular.py
tests/unittests/test_tabular.py
tests/unittests/test_text_classification.py

- Enable type setting to training types during inference
- Added error during inference when columns are missing
- Minor logging cleanup

Tabular: Enable type setting to training types during inference

---

autogluon/task/tabular_prediction/predictor.py
autogluon/task/tabular_prediction/tabular_prediction.py
autogluon/utils/tabular/ml/trainer/abstract_trainer.py

Fixed exception raised when calling fit_summary after deleting models.

Tabular: Fixed exception raised when calling fit_summary after deleting models.

---

setup.py

as suggested by Sheng:  https://github.com/awslabs/autogluon/issues/482

cap gluoncv version to 0.x

---

autogluon/__init__.py

#493 
Suppressed distributed warnings

Suppressed distributed warnings

---

autogluon/scheduler/fifo.py
autogluon/scheduler/hyperband.py
autogluon/scheduler/remote/dask_scheduler.py
autogluon/scheduler/rl_scheduler.py
autogluon/scheduler/scheduler.py

- Put some thread creation job to lazy init

Lazy init thread workers

---

setup.py

Updated version to 0.0.11

---

autogluon/scheduler/hyperband.py
docs/api/autogluon.scheduler.rst
docs/api/autogluon.space.rst
docs/tutorials/course/algorithm.md
docs/tutorials/course/mlp.md
docs/tutorials/torch/hpo.md
tests/unittests/test_scheduler.py

*Issue #, if available:* #498 

Allow HyperbandScheduler to infer max_t from train_fn.args

---

autogluon/utils/tabular/ml/models/tabular_nn/categorical_encoders.py

Fix import error caused by removed private scikit-learn function

---

autogluon/utils/tabular/ml/models/catboost/catboost_model.py
autogluon/utils/tabular/ml/models/ensemble/bagged_ensemble_model.py
autogluon/utils/tabular/ml/models/ensemble/greedy_weighted_ensemble_model.py
autogluon/utils/tabular/ml/models/ensemble/stacker_ensemble_model.py
autogluon/utils/tabular/ml/models/ensemble/weighted_ensemble_model.py
autogluon/utils/tabular/ml/models/knn/knn_model.py
autogluon/utils/tabular/ml/models/lgb/lgb_model.py
autogluon/utils/tabular/ml/models/lr/lr_model.py
autogluon/utils/tabular/ml/models/rf/rf_model.py
autogluon/utils/tabular/ml/models/tabular_nn/tabular_nn_model.py

Removed redundant explicit parameter definitions in models.

Tabular: Removed redundant explicit parameter definitions in models

---

autogluon/utils/tabular/features/abstract_feature_generator.py
autogluon/utils/tabular/features/auto_ml_feature_generator.py
autogluon/utils/tabular/features/vectorizers.py
autogluon/utils/tabular/ml/learner/default_learner.py

Improves memory efficiency significantly by:
- Removing unnecessary copy of text data during fit_transform of vectorizer
- Using uint8 representation of ngrams and bucketed features instead of int64 (8x memory reduction)
- Removing original text keys in categoricals from the post-processed data (major improvement for large text fields with many unique values, often >100x reduction)
- Added memory checks to pre and post transformation to help identify likely OOM scenarios
Changes are internally benchmarked, no regressions identified.

Tabular: Improved NLP memory efficiency

---

autogluon/utils/tabular/features/abstract_feature_generator.py
autogluon/utils/tabular/ml/models/tabular_nn/tabular_nn_model.py

This change theoretically could enable 50% larger datasets to be preprocessed in NN without going OOM.

Tabular: Fixed predict defect in NN, optimized memory usage in NN

---

autogluon/utils/tabular/ml/models/lgb/hyperparameters/searchspaces.py
autogluon/utils/tabular/ml/models/lgb/lgb_model.py

Fixed LGBM HPO defect when using built-in LGBM metrics

Tabular: Fixed LGBM HPO defect

---

autogluon/task/tabular_prediction/predictor.py
autogluon/utils/tabular/ml/learner/abstract_learner.py
autogluon/utils/tabular/ml/models/ensemble/stacker_ensemble_model.py
autogluon/utils/tabular/ml/trainer/abstract_trainer.py

- Fixed defect in transform_features when training data's indices are not 0-n
- Added return_original_features argument to simplify obtaining pure OOF predictions

Tabular: Fixed defect in transform_features + new arg

---

setup.py

v0.0.12 version update

---

Jenkinsfile
autogluon/task/text_classification/dataset.py
autogluon/task/text_classification/network.py
autogluon/task/text_classification/pipeline.py
autogluon/task/text_classification/predictor.py
autogluon/task/text_classification/text_classification.py
autogluon/task/text_classification/transforms.py
autogluon/utils/try_import.py
docs/tutorials/text_classification/beginner.md
examples/text_classification/example_custom_dataset.py
setup.py

The first step of refactoring the text part in the code base.

[NLP Refactor] Revise the dependency structure of gluonnlp to lazy dependency

---

autogluon/utils/tabular/ml/models/catboost/catboost_model.py

Moved CatBoost import into model fit call, this enables CatBoost to be an optional dependency without causing an overall crash if it is included in the model list.

Tabular: Moved CatBoost import into model fit call

---

autogluon/utils/tabular/features/abstract_feature_generator.py
autogluon/utils/tabular/ml/models/tabular_nn/tabular_nn_model.py

Resolves #532 
Added support for empty / useless data input

Tabular: Added support for empty / useless data input

---

autogluon/task/tabular_prediction/tabular_prediction.py
autogluon/utils/tabular/ml/learner/default_learner.py
autogluon/utils/tabular/ml/trainer/abstract_trainer.py
autogluon/utils/tabular/ml/trainer/auto_trainer.py

Added 'excluded_model_types' fit() argument

Tabular: Added 'excluded_model_types' fit() argument

---

autogluon/task/tabular_prediction/predictor.py
autogluon/task/tabular_prediction/presets_configs.py
autogluon/task/tabular_prediction/tabular_prediction.py
autogluon/utils/tabular/features/abstract_feature_generator.py
autogluon/utils/tabular/features/auto_ml_feature_generator.py
autogluon/utils/tabular/features/feature_types_metadata.py
autogluon/utils/tabular/features/utils.py
autogluon/utils/tabular/ml/learner/abstract_learner.py
autogluon/utils/tabular/ml/learner/default_learner.py
autogluon/utils/tabular/ml/models/abstract/abstract_model.py
autogluon/utils/tabular/ml/models/ensemble/stacker_ensemble_model.py
autogluon/utils/tabular/ml/models/knn/knn_model.py
autogluon/utils/tabular/ml/models/lr/lr_model.py
autogluon/utils/tabular/ml/models/tabular_nn/tabular_nn_model.py
autogluon/utils/tabular/ml/trainer/abstract_trainer.py
autogluon/utils/tabular/utils/exceptions.py

- Refactored feature_types_metadata to be a custom class object instead of a dictionary for increased extensibility.
- Refactored feature_generator to have improved readability and extensibility.
- KNN now drops NLP features to avoid large inaccurate KNN models with massive inference time in NLP problems.

Tabular: Refactored feature types metadata

---

autogluon/task/tabular_prediction/predictor.py
tests/unittests/test_tabular.py

Added fit_weighted_ensemble function to predictor.py

Tabular: Added fit_weighted_ensemble function to predictor.py

---

autogluon/task/tabular_prediction/predictor.py
autogluon/task/tabular_prediction/tabular_prediction.py
autogluon/utils/tabular/data/label_cleaner.py
autogluon/utils/tabular/features/abstract_feature_generator.py
autogluon/utils/tabular/metrics/__init__.py
autogluon/utils/tabular/ml/learner/abstract_learner.py
autogluon/utils/tabular/ml/learner/default_learner.py
autogluon/utils/tabular/ml/models/abstract/abstract_model.py
autogluon/utils/tabular/ml/models/abstract/model_trial.py
autogluon/utils/tabular/ml/models/catboost/catboost_model.py
autogluon/utils/tabular/ml/models/ensemble/bagged_ensemble_model.py
autogluon/utils/tabular/ml/models/ensemble/greedy_weighted_ensemble_model.py
autogluon/utils/tabular/ml/models/ensemble/stacker_ensemble_model.py
autogluon/utils/tabular/ml/models/ensemble/weighted_ensemble_model.py
autogluon/utils/tabular/ml/models/knn/knn_model.py
autogluon/utils/tabular/ml/models/lgb/hyperparameters/lgb_trial.py
autogluon/utils/tabular/ml/models/lgb/lgb_model.py
autogluon/utils/tabular/ml/models/lr/lr_model.py
autogluon/utils/tabular/ml/models/rf/rf_model.py
autogluon/utils/tabular/ml/models/tabular_nn/tabular_nn_model.py
autogluon/utils/tabular/ml/models/tabular_nn/tabular_nn_trial.py
autogluon/utils/tabular/ml/trainer/abstract_trainer.py
autogluon/utils/tabular/ml/trainer/auto_trainer.py
autogluon/utils/tabular/ml/trainer/model_presets/presets.py
autogluon/utils/tabular/ml/tuning/ensemble_selection.py
autogluon/utils/tabular/ml/tuning/feature_pruner.py
autogluon/utils/tabular/ml/utils.py
examples/tabular/example_custom_model_tabular.py

Major Changes:
- Added support for custom model specification that can be fed directly into hyperparameters function of task.fit alongside other models.
- Simplified usage of tabular models outside of the task.fit context.
- Added example script to demonstrate creating and using custom models.
- Major renaming refactors:
- X_test, Y_test -> X_val, y_val
- objective_func -> eval_metric
- Y_train -> y_train

Tabular: Custom Model Support + Major Renaming

---

setup.py

Update to v0.0.13 to fix pre-release PyPi builds.

v0.0.13 version update

---

autogluon/task/tabular_prediction/predictor.py
autogluon/task/tabular_prediction/tabular_prediction.py
autogluon/utils/tabular/ml/augmentation/distill_utils.py
autogluon/utils/tabular/ml/learner/abstract_learner.py
autogluon/utils/tabular/ml/learner/default_learner.py
autogluon/utils/tabular/ml/models/catboost/catboost_model.py
autogluon/utils/tabular/ml/models/catboost/catboost_softclass_utils.py
autogluon/utils/tabular/ml/models/catboost/catboost_utils.py
autogluon/utils/tabular/ml/models/catboost/hyperparameters/parameters.py
autogluon/utils/tabular/ml/models/lgb/hyperparameters/parameters.py
autogluon/utils/tabular/ml/models/lgb/lgb_model.py
autogluon/utils/tabular/ml/models/lgb/lgb_utils.py
autogluon/utils/tabular/ml/trainer/abstract_trainer.py
autogluon/utils/tabular/ml/trainer/model_presets/presets.py
autogluon/utils/tabular/ml/trainer/model_presets/presets_distill.py
autogluon/utils/tabular/ml/utils.py
autogluon/utils/try_import.py
examples/tabular/distill/example_distill_binary.py
examples/tabular/distill/example_distill_multiclass.py
examples/tabular/distill/example_distill_regression.py
examples/tabular/example_advanced_tabular.py
examples/tabular/example_simple_tabular.py
tests/unittests/test_tabular.py

Adds initial version of distillation functionality. Will follow-up with refit_full + HPO version + Tutorial notebook + Gibbs-sampler in 3 separate PRs for better clarity.
Example distillation scripts showing various usage options are in:
`autogluon/examples/tabular/distill/`
e.g. https://github.com/awslabs/autogluon/blob/userdist/examples/tabular/distill/example_distill_binary.py 
Added a distillation unit-test at the end of `test_tabular_bagstack`

Distillation PR 1

---

setup.py

Test fix for psutil error

---

setup.py

- Downgraded psutil to <=5.7.0 in an attempt to fix non-deterministic CI issue regarding the doc build.

Downgraded psutil to <=5.7.0

---

autogluon/task/tabular_prediction/presets_configs.py
autogluon/utils/tabular/features/abstract_feature_generator.py
autogluon/utils/tabular/features/auto_ml_feature_generator.py

#575 
- Fixed defect causing `TabularPrediction.fit()` to crash when given positional arguments
- Moved and optimized memory usage of text_special feature generation

Tabular: Enabled conditional arguments in TabularPrediction.fit()

---

autogluon/contrib/enas/enas.py
docs/tutorials/nas/enas_proxylessnas.md
tests/unittests/test_contrib_enas.py

https://github.com/awslabs/autogluon/issues/558
ENAS network is dynamic so some parameters may not needed during export, remove the check.
Note that this is one-directional serialization for now, since the enas is wrapped dynamic searchable network architecture.

[Fix] Fix #558 enas export

---

autogluon/utils/tabular/ml/models/abstract/abstract_model.py
autogluon/utils/tabular/ml/models/ensemble/bagged_ensemble_model.py
autogluon/utils/tabular/ml/models/knn/knn_model.py

- Optimized OOF memory usage by converting from float64 -> float32
- Optimized KNN memory usage / disk usage / speed by converting to float32 and removing unnecessary categorical removal (Already handled by AG_args_fit defaults). This typically reduces disk/memory usage of KNN by ~20-25%.

Tabular: Optimized OOF memory usage

---

autogluon/utils/tabular/ml/learner/abstract_learner.py
autogluon/utils/tabular/ml/learner/default_learner.py

- Added KeyError when label is missing from training data

Tabular: Added KeyError when label is missing from training data

---

autogluon/task/tabular_prediction/predictor.py
tests/unittests/test_tabular.py

- Update tabular unit tests to test all of `Predictor.fit_summary()` functionality
- Fix issue in `fit_summary()` plots after fitting with HPO.

Fix fit_summary() HPO functionality

---

docs/tutorials/image_classification/beginner.md
docs/tutorials/image_classification/hpo.md
docs/tutorials/object_detection/beginner.md

Fixes some inline RST links and typos in the tutorial docs

[doc] Fix typos and inline links

---

autogluon/utils/tabular/ml/models/abstract/abstract_model.py
autogluon/utils/tabular/ml/models/ensemble/bagged_ensemble_model.py
autogluon/utils/tabular/ml/models/ensemble/weighted_ensemble_model.py
autogluon/utils/tabular/ml/models/lgb/lgb_model.py
autogluon/utils/tabular/ml/trainer/abstract_trainer.py

- Fixed defect in feature importance when duplicated indices in input.
- Fixed defect in lgbm feature importance.
- Fixed defect in transform_model strategy that ignored subsample_size.

Tabular: Fixed defect in feature importance when duplicated indices

---

setup.py

Update to version v0.0.14 to correct nightly PyPi builds.

v0.0.14 version update

---

README.md

adds some links to resources regarding hyperparameter optimization and neural architecture search with AutoGluon

add links to HNAS resources

---

autogluon/utils/tabular/ml/models/knn/knn_model.py
autogluon/utils/tabular/ml/models/rf/rf_model.py
autogluon/utils/tabular/utils/loaders/load_s3.py

Reduced mem usage limit of KNN, RF, XT + misc fix to load_s3.py

Tabular: Reduced mem usage limit of KNN, RF, XT + misc fix to load_s3.py

---

autogluon/task/text_prediction/text_prediction.py
tests/unittests/test_nlp_text_prediction.py

*Issue #, if available:* https://github.com/awslabs/autogluon/issues/647

[Bugfix] Fix the problem that the specified feature_columns will be ignored

---

autogluon/utils/tabular/ml/models/lgb/lgb_model.py
autogluon/utils/tabular/ml/models/lgb/lgb_utils.py
setup.py
tests/unittests/test_skoptsearcher.py

Updated LightGBM to v3.0
Benchmarks observe a ~100% training time speedup and 25% inference time speedup for LGB models while roughly maintaining accuracy.

Tabular: Updated LightGBM to v3.0

---

autogluon/utils/tabular/ml/models/abstract/abstract_model.py
autogluon/utils/tabular/ml/models/ensemble/bagged_ensemble_model.py
autogluon/utils/tabular/ml/models/fastainn/tabular_nn_fastai.py
autogluon/utils/tabular/ml/models/lgb/lgb_model.py
autogluon/utils/tabular/ml/models/tabular_nn/tabular_nn_model.py
autogluon/utils/tabular/ml/models/utils.py

Code cleanup for model save/load functionality.

Tabular: Model save/load cleanup

---

setup.py

Upgraded sklearn version to <0.24

Upgraded sklearn version to <0.24

---

setup.py

Upgraded pandas version to >=1.0

Upgraded pandas version to >=1.0

---

docs/build.yml
docs/build_contrib.yml

https://github.com/boto/boto3/issues/2596
Fix awscli

Fix awscli

---

autogluon/utils/tabular/ml/learner/default_learner.py
autogluon/utils/tabular/ml/trainer/abstract_trainer.py
autogluon/utils/tabular/ml/trainer/auto_trainer.py

Simplified handling of time_limit in Trainer. Now it is managed by two private variables instead of 4 public variables. This will help better support future fit calls to work properly.

Tabular: Simplified handling of time_limit in Trainer

---

autogluon/utils/tabular/ml/trainer/model_presets/presets.py

Updated training priority for multiclass so tree algorithms train last.

Tabular: Updated training priority for multiclass

---

autogluon/task/tabular_prediction/hyperparameter_configs.py
autogluon/task/tabular_prediction/tabular_prediction.py

Added LightGBM XT model to hyperparameter configs

Tabular: Added LightGBM XT model to hyperparameter configs

---

docs/tutorials/tabular_prediction/tabular-faq.md
docs/tutorials/tabular_prediction/tabular-indepth.md

Add more troubleshooting tips

---

autogluon/task/tabular_prediction/predictor.py

Should fix Issue: https://github.com/awslabs/autogluon/issues/675

bugfix fit_summary with HPO

---

docs/build.yml
docs/build_contrib.yml
docs/install-faq.rst
docs/install-include.rst

Use official MXNet 1.7.0

---

autogluon/utils/tabular/ml/models/tabular_nn/tabular_nn_model.py

Entirely NA columns could appear during bagging due to data-split, which caused an issue during the TabularNeuralNet data preprocessing.  These columns are now deleted in TabularNeuralNet data preprocessing.

Bug fix for NN-preprocessing of entirely-NA columns

---

README.md
autogluon/task/tabular_prediction/tabular_prediction.py

Tabular: tabular_prediction.py fit args cleanup + README.md update

Tabular: tabular_prediction.py fit args cleanup + README.md update

---

setup.py

Update setup.py version to 0.0.15

Update setup.py version to 0.0.15

---

docs/config.ini
tabular/src/autogluon/tabular/utils/ml/learner/abstract_learner.py

Post-PR fixes, v0.0.14 doc links update

[Modularizaton] Post-PR fixes, doc links update

---

text/src/autogluon/text/text_prediction/column_property.py
text/tests/unittests/test_nlp_text_prediction.py

#704 
Fixing as suggested by @sxjscience .

#704 Fix  bug with deserializing model

---

core/setup.py

Added `agremote` entry point. 

[Modularizaton] Post-PR fixes: added CLI entry points

---

.gitignore

Added version.py files to .gitignore

Added version.py files to .gitignore

---

tabular/src/autogluon/tabular/models/catboost/catboost_model.py

#693 
Removed inference-time usage of select_dtypes from catboost_model.py
For online-inference, this can result in ~25% - 37% reduction in inference latency.

Removed inference-time usage of select_dtypes from catboost_model.py

---

README.md
docs/index.rst
docs/install-faq.rst
docs/install-include.rst
docs/install-warning.rst

#722 
- Updated install instructions and readme to be more clear about differences in v0.0.14 and mainline.
- Made it clearer that AutoGluon is not limited to only deep learning.

Updated install instructions and readme to be more clear

---

tabular/src/autogluon/tabular/task/tabular_prediction/predictor.py
tabular/src/autogluon/tabular/task/tabular_prediction/tabular_prediction.py

Removed deprecated arguments and methods.

Tabular: Removed deprecated arguments and methods.

---

core/tests/unittests/test_bayesopt_searcher.py

Disabled test_bayesopt_searcher

---

docs/ReleaseInstructions.md
docs/config.ini
docs/versions.rst

Added previous version documentation page

[CI Refactoring] added versions.rst

---

tabular/src/autogluon/tabular/models/fastainn/callbacks.py
tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py

Updated fastai model to handle `refit_full` functionality. The model will use average of the best epoch from used in folds.
Note: this is likely sub-optimal for large datasets because refit_full will receive 10% more data and optimal stopping might be different.

[Tabular][FASTAI] Updated fastai model to handle refit_full functionality

---

README.md
docs/tutorials/tabular_prediction/tabular-quickstart.md

Clarify "maximizing accuracy" tips are also relevant when benchmarking,

Benchmarking tip added

---

Jenkinsfile
docs/config.ini

Header changes:
* stable branch will have a link to nightly release build docs
* all other branches will have a link to stable

[CI Refactoring] Other docs version links generation

---

tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py

fastai has issues predicting on a single row, duplicating the row as a workaround

[Tabular][FASTAI] Fixing single row prediction failure

---

core/src/autogluon/core/searcher/bayesopt/autogluon/searcher_factory.py
core/src/autogluon/core/searcher/bayesopt/gpautograd/custom_op.py
core/src/autogluon/core/searcher/bayesopt/utils/comparison_gpy.py
core/src/autogluon/core/searcher/gp_searcher.py
core/tests/unittests/bayesopt/gpautograd/test_cholesky_factorization.py

Fixes a problem with @gradientsky found, plus two other small things

Avoid using numpy.linalg.cholesky (has locking issues)

---

examples/tabular/example_custom_model_tabular.py
tabular/src/autogluon/tabular/models/abstract/abstract_model.py
tabular/src/autogluon/tabular/models/abstract/model_trial.py
tabular/src/autogluon/tabular/models/catboost/catboost_model.py
tabular/src/autogluon/tabular/models/ensemble/bagged_ensemble_model.py
tabular/src/autogluon/tabular/models/ensemble/greedy_weighted_ensemble_model.py
tabular/src/autogluon/tabular/models/ensemble/stacker_ensemble_model.py
tabular/src/autogluon/tabular/models/ensemble/weighted_ensemble_model.py
tabular/src/autogluon/tabular/models/fastainn/callbacks.py
tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
tabular/src/autogluon/tabular/models/knn/knn_model.py
tabular/src/autogluon/tabular/models/lgb/lgb_model.py
tabular/src/autogluon/tabular/models/lr/lr_model.py
tabular/src/autogluon/tabular/models/rf/rf_model.py
tabular/src/autogluon/tabular/models/tabular_nn/tabular_nn_model.py
tabular/src/autogluon/tabular/trainer/abstract_trainer.py

#691 
- Enables stateful model preprocessing. Required to integrate XGBoost model.
- Fixed HPO for LR and FASTAI models.
- Fixed crash when model isn't specified a feature_metadata (fixes example for custom model).
**TODO**

Tabular: Stateful model preprocessing

---

tabular/src/autogluon/tabular/task/tabular_prediction/presets_configs.py
tabular/src/autogluon/tabular/task/tabular_prediction/tabular_prediction.py

Fixed 'ignore_text' preset causing crash.

Tabular: Fixed 'ignore_text' preset

---

README.md
core/src/autogluon/core/space.py
docs/api/index.rst
docs/index.rst
docs/tutorials/course/index.rst
docs/tutorials/course/mlp.md
docs/tutorials/course/object.md
docs/tutorials/course/script.md
docs/tutorials/index.rst
docs/tutorials/torch/hpo.md
docs/tutorials/torch/index.rst

https://github.com/awslabs/autogluon/issues/722

standardize / improve naming

---

CONTRIBUTING.md

*Issue #, if available:* 
Original url 404
fix the **lazy_import** url

fix lazy-import url

---

tabular/tests/conftest.py
tabular/tests/unittests/models/test_catboost.py
tabular/tests/unittests/models/test_knn.py
tabular/tests/unittests/models/test_lightgbm.py
tabular/tests/unittests/models/test_linear.py
tabular/tests/unittests/models/test_rf.py
tabular/tests/unittests/models/test_tabular_nn.py
tabular/tests/unittests/models/test_tabular_nn_fastai.py
tabular/tests/unittests/models/test_xt.py

- Added unit tests for models
- FastAI NN unit tests are disabled at present since required dependencies are not installed during test runs on CI.

Tabular: Added unit tests for models

---

core/src/autogluon/core/__init__.py

#493 (Redo the fix after modularization)
Suppresses distributed log spam

Suppressed distributed logs

---

Jenkinsfile

Separate modular unittests into parallel jenkins nodes, to speed up the tests

[CI] separate unittest in parallel nodes

---

core/setup.py

Fixes install when NumPy isn't already installed, see https://github.com/automl/ConfigSpace/pull/115

Update ConfigSpace dependency

---

tabular/src/autogluon/tabular/models/tab_transformer/hyperparameters/parameters.py
tabular/src/autogluon/tabular/models/tab_transformer/hyperparameters/searchspaces.py
tabular/src/autogluon/tabular/models/tab_transformer/tab_transformer_model.py
tabular/src/autogluon/tabular/models/tab_transformer/utils.py
tabular/src/autogluon/tabular/task/tabular_prediction/tabular_prediction.py

Fix HPO CPU, bug fix for unlabeled/train mismatch, TT hyperparameter changes, train/pretrain split time_limits.

TabTransformer final fixes PR

---

Jenkinsfile
autogluon/setup.py
core/setup.py
docs/build_pip_install.sh
extra/setup.py
mxnet/setup.py
tabular/setup.py
text/setup.py
vision/setup.py

Parallel jenkins build_docs stage

parallel and stashing tutorials

---

tabular/src/autogluon/tabular/models/tab_transformer/hyperparameters/parameters.py
tabular/src/autogluon/tabular/models/tab_transformer/tab_transformer_model.py

Added num_gpus behavior for TabTransformer.

---

tabular/src/autogluon/tabular/trainer/abstract_trainer.py

Code cleanup
- Fixed refit_full using incorrect base models at L2+. The refit_full models were using all ancestors as base models instead of just the immediate predecessors. This issue didn't affect weighted ensembles, so it only occurred if `stack_ensemble_levels>=2` and `refit_full=True`.
- Code cleanup in trainer

Fixed refit_full using incorrect base models at L2+

---

tabular/src/autogluon/tabular/models/xgboost/xgboost_utils.py

Reduce nesting

---

docs/tutorials/tabular_prediction/tabular-faq.md
docs/tutorials/tabular_prediction/tabular-quickstart.md
examples/tabular/distill/example_distill_binary.py
examples/tabular/distill/example_distill_multiclass.py
examples/tabular/distill/example_distill_regression.py
examples/tabular/example_advanced_tabular.py
examples/tabular/example_simple_tabular.py
tabular/src/autogluon/tabular/data/label_cleaner.py
tabular/src/autogluon/tabular/models/ensemble/bagged_ensemble_model.py
tabular/src/autogluon/tabular/models/ensemble/stacker_ensemble_model.py
tabular/src/autogluon/tabular/task/tabular_prediction/predictor.py
tabular/tests/unittests/data/test_label_cleaner.py
tabular/tests/unittests/test_tabular.py

- Added out-of-fold methods to Predictor
- Added positive_class() method to Predictor (curious on if it should be property, variable, or method)
- Minor PEP8 cleanup

Tabular: Added out-of-fold methods to predictor.py

---

core/src/autogluon/core/constants.py
tabular/src/autogluon/tabular/models/catboost/catboost_model.py
tabular/src/autogluon/tabular/task/tabular_prediction/tabular_prediction.py
tabular/src/autogluon/tabular/trainer/abstract_trainer.py
tabular/src/autogluon/tabular/trainer/model_presets/presets.py
tabular/src/autogluon/tabular/trainer/model_presets/presets_distill.py
tabular/tests/unittests/models/test_catboost.py

#782 
- Changed model names based on agreed proposals in #782. 
- This PR does not incorporate the level+1 change due to the logic changes required (will do in separate PR).
- Keeps KNeighbors to avoid unnecessarily long name.
- NeuralNet -> NeuralNetMXNet
```
0                  CatBoost_BAG_L0
1                  CatBoost_BAG_L1
2             CatBoost_FULL_BAG_L0
3             CatBoost_FULL_BAG_L1
4            ExtraTreesEntr_BAG_L0
5            ExtraTreesEntr_BAG_L1
6       ExtraTreesEntr_FULL_BAG_L0
7       ExtraTreesEntr_FULL_BAG_L1
8            ExtraTreesGini_BAG_L0
9            ExtraTreesGini_BAG_L1
10      ExtraTreesGini_FULL_BAG_L0
11      ExtraTreesGini_FULL_BAG_L1
12           KNeighborsDist_BAG_L0
13 …
```

Tabular: Refactored model names

---

docs/build.yml
docs/build_contrib.yml
docs/tutorials/text_prediction/beginner.md
docs/tutorials/text_prediction/customization.md
extra/setup.py
text/src/autogluon/text/text_prediction/models/basic_v1.py

Reduce the runtime for the text notebooks.

[Test][Text] Reduce runtime of text tutorial

---

tabular/src/autogluon/tabular/models/abstract/abstract_model.py
tabular/src/autogluon/tabular/models/ensemble/stacker_ensemble_model.py
tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
tabular/src/autogluon/tabular/models/knn/knn_model.py
tabular/src/autogluon/tabular/models/lgb/lgb_model.py
tabular/src/autogluon/tabular/models/lr/lr_model.py
tabular/src/autogluon/tabular/models/rf/rf_model.py
tabular/src/autogluon/tabular/models/tabular_nn/tabular_nn_model.py
tabular/src/autogluon/tabular/task/tabular_prediction/tabular_prediction.py

Disabled forkserver forcing for HPO - it is unstable at the moment.

Disable forkserver forcing by default

---

examples/tabular/tabular-fasttext.ipynb
tabular/src/autogluon/tabular/models/fasttext/fasttext_model.py
tabular/src/autogluon/tabular/models/fasttext/hyperparameters/parameters.py

*Issue #, if available:* #580 
Added the fastText custom model. See  examples/tabular/tabular-fasttext.md for a demo. 

[Tabular][FastText] add fastText custom model for classification (#580)

---

tabular/src/autogluon/tabular/models/fasttext/fasttext_model.py
tabular/src/autogluon/tabular/trainer/model_presets/presets.py

Code cleanup for FastTextModel

Tabular: Code cleanup for FastTextModel

---

README.md
examples/hnas/example_mlp.py

Example mlp

---

tabular/src/autogluon/tabular/features/feature_metadata.py
tabular/src/autogluon/tabular/features/generators/category.py
tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py

- Updated feature generators to handle `bool` features as categorical
- Update fastai network to use `feature_metadata` APIs

[Tabular] Added booleans handling as categorical

---

docs/build_pip_install.sh

- if package is installed, this will wait for y/n user input without `-y`

[CI] fixing build script

---

core/src/autogluon/core/scheduler/fifo.py
core/src/autogluon/core/scheduler/hyperband.py
core/src/autogluon/core/scheduler/jobs.py
core/src/autogluon/core/scheduler/managers.py
core/src/autogluon/core/scheduler/rl_scheduler.py
core/src/autogluon/core/scheduler/scheduler.py
core/src/autogluon/core/utils/files.py
tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py

[Refactoring] Distributed code refactoring

---

tabular/src/autogluon/tabular/models/rf/rf_model.py

Optimized memory efficiency of RF/XT during training.
This helps in the case where the trees are massive in memory and training 8 trees + pickling 8 trees led to 16 trees in memory which raised a memory error during the memory safe check. This change makes it so only 5 trees are in memory at a time during the memory safe check, making it take ~3x less memory to avoid OOM errors.

Tabular: optimized memory efficiency of rf/xt during training

---

tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py

Missing values preprocessing fixes

[Tabular][fastai] Preprocessing fixes

---

tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py

- fixing missing category handling in fastai model

[Tabular][fastai] Missing category fix

---

core/src/autogluon/core/searcher/bayesopt/autogluon/config_ext.py
core/src/autogluon/core/searcher/bayesopt/autogluon/debug_log.py
core/src/autogluon/core/searcher/bayesopt/autogluon/gp_fifo_searcher.py
core/src/autogluon/core/searcher/bayesopt/autogluon/gp_multifidelity_searcher.py
core/src/autogluon/core/searcher/bayesopt/autogluon/hp_ranges.py
core/src/autogluon/core/searcher/bayesopt/gpautograd/kernel/exponential_decay.py
core/src/autogluon/core/searcher/bayesopt/gpautograd/kernel/product_kernel.py
core/src/autogluon/core/searcher/bayesopt/gpautograd/warping.py

- Various bug fixes (for example, in kernel computation code)
- Simplifications and small extensions

Various bug fixes

---

tabular/src/autogluon/tabular/models/abstract/abstract_model.py
tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
tabular/src/autogluon/tabular/models/tabular_nn/categorical_encoders.py

- Fixes FastAI crash whenever passed object dtype data.
- Improved FastAI logic to more cleanly utilize the API of abstract_model
- Fixed defect in XGB when new test time categories were present causing crash. (Often occurs in multimodal)

Tabular: Fix FastAI in multimodal

---

tabular/src/autogluon/tabular/models/text_prediction/text_prediction_v1_model.py

- Fixes crash if numeric columns have NaN values in TextPrediction.
TODO:

Tabular: Fixed TextPrediction crash when NaN values are present.

---

tabular/src/autogluon/tabular/data/label_cleaner.py
tabular/src/autogluon/tabular/learner/abstract_learner.py

- Changes internal learner scorer to use external label values in eval_metric calls rather than internal label values. This fixes edge case issues in `balanced_accuracy` when multiple new test time classes are provided and are all converted to class `-1` internally, causing an incorrect score to be returned.

Tabular: Fixed balanced_accuracy scoring issue with missing classes

---

core/src/autogluon/core/task/base/base_task.py
core/src/autogluon/core/utils/miscs.py
core/src/autogluon/core/utils/utils.py
examples/tabular/example_tabular_predictor_v2.py
tabular/src/autogluon/tabular/learner/abstract_learner.py
tabular/src/autogluon/tabular/learner/default_learner.py
tabular/src/autogluon/tabular/models/abstract/abstract_model.py
tabular/src/autogluon/tabular/models/abstract/model_trial.py
tabular/src/autogluon/tabular/models/ensemble/bagged_ensemble_model.py
tabular/src/autogluon/tabular/models/ensemble/greedy_weighted_ensemble_model.py
tabular/src/autogluon/tabular/models/ensemble/stacker_ensemble_model.py
tabular/src/autogluon/tabular/models/ensemble/weighted_ensemble_model.py
tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
tabular/src/autogluon/tabular/models/fasttext/fasttext_model.py
tabular/src/autogluon/tabular/models/knn/knn_model.py
tabular/src/autogluon/tabular/models/lgb/lgb_model.py
tabular/src/autogluon/tabular/models/lr/lr_model.py
tabular/src/autogluon/tabular/models/rf/rf_model.py
tabular/src/autogluon/tabular/models/tab_transformer/tab_transformer_model.py
tabular/src/autogluon/tabular/models/tabular_nn/tabular_nn_model.py
tabular/src/autogluon/tabular/models/xgboost/xgboost_model.py
tabular/src/autogluon/tabular/task/tabular_prediction/feature_generator_presets.py
tabular/src/autogluon/tabular/task/tabular_prediction/predictor.py
tabular/src/autogluon/tabular/task/tabular_prediction/predictor_v2.py
tabular/src/autogluon/tabular/task/tabular_prediction/tabular_prediction.py
tabular/src/autogluon/tabular/trainer/abstract_trainer.py
tabular/src/autogluon/tabular/trainer/auto_trainer.py
tabular/src/autogluon/tabular/trainer/model_presets/presets.py
tabular/src/autogluon/tabular/trainer/model_presets/presets_distill.py

- Added TabularPredictorV2
- Numerous internal cleanup and extensibility improvements
Note:
- I have various TODO's of logic that I plan to update after a few other major PRs are merged to avoid requiring rebases from other contributors.
This PR is part 1 of the API refactor logic:
Part 1: Majority of logic changes
Part 2: Migrate unit tests to use new API
Part 3: Remainder of logic changes + deprecate old API (Old API incompatible with the more complex logic changes without significant effort)
Part 4: Documentation of new API
Part 5: Removal of old Tabular API
Part 6: Update Text API to align with new API
Part 7: Update Vision API to align with new API …

[Part 1] Tabular: Added TabularPredictorV2

---

.gitignore
core/src/autogluon/core/metrics/__init__.py
tabular/src/autogluon/tabular/models/catboost/catboost_utils.py
tabular/src/autogluon/tabular/task/tabular_prediction/tabular_prediction.py

- added multi-class one-vs-one variant of roc_auc

[Tabular] added roc_auc one-vs-one for multi-class AUC classification

---

tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py

Disable ngram features in fastai model due to extremely long train and inference times.

Tabular: Disable ngram features in fastai model

---

core/src/autogluon/core/scheduler/fifo.py
tabular/src/autogluon/tabular/models/lgb/callbacks.py
tabular/src/autogluon/tabular/models/tabular_nn/tabular_nn_model.py

Improvements to HPO perfomance metrics charts
- now actual metric is displayed instead of generic `validation_performance`
- metric with 'less is better' are now displayed correctly without inverted -1 multiplier

[Tabular][HPO] fixes to HPO performance charts

---

text/src/autogluon/text/text_prediction/models/basic_v1.py

Fix due to the recent upgrade of the visualization code in https://github.com/awslabs/autogluon/pull/863

Fix Text HPO

---

text/src/autogluon/text/text_prediction/models/basic_v1.py

First dump the dataframes to parquet and load them in the internal train function.

[Fix][Text] Fix for large dataset

---

core/src/autogluon/core/utils/exceptions.py
core/src/autogluon/core/utils/utils.py
tabular/src/autogluon/tabular/features/generators/category.py
tabular/src/autogluon/tabular/models/abstract/abstract_model.py
tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
tabular/src/autogluon/tabular/models/text_prediction/text_prediction_v1_model.py
tabular/src/autogluon/tabular/task/tabular_prediction/predictor.py
tabular/src/autogluon/tabular/trainer/abstract_trainer.py
tabular/src/autogluon/tabular/trainer/auto_trainer.py
tabular/tests/unittests/features/generators/test_category.py

- Improved TextPrediction with category features
- Improved GPU usage logging.
- Trying to train TextPrediction Tabular model without GPU will now error instead of hang the process.
- TextPrediction model will now automatically use GPU if available.
- Added new `fillna` parameter to CategoryFeatureGenerator with option 'mode' to fillna to the mode category.

Tabular: Improved TextPrediction with category features, improved GPU usage logging.

---

tabular/src/autogluon/tabular/features/generators/abstract.py
tabular/src/autogluon/tabular/task/tabular_prediction/hyperparameter_configs.py
tabular/src/autogluon/tabular/trainer/model_presets/presets_custom.py

- Added 'multimodal' hyperparameters preset

Tabular: Added 'multimodal' hyperparameters preset

---

text/src/autogluon/text/text_prediction/models/basic_v1.py

https://github.com/awslabs/autogluon/issues/872
Enable multi-gpu in inference.

[Text][Fix] Support multi-gpu inference

---

.github/workflows/pypi_release.yml
.github/workflows/pythonpublish.yml

With arrays and for statements, we can expect the following:
- Addition of processing when releasing a new function

Make ci simpler and easier to maintain

---

text/src/autogluon/text/text_prediction/models/basic_v1.py

Previously, we used `time_out`, which should actually be `time_limits`.

[HPO][Text] Fix time_limits

---

core/setup.py

Prevent writing minor version file when release build is performed

[CI] Prevent writing minor version file when release build is performed

---

core/src/autogluon/core/metrics/__init__.py
core/src/autogluon/core/models/abstract/abstract_model.py
core/src/autogluon/core/models/abstract/model_trial.py
core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
core/tests/unittests/metrics/test_classification_metrics.py
tabular/src/autogluon/tabular/learner/abstract_learner.py
tabular/src/autogluon/tabular/models/catboost/catboost_model.py
tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
tabular/src/autogluon/tabular/models/lgb/callbacks.py
tabular/src/autogluon/tabular/models/lgb/hyperparameters/lgb_trial.py
tabular/src/autogluon/tabular/models/lgb/lgb_model.py
tabular/src/autogluon/tabular/models/tab_transformer/tab_transformer_model.py
tabular/src/autogluon/tabular/models/tab_transformer/utils.py
tabular/src/autogluon/tabular/models/tabular_nn/tabular_nn_model.py
tabular/src/autogluon/tabular/models/tabular_nn/tabular_nn_trial.py
tabular/src/autogluon/tabular/models/xgboost/xgboost_model.py
tabular/src/autogluon/tabular/task/tabular_prediction/predictor_legacy.py
tabular/src/autogluon/tabular/trainer/model_presets/presets.py
tabular/src/autogluon/tabular/trainer/model_presets/presets_custom.py

https://github.com/awslabs/autogluon/issues/263, https://github.com/awslabs/autogluon/issues/894
- Added GPU support for LightGBM, XGBoost, CatBoost, Neural Network Models. This is supported both in normal training and during HPO.
- Fixed major bug in CatBoost that occurs when it gets a perfect validation score causing it to perform much worse.

Tabular: Added GPU support for LightGBM, XGBoost, CatBoost, Neural Network Models

---

.github/workflows/pypi_release.yml
.github/workflows/pythonpublish.yml

Fix nightly pypi release to release autogluon.features

Fix nightly pypi release to release autogluon.features

---

core/src/autogluon/core/metrics/classification_metrics.py
tabular/src/autogluon/tabular/models/tab_transformer/tab_transformer_encoder.py
tabular/src/autogluon/tabular/models/tabular_nn/categorical_encoders.py
vision/src/autogluon/vision/utils/augment.py

Resolved numpy 1.20.0 dtype deprecation warnings

Resolved numpy 1.20.0 dtype deprecation warnings

---

core/src/autogluon/core/utils/decorators.py
tabular/src/autogluon/tabular/configs/presets_configs.py
tabular/src/autogluon/tabular/predictor/predictor.py

Moved presets decorators to core

Moved presets decorators to core

---

tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py

Re-enable ngram usage in FastAI

Tabular: Re-enable ngram usage in FastAI

---

Jenkinsfile
core/setup.py
docs/tutorials/object_detection/beginner.md
extra/setup.py
features/setup.py
mxnet/setup.py
tabular/setup.py
tabular/tests/unittests/features/generators/test_category.py
text/setup.py
vision/setup.py

- rework of build scripts to use clean venv for each build - this should improve libraries version compatibility checks so old dependencies are not masking such problems.
- version updates to ConfigSpace/numpy/pyarrow so they are compatible
- `batch_size` set to 8 for object detection to prevent GPU memory issues

[CI] Updates to build scripts to use clean venvs for each build

---

core/src/autogluon/core/models/abstract/abstract_model.py
tabular/src/autogluon/tabular/trainer/auto_trainer.py

Reduce logging noise from numpy 1.20 deprecation warnings coming from scipy

[Logging] Reduce numpy 1.20 deprecation warnings from scipy

---

core/setup.py
extra/setup.py
features/setup.py
mxnet/setup.py
tabular/setup.py
text/setup.py
vision/setup.py

Updating to use the latest compatible numpy

[Compatibility] Updating numpy to 1.9 -> 1.9.5

---

core/src/autogluon/core/metrics/__init__.py
core/src/autogluon/core/models/greedy_ensemble/ensemble_selection.py
tabular/src/autogluon/tabular/trainer/abstract_trainer.py

- Added tie_breaker options for EnsembleSelection, defaulted to 'second_metric'
Next Steps:

Tabular: Added tie_breaker options for EnsembleSelection, defaulted to 'second_metric'

---

core/setup.py
extra/setup.py
features/setup.py
mxnet/setup.py
tabular/setup.py
tabular/src/autogluon/tabular/models/xgboost/callbacks.py
tabular/src/autogluon/tabular/models/xgboost/hyperparameters/parameters.py
tabular/src/autogluon/tabular/models/xgboost/xgboost_model.py
text/setup.py

- Updated sklearn to 0.24
- Updated xgboost to 1.3

Updated sklearn and xgboost versions

---

autogluon/setup.py
core/setup.py
core/src/autogluon/core/_setup_utils.py
extra/setup.py
features/setup.py
mxnet/setup.py
tabular/setup.py
text/setup.py
vision/setup.py

- Simplified setup.py code, reduced code duplication

Simplified setup.py code, reduced code duplication

---

Jenkinsfile
core/setup.py

Updating ConfigSpace to address binary compatibility issues with numpy. See [ConfigSpace-173](https://github.com/automl/ConfigSpace/issues/173)

[CI] ConfigSpace binary compatibility fix

---

core/src/autogluon/core/models/abstract/abstract_model.py
core/src/autogluon/core/models/ensemble/stacker_ensemble_model.py
core/src/autogluon/core/models/greedy_ensemble/greedy_weighted_ensemble_model.py
tabular/src/autogluon/tabular/models/rf/rf_model.py
tabular/src/autogluon/tabular/models/tab_transformer/tab_transformer_model.py
tabular/src/autogluon/tabular/models/tabular_nn/tabular_nn_model.py
tabular/src/autogluon/tabular/trainer/abstract_trainer.py
tabular/src/autogluon/tabular/trainer/auto_trainer.py
tabular/src/autogluon/tabular/trainer/model_presets/presets.py
tabular/src/autogluon/tabular/trainer/model_presets/presets_distill.py

- Refactored distillation
- Now distillation also creates a weighted ensemble
- Fixed rare bug related to NaN validation scores in Neural Network

Tabular: Refactored distillation

---

tabular/src/autogluon/tabular/models/tabular_nn/embednet.py

Fix for bug in mxnet tabular neural net that appeared when GPU was used for certain regression tasks

fix GPU bug in mxnet neural net for regression

---

core/src/autogluon/core/utils/compression_utils.py
core/tests/unittests/test_compression_utils.py

*[Issue # 581](https://github.com/awslabs/autogluon/issues/581)*
Quick Follow up to [PR #940](https://github.com/awslabs/autogluon/pull/940) with PEP8 formatting changes.

follow up to PR #940 with PEP8 formatting changes

---

Jenkinsfile
autogluon/setup.py
core/setup.py
core/src/autogluon/core/searcher/skopt_searcher.py
core/src/autogluon/core/utils/try_import.py
core/src/autogluon/core/utils/utils.py
docs/build_pip_install.sh
docs/tutorials/tabular_prediction/tabular-indepth.md
full_install.sh
tabular/setup.py

- Made xgboost, catboost, lightgbm, fastai, torch, and skopt optional

Added optional dependencies

---

tabular/src/autogluon/tabular/learner/abstract_learner.py
tabular/src/autogluon/tabular/models/catboost/catboost_model.py

- Fixed CatBoost crashing when time_limit != None and stopping_metric = 'f1'.
- Fixed leaderboard, evaluate, and evaluate_predictions methods crashing with 'f1' metric when raw class labels are not integers.

Tabular: Fixed errors related to 'f1' metric.

---

core/src/autogluon/core/features/infer_types.py
core/src/autogluon/core/utils/savers/save_pkl.py
core/src/autogluon/core/utils/try_import.py
tabular/src/autogluon/tabular/trainer/abstract_trainer.py

- Verbose exception traceback will only be printed on verbosity>2 for ImportErrors
- Replaced overly verbose logger.exception calls (that include traceback) with logger.error calls.

Tabular: Improved exception handling

---

core/src/autogluon/core/models/abstract/abstract_model.py
core/src/autogluon/core/models/abstract/model_trial.py
core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
core/src/autogluon/core/models/ensemble/stacker_ensemble_model.py
core/src/autogluon/core/models/ensemble/weighted_ensemble_model.py
core/src/autogluon/core/models/greedy_ensemble/greedy_weighted_ensemble_model.py
examples/tabular/example_custom_model_tabular.py
tabular/src/autogluon/tabular/augmentation/distill_utils.py
tabular/src/autogluon/tabular/learner/abstract_learner.py
tabular/src/autogluon/tabular/models/catboost/catboost_model.py
tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
tabular/src/autogluon/tabular/models/fasttext/fasttext_model.py
tabular/src/autogluon/tabular/models/knn/knn_model.py
tabular/src/autogluon/tabular/models/knn/knn_utils.py
tabular/src/autogluon/tabular/models/lgb/lgb_model.py
tabular/src/autogluon/tabular/models/lr/lr_model.py
tabular/src/autogluon/tabular/models/rf/rf_model.py
tabular/src/autogluon/tabular/models/tab_transformer/tab_transformer_model.py
tabular/src/autogluon/tabular/models/tab_transformer/utils.py
tabular/src/autogluon/tabular/models/tabular_nn/tabular_nn_model.py
tabular/src/autogluon/tabular/models/tabular_nn/tabular_nn_trial.py
tabular/src/autogluon/tabular/models/text_prediction/text_prediction_v1_model.py
tabular/src/autogluon/tabular/models/xgboost/xgboost_model.py
tabular/src/autogluon/tabular/predictor/predictor.py
tabular/src/autogluon/tabular/task/tabular_prediction/predictor_legacy.py
tabular/src/autogluon/tabular/trainer/abstract_trainer.py
tabular/src/autogluon/tabular/trainer/auto_trainer.py
tabular/src/autogluon/tabular/tuning/feature_pruner.py
tabular/tests/unittests/test_tabular.py

- Renamed X_train -> X to align with sklearn API.
- Renamed y_train -> y to align with sklearn API.

Renamed X_train -> X, y_train -> y

---

full_install.sh

Add shebang to full_install.sh

---

core/src/autogluon/core/scheduler/scheduler_factory.py
core/src/autogluon/core/scheduler/seq_scheduler.py
core/src/autogluon/core/searcher/gp_searcher.py
core/src/autogluon/core/searcher/searcher.py
core/src/autogluon/core/task/base/base_task.py
tabular/src/autogluon/tabular/predictor/predictor.py
tabular/tests/unittests/models/test_text_prediction_v1_model.py
tabular/tests/unittests/scheduler/test_seq_scheduler.py
tabular/tests/unittests/test_tabular.py
text/src/autogluon/text/text_prediction/models/basic_v1.py
text/src/autogluon/text/text_prediction/text_prediction.py
text/tests/unittests/test_text_prediction.py

- Sequential scheduler
- CI binary compatibility fixes

Sequential Scheduler POC

---

docs/api/autogluon.task.rst
tabular/src/autogluon/tabular/predictor/predictor.py

- Removed legacy API note in documentation

Removed legacy API note in documentation

---

core/src/autogluon/core/constants.py
tabular/src/autogluon/tabular/learner/abstract_learner.py
tabular/src/autogluon/tabular/learner/default_learner.py
tabular/src/autogluon/tabular/predictor/predictor.py

extra string options for `sample_weight` argument.

support for predefined sample weights: ' balance', 'auto' options.

---

docs/api/autogluon.tabular.models.rst

*Issue #, if available:* #961
- Added documentation of name suffix meaning

Tabular: Added documentation of name suffix meaning

---

core/src/autogluon/core/models/abstract/abstract_model.py
core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
core/src/autogluon/core/models/ensemble/stacker_ensemble_model.py
core/src/autogluon/core/models/ensemble/weighted_ensemble_model.py
core/src/autogluon/core/models/greedy_ensemble/greedy_weighted_ensemble_model.py
core/src/autogluon/core/utils/try_import.py
tabular/src/autogluon/tabular/models/catboost/catboost_model.py
tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
tabular/src/autogluon/tabular/models/fasttext/fasttext_model.py
tabular/src/autogluon/tabular/models/knn/knn_model.py
tabular/src/autogluon/tabular/models/lgb/lgb_model.py
tabular/src/autogluon/tabular/models/lr/lr_model.py
tabular/src/autogluon/tabular/models/rf/rf_model.py
tabular/src/autogluon/tabular/models/tab_transformer/tab_transformer_model.py
tabular/src/autogluon/tabular/models/tabular_nn/tabular_nn_model.py
tabular/src/autogluon/tabular/models/text_prediction/text_prediction_v1_model.py
tabular/src/autogluon/tabular/models/xgboost/xgboost_model.py
tabular/src/autogluon/tabular/predictor/predictor.py

- Added documentation for AbstractModel
- Reduced logging verbosity of TextPredictor when used in Tabular.

Tabular: Added documentation of AbstractModel

---

tabular/src/autogluon/tabular/configs/hyperparameter_configs.py
tabular/src/autogluon/tabular/predictor/predictor.py
tabular/src/autogluon/tabular/trainer/abstract_trainer.py
tabular/src/autogluon/tabular/trainer/model_presets/presets_custom.py
tabular/tests/unittests/test_tabular.py
text/src/autogluon/text/text_prediction/predictor/predictor.py

- GBM preset -> GBMLarge and moved to 'GBM' list so it is filtered out by exclude_models.
- Documented 'multimodal' hyperparameters preset.
- Minor cleanup on TextPredictor.predict.

Tabular: Minor improvements

---

docs/tutorials/text_prediction/multimodal_text.md
text/src/autogluon/text/text_prediction/mx/models.py
text/src/autogluon/text/text_prediction/predictor/predictor.py
text/tests/unittests/text_prediction/test_predictor.py

Add class_labels to TextPredictor to align with the Tabular API. @Innixma 

[Text] Add class_labels to TextPredictor

---

core/src/autogluon/core/models/abstract/abstract_model.py
tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
tabular/src/autogluon/tabular/models/fasttext/fasttext_model.py
tabular/src/autogluon/tabular/models/rf/rf_model.py
tabular/src/autogluon/tabular/models/text_prediction/text_prediction_v1_model.py
tabular/src/autogluon/tabular/models/xgboost/xgboost_model.py

#967 
- Fixed FASTAI and AG_TEXT_NN model saving when inner model is None. (Crashed on high_quality/good_quality presets).
- Reduced code duplication in predict_proba.

Tabular: Fixed FASTAI and AG_TEXT_NN model saving

---

core/src/autogluon/core/data/label_cleaner.py
core/src/autogluon/core/task/base/base_task.py
docs/install-include.rst
docs/tutorials/tabular_prediction/tabular-faq.md
docs/tutorials/tabular_prediction/tabular-indepth.md
text/src/autogluon/text/text_prediction/mx/models.py

- Improved logging clarity for positive_class

Tabular: Improved logging clarity for positive_class

---

docs/api/autogluon.tabular.models.rst
examples/text_prediction/run_competition.py
tabular/src/autogluon/tabular/models/__init__.py
tabular/src/autogluon/tabular/models/text_prediction/text_prediction_v1_model.py
tabular/src/autogluon/tabular/trainer/model_presets/presets.py
text/src/autogluon/text/text_prediction/predictor/predictor.py

Add positive_class as the property. Also, add `as_multiclass` to predict_proba.
@Innixma 

[Text] Align API of TextPredictor to TabularPredictor

---

tabular/src/autogluon/tabular/models/text_prediction/text_prediction_v1_model.py
text/src/autogluon/text/text_prediction/mx/models.py
text/src/autogluon/text/text_prediction/mx/preprocessing.py
text/src/autogluon/text/text_prediction/predictor/predictor.py

Based on the offline discussion with @Innixma , we agree that the verbosity concept of TextPredictor should be verbosity of TabularPredictor + 1 because people may be more experienced in NLP / machine learning if they directly use TextPredictor.
This PR changes the verbosity level of TextPredictor.

[Text] Fix verbosity

---

docs/tutorials/text_prediction/customization.md
text/src/autogluon/text/text_prediction/presets.py

Update hpo tutorial to remove random search + hyperband opt because they are not stable currently

---

Jenkinsfile

Inject the s3 url to replace mnist download link

[CI] Fix torchvision dataset url

---

core/src/autogluon/core/models/abstract/abstract_model.py
core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
core/src/autogluon/core/utils/utils.py
tabular/src/autogluon/tabular/learner/abstract_learner.py
tabular/src/autogluon/tabular/models/text_prediction/text_prediction_v1_model.py
tabular/src/autogluon/tabular/predictor/predictor.py
tabular/src/autogluon/tabular/trainer/abstract_trainer.py

- Add option to calculate feature group importance
- Minor fix to drop ignored columns during raw feature importance, so they aren't returned in FI DF

Tabular: Add option to calculate feature group importance

---

core/src/autogluon/core/utils/try_import.py
tabular/src/autogluon/tabular/models/rf/rf_rapids_model.py

- Added initial RFRapidsModel
- Has significant difference in accuracy on AdultIncome dataset from sklearn. Tracking issue: https://github.com/rapidsai/cuml/issues/2518

Tabular: Added initial RFRapidsModel

---

tabular/src/autogluon/tabular/models/knn/knn_rapids_model.py

- Added initial RAPIDS KNN model
- On a p3.2xlarge, shows **1000x+** faster inference speed with zero accuracy drop compared to sklearn!!

Tabular: Added initial RAPIDS KNN model

---

tabular/src/autogluon/tabular/models/lr/hyperparameters/parameters.py
tabular/src/autogluon/tabular/models/lr/lr_model.py
tabular/src/autogluon/tabular/models/lr/lr_rapids_model.py

- Added initial RAPIDS LR model
- Refactored sklearn LR model

Tabular: Added initial RAPIDS LR model

---

tabular/src/autogluon/tabular/learner/abstract_learner.py

Add missing sample_weight to score_debug's EnsembleSelection

add sample_weight to score_debug EnsembleSelection

---

core/src/autogluon/core/scheduler/scheduler_factory.py
core/src/autogluon/core/scheduler/seq_scheduler.py
core/src/autogluon/core/searcher/bayesopt/autogluon/searcher_factory.py
core/src/autogluon/core/searcher/searcher_factory.py
core/src/autogluon/core/task/base/base_task.py
core/tests/unittests/core/scheduler/test_scheduler_factory.py
core/tests/unittests/test_base_task.py
docs/tutorials/tabular_prediction/tabular-indepth.md
tabular/src/autogluon/tabular/predictor/predictor.py
tabular/tests/unittests/test_tabular.py
text/src/autogluon/text/text_prediction/mx/models.py
text/src/autogluon/text/text_prediction/presets.py
vision/src/autogluon/vision/predictor/predictor.py

- Separating schedulers from searchers

[Schedulers] Schedulers Refactoring

---

docs/tutorials/image_prediction/dataset.md
docs/tutorials/image_prediction/index.rst
docs/tutorials/index.rst
docs/tutorials/object_detection/dataset.md
docs/tutorials/object_detection/index.rst
vision/src/autogluon/vision/detector/detector.py
vision/src/autogluon/vision/predictor/predictor.py
vision/src/autogluon/vision/utils/error_handler.py

Add tutorials and sanity checks for vision datasets.

[Vision] Tutorials for loading data

---

core/src/autogluon/core/models/abstract/_tags.py
core/src/autogluon/core/models/abstract/abstract_model.py
core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
tabular/src/autogluon/tabular/models/knn/_knn_loo_variants.py
tabular/src/autogluon/tabular/models/knn/knn_model.py
tabular/src/autogluon/tabular/models/knn/knn_rapids_model.py
tabular/src/autogluon/tabular/trainer/abstract_trainer.py
tabular/src/autogluon/tabular/trainer/model_presets/presets.py

Added LOO-based bagging alternative to KNN (enabled by default).
Now, during bagging KNN will only train a single model and use LOO to get unbiased training predictions for out-of-fold.
This results in a **10x-200x** reduction in training time, inference time, and disk space usage during bagging for KNN, with no statistical drop in model quality.
Code: (New version vs old version, new version is 100x faster to train/infer, takes up 100x less disk space)
```
from autogluon.tabular import TabularDataset, TabularPredictor
LABEL = 'class'
SAMPLE = 10000
path_prefix = 'https://autogluon.s3.amazonaws.com/datasets/AdultIncomeBinaryClassification/'
path_train = path_prefix + 'train_data.csv'
path_test = path_prefix + …
```

Tabular: Added LOO-based bagging alternative to KNN

---

core/src/autogluon/core/utils/try_import.py
tabular/setup.py
tabular/src/autogluon/tabular/models/fastainn/callbacks.py
tabular/src/autogluon/tabular/models/fastainn/fastai_helpers.py
tabular/src/autogluon/tabular/models/fastainn/hyperparameters/parameters.py
tabular/src/autogluon/tabular/models/fastainn/hyperparameters/searchspaces.py
tabular/src/autogluon/tabular/models/fastainn/imports_helper.py
tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py

Re-write of `NeuralNetFastAI` from fast.ai v1 to v2

[Tabular][FastAI] Upgrade fastai v1 -> fastai2

---

tabular/setup.py
tabular/src/autogluon/tabular/models/knn/_knn_loo_variants.py
tabular/src/autogluon/tabular/models/knn/knn_model.py
tabular/src/autogluon/tabular/models/lr/lr_model.py
tabular/src/autogluon/tabular/models/rf/rf_model.py
tabular/src/autogluon/tabular/models/xt/xt_model.py

Added daal4py support to KNN: https://intelpython.github.io/daal4py/
This results in an average of **25x speed-up** of KNN inference on intel CPUs compared to native sklearn with minimal to no accuracy loss. Combined with the optimized LOO stacking strategy, mainline with daal will be **250x+** faster than v0.1.0 for KNN models.
All that is needed to get the speedup is to install daal4py:
```
pip install autogluon
pip install daal4py
```
Benchmark result (only KNN models):
```
valid_tasks: 550
framework  time_train_s  metric_error  time_infer_s  bestdiff  loss_rescaled  time_infer_s_rescaled      rank  rank=1_count  rank=2_count  rank=3_count  rank>3_count  error_count
0  AutoGluon_bestquality_1h_2021_03_20_knn_v3_KNe...      0.959381 …
```

Tabular: Added initial daal4py support

---

core/src/autogluon/core/models/_utils.py
core/src/autogluon/core/models/abstract/abstract_model.py
core/src/autogluon/core/utils/early_stopping.py
tabular/src/autogluon/tabular/models/catboost/catboost_model.py
tabular/src/autogluon/tabular/models/lgb/callbacks.py
tabular/src/autogluon/tabular/models/lgb/lgb_model.py
tabular/src/autogluon/tabular/models/xgboost/xgboost_model.py

- Added Adaptive Early Stopping to LightGBM.
TODO:

Tabular: Added Adaptive Early Stopping

---

tabular/setup.py

Upgraded CatBoost to v0.25
TODO:

Tabular: Upgraded CatBoost to v0.25

---

core/src/autogluon/core/_setup_utils.py
tabular/setup.py

- Upgraded psutil and scipy versions

Upgrade psutil and scipy

---

text/src/autogluon/text/text_prediction/mx/models.py

Issue # 1085
Check predictions shape and use second column if more than one for binary problems.

TextPredictor fails if eval_metric = 'average_precision'

---

README.md

- Added tutorial / API reference table to README.md

Added tutorial / API reference table to README.md

---

Jenkinsfile
core/src/autogluon/core/features/feature_metadata.py
core/src/autogluon/core/features/types.py
core/src/autogluon/core/utils/try_import.py
features/src/autogluon/features/generators/auto_ml_pipeline.py
features/src/autogluon/features/generators/category.py
features/src/autogluon/features/generators/drop_unique.py
tabular/src/autogluon/tabular/models/__init__.py
tabular/src/autogluon/tabular/models/image_prediction/image_predictor.py
tabular/src/autogluon/tabular/models/text_prediction/text_prediction_v1_model.py
tabular/src/autogluon/tabular/trainer/model_presets/presets.py
tabular/tests/unittests/models/test_image_predictor.py

Tabular: Added ImagePredictorModel

---

docs/install-include.rst

- Added documentation of each of the optional dependencies of Tabular
- Added documentation of `autogluon.mxnet`

Updated submodule install docs

---

tabular/src/autogluon/tabular/models/lgb/hyperparameters/parameters.py
tabular/src/autogluon/tabular/trainer/model_presets/presets.py
tabular/src/autogluon/tabular/trainer/model_presets/presets_custom.py

- Removed redundant params in LightGBMLarge config (they are already set by defaults).
- Removed need to specify num_classes when getting LightGBMLarge config.

Simplify custom LightGBM config

---

core/src/autogluon/core/models/abstract/abstract_model.py
tabular/src/autogluon/tabular/models/knn/knn_model.py
tabular/src/autogluon/tabular/models/knn/knn_rapids_model.py
tabular/src/autogluon/tabular/models/rf/rf_model.py
tabular/src/autogluon/tabular/models/rf/rf_rapids_model.py
tabular/src/autogluon/tabular/trainer/model_presets/presets.py

- Make special RF quantile ensemble logic live in model code

Clean RF quantile ensemble logic

---

docs/tutorials/tabular_prediction/tabular-faq.md

#1097 
- Added documentation on training models with GPU to Tabular FAQ

Tabular: Added GPU training instructions to FAQ

---

core/src/autogluon/core/utils/utils.py
tabular/src/autogluon/tabular/predictor/predictor.py
tabular/src/autogluon/tabular/trainer/abstract_trainer.py
tabular/src/autogluon/tabular/trainer/auto_trainer.py

#1096 
- Added warning when time_limit=None and data is large.
- Hid NumExpr log statement caused by pandas.

Tabular: Added time_limit=None warning

---

vision/src/autogluon/vision/predictor/predictor.py
vision/tests/unittests/test_image_classification.py

Fix #1109
Check for ImageDataset with invalid labels, try to auto-correct it if possible.

[Vision] Increase validation check for ImagePredictor dataset, fix #1109

---

tabular/src/autogluon/tabular/predictor/predictor.py
text/src/autogluon/text/text_prediction/mx/models.py
text/src/autogluon/text/text_prediction/predictor/predictor.py

#1115
- Add more detailed error messages when users pass invalid data objects.

Clarify dtype requirement for data

---

core/src/autogluon/core/__init__.py
features/src/autogluon/features/binning.py
features/src/autogluon/features/generators/astype.py
features/src/autogluon/features/generators/binned.py
features/src/autogluon/features/generators/category.py
features/src/autogluon/features/generators/fillna.py
features/src/autogluon/features/generators/memory_minimize.py
features/src/autogluon/features/generators/text_ngram.py
features/src/autogluon/features/generators/text_special.py
tabular/src/autogluon/tabular/augmentation/distill_utils.py
tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
tabular/src/autogluon/tabular/models/lgb/lgb_model.py
tabular/tests/unittests/features/generators/test_auto_ml_pipeline.py
tabular/tests/unittests/features/generators/test_bulk.py
tabular/tests/unittests/features/generators/test_category.py
tabular/tests/unittests/features/generators/test_pipeline.py
tabular/tests/unittests/features/generators/test_text_special.py

- 2.5x+ speedup of online-inference latency in feature generation.
- 7.8x+ speedup when text features are present.
- ~30%+ speedup for FastAI NN inference when many features are present.
- Slight speedup for LightGBM when text features are present.
TODO:

[Tabular] Online inference optimization

---

core/src/autogluon/core/data/label_cleaner.py
core/src/autogluon/core/features/feature_metadata.py
core/src/autogluon/core/models/abstract/abstract_model.py
core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
core/src/autogluon/core/models/ensemble/stacker_ensemble_model.py
core/src/autogluon/core/models/greedy_ensemble/greedy_weighted_ensemble_model.py
core/src/autogluon/core/utils/utils.py
examples/tabular/example_custom_model_tabular.py
tabular/src/autogluon/tabular/models/lgb/hyperparameters/parameters.py
tabular/src/autogluon/tabular/models/lgb/lgb_model.py
tabular/src/autogluon/tabular/trainer/abstract_trainer.py
tabular/src/autogluon/tabular/trainer/auto_trainer.py
tabular/src/autogluon/tabular/trainer/model_presets/presets.py
tabular/tests/conftest.py
tabular/tests/unittests/data/test_label_cleaner.py
tabular/tests/unittests/models/test_lightgbm.py

- Made name, path, problem_type, num_classes arguments optional (inferred / defaulted if not specified)
Now users can initialize and fit a model outside of a predictor easily:
```
from autogluon.tabular.models import RFModel
model = RFModel()
model.fit(X=X_train, y=y_train, X_val=X_val, y_val=y_val)
```
```
from autogluon.tabular.models import LGBModel
from autogluon.core.models import BaggedEnsembleModel
bagged_model = BaggedEnsembleModel(LGBModel())
bagged_model.fit(X=X_train, y=y_train)
```
This should simplify the contribution of new models and make testing models easier.
TODO:
Code Example:
```
from autogluon.tabular import TabularDataset
path_prefix = …
```

Tabular: Simplify AbstractModel initialization

---

Jenkinsfile
forecasting/setup.py
forecasting/src/autogluon/__init__.py
forecasting/tests/conftest.py
forecasting/tests/test_check_style.py
forecasting/tests/unittests/test_forecasting.py
full_install.sh

Need this separate PR to update Jenkinsfile (this PR just uses a dummy forecasting submodule), as this file can only be updated in PRs solely authored by certain authors.

update forecast CI

---

core/src/autogluon/core/_setup_utils.py
vision/src/autogluon/vision/predictor/predictor.py
vision/src/autogluon/vision/utils/__init__.py
vision/src/autogluon/vision/utils/space_sanitizer.py
vision/tests/unittests/test_image_classification.py

#1179
- Fix batch size, catch invalid types
- Add unittests for presets

[Vision] Fix #1179: fix batch size, add unittest

---

core/src/autogluon/core/utils/plots.py
docs/tutorials/tabular_prediction/tabular-indepth.md
docs/tutorials/tabular_prediction/tabular-quickstart.md
examples/tabular/example_simple_tabular.py
tabular/src/autogluon/tabular/predictor/predictor.py

#1062 
- Disables showing plot by default to avoid halting scripts, particularly if the user is using command line.

Tabular: Avoid showing plot by default in fit_summary()

---

text/setup.py

#1053
- Remove pyarrow dependency. Users can install pyarrow separately if they wish to load parquet files.

Text: Remove pyarrow

---

forecasting/src/autogluon/forecasting/__init__.py

- Added version to Forecasting

Forecasting: Added version

---

core/src/autogluon/core/models/__init__.py
core/src/autogluon/core/models/abstract/abstract_model.py
core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
core/src/autogluon/core/models/greedy_ensemble/ensemble_selection.py
core/src/autogluon/core/models/greedy_ensemble/greedy_weighted_ensemble_model.py
core/src/autogluon/core/utils/utils.py
tabular/src/autogluon/tabular/learner/default_learner.py
tabular/src/autogluon/tabular/predictor/predictor.py
tabular/src/autogluon/tabular/trainer/abstract_trainer.py
tabular/src/autogluon/tabular/trainer/auto_trainer.py
tabular/src/autogluon/tabular/trainer/model_presets/presets.py
tabular/tests/unittests/test_tabular.py

- Added use_bag_holdout option to allow bagging/stacking with a holdout set. (This is not equivalent to blending)
- Greatly improved handling of rare classes in various situations + bug fixes to rare class duplication logic.
Before merging:

[Tabular] Added use_bag_holdout functionality

---

tabular/src/autogluon/tabular/models/image_prediction/image_predictor.py

#1207 
- Fixed crash when images are null in train or test

Vision: Fixed crash when image is null

---

features/src/autogluon/features/generators/__init__.py
features/src/autogluon/features/generators/auto_ml_pipeline.py
features/src/autogluon/features/generators/isnan.py
tabular/tests/unittests/features/generators/test_isnan.py

- Adds IsNanFeatureGenerator which adds boolean flag features on if values are null.
- Currently enabled only for image path features, to indicate to tabular models whether an image is present or not.

Features: Added IsNanFeatureGenerator

---

tabular/setup.py
tabular/src/autogluon/tabular/models/xgboost/xgboost_model.py

- Update XGBoost to 1.4
- Default XGBoost tree_method hyperparameter to 'hist'
TODO:

Tabular: Update XGBoost to 1.4, default to tree_method='hist'

---

docs/model_zoo/index.rst
vision/src/autogluon/vision/predictor/predictor.py

#158 
- Fix efficientnet docs
- Added FIXME: 'imagenet' does not work as input dataset

Vision: Fixed docs description, added FIXME

---

docs/api/autogluon.tabular.models.rst
docs/tutorials/index.rst
docs/tutorials/tabular_prediction/index.rst
docs/tutorials/tabular_prediction/tabular-custom-model.md
docs/tutorials/tabular_prediction/tabular-faq.md
docs/tutorials/tabular_prediction/tabular-indepth.md
tabular/src/autogluon/tabular/models/lgb/lgb_model.py

#1214 
- Added custom model tutorial to Tabular docs

Docs: Added Tabular Custom Model tutorial

---

core/src/autogluon/core/utils/utils.py
docs/tutorials/tabular_prediction/tabular-indepth.md
examples/object_detection/benchmark.py
tabular/src/autogluon/tabular/models/image_prediction/image_predictor.py
tabular/src/autogluon/tabular/models/text_prediction/text_prediction_v1_model.py
text/src/autogluon/text/text_prediction/mx/models.py
vision/src/autogluon/vision/configs/presets_configs.py
vision/src/autogluon/vision/detector/detector.py
vision/src/autogluon/vision/predictor/predictor.py

#1127
- Hopefully fixes issues with GPU not being detected on Windows.

Fixed GPU usage on Windows

---

docs/tutorials/tabular_prediction/tabular-indepth.md
tabular/src/autogluon/tabular/learner/abstract_learner.py
tabular/src/autogluon/tabular/predictor/predictor.py

- Added `predictor.features()`
- Added features and feature_metadata_in to `predictor.info()` output.

Tabular: Added predictor.features()

---

Jenkinsfile
docs/build_pip_install.sh
docs/tutorials/forecasting/index.rst
docs/tutorials/forecasting/temp.md

Update to jenkinsfile for forecasting that cannot be made from forecasting PR

update jenkinsfile forecasting stash

---

core/src/autogluon/core/_setup_utils.py
core/src/autogluon/core/models/ensemble/ray_parallel_fold_fitting_strategy.py

Updating pillow to the the version without known security issues

[Security][CV] - Updating pillow to versions without known security issues

---

core/src/autogluon/core/_setup_utils.py

- Updated pandas version since 1.3.1 released fixing the regression in 1.3.0

Updated pandas version

---

core/setup.py

- Updated ConfigSpace from 0.4.18 -> 0.4.19

Update ConfigSpace version

---

core/src/autogluon/core/models/abstract/abstract_model.py
core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
core/src/autogluon/core/models/ensemble/stacker_ensemble_model.py
tabular/src/autogluon/tabular/trainer/abstract_trainer.py
tabular/src/autogluon/tabular/trainer/auto_trainer.py
tabular/src/autogluon/tabular/trainer/model_presets/presets.py

- Fixed incorrect implementation of `convert_to_template`
- Fixed incorrect output of `_get_init_args`, renamed to `get_params` to align with sklearn
- Moved `stopping_metric` and `quantile_levels` to ag_args_fit to simplify code logic
- Refactored refit_full logic to minimize chance of defects in future
- Fixed user specified stopping_metric being ignored

Tabular: Refactor AbstractModel

---

core/src/autogluon/core/metrics/__init__.py
core/src/autogluon/core/utils/loaders/load_pd.py
docs/tutorials/index.rst
docs/tutorials/tabular_prediction/index.rst
docs/tutorials/tabular_prediction/tabular-custom-metric.md
features/src/autogluon/features/generators/category.py
features/src/autogluon/features/generators/memory_minimize.py

- Added custom metric tutorial
- Sped up regression metric calculations by ~50%
- Removed error_bad_lines in load_pd as it is deprecated in pandas 1.3

Tabular: Added custom metric tutorial

---

core/setup.py
core/src/autogluon/core/_setup_utils.py
core/src/autogluon/core/dataset.py
core/src/autogluon/core/utils/miscs.py
extra/src/autogluon/extra/contrib/enas/enas.py
tabular/src/autogluon/tabular/learner/abstract_learner.py
tabular/src/autogluon/tabular/trainer/abstract_trainer.py
text/src/autogluon/text/text_prediction/mx/models.py
vision/src/autogluon/vision/detector/detector.py
vision/src/autogluon/vision/predictor/predictor.py

- Upgrade numpy
- Upgrade graphviz
- Upgrade dill
- Fix logging / warning filters, avoided altering global context

Upgrade numpy, graphviz, dill

---

Jenkinsfile
core/src/autogluon/core/utils/loaders/_utils.py
core/src/autogluon/core/utils/loaders/load_zip.py
docs/index.rst
docs/tutorials/index.rst
docs/tutorials/tabular_prediction/index.rst
docs/tutorials/tabular_prediction/tabular-multimodal-text-others.md
docs/tutorials/tabular_prediction/tabular-multimodal.md
tabular/src/autogluon/tabular/configs/hyperparameter_configs.py

- Added multimodal image, text, tabular tutorial

Added multimodal tutorial

---

core/src/autogluon/core/features/feature_metadata.py
core/src/autogluon/core/features/infer_types.py
core/src/autogluon/core/features/types.py
features/src/autogluon/features/generators/astype.py
features/src/autogluon/features/generators/isnan.py
tabular/src/autogluon/tabular/models/knn/knn_model.py
tabular/tests/unittests/features/generators/test_isnan.py

- Automatically convert features with only 2 unique values to boolean
- Drop boolean features for KNN, speeds up KNN by 100x+ without loss of quality on datasets such as CoverType.
TODO:

Tabular: Added automatic boolean conversion

---

tabular/src/autogluon/tabular/predictor/predictor.py

- Fixed error when use_bag_holdout=True and save_bag_folds=False (Such as with high quality preset)

Tabular: Fixed error when use_bag_holdout=True and save_bag_folds=False

---

tabular/src/autogluon/tabular/predictor/predictor.py

#475 
- Save predictor prior to fit to enable continuing training or perform predictions after a crash.
- Users should use `predictor.fit_extra` to fit additional models after reloading the predictor from a crash.

Tabular: Save predictor prior to fit

---

docs/tutorials/tabular_prediction/tabular-multilabel.md

Bugfixes related to optional path, eval_metrics in multilabel predictor
May help address issues like:  https://github.com/awslabs/autogluon/discussions/1307

multilabel bug fixes

---

core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py

#1357
- A bug occurs if doing HPO without time limit, with bagging enabled, and with `num_bag_sets>1` which causes an index error during bagging due to an incorrectly valued `fold_end_n_repeat` value.
- This fix corrects the calculation of `fold_end_n_repeat` and updates the `cv_splitter` if it doesn't have enough `n_repeats` during its init to have enough `kfolds` output.
- Previously, when doing HPO the first fold of the first repeat is trained. Then later the remaining folds and repeats are trained after HPO has finished. Because n_repeats=1 during HPO, the cv_splitter doesn't have information on the kfold splits for n_repeats>1 when performing the remaining folds + repeats in the 2nd part, causing a crash. Additionally, the incorrect …

Tabular: Fixed index error bug in bagging logic

---

core/src/autogluon/core/calibrate/temperature_scaling.py
core/src/autogluon/core/models/abstract/abstract_model.py
core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
core/src/autogluon/core/trainer/abstract_trainer.py
tabular/src/autogluon/tabular/predictor/predictor.py

Applies temperature scaling to model if calibrate is true and multiclass is problem type

Temperature scaling

---

Jenkinsfile
docs/index.rst
docs/tutorials/cloud_fit_deploy/cloud-aws-lambda-deployment.md
docs/tutorials/cloud_fit_deploy/cloud-aws-sagemaker-deployment.md
docs/tutorials/cloud_fit_deploy/cloud-aws-sagemaker-training.md
docs/tutorials/cloud_fit_deploy/index.rst
docs/tutorials/index.rst

Adding cloud fit/deploy documentation.

[docs] Cloud Training with AWS SageMaker

---

docs/tutorials/cloud_fit_deploy/index.rst

[docs] link fix

---

docs/install-include.rst

Documentations changes with instructions how to install pytorch CPU version

[docs] Added pytorch installation recommendation for CPU deployments

---

tabular/src/autogluon/tabular/predictor/predictor.py

- Raise exception if duplicate indices in data.
- Fixes incorrect prediction dimensions returned in `predictor.get_oof_pred_proba` when training data contained duplicate indices.
- Fixed incorrect eval metric comparison in pseudo labeling logic (only impacts warning message).

Tabular: Raise Exception if duplicate indices present in data

---

core/src/autogluon/core/utils/utils.py

- Fixed incorrect log on problem_type declaration

Tabular: Fixed incorrect log on problem_type declaration

---

examples/tabular/example_quantile_regression.py

improve presentation of the quantile-regression example

improve quantile example presentation

---

features/src/autogluon/features/generators/text_ngram.py
features/src/autogluon/features/vectorizers.py

get_feature_names -> get_feature_names_out

---

Jenkinsfile
autogluon/setup.py
core/setup.py
core/src/autogluon/core/models/abstract/abstract_model.py
core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
core/src/autogluon/core/models/ensemble/fold_fitting_strategy.py
core/src/autogluon/core/trainer/abstract_trainer.py
core/src/autogluon/core/utils/exceptions.py
core/src/autogluon/core/utils/try_import.py
core/tests/test_check_style.py
core/tests/unittests/test_parallel_local_folding.py
docs/build_pip_install.sh
docs/tutorials/tabular_prediction/tabular-custom-model.md
tabular/src/autogluon/tabular/models/catboost/catboost_model.py
tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
tabular/src/autogluon/tabular/models/knn/knn_model.py
tabular/src/autogluon/tabular/models/lgb/lgb_model.py
tabular/src/autogluon/tabular/models/lr/lr_model.py
tabular/src/autogluon/tabular/models/rf/rf_model.py
tabular/src/autogluon/tabular/models/tabular_nn/tabular_nn_model.py
tabular/src/autogluon/tabular/models/xgboost/xgboost_model.py
tabular/src/autogluon/tabular/predictor/predictor.py
tabular/tests/unittests/test_tabular.py

Added support for training folds in parallel.

Ray parallel

---

core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
tabular/tests/unittests/test_tabular.py

Disable parallel for now while fixing it

disable parallel

---

tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py

- Make FastAI training deterministic (Same model trained given same data/hyperparameters)

Tabular: Make FastAI deterministic

---

common/src/autogluon/common/utils/log_utils.py
core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
tabular/src/autogluon/tabular/predictor/predictor.py

ray not working correctly on macos: https://github.com/ray-project/ray/issues/20084. Hence, disabling it on macos until the issue is fixed.

Disable parallel on macos

---

core/src/autogluon/core/models/abstract/abstract_model.py
core/src/autogluon/core/models/abstract/model_trial.py
core/src/autogluon/core/scheduler/__init__.py
core/src/autogluon/core/scheduler/scheduler_factory.py
core/src/autogluon/core/scheduler/seq_scheduler.py
core/src/autogluon/core/searcher/__init__.py
core/src/autogluon/core/searcher/local_random_searcher.py
core/src/autogluon/core/searcher/local_searcher.py
core/src/autogluon/core/searcher/searcher_factory.py
core/src/autogluon/core/space.py
core/src/autogluon/core/task/base/base_task.py
core/tests/unittests/core/scheduler/test_scheduler_factory.py
core/tests/unittests/test_local_random_searcher.py
core/tests/unittests/test_local_searcher.py
docs/tutorials/image_prediction/hpo.md
docs/tutorials/tabular_prediction/tabular-indepth.md
tabular/tests/unittests/scheduler/test_seq_scheduler.py
tabular/tests/unittests/test_tabular.py
text/src/autogluon/text/text_prediction/mx/models.py
text/src/autogluon/text/text_prediction/presets.py
text/tests/unittests/text_prediction/test_predictor.py

- Added LocalSearcher and LocalRandomSearcher which don't depend on ConfigSpace
- These searchers use no multiprocessing or locks, and therefore can be ran in Python debugger
- Greatly simplified HPO logic, removed usage of ag.args and decorators
TODO:

Added Local Searcher

---

Jenkinsfile
docs/build_contrib_gpu.yml
docs/build_gpu.yml

Fix CI by installing cuda env with conda

---

tabular/src/autogluon/tabular/models/fastainn/callbacks.py
tabular/src/autogluon/tabular/models/fastainn/hyperparameters/parameters.py
tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
tabular/tests/unittests/models/test_tabular_nn_fastai.py

- adaptive batch size and epochs number selection
- normalization process improvements

[fastai] adaptive batch size and epochs number selection; normalization improvements

---

core/setup.py
core/src/autogluon/core/_setup_utils.py
core/src/autogluon/core/utils/try_import.py
forecasting/setup.py

- Remove unused dependencies cython, dill, paramiko, autograd

Remove cython, dill, paramiko, autograd

---

docs/tutorials/index.rst

[docs] index cards missing

---

.github/workflows/platform_tests-command.yml
.github/workflows_env/unittest_env.yml
CONTRIBUTING.md
tabular/tests/unittests/models/test_image_predictor.py
tabular/tests/unittests/models/test_text_prediction_v1_model.py

Platform tests(macos and windows) that can be triggerd by chatOP

Platform Tests

---

core/src/autogluon/core/utils/utils.py
tabular/src/autogluon/tabular/learner/abstract_learner.py
tabular/tests/unittests/test_tabular.py

https://github.com/awslabs/autogluon/issues/1434
Return empty prediction if given empty dataframe.

Fix empty predict

---

docs/tutorials/image_prediction/beginner.md
docs/tutorials/image_prediction/dataset.md
docs/tutorials/image_prediction/hpo.md
docs/tutorials/tabular_prediction/tabular-custom-metric.md
docs/tutorials/tabular_prediction/tabular-faq.md
docs/tutorials/tabular_prediction/tabular-indepth.md
docs/tutorials/tabular_prediction/tabular-kaggle.md
docs/tutorials/tabular_prediction/tabular-multimodal.md
docs/tutorials/tabular_prediction/tabular-quickstart.md

1477
Minor typos and grammar fixes to tabular and image documentation. 

fix minor typos and grammar

---

common/src/autogluon/common/features/infer_types.py
core/src/autogluon/core/utils/utils.py
tabular/src/autogluon/tabular/learner/default_learner.py

https://github.com/awslabs/autogluon/issues/957
The issue was caused by numpy not able to recognize pandas new string dtype while autogluon inferring problem type. String dtype should be categorized as MULTICLASS

Fix string dtype

---

core/src/autogluon/core/searcher/local_grid_searcher.py
core/tests/unittests/searcher/test_local_grid_searcher.py

Added support for numeric spaces for LocalGridSearcher

Added support for numeric spaces for LocalGridSearcher

---

core/src/autogluon/core/scheduler/scheduler_factory.py

https://github.com/awslabs/autogluon/issues/1492
Disabled bayesopt and use random instead.

disable bayesopt

---

core/src/autogluon/core/utils/try_import.py
tabular/src/autogluon/tabular/models/vowpalwabbit/vowpalwabbit_model.py

https://github.com/awslabs/autogluon/issues/1498
* Filter out image_path as vowpal model input
* Fixed a version incompatibility

fix vowpal

---

README.md

Updated links to the containers and cloud deployment docs

[docs] updating containers doc links

---

README.md
ROADMAP.md

- Added initial ROADMAP.md
- Removed outdated NAS link in README.md

Added ROADMAP.md

---

tabular/src/autogluon/tabular/models/xgboost/xgboost_model.py

- Instead of saving to pickle (which internally xgboost saves to json) we instead save to binary using XGBoost's save/load API.
- This speeds up loading by ~10-15x, previously it was very slow compared to other models.
- Halves disk usage due to more tight save format.
- Overall speeds up inference on AutoGluon BestQuality by 40%, AutoGluon MediumQuality by 10%, much more for online inference if models not persisted.
- On average XGBoost is 6x-7x faster during inference.
Benchmark comparisons:
2022_01_19_cal == Mainline
2022_01_21_xgb == This PR
~647% inf speedup on XGBoost:
```
AutoGluon_4h8c_2022_01_19_cal_XGBoost VS all
framework  winrate  >  <     =  % Less Avg. Errors  time_train_s  time_infer_s  loss_rescaled  time_train_s_rescaled …
```

Optimize XGBoost Save/Load

---

tabular/src/autogluon/tabular/predictor/predictor.py

https://github.com/awslabs/autogluon/issues/1418
Raise exception if duplicate index found in the data. Previously this check was done only for `fit`, added this check to other APIs

Validate unique indices for various API

---

.github/workflows/platform_tests-command.yml
tabular/src/autogluon/tabular/models/tabular_nn/torch/torch_network_modules.py

* Add tabular[tests] dependency to platform tests
* Fixed tensor type on windows

Add tabular tests dependency to platform test

---

tabular/src/autogluon/tabular/configs/config_helper.py
tabular/tests/unittests/autogluon/tabular/configs/test_config_helper.py

Added helper methods to enable AG config building with fluent python APIs. The primary benefits are intellisense assistance in IDE with granular help docs on attribute level.
Additional methods added to facilitate the request https://github.com/awslabs/autogluon/issues/1458.
Usage:
```python
config = (ConfigBuilder()
.presets('best_quality')
.hyperparameters('light')
.included_model_types(['GBM', 'KNN'])
.feature_generator().enable_numeric_features(False).enable_text_ngram_features(False).build()
.time_limit(60)
.build())
predictor = TabularPredictor(label=label, path='/Users/ashyrkou/Projects/autogluon/temp/').fit(train_data, **config)
```
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …

TabularPredictor config helper

---

core/src/autogluon/core/_setup_utils.py

Capped version of pandas because pandas 1.4.0 because of issue: https://github.com/pandas-dev/pandas/issues/45603

cap pandas version

---

core/src/autogluon/core/_setup_utils.py
features/src/autogluon/features/generators/text_ngram.py
features/src/autogluon/features/generators/text_special.py
features/tests/features/conftest.py
features/tests/features/generators/test_text_ngram.py
features/tests/features/generators/test_text_special.py

https://github.com/awslabs/autogluon/issues/1300
Fill empty string if the category is nan

Handle nan in categorical feature in text feature generator

---

core/src/autogluon/core/utils/try_import.py
tabular/setup.py

#1341
Cap dependency versions, first cut.  Most are already implemented prior to this change.

Cap dependency versions [1341]

---

docs/tutorials/tabular_prediction/index.rst
docs/tutorials/tabular_prediction/tabular-gpu.md

Added Training models with GPU support section

[docs] Added Training models with GPU support section

---

tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py

Exclude ngrams for FastAI to speedup inference speed by 20x+.
Previously, FastAI is very slow if given many ngrams as input, and accuracy is not good compared to a language model. It is better to not send ngrams to FastAI. This improves inference latency for 1 row of data from 1.5 seconds to 75 ms for NLP datasets.
Additionally added a copy to preprocessing to avoid warning from pandas regarding fragmented DF.

Tabular: Exclude ngrams for FastAI

---

.github/workflows/platform_tests-command.yml

Add platform nightly tests. Will be triggered 11:59 pm PST everyday.

Add platform nightly tests

---

CONTRIBUTING.md
tabular/src/autogluon/tabular/configs/hyperparameter_configs.py
tabular/src/autogluon/tabular/models/rf/rf_quantile.py
tabular/src/autogluon/tabular/predictor/predictor.py
tabular/src/autogluon/tabular/trainer/model_presets/presets.py
tabular/src/autogluon/tabular/trainer/model_presets/presets_distill.py

#1542 
Rename 'mse' to 'squared_error' in parameters to sklearn::xt and sklearn::rf

Fix trees MSE deprecation warning [1542]

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/doc_improvement.yml

- Updated bug_report.md to have improved formatting + more instructions
- Added doc_improvement.yml to include a doc improvement issue template.
- Added config.yml that provides links to discussion and blank templates.

Updated bug_report.md, added doc_improvement.yml, added config.yml

---

Jenkinsfile
docs/tutorials/text_prediction/beginner.md
docs/tutorials/text_prediction/multilingual_text.md
docs/tutorials/text_prediction/multimodal_text.md
text/src/autogluon/text/automm/predictor.py
text/src/autogluon/text/text_prediction/predictor.py
text/src/autogluon/text/text_prediction/presets.py
text/tests/unittests/text_prediction/test_predictor_pytorch.py

- Fix bfloat16. Now we will automatically switch to 32 if bfloat16 is not supported.
- Add a `enable_progress_bar` flag and an environmental variable "AUTOMM_DISABLE_PROGRESS_BAR" to disable progress bar.

Fix bfloat16 support + Fix documentation

---

docs/index.rst
docs/static/mxnet.css

* Add badges
* Fix badge and table format. Table now has correct alignment 
* Table still has word break problem. This should be caused by d2lbook as sphinx rendering even with mxtheme doesn't have this problem. Upon checking the html source code, a single word is sometimes break into two part. This might be addressed in a separate pr if necessary, where we migrate from d2l to other method, i.e. sphinx + nbnotebook

Fix web format

---

docs/tutorials/text_prediction/automm.md
docs/tutorials/text_prediction/beginner.md
docs/tutorials/text_prediction/customization.md
docs/tutorials/text_prediction/multilingual_text.md
docs/tutorials/text_prediction/multimodal_text.md
text/src/autogluon/text/automm/utils.py

1. Highlighted motivation.
2. Adjusted the presentation order of multimodal and single modal training.
3. Simplified each section.
4. Added one API section.

[PR #1537 Patch 8] Refine the AutoMM tutorial

---

docs/tutorials/text_prediction/multilingual_text.md
text/src/autogluon/text/automm/configs/optimization/adamw.yaml
text/src/autogluon/text/text_prediction/presets.py

Change the default lr_decay to 0.9 based on the internal HPO results.
Also, improve the tutorial about zero-shot cross lingual transfer.

Improve multilingual tutorial + Change default lr_decay to 0.9

---

docs/README.md
docs/install-cpu-pip.rst
docs/install-cpu-source.rst
docs/install-faq.rst
docs/install-gpu-pip-windows.rst
docs/install-gpu-pip.rst
docs/install-gpu-source-windows.rst
docs/install-gpu-source.rst

Remove references to requiring MXNet during install of AutoGluon

Remove MXNet install reference

---

ROADMAP.md
docs/whats_new/v0.4.0.md

- Added v0.4.0 release notes
TODO:

[WIP] Added v0.4.0 release notes

---

docs/ReleaseInstructions.md

- Update release instructions to include more information

Update release instructions

---

Jenkinsfile

Try fixing text CI memory issue

[WIP] Try fixing text CI memory issue

---

core/setup.py
core/src/autogluon/core/utils/try_import.py

Try upgrade ray for security patch. Need 1.10+

[security] Try upgrade ray for security patch

---

docs/tutorials/text_prediction/customization.md

1. Added customizing backbones from the Huggingface model zoo.
2. Added how to use local backbones.

Update the text tutorial of customizing hyperparameters

---

text/src/autogluon/text/automm/configs/data/default.yaml
text/src/autogluon/text/automm/data/dataset.py
text/src/autogluon/text/automm/data/infer_types.py

1. Added prompts for the percentage of missing images during image column detection.
2. Added one comment in data config.
3. Removed one deprecated comment in dataset.py.

Add prompts for the percentage of missing images

---

text/src/autogluon/text/automm/predictor.py
text/src/autogluon/text/text_prediction/predictor.py
text/tests/unittests/text_prediction/test_predictor_pytorch.py

Fix warning message about bf16.

---

tabular/src/autogluon/tabular/models/catboost/catboost_model.py
tabular/src/autogluon/tabular/models/lgb/lgb_model.py
tabular/src/autogluon/tabular/models/xgboost/xgboost_model.py

#1614 
- Improve memory warning thresholds so they trigger less often.
- Fix typos.

Tabular: Improve memory warning thresholds

---

tabular/tests/conftest.py

https://github.com/awslabs/autogluon/pull/1555
Marking tabular regression tests to be added as non-default. Requires `--runregression` to run

Marking regression test non-default

---

text/src/autogluon/text/automm/predictor.py
text/tests/unittests/automm/test_metrics.py

[Bug Fix] Fix the corner case of calculating the gradient accumulation step

---

forecasting/src/autogluon/forecasting/dataset/ts_dataframe.py
forecasting/tests/unittests/test_ts_dataset.py

This is part of the #1538
Added `TimeSeriesDataFrame` class to represent time-series dataset for autogluon.forecasting.

TimeSeriesDataFrame

---

docs/requirements_doc.txt

fix jinja version

---

tabular/src/autogluon/tabular/models/catboost/catboost_model.py
tabular/src/autogluon/tabular/models/catboost/catboost_utils.py

#1635 
- Fix CatBoost custom metric & F1 support

Fix CatBoost custom metric & F1 support

---

core/src/autogluon/core/models/abstract/abstract_model.py
core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
tabular/src/autogluon/tabular/models/image_prediction/image_predictor.py
tabular/src/autogluon/tabular/models/text_prediction/text_prediction_v1_model.py

#1676
Simplified logic added in #1676 and made it more flexible.
- Previous implementation would crash if user specified `'auto'` for resources, fixed in this PR.
- Added `get_minimum_resources` to explicitly define minimum resource requirements within a method.

Update resource logic in models

---

text/src/autogluon/text/automm/optimization/lit_module.py
text/src/autogluon/text/automm/optimization/utils.py
text/src/autogluon/text/automm/predictor.py
text/src/autogluon/text/automm/utils.py
text/src/autogluon/text/text_prediction/predictor.py
text/tests/unittests/automm/test_metrics.py
text/tests/unittests/text_prediction/test_predictor_pytorch.py

*Issue #, if available:* https://github.com/awslabs/autogluon/issues/1686, https://github.com/awslabs/autogluon/issues/1698
(Not essentially a bug.) Change load from a classmethod to staticmethod to avoid incorrect usage.

[Fix] Use staticmethod for load + Add fallback for validation metrics + Support average_precision in AutoMM

---

text/src/autogluon/text/automm/predictor.py

1. checkpoint_callback.best_k_models becomes an empty dict in the multi-gpu setting. Avoid using it in collecting the top k checkpoint paths.
2. clean the last.ckpt after finishing the top k averaging.

fix top k averaging in the multi-gpu setting

---

docs/tutorials/tabular_prediction/tabular-custom-metric.md
docs/tutorials/tabular_prediction/tabular-faq.md
tabular/src/autogluon/tabular/predictor/predictor.py

#1637
- Added instructions on how to make a custom metric serializable.

Add notice to ensure serializable custom metrics

---

text/src/autogluon/text/automm/constants.py
text/src/autogluon/text/automm/models/clip.py
text/src/autogluon/text/automm/models/fusion.py
text/src/autogluon/text/automm/models/huggingface_text.py
text/src/autogluon/text/automm/models/timm_image.py
text/src/autogluon/text/automm/models/utils.py

1. Add one util function to extract column features for both image and text.
2. Support extracting column features for models `timm_image`, `hf_text`, and `clip`.

Extract column features from AutoMM's model outputs

---

Jenkinsfile
docs/whats_new/v0.4.1.md

Added v0.4.1 release notes

---

README.md
docs/badges.rst
docs/versions.rst

0.4.1 version updates

---

forecasting/src/autogluon/forecasting/learner.py
forecasting/src/autogluon/forecasting/models/gluonts/abstract_gluonts.py
forecasting/src/autogluon/forecasting/trainer/abstract_trainer.py
forecasting/tests/unittests/models/test_models.py

Support other metrics in score function of AbstractGluonTSModel.

Support other metrics in score function of AbstractGluonTSModel

---

Jenkinsfile

According to the documentation: https://black.readthedocs.io/en/stable/the_black_code_style/future_style.html#preview-style, preview might bring potentially disruptive style changes. It's safer to not use it.

[CI] Remove black preview

---

text/tests/README.md

In this README, we introduce how to do code formatting and unit testing locally.

Add README for AutoMM tests

---

docs/tutorials/tabular_prediction/tabular-indepth.md
tabular/src/autogluon/tabular/learner/abstract_learner.py
tabular/src/autogluon/tabular/predictor/predictor.py
tabular/tests/unittests/test_tabular.py

- Add transform_features arg to TabularPredictor predict and predict_proba methods.
- Add tutorials for advanced methods to speed up inference.

Add transform_features arg

---

docs/tutorials/tabular_prediction/index.rst
docs/tutorials/tabular_prediction/tabular-custom-model-advanced.md
docs/tutorials/tabular_prediction/tabular-custom-model.md

- Add advanced custom model tutorial showcasing the ability to bypass preprocessing of features.

Add advanced custom model tutorial

---

docs/ReleaseInstructions.md

- Update release instructions to include cheatsheet

Update release instructions to include cheatsheet

---

text/src/autogluon/text/automm/configs/data/default.yaml
text/src/autogluon/text/automm/data/preprocess_dataframe.py
text/src/autogluon/text/automm/data/process_text.py
text/tests/unittests/automm/test_automm_predictor.py

[Bugfix] Fix text augmentation + Change the default label scaler to standardscaler

---

timeseries/src/autogluon/timeseries/models/gluonts/__init__.py
timeseries/src/autogluon/timeseries/models/gluonts/models.py
timeseries/src/autogluon/timeseries/models/presets.py
timeseries/tests/unittests/models/test_gluonts.py
timeseries/tests/unittests/test_ts_dataset.py

- also fix lint and other issues in ts dataframe tests

add transformer and MQRNN as first-class models

---

text/setup.py

Cap protobuf version to help solve https://github.com/awslabs/autogluon/issues/1762

Cap protobuf version in text/automm

---

docs/api/autogluon.predictor.rst
timeseries/src/autogluon/timeseries/dataset/ts_dataframe.py
timeseries/src/autogluon/timeseries/predictor.py
timeseries/src/autogluon/timeseries/trainer/abstract_trainer.py

Revise doc strings and make timeseries API docs available

---

docs/tutorials/tabular_prediction/tabular-interpretability.md
tabular/setup.py
tabular/src/autogluon/tabular/configs/hyperparameter_configs.py
tabular/src/autogluon/tabular/models/__init__.py
tabular/src/autogluon/tabular/models/imodels/imodels_models.py
tabular/src/autogluon/tabular/trainer/model_presets/presets.py
tabular/tests/unittests/configs/test_config_helper.py

Minor updates to the interpretable preset:
1. bumping the `imodels` version (to support better model visualization)
2. updating the preset model names to work with the new version
3. minor update to the tutorial
Hopefully should be able to merge in without any issue!

[Minor change] Interpretable models update

---

core/src/autogluon/core/metrics/__init__.py
tabular/src/autogluon/tabular/predictor/predictor.py
tabular/tests/conftest.py
tabular/tests/unittests/models/test_lightgbm.py

- Added MAPE metric (https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_absolute_percentage_error.html)
- Refactored eval_metric code to be cleaner and provide more helpful error messages communicating which metrics are supported in which problem types.
- Added unit test in LightGBM to test all eval metrics for each problem type to ensure they work without error.

Add MAPE metric

---

core/src/autogluon/core/trainer/abstract_trainer.py

#1813
- Fix RF, XT, KNN to use all data (including holdout) when refitting with bagging + use_bag_holdout=True

Fix refit with use_bag_holdout

---

Jenkinsfile
docs/build_contrib.yml
docs/build_contrib_gpu.yml
docs/build_gpu.yml

Removed defaults channel since it's a bad practice

Removing defaults channel

---

timeseries/src/autogluon/timeseries/__init__.py
timeseries/src/autogluon/timeseries/dataset/ts_dataframe.py
timeseries/src/autogluon/timeseries/learner.py
timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
timeseries/src/autogluon/timeseries/models/abstract/model_trial.py
timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
timeseries/src/autogluon/timeseries/predictor.py
timeseries/src/autogluon/timeseries/trainer/abstract_trainer.py
timeseries/src/autogluon/timeseries/utils/warning_filters.py
timeseries/tests/unittests/test_trainer.py

Improves usability in time series by
- revising suppression of warnings
- improving logging
- revising leaderboard
cc: @huibinshen 

Improve logging and leaderboard in timeseries

---

core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
core/src/autogluon/core/models/ensemble/fold_fitting_strategy.py

* Fix init args when parallel bagging fall back to sequential

fix sequential args

---

docs/tutorials/cloud_fit_deploy/cloud-aws-sagemaker-deployment.md
docs/tutorials/cloud_fit_deploy/cloud-aws-sagemaker-training.md

Updated tutorials for cloud deployment

[docs] Updated tutorials for cloud deployment

---

core/src/autogluon/core/trainer/abstract_trainer.py

- Improve clarity of negative metrics

Improve clarity of negative metrics

---

Jenkinsfile
timeseries/setup.py
timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
timeseries/src/autogluon/timeseries/models/sktime/__init__.py
timeseries/src/autogluon/timeseries/models/sktime/abstract_sktime.py
timeseries/src/autogluon/timeseries/models/sktime/models.py
timeseries/tests/unittests/models/test_gluonts.py
timeseries/tests/unittests/models/test_models.py
timeseries/tests/unittests/models/test_sktime.py

**Depends on**: ~~#1830~~ #1839 
Add ETS, ARIMA, and TBATS support for time series through the sktime package.
cc: @huibinshen 

Add sktime support to timeseries

---

timeseries/src/autogluon/timeseries/models/__init__.py
timeseries/src/autogluon/timeseries/models/presets.py

Start using AutoArima and AutoETS model in preset.

Use arima and ets

---

docs/tutorials/multimodal/beginner_text.md
docs/tutorials/multimodal/multilingual_text.md
docs/tutorials/multimodal/multimodal_text_tabular.md

[AutoMM] Tutorial fix

---

.github/workflows/platform_tests-command.yml
.github/workflows/pypi_release.yml
.github/workflows/pythonpublish.yml
.github/workflows/pythonpublish_testpypi.yml
autogluon/setup.py
full_install.sh

- Add autogluon.timeseries to release modules

Add autogluon.timeseries to release modules

---

docs/whats_new/v0.4.2.md

adding v0.4.2.md

---

docs/build_pip_install.sh
docs/index.rst
docs/tutorials/timeseries/forecasting-faq.md
docs/tutorials/timeseries/forecasting-quickstart.md
docs/tutorials/timeseries/index.rst
docs/tutorials/timeseries/temp.md
full_install.sh
timeseries/src/autogluon/timeseries/dataset/ts_dataframe.py

Depends on weighted ensemble PR: #1838 
Adds FAQ and quickstart tutorial for time series forecasting.

Add TimeSeries quickstart guide

---

tabular/src/autogluon/tabular/models/tabular_nn/mxnet/tabular_nn_mxnet.py
tabular/src/autogluon/tabular/trainer/model_presets/presets.py
vision/src/autogluon/vision/_gluoncv/image_classification.py

- Update deprecation messages for MXNet from v0.5 -> v0.6

update deprecation warnings v0.5 -> v0.6

---

multimodal/src/autogluon/multimodal/data/preprocess_dataframe.py
tabular/src/autogluon/tabular/models/automm/automm_model.py

Avoid predicting nan for regression problem

Final fix before 0.5: remove predicting nan for regression problems

---

.github/workflows/pythonpublish.yml

- Update pre-release time to 12:30 AM PST

Update pre-release time to 12:30 AM PST

---

.github/workflows/pythonpublish.yml

Only keep timeseries and autogluon for now. Need to revert back later

Fix timeseries dependency and add manual trigger

---

.github/workflows/pythonpublish.yml
core/src/autogluon/core/_setup_utils.py

Revert pythonpublish

---

.github/workflows/pypi_release.yml

Release override

---

core/src/autogluon/core/_setup_utils.py

Revert _setup_utils.py hack for release

---

.github/workflows/pypi_release.yml
.github/workflows/pythonpublish.yml
.github/workflows/pythonpublish_testpypi.yml

- Cleanup override logic from v0.5 release.

Cleanup override logic

---

multimodal/src/autogluon/multimodal/data/preprocess_dataframe.py
multimodal/src/autogluon/multimodal/predictor.py
multimodal/src/autogluon/multimodal/utils.py
multimodal/tests/unittests/test_utils.py

1. Support input data in the `list` format, i.e., no column names are provided.
2. Check if the provided columns contain all the required columns.
3. Add unit tests.

Improve converting input data to dataframe for AutoMM

---

docs/tutorials/multimodal/beginner_multimodal.md

1. Create a tutorial dataset (by binarizing Petfinder's labels and subsampling the dataset) used in the multimodal tutorial for beginners.
2. Change metric from `accuracy` to `roc_auc`.

Improve the AutoMM beginner tutorial

---

docs/tutorials/multimodal/customization.md
multimodal/src/autogluon/multimodal/configs/optimization/adamw.yaml
multimodal/src/autogluon/multimodal/predictor.py

Support customizing the below configs:
1. gradient_clip_val
2. gradient_clip_algorithm
3. log_every_n_steps

Add new optimization configs

---

docs/tutorials/tabular_prediction/tabular-faq.md

#1921 
- Add FAQ section on reproducing results

Add FAQ section on reproducing results

---

features/src/autogluon/features/generators/text_ngram.py

- Update docs to mention TFIDF support

Update docs to mention TFIDF support

---

core/src/autogluon/core/utils/try_import.py
tabular/setup.py
tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
tabular/src/autogluon/tabular/models/tabular_nn/torch/tabular_nn_torch.py

- Update fastai to 2.7 to support pytorch 1.12
- Optimize fitting of Torch NN to avoid resetting num threads every epoch.
TODO:

Update fastai to 2.7

---

core/src/autogluon/core/hpo/executors.py
core/src/autogluon/core/hpo/ray_hpo.py
multimodal/src/autogluon/multimodal/predictor.py

* Fixed the inconsistency of `register_resources` interface.
* Updated ray hpo interface to use GPU calculator when the trial requires gpu not when the machine has gpu.

Fix RayExecutor Interface

---

tabular/src/autogluon/tabular/models/_utils/rapids_utils.py
tabular/src/autogluon/tabular/models/knn/knn_rapids_model.py
tabular/src/autogluon/tabular/models/lr/lr_rapids_model.py
tabular/src/autogluon/tabular/models/rf/rf_rapids_model.py

#1845 
- Improve RAPIDS support (require GPU, fix usage of GPU in parallel)
- Clean up RAPIDS code by adding RapidsModelMixin

Improve RAPIDS support (require GPU, fix usage of GPU in parallel)

---

docs/tutorials/multimodal/customization.md
multimodal/src/autogluon/multimodal/configs/environment/default.yaml
multimodal/src/autogluon/multimodal/configs/optimization/adamw.yaml
multimodal/src/autogluon/multimodal/optimization/utils.py
multimodal/src/autogluon/multimodal/predictor.py
multimodal/src/autogluon/multimodal/utils.py
multimodal/tests/unittests/test_zero_shot.py

1. Move `track_grad_norm` from environment into optimization and change its default to -1.
2. Use clip base in zero shot unit tests.
3. Update the customization doc by adding distiller configs.
4. Move one util from optimization/utils.py into multimodal/utils.py (a semantically better location for this function).

Update configs and add distiller customization docs

---

docs/tutorials/multimodal/clip_embedding.md
docs/tutorials/multimodal/clip_zeroshot.md
docs/tutorials/multimodal/index.rst

NA
Add a tutorial of using CLIP to extract embeddings for retrieval problem.

Clip embedding

---

multimodal/tests/unittests/test_zero_shot.py

Temporarily skip the zero shot test to pass Jenkins build

---

docs/whats_new/v0.5.1.md

Add v0.5.1 release notes from AutoMM

---

.github/workflow_scripts/build_all_docs.sh
.github/workflows/continuous_integration.yml
README.md

* Update build badge to use github action badge
* Added platform tests badge

Update README Badges

---

multimodal/tests/unittests/test_hpo.py

Re-enable hpo tests as old Jenkins CI has been replaced

Re-enable hpo tests

---

docs/whats_new/v0.5.1.md

Add release notes for time series.

update v0.5.1 release notes for time series

---

multimodal/src/autogluon/multimodal/predictor.py

https://github.com/awslabs/autogluon/issues/1976
* Take floor of float value if provided as `num_gpus`

Fix AutoMM Parallel Bagging

---

.github/workflow_scripts/env_setup.sh
.github/workflow_scripts/lint_check.sh
multimodal/src/autogluon/multimodal/utils.py

Add [bandit](https://github.com/PyCQA/bandit) to check for security errors.

[Security] Add bandit to check for security vulnerabilities in multimodal package.

---

docs/tutorials/tabular_prediction/tabular-gpu.md

Details please refer to https://github.com/awslabs/autogluon/issues/2006
*Issue #, if available:* #2006
I just change a single word in the corresponding markdown file.

Change the typo reported on Issue 2006

---

CI/batch/docker/Dockerfile.cpu
CI/batch/docker/Dockerfile.gpu

* Update CI container to 0.5.2.
* Images have been pushed, this PR mainly for triggering CI for testing and keep container code up to date

[CI] Update CI container

---

multimodal/src/autogluon/multimodal/data/process_image.py
multimodal/src/autogluon/multimodal/models/mmdet_image.py
multimodal/src/autogluon/multimodal/presets.py
multimodal/src/autogluon/multimodal/utils.py

Fix the gpu inference for object detection.

Fix the gpu inference for object detection

---

docs/tutorials/tabular_prediction/tabular-faq.md

- Added missing value imputation FAQ section

Added missing value imputation FAQ section

---

multimodal/src/autogluon/multimodal/configs/model/fusion_mlp_image_text_tabular.yaml
multimodal/src/autogluon/multimodal/predictor.py
multimodal/src/autogluon/multimodal/utils.py
multimodal/tests/unittests/test_config.py
multimodal/tests/unittests/test_data_augmentation.py
multimodal/tests/unittests/test_predictor.py

1. Empty the default model names in the yaml config.
2. Remove using the old config in tests.

Fix model names in AutoMM

---

.github/actions/submit-job/action.yml
.github/workflows/continuous_integration.yml

* Add quotation mark around env vars to avoid bash command injection attack

[Security] Fix env vars

---

.github/actions/setup-env-vars/action.yml
.github/workflows/continuous_integration.yml

* Found more env vars need to be fixed
* Also removed unneeded quotation mark in comment msg by the bot.

[Security] More env vars fixes

---

README.md

add timeseries to readme
