- autogluon/utils/tabular/ml/trainer/abstract_trainer.py
Could be related to https://github.com/awslabs/autogluon/issues/168
Models are not cleaned up after training in low-memory mode because `models` collection holds reference to the object.
> Fixed model cleanup after training in low_memory mode

- autogluon/utils/tabular/ml/learner/default_learner.py
Fixing TypeError in logging statement
```
~/Projects/autogluon/autogluon/utils/tabular/ml/learner/default_learner.py in augment_rare_classes(self, X)
245             new_df = new_df[:remainder]
246             while duplicate_times > 0:
--> 247                 logger.debug("Duplicating data from rare class: " + clss)
248                 duplicate_times -= 1
249                 new_df = new_df.append(clss_df.copy())
TypeError: must be str, not int
```
(cherry picked from commit 32ba0d4cdeaa6e6c09302dcb639352622d499a84)
Added conversion to str, so the line does not fail with exception
> TypeError fix

- autogluon/task/image_classification/classifier.py
#194 'OrderedDict' is not defined in classifier.py
Imports the `OrderedDict` module in `classifier.py`.
> Fix OrderedDict not imported

- autogluon/utils/tabular/features/abstract_feature_generator.py
- autogluon/utils/tabular/ml/learner/abstract_learner.py
#192 
Made type detection generic using np.issubdtype, this enables AutoGluon to handle label dtypes of any kind of integer and float instead of only int64 and float64, which was causing issues on Windows.
> Fixed problem_type detection on Windows

- autogluon/utils/tabular/ml/models/tabular_nn/tabular_nn_model.py
- autogluon/utils/tabular/ml/models/tabular_nn/tabular_nn_trial.py
`nd.sum(loss).asscalar()` is doing implicit conversion tonumpy(), which is expensive (especially on GPU). Computing everything in NDArray speeds up computation. This problem exists in other parts of the NN training loop (scoring), but not as severe since loss is computed on batch level.
> MXNet Neural Network performance improvements (reduced minibatch runtime on large datasets)

- autogluon/task/tabular_prediction/tabular_prediction.py
- autogluon/utils/tabular/ml/learner/default_learner.py
- autogluon/utils/tabular/ml/models/catboost/catboost_utils.py
#205 
- Improved documentation of metric options in Tabular
- Improved CatBoost support for binary metrics
- Fixed defect prevent log_loss metric usage in binary classification
> Tabular Metric Documentation Improvement + Bugfix

- autogluon/task/tabular_prediction/predictor.py
- autogluon/utils/tabular/ml/learner/abstract_learner.py
- autogluon/utils/tabular/ml/trainer/abstract_trainer.py
- Added 'model' parameter to Predictor.predict() and .predict_proba() which enables users to specify the model they wish to get predictions for, rather than always getting predictions from the best validation score model.
- Added model_names parameter to predictor
> Tabular Predictor Model Parameter

- autogluon/utils/tabular/ml/models/tabular_nn/hyperparameters/parameters.py
- autogluon/utils/tabular/ml/models/tabular_nn/tabular_nn_model.py
Tiny improvement to change default num_categories_to_keep hyperparameter of NN from 500 to 100, in order to improve runtimes.
Also allow neural net to be trained for 0 epochs (no training) which is useful for debugging and using just its data preprocessor.
> Improve NN runtime by reducing num_categories_to_keep

- setup.py
I'm installing autogluon from source via the following command on an EC2 Deep Learning base AMI: "Deep Learning Base AMI (Ubuntu 18.04)"
```
pip install -U -e . --user
```
However, it still shows the following error:
```python
In [1]: import autogluon                                                                       
File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 3296, in run_code
exec(code_obj, self.user_global_ns, self.user_ns)
File "<ipython-input-1-22265195b07c>", line 1, in <module>
import autogluon
File "/home/ubuntu/autogluon/autogluon/__init__.py", line 10, in <module>
from . import scheduler, searcher, utils
File "/home/ubuntu/autogluon/autogluon/scheduler/__init__.py", line 5, in <module>
from …
```
> Add pynvml to dependency

- autogluon/utils/tabular/ml/models/tabular_nn/tabular_nn_model.py
Makes tabular neural data processing more memory efficient. 
There still exist a duplicate copy of dataset inside the initialization of tabular_nn_dataset, when the data are converted to mx.nd.array, but that duplicate is not easy to remove.
> remove redundant copies of dataset object in tabular neural net

- setup.py
> Relax some dependencies in setup.py to ease compatibility

- autogluon/utils/tabular/ml/learner/abstract_learner.py
- autogluon/utils/tabular/ml/models/ensemble/stacker_ensemble_model.py
- autogluon/utils/tabular/ml/trainer/abstract_trainer.py
Enables optional inference speedup when the entire ensemble can fit in memory.
Speedup observed to be ~10-50% on MacOS when the ensemble is ~1 GB large.
> Tabular: Added persist_trainer function in AbstractLearner

- autogluon/task/tabular_prediction/tabular_prediction.py
Fixes #315 
Simple fix. Should be revisited, to separate scheduler from searcher
> Fix for search_strategy = 'hyperband' in TabularPrediction.fit

- autogluon/utils/tabular/ml/models/abstract/model_trial.py
- autogluon/utils/tabular/ml/models/lgb/hyperparameters/lgb_trial.py
- autogluon/utils/tabular/ml/models/tabular_nn/tabular_nn_trial.py
*Issue #266, if available:*
Terminating reporter if tabular model failed to train due to some reason.
```
import autogluon as ag
from autogluon.task import TabularPrediction as task
import sklearn.datasets
cancer_data = sklearn.datasets.load_breast_cancer(return_X_y=False)
data = pd.DataFrame(cancer_data['data'], columns=cancer_data['feature_names'])
data['target'] = cancer_data['target']
hp_tune = True
cat_options = {
'num_leaves': ag.space.Int(lower=26, upper=66, default=36),
'depth': ag.space.Int(lower=4, upper=10, default=6),
}
gbm_options = {
'num_boost_round': 100,
'num_leaves': ag.space.Int(lower=26, upper=66, default=36),
}
'CAT': cat_options,
'GBM': gbm_options,
}
time_limits = 2 * 60
num_trials = 3 …
```
> FIX: tabular training hang due to error in model training

- autogluon/task/tabular_prediction/tabular_prediction.py
- Removed "rl" searcher option from tabular_prediction.fit() as it has issue: https://github.com/awslabs/autogluon/issues/317
- extra tabular_prediction fit() example to demonstrate how to maximize predictive accuracy
> update tabular fit docs

- autogluon/searcher/skopt_searcher.py
Previously:
```
Finished Task with config: {'depth': 7, 'l2_leaf_reg': 2.411136570044195, 'learning_rate': 0.16222294597513923} and reward: 0.8516593362654938
Finished Task with config: b'\x80\x03}q\x00(X\x05\x00\x00\x00depthq\x01K\x07X\x0b\x00\x00\x00l2_leaf_regq\x02G@\x03J\x01\xf8T<FX\r\x00\x00\x00learning_rateq\x03G?\xc4\xc3\xb8\xb3\xcf\xdf)u.' and reward: 0.8516593362654938
Finished Task with config: b'\x80\x03}q\x00(X\x05\x00\x00\x00depthq\x01K\x07X\x0b\x00\x00\x00l2_leaf_regq\x02G@\x03J\x01\xf8T<FX\r\x00\x00\x00learning_rateq\x03G?\xc4\xc3\xb8\xb3\xcf\xdf)u.' and reward: 0.8516593362654938
```
Now:
```
Finished Task with config: {'feature_fraction': 0.9670482733697998, 'learning_rate': 0.005265640081214188, 'min_data_in_leaf': 3, …
```
> Removed redundant skopt logging

- autogluon/task/base/base_predictor.py
- autogluon/task/image_classification/classifier.py
- autogluon/task/object_detection/detector.py
Basic PEP8 corrections, 
Removing `_format_results` from `Classifier` and `Detector` since it is moved to mother class.
> FIX: removing duplicate method `_format_results`

- autogluon/utils/tabular/ml/models/abstract/abstract_model.py
- autogluon/utils/tabular/ml/models/lgb/callbacks.py
- autogluon/utils/tabular/ml/models/lgb/hyperparameters/lgb_trial.py
- autogluon/utils/tabular/ml/models/lgb/lgb_model.py
Major Changes:
- Significantly simplified lgb_trial.py to call model.fit.
- Corrected HPO model path reporting and names
- Enabled time-based early stopping of HPO trials for LightGBM
- Enabled memory-based early stopping of HPO trials for LightGBM
- Significantly simplified LightGBM callback code, merged two existing callbacks into one
- Corrected LightGBM HPO hyperparameters (Previously was throwing away seed and num_boost_rounds, + altering original model hyperparameters incorrectly)
- Optimized early stopping for LightGBM HPO to use dynamic early stopping rounds
Note: These issues still exist for the other models. Because this is a major change, I will leave the code changes for other models to separate PR's.
By submitting this pull …
> Tabular: Fixed LightGBM HPO

- autogluon/searcher/searcher.py
- autogluon/searcher/skopt_searcher.py
- Basic PEP8 corrections and optimisations. 
- Fixing random searcher, when reward is negative value (for example r2).
> FIX: random searcher for negative reward

- autogluon/utils/tabular/ml/models/catboost/catboost_model.py
Fixed CatBoost iterations value after training, previously was 1 too few. Caused _FULL models to train for 1 fewer iterations than expected.
> Tabular: Fixed CatBoost iterations value after training

- autogluon/scheduler/fifo.py
- autogluon/scheduler/reporter.py
- autogluon/scheduler/scheduler.py
- autogluon/utils/__init__.py
- autogluon/utils/custom_process.py
*Issue #329 , if available:*
- Implementation of `CustomProcess` class, which has property `exception`.
- Using `CustomProcess` class for individual training process.
- Checking individual training fails due to some Exception using `exception` property of `CustomProcess`.
- Before fetching from local reporter queue checking if it has some results, if not continue waiting for results or exception in `while self.process.is_alive()`. 
- If process is not fails,  then reported results are transferred to `dist_reporter` and so on.
- if process fails, terminating `local_reporter` and transferring exception traceback to `dist_reporter`.
The change is implemented only for `FIFO` scheduler, it will be approved, then we can implement also for other schedulers. 
Code sample …
> FIX: fixing training hanging

- autogluon/utils/tabular/ml/models/abstract/abstract_model.py
- autogluon/utils/tabular/ml/models/abstract/model_trial.py
- autogluon/utils/tabular/ml/models/ensemble/bagged_ensemble_model.py
- autogluon/utils/tabular/ml/models/ensemble/stacker_ensemble_model.py
- autogluon/utils/tabular/ml/models/knn/knn_model.py
- autogluon/utils/tabular/ml/models/lgb/hyperparameters/lgb_trial.py
- autogluon/utils/tabular/ml/models/rf/rf_model.py
- autogluon/utils/tabular/ml/models/tabular_nn/tabular_nn_model.py
- autogluon/utils/tabular/ml/models/tabular_nn/tabular_nn_trial.py
- autogluon/utils/tabular/ml/trainer/abstract_trainer.py
Changes:
- Added refitfull support for non-bagged models
- Disabled unnecessary model.save_info() calls during training
- Added fit_time, predict_time to HPO models
- Various HPO cleanup
- Removed outdated code and outdated TODOs
> Tabular: HPO Fix + Various Cleanup

- autogluon/utils/tabular/ml/learner/abstract_learner.py
- autogluon/utils/tabular/ml/models/abstract/abstract_model.py
- autogluon/utils/tabular/ml/models/catboost/catboost_model.py
- autogluon/utils/tabular/ml/models/ensemble/bagged_ensemble_model.py
- autogluon/utils/tabular/ml/models/ensemble/greedy_weighted_ensemble_model.py
- autogluon/utils/tabular/ml/models/ensemble/weighted_ensemble_model.py
- autogluon/utils/tabular/ml/models/knn/knn_model.py
- autogluon/utils/tabular/ml/models/lgb/lgb_model.py
- autogluon/utils/tabular/ml/models/rf/rf_model.py
- autogluon/utils/tabular/ml/trainer/abstract_trainer.py
#304 
Major Update
- Added get_feature_importance() function to learner and trainer.
- Note: This is not surfaced to the user-facing API yet
Code Example:
```
import datetime
import sklearn.datasets
from autogluon.utils.tabular.ml.utils import generate_train_test_split
from autogluon import TabularPrediction as task
LABEL = 'target'
utcnow = datetime.datetime.utcnow()
timestamp_str_now = utcnow.strftime("%Y%m%d_%H%M%S")
path_prefix = 'datasets/breast_cancer/'
path_model_prefix = path_prefix + 'learners/' + timestamp_str_now + '/'
cancer_data = sklearn.datasets.load_breast_cancer(return_X_y=False)
X = pd.DataFrame(cancer_data['data'], columns=cancer_data['feature_names'])
X[LABEL] = …
```
> Tabular: Feature Importance

- autogluon/utils/tabular/ml/models/lgb/lgb_model.py
Fixed defect causing LightGBM to fail on multiclass classification
Defect introduced in #344 
This highlights that we should alter tests to fail if **ANY** model failure occurs, rather than if training fails entirely.
> Fixed defect causing LightGBM to fail on multiclass classification

- autogluon/utils/tabular/ml/learner/default_learner.py
Bug fix: old code fails when the indexing of the dataframe is different than `0, 1, 2, ...`.
> FIX: bug fix when cleaning missing labels

- autogluon/utils/tabular/ml/models/knn/knn_model.py
Fixed KNN crashing when training data >4GB
> Fixed KNN crashing when training data >4GB

- autogluon/utils/tabular/metrics/classification_metrics.py
closes #378
Before:
```python
>>> ag.utils.tabular.metrics.balanced_accuracy(y_test, y_pred)
[error]
```
After
```python
>>> ag.utils.tabular.metrics.balanced_accuracy(y_test, y_pred)
0.1826867855754422
```
Sklearn:
```python
>>> sklearn.metrics.balanced_accuracy_score(y_test, y_pred)
0.1826867855754422
```
```python
import autogluon as ag
d = {'solution': ['a','b','c','a','b','c'], 'prediction': ['b','b','c','d','b','c']}
df = pd.DataFrame(data=d)
ag.utils.tabular.metrics.balanced_accuracy(df['solution'], df['prediction'])
```
with this PR, it returns `0.75`, without, you get an error. 
* There may be more efficient ways to do the OHE.
* We could also just wrap around `sklearn.metrics.balanced_accuracy_score`, note however that it fails on the MWE above because that …
> fix for balanced accuracy computation

- autogluon/scheduler/fifo.py
- autogluon/scheduler/hyperband.py
- autogluon/scheduler/resource/resource.py
- autogluon/scheduler/scheduler.py
Thanks @mseeger for pointing this out.  The current searcher would suggest next configuration even there is no compute resources available. This will impact the performance of search algorithms. The last one configuration can not fully utilize all previous results.
As suggested by @mseeger , moving cls.RESOURCE_MANAGER._request(), before searcher.get_config()
> searcher improvement

- autogluon/utils/plots.py
Update mousoverplot to match bokeh update to v2.0.1 which dropped compatibility with previewsave tool.
> Fix mousouver plot after bokeh dropped previewsave

- autogluon/task/tabular_prediction/predictor.py
- autogluon/utils/plots.py
- autogluon/utils/tabular/ml/learner/abstract_learner.py
- autogluon/utils/tabular/ml/trainer/abstract_trainer.py
- setup.py
#175 
Major Changes:
- Added networkx dependency
- Added Directed Acyclic Graph model dependency representation in Tabular Trainer
- Added pred_time_val_full to .leaderboard() -> pred_time_val of model + pred_time_val of all required base models
- Added fit_time_full to .leaderboard() -> fit_time of model + fit_time of all required base models
- Improved pred_time_test_full on .leaderboard() -> It is now accurate for weighted ensembles, previously it overestimated the time.
- Improved model sorting in leaderboard, if two models have the same score, put the one with lower inference time in front.
- All improvements also added to .fit_summary() …
> Tabular: Added improved inference time estimates + networkx dependency

- autogluon/utils/tabular/metrics/classification_metrics.py
In prior version, with the following code:
```
import autogluon
```
Produces warning output:
```
FutureWarning: The sklearn.metrics.classification module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.metrics. Anything that cannot be imported from sklearn.metrics is now part of the private API.
warnings.warn(message, FutureWarning)
```
After this change, nothing is logged (No warning). This change should enable AutoGluon to work with sklearn 0.24 when it releases.
> Added support for sklearn 0.24+, resolved sklearn deprecation warning

- autogluon/task/tabular_prediction/predictor.py
- autogluon/utils/tabular/ml/learner/abstract_learner.py
- autogluon/utils/tabular/ml/trainer/abstract_trainer.py
- autogluon/utils/tabular/ml/utils.py
Enables user to filter leaderboard to the relevant models when choosing between inference speed and accuracy.
Example Code:
```
import sklearn.datasets
from autogluon.utils.tabular.ml.utils import generate_train_test_split
from autogluon import TabularPrediction as task
LABEL = 'target'
cancer_data = sklearn.datasets.load_breast_cancer(return_X_y=False)
X = pd.DataFrame(cancer_data['data'], columns=cancer_data['feature_names'])
X[LABEL] = cancer_data[LABEL]
X_train, X_test, y_train, y_test = generate_train_test_split(X=X.drop(LABEL, axis=1), y=X[LABEL], problem_type='binary', test_size=0.2)
X = X_train
X[LABEL] = y_train
X_test[LABEL] = y_test
X = X.reset_index(drop=True)
X_test = …
```
> Tabular: Added only_breakpoints parameter to .leaderboard()

- autogluon/utils/tabular/ml/trainer/abstract_trainer.py
Issue caused when time_limit specified and repeated bagging occurs. Model will not update val_score beyond its initial score achieved after a single bagged fit. This fix makes it so the val_score is updated each time it is updated as a model in trainer. Before this fix, .leaderboard() would not show correct val_score for these models, however the best_model would still be chosen correctly.
> Tabular: Fixed defect where model val_score was not updated properly

- autogluon/utils/tabular/ml/learner/abstract_learner.py
- autogluon/utils/tabular/ml/models/ensemble/stacker_ensemble_model.py
- autogluon/utils/tabular/ml/models/ensemble/weighted_ensemble_model.py
- autogluon/utils/tabular/ml/trainer/abstract_trainer.py
Major Changes:
- Expanded stacker functionality to work outside of level-alignment
- This means that a stacker model at L3 can now take models at L0, L1, and L2 as input.
- Previously they could only take models at L2 as input.
- Upcoming PR will build upon this functionality to enable _FULL ensembles, resulting in 10-200x inference speedup with minimal accuracy loss for bag enabled ensembles.
- Enables functionality to swap model pred_proba inputs on an already fitted stacker model. (Tradeoff between bagged stacker and _FULL stacker on-the-fly for accuracy/inference speed.)
> Tabular: Added support for advanced stacker model interactions

- autogluon/utils/sync_remote.py
Fixes the synchronization across multiple SageMaker machines. 
```
Worker algo-2 exiting: training not started in 300 seconds.
Host rank 1 exit.
```
Original keyword was for master node, but we need the worker node keyword to grap. 
> Fix SageMaker sync keyword

- autogluon/task/tabular_prediction/predictor.py
- autogluon/utils/tabular/ml/learner/abstract_learner.py
- autogluon/utils/tabular/ml/trainer/abstract_trainer.py
#249, #428
Added transform_features function to TabularPredictor
Now users can utilize this function to get feature transformations on their datasets to use with their own custom models outside of AutoGluon, even enabling users to extend the stack ensemble by receiving the out-of-fold prediction features of the AutoGluon ensemble.
> Tabular: Added transform_features function to TabularPredictor

- autogluon/task/tabular_prediction/predictor.py
- autogluon/utils/tabular/data/label_cleaner.py
#428, #432 
Added transform_labels function to TabularPredictor
Now users can also transform the labels of the data to the internal representation and back, including the probabilities.
> Tabular: Added transform_labels function to TabularPredictor

- autogluon/task/tabular_prediction/predictor.py
#249, #428, #429 
Added load_data_internal function to TabularPredictor.
Now when users use transform_features(), they can get the y labels as well by calling these functions.
> Tabular: Added load_data_internal function to TabularPredictor

- docs/tutorials/index.rst
- fix broken distributed tutorial link
- add missing tabular kaggle tutorial card to tutorials page
- improve core tutorial descriptions to emphasize these are for tuning custom model/training-script
> Fix broken/missing links in tutorial docs

- autogluon/utils/tabular/ml/models/abstract/abstract_model.py
- autogluon/utils/tabular/ml/models/ensemble/bagged_ensemble_model.py
- autogluon/utils/tabular/ml/models/ensemble/stacker_ensemble_model.py
Changes:
- Added memory_size, max_memory_size, and min_memory_size attributes to get_info of models.
- Fixed bagged ensembles incorrectly calculating feature importances when created through HPO.
- Fixed stacker ensembles not having a val_score set after first fold is trained during HPO. (Defect had no impact in previous version, but impacted the development of new functionality.)
> Tabular: Added memory_size to info + minor fixes to HPO

- autogluon/utils/tabular/ml/models/catboost/catboost_model.py
https://github.com/openml/automlbenchmark/pull/109
Removed unnecessary logging files produced by catboost in the root directory.
> Tabular: Defaulted CatBoost 'allow_writing_files' to False

- autogluon/task/tabular_prediction/predictor.py
- autogluon/utils/tabular/data/label_cleaner.py
- autogluon/utils/tabular/ml/learner/abstract_learner.py
https://github.com/openml/automlbenchmark/pull/109
Added as_multiclass parameter to predict_proba
Now it is much easier for users to get the correct label corresponding to True/False in binary classification by specifying as_multiclass=True and adding values to predictor.class_labels and predictor.class_labels_internal for binary classification.
> Tabular: Added as_multiclass parameter to predict_proba

- autogluon/model_zoo/models/utils.py
Pad_width and pad_height are misplaced. It may cause the following conv layer's output has a different size when stride param of SamePadding is a tuple and stride[0] != stride[1].
swap the pad_width and pad_height.
> Bug fix in SamePadding that pad_width and pad_height are misplaced

- autogluon/task/tabular_prediction/predictor.py
- autogluon/utils/tabular/ml/models/abstract/abstract_model.py
- autogluon/utils/tabular/ml/models/ensemble/bagged_ensemble_model.py
- autogluon/utils/tabular/ml/models/ensemble/stacker_ensemble_model.py
- autogluon/utils/tabular/ml/models/ensemble/weighted_ensemble_model.py
- autogluon/utils/tabular/ml/models/tabular_nn/tabular_nn_model.py
- autogluon/utils/tabular/ml/trainer/abstract_trainer.py
Major changes:
- Optimized Tabular NN disk and memory usage to house the model to be reduced by ~80%+ in most cases. This brings NN disk/memory usage from 3 MB -> 500 KB in most cases, which also speeds up inference times on small datasets by >20% due to faster model loading.
- Added delete_models function which allows user to delete unwanted models from predictor. This is extremely useful for users that want to create a model endpoint and don't want the extra unused models taking up disk space on their machines.
- Added reduce_memory_size function which allows user to remove unwanted information such as OOF predictions and train/val data caches to reduce disk usage.
- Moved OOF predictions outside of bagged models into a separate oof.pkl …
> Tabular: Added delete_models and reduce_memory_size functions

- autogluon/utils/tabular/ml/trainer/abstract_trainer.py
Removed redundant preprocess call during feature importance that causes LightGBM to crash if it internally renamed columns.
> Tabular: Fixed feature importance for LightGBM

- autogluon/task/tabular_prediction/hyperparameter_configs.py
- autogluon/task/tabular_prediction/presets_configs.py
- autogluon/task/tabular_prediction/tabular_prediction.py
- autogluon/utils/tabular/ml/learner/abstract_learner.py
- autogluon/utils/tabular/ml/learner/default_learner.py
- autogluon/utils/tabular/ml/models/abstract/abstract_model.py
- autogluon/utils/tabular/ml/models/ensemble/bagged_ensemble_model.py
- autogluon/utils/tabular/ml/models/ensemble/stacker_ensemble_model.py
- autogluon/utils/tabular/ml/models/ensemble/weighted_ensemble_model.py
- autogluon/utils/tabular/ml/models/tabular_nn/hyperparameters/parameters.py
- autogluon/utils/tabular/ml/models/tabular_nn/tabular_nn_model.py
- autogluon/utils/tabular/ml/trainer/abstract_trainer.py
- autogluon/utils/tabular/ml/trainer/auto_trainer.py
Major Changes:
- Added presets parameter, enables novice users to specify complex options with minimal knowledge.
- Added save_bagged_models parameter, enables users to avoid saving bagged models when they plan to refit_full, reducing disk usage by >10x.
- Added keep_only_best parameter, when True acts as calling predictor.delete_models(models_to_keep='best', dry_run=False) at the end of fit().
- Added save_space parameter, when True acts as calling predictor.save_space() at the end of fit().
- Added option to specify string presets for 'hyperparameters' to simplify interface for novice users.
- can_infer function added to models to enable save_bagged_models parameter
- Improved comprehensiveness of save_space() to delete empty …
> Tabular: Added presets, save_bagged_models, keep_only_best, and save_space

- setup.py
#461 
Updated version to 0.0.9. This will enable the daily PyPi pre-releases to be installable through `pip install autogluon --pre`
Fixes defect caused by `import skopt` after sklearn released 0.23
> Updated version to 0.0.9

- autogluon/utils/tabular/ml/models/abstract/abstract_model.py
- autogluon/utils/tabular/ml/models/ensemble/bagged_ensemble_model.py
Fixed refit_full models without bagging being in subdirectory of their original model.
This previously caused 'optimize_for_deployment' preset to crash when auto_stack=False, refit_full=True, and set_best_to_refit_full=True. This now works correctly.
> Tabular: Fixed refit_full models without bagging

- autogluon/task/tabular_prediction/predictor.py
- autogluon/utils/tabular/ml/learner/abstract_learner.py
- autogluon/utils/tabular/ml/trainer/abstract_trainer.py
- tests/unittests/test_tabular.py
Changes:
- Added 'original' feature importance
- This is the original features only, so automatically generated ngrams are not included, and it will properly give importance calculations to text features.
- Updated raw arg to feature_stage for feature importance
- Lowered default subsample_size to 1,000 from 10,000
- Fixed crash in feature importance when sent a dataset with nan class labels after label transformation.
> Tabular: Added 'original' feature importance

- autogluon/utils/tabular/metrics/classification_metrics.py
- autogluon/utils/tabular/ml/learner/abstract_learner.py
- autogluon/utils/tabular/ml/learner/default_learner.py
#480 
- Fixed pac_score metric for both binary and multiclass classification
- Fixed defective differences between learner.evaluate(), learner.score() and learner.score_debug().
> Tabular: Fixed pac_score metric

- autogluon/utils/tabular/ml/trainer/auto_trainer.py
Tabular: Make all get_models args use keywords in code
This simplifies future extensibility in the case that someone extends Trainer but doesn't care about the hyperparameter arg in get_models.
> Tabular: Make all get_models args use keywords in code

- autogluon/utils/tabular/ml/models/catboost/catboost_utils.py
Optimized usage of metrics to use native CatBoost metrics when available. This impacts regression datasets and when stopping_metric='roc_auc' for binary datasets.
> Tabular: Optimized CatBoost training speed by ~100% in some cases

- setup.py
Updated minimum sklearn version to 0.22 as Tabular NN raises an exception on lower sklearn versions when onehot encoded features are present.
> Updated minimum sklearn version to 0.22

- autogluon/task/image_classification/classifier.py
I believe the reason the example is [not rendering correctly](https://autogluon.mxnet.io/api/autogluon.task.html#autogluon.task.ImageClassification.Classifier.predict) in the docs is because it's missing the linebreak between the end of the docstring and example.
*Description of changes: Just adding a linebreak so that the example renders correctly in the docs.
> Small fix to documentation

- autogluon/utils/tabular/ml/models/catboost/catboost_model.py
The RSM optimization works only when trained on CPU - added check if GPU training is active
> CatBoost - disabled RSM if GPU training is enabled

- autogluon/task/tabular_prediction/predictor.py
- autogluon/task/tabular_prediction/tabular_prediction.py
- autogluon/utils/tabular/ml/learner/abstract_learner.py
- autogluon/utils/tabular/ml/learner/default_learner.py
Resolves #535 
- Added version check when loading predictor that warns user if different version
- Added log of version during fit
- Removed duplicate code
- Added version to info output
Log Example:
```
############################## WARNING ##############################
WARNING: AutoGluon version differs from the version used during the original model fit! This may lead to instability and it is highly recommended the model be loaded with the exact AutoGluon version it was fit with.
Fit Version:     Unknown (Likely <=0.0.11)
Current Version: 0.0.12
############################## WARNING ##############################
```
```
Beginning AutoGluon training ...
AutoGluon will save models to AutogluonModels/ag-20200625_214800/
AutoGluon …
```
> Tabular: Added version check when loading predictor

- autogluon/utils/tabular/ml/models/tabular_nn/tabular_nn_model.py
Defect introduced in #518 
Fixed major defect in NN causing crashes with categoricals. Since 0.0.11 release, any dataset with categoricals that cause embeddings to be created in the NN will cause the NN to fail during training.
> Tabular: Fixed major defect in NN causing crashes with categoricals

- autogluon/scheduler/fifo.py
- autogluon/scheduler/hyperband.py
- autogluon/scheduler/rl_scheduler.py
- autogluon/searcher/bayesopt/autogluon/searcher_factory.py
- autogluon/searcher/gp_searcher.py
- autogluon/utils/default_arguments.py
- docs/tutorials/nas/rl_searcher.md
- tests/unittests/test_scheduler.py
Extends something I did for GP searchers to schedulers. Arguments are losely type-checked, and default values are maintained consistently (e.g., do not have to copy&paste default values from superclass).
Also, whenever a default value is imputed, this is written into the log, so you later on know what argument values were used.
> Clean up argument checking and default value imputation for schedulers

- docs/install.rst
Replaced the 60-minute Gluon crash course link
> Fix dead link in docs/install.rst

- .github/workflows/pypi_release.yml
Added comment about this issue: https://github.community/t/workflow-set-for-on-release-not-triggering-not-showing-up/16286/5
for anybody that releases future autogluon versions to be less confused if the Pypi release action failed to trigger.
> comment how to avoid release bug in pypyi workflow

- autogluon/core/decorator.py
- autogluon/core/space.py
- tests/unittests/test_search_space.py
Issue #: https://github.com/awslabs/autogluon/issues/560
Description of changes:
- Change the splitter in the nested search space to a special unicode character: u'▁'  (U+2581).
> [Bugfix] Use a special unicode as the separator in search space

- autogluon/scheduler/fifo.py
- tests/unittests/test_scheduler.py
Sometimes, we will want to load the weights of the best model searched via HPO. This is similar to the `get_best_logdir` option in ray/tune (See https://docs.ray.io/en/latest/tune/tutorials/tune-tutorial.html#tune-tutorial).
Thus, I added this `get_best_task_id` method to FIFOScheduler.
> [HPO][Scheduler] Add `get_best_task_id`

- autogluon/task/tabular_prediction/dataset.py
- autogluon/utils/tabular/features/abstract_feature_generator.py
- autogluon/utils/tabular/features/auto_ml_feature_generator.py
#579
- Fixed datetime features to avoid repeated appending to feature name list (no impact on predictions, only on memory usage after many calls to predict).
- Fixed similar defect in text_as_category features.
- Removed inplace=True from reset_index calls to avoid outward propagation of index changes.
- Disabled default df.copy(deep=True) call in TabularDataset init, to avoid unnecessarily doubling memory usage.
- Various code cleanup
> Tabular: Refactor FeatureGenerator (Part 1)

- autogluon/utils/tabular/ml/models/knn/knn_model.py
- autogluon/utils/tabular/ml/models/knn/knn_utils.py
- autogluon/utils/try_import.py
- setup.py
This code adds 
The new KNeighborsClassifier is a drop-in replacement for the sklearn model, but is built on top of the FAISS index. There is one additional optional parameter for the model: index_factory_string, which describes what type of FAISS index to use (this just gets passed to FAISS's index construction method).
There is one new dependency on faiss-cpu. 
> Integrate FAISS index for KNN classifier

- CONTRIBUTING.md
Add sample command to convert ipynb to markdown files, and clear output cells
*Description of changes:* minor
> add sample command to convert ipynb to markdown files

- autogluon/utils/tabular/metrics/classification_metrics.py
- autogluon/utils/tabular/ml/learner/abstract_learner.py
- tests/unittests/utils/tabular/metrics/test_classification_metrics.py
*Issue #544 :*
**Motivation**
Added confusion matrix metric into tabular classification metrics library with corresponding unit tests
**Implementation**
- Checked if both true and predicted targets are of same shape and are of type binary or multi-class
- Checked if labels (if passed as a parameter) is a 1-D binary or multi-class array without duplicate elements
- Checked if weights (if passed as a parameter) is a 1-D binary, multi-class or continuous array
- Removed indexes having targets that are not included in the desired label array
- Returned coordinate matrix with the processed targets, labels and weights
**Testing**
Unit tests passed 
> Added confusion matrix metric for binary and multi-class classification

- autogluon/task/tabular_prediction/predictor.py
- autogluon/utils/tabular/ml/learner/abstract_learner.py
Resolves #565 
#544 
- Fixed defect where ndarray y_pred and series y_true were sent as input to `predictor.evaluate_predictions` and y_true's index was not reset causing index misalignment and incorrect scoring of eval_metric.
- Improved code clarity / quality + added TODO's for future improvements
- Improved return value of confusion matrix to be a DataFrame instead of a json string.
> Tabular: Fixed incorrect metric score calculation in evaluate

- autogluon/searcher/rl_controller.py
I was using RL NAS part of Autogluon. But I found that `rl_scheduler.get_best_config()` wasn't returning the best config.
So I check the code of Autogluon and found wrong overloading. The `RLSearcher` is inherited from `BaseSearcher`. While `BaseSearcher` has the right `get_best_config()`, `RLSearcher` overloaded this function with simply `inference()` which is obviously wrong. 
So I remove the wrong overloading and everything works fine again.
> Fix wrong function overloading.

- autogluon/scheduler/scheduler.py
- tests/unittests/test_scheduler.py
According to the document of dask: https://distributed.dask.org/en/latest/api.html#distributed.Future.result
`.result(timeout)` will raise a `distributed.TimeoutError`. However, in the code base, the try + except just handles the `TimeoutError`.
We may use the following tiny example to understand the issue. If the exception is handled correctly, it will print 123. However, it actually raises the Exception.
```python
import distributed
try:
raise(distributed.TimeoutError)
except TimeoutError:
print(123)
```
Output:
```
TimeoutError: 
```
@zhreshold
> [HPO][BugFix] Fix the bug in scheduler

- autogluon/utils/tabular/data/label_cleaner.py
- autogluon/utils/tabular/ml/learner/abstract_learner.py
- autogluon/utils/tabular/ml/learner/default_learner.py
- autogluon/utils/tabular/ml/utils.py
- tests/unittests/utils/tabular/data/test_label_cleaner.py
- Fixed crash that occurs on LGBM training when label dtype was category instead of object.
- Improved type consistency in internal label, converts category to object
- Added unit tests for LabelCleaner
> Tabular: Fixed category dtype label input crash on LGBM

- Jenkinsfile
- docs/build.yml
- docs/build_contrib.yml
- docs/install-include.rst
Test for MXNet 1.7.0 nightly to see if there are any issue.
> Update build and test with mxnet 1.7.0

- autogluon/utils/tabular/ml/utils.py
avoid crashes when two autogluon jobs launched in the same second.
*Issue #, if available:* #614 
As described in the issue, repeatedly add a increasing sequential number to the output directory until we find one that is available. As a guardrail, we limit the number of tries to 1000.
Tests:
Change savedir in the example script to None, and run the following command:
```
for i in $(seq 4); do python examples/tabular/example_simple_tabular.py & done
```
Before the change, two or three jobs will fail due to FileExistsError.
After the change, all four jobs succeed, with jobs launched in the same second go to different output directories
```
ag-20200817_004754
ag-20200817_004754-001
ag-20200817_004754-002
```
By submitting this pull request, I confirm that you can …
> more robust method to automatically set up output directory (#614)

- autogluon/task/tabular_prediction/predictor.py
- autogluon/utils/tabular/ml/learner/abstract_learner.py
- autogluon/utils/tabular/ml/models/abstract/abstract_model.py
- autogluon/utils/tabular/ml/models/ensemble/bagged_ensemble_model.py
- autogluon/utils/tabular/ml/models/lgb/lgb_model.py
- autogluon/utils/tabular/ml/models/tabular_nn/tabular_nn_model.py
- autogluon/utils/tabular/ml/trainer/abstract_trainer.py
- tests/unittests/test_tabular.py
- Added extra_info argument to predictor.leaderboard(). This includes many very useful info columns such as memory usage and model hyperparameters.
- Fixed NN using 1 less epoch then intended during refit_full.
- Fixed LightGBM having wrong hyperparameters_fit value after refit_full.
> Tabular: Added extra_info argument to predictor.leaderboard()

- autogluon/utils/tabular/ml/learner/abstract_learner.py
Fixed crash when NaN labels are present in y_true during evaluate_predictions, now it properly shows the warning and drops the NaN rows.
> Tabular: Fixed crash on NaN labels in evaluate_predictions

- autogluon/utils/tabular/ml/models/abstract/abstract_model.py
- autogluon/utils/tabular/ml/models/knn/knn_model.py
- autogluon/utils/tabular/ml/models/rf/rf_model.py
Reduced maximum allowed memory usage for RF, XT, and KNN models to avoid OOM errors during memory size calculation in .info
> Tabular: Reduced maximum allowed memory usage for RF, XT, and KNN models

- docs/install-faq.rst
- docs/install-include.rst
- docs/install.rst
- docs/tutorials/text_prediction/beginner.md
- docs/tutorials/text_prediction/customization.md
The temporary solution is to ask the users to install the new version of MXNet by following the guide in https://sxjscience.github.io/KDD2020/.
Here, the user may met the issue that they cannot find the correct MXNet package with `-f https://sxjscience.github.io/KDD2020/`. So I created this fix (Also, I replaced `pip install` to `python3 -m pip install` to ensure that it works for most platforms including Anaconda and EC2 AMI).
In addition, reduce the time_limits to 5 minutes for the TextPrediction-customization tutorial.
> [Fix] [Documentation] Update installation guide

- docs/tutorials/tabular_prediction/index.rst
- docs/tutorials/tabular_prediction/tabular-faq.md
Adds an FAQ page for the docs that includes an example for chunking the inference dataset
> Add example for chunked inferencing

- autogluon/task/tabular_prediction/tabular_prediction.py
Added missing ` at the end of code snippet
> Typo fix in docstring

- autogluon/utils/tabular/ml/models/tabular_nn/tabular_nn_model.py
Change NN to early-stop if validation-score hasn't *strictly* improved in `epochs_wo_improve` consecutive epochs.
Suppose epoch `e1` = epoch where validation-score first hits max-value and validation-score plateaus at this point. 
After this change, we now consider the "best" model the one from epoch `e2 = e1 + epochs_wo_improve`. 
Thus we still train a little bit beyond the point where validation-score plateaus (perhaps margin of decision-boundary can still be improved), but the amount of extra-training is strictly limited by the user-controllable hyperparameter `epochs_wo_improve` (rather than before where the NN could continue training for a long time while validation-score remained plateaued).
So users who want to be sure they are achieving maximal accuracy (at potential cost of long …
> more aggressive NN early stopping

- autogluon/task/tabular_prediction/predictor.py
- autogluon/utils/tabular/ml/learner/abstract_learner.py
- autogluon/utils/tabular/ml/models/ensemble/bagged_ensemble_model.py
- autogluon/utils/tabular/ml/trainer/abstract_trainer.py
- tests/unittests/test_tabular.py
#376 
Added persist_models, unpersist_models methods to TabularPredictor
> Tabular: Added persist_models, unpersist_models methods to TabularPredictor

- autogluon/task/tabular_prediction/predictor.py
- autogluon/utils/tabular/ml/learner/abstract_learner.py
Removed prediction cache functionality
- Prediction cache didn't work with a lot of more complex functionality and is something that ideally should be done by users instead of by AutoGluon.
- Technically this is an API breaking change if users were specifying the cache arguments in predictor.predict.
- Fixed defect in as_pandas output of predict_proba not using correct index.
- Removed old and unused variables and methods from abstract_learner.py
> Tabular: Removed prediction cache functionality

- autogluon/utils/tabular/ml/trainer/abstract_trainer.py
Fixed weighted ensemble stopping metric.
Previously, it was incorrectly using the stopping_metric for early stopping, now it is using eval_metric as intended.
> Tabular: Fixed weighted ensemble stopping metric

- autogluon/utils/tabular/ml/learner/abstract_learner.py
Reduced max memory usage of leaderboard by moving the model size calculations to before the calculation of pred_proba predictions of models.
> Tabular: Reduced max memory usage of leaderboard

- autogluon/utils/tabular/contrib/tabular_nn_pytorch/hyperparameters/parameters.py
- autogluon/utils/tabular/contrib/tabular_nn_pytorch/hyperparameters/searchspaces.py
- autogluon/utils/tabular/contrib/tabular_nn_pytorch/tabular_nn_fastai.py
- autogluon/utils/tabular/ml/models/fastainn/callbacks.py
- autogluon/utils/tabular/ml/models/fastainn/hyperparameters/parameters.py
- autogluon/utils/tabular/ml/models/fastainn/hyperparameters/searchspaces.py
- autogluon/utils/tabular/ml/models/fastainn/tabular_nn_fastai.py
- autogluon/utils/tabular/ml/trainer/model_presets/presets.py
- autogluon/utils/try_import.py
This code adds tabular neural networks using pytorch/fastAI frameworks. 
```python
custom_hyperparameters = {'FASTAI': {}}
predictor = task.fit(train_data=train_data, label=label_column, hyperparameters=custom_hyperparameters) 
predictor.leaderboard()
```
openml 10-minute benchmarks results:
|id                 |task                                  |framework       |constraint|fold|result   |metric |mode |version|params                               |tag   |utc                |duration|models|seed      |info|acc     |auc     |logloss  |models_ensemble_count|predict_duration|
|-------------------|--------------------------------------|----------------|----------|----|---------|-------|-----|-------|-------------------------------------|------|-------------------|--------|------|----------| …
> fastai v1 tabular model

- autogluon/task/text_prediction/models/basic_v1.py
- autogluon/task/text_prediction/modules/basic_prediction.py
- autogluon/task/text_prediction/preprocessing.py
- autogluon/task/text_prediction/text_prediction.py
- tests/unittests/test_nlp_text_prediction.py
*Issue #, if available:* https://github.com/awslabs/autogluon/issues/647
> [Bugfix] Fix TextPrediction Bug

- autogluon/utils/tabular/ml/models/fastainn/tabular_nn_fastai.py
`select_dtypes(['float'])` will select only float64. If the dataset has float32 or other types, those would be ignored. Expanded list of supported types.
> [Tabular] fast.ai: expanded data types selector to handle wider range of types.

- autogluon/task/text_prediction/dataset.py
- autogluon/utils/pil_transforms.py
- autogluon/utils/tabular/features/types.py
- autogluon/utils/tabular/ml/trainer/abstract_trainer.py
*Issue : Fixes #659 *
* Import ABC from `collections.abc`
* Fix syntax warnings due to comparison of literals using is
> Fix warnings in Python 3.8

- autogluon/utils/tabular/ml/models/rf/rf_model.py
- setup.py
- Updated CatBoost version
- Made RF and XT models deterministic by default (random_state=0) so that their results can be reproduced on repeated runs.
> Tabular: Updated CatBoost to 0.24.x

- autogluon/utils/tabular/ml/models/fastainn/tabular_nn_fastai.py
pandas `select_dtypes()` does not accepts the types `'str', 'string_', 'unicode_'` - removed those
> [Bugfix] Removed str types from categorical columns - not supported by selector

- autogluon/searcher/bayesopt/autogluon/searcher_factory.py
- autogluon/searcher/gp_searcher.py
Fixes issue #685 . It also changes the default to a random seed and makes it mandatory to pass the confispace argument to the GPFIFOSearcher 
> Fix gp fifo searcher

- vision/src/autogluon/vision/object_detection/object_detection.py
PR provides a fix in object detection task when ngpus_per_trial is set to 0 for detector. 
**Error observed**
_ind, prob, loc = detector.predict(image_path)_ 
>   File "/usr/local/lib/python3.6/site-packages/autogluon/task/object_detection/detector.py", line 171, in predict
>     net.collect_params().reset_ctx(ctx=mx.cpu())
>   File "/usr/local/lib/python3.6/site-packages/mxnet/gluon/parameter.py", line 929, in reset_ctx
>     i.reset_ctx(ctx)
>   File "/usr/local/lib/python3.6/site-packages/mxnet/gluon/parameter.py", line 493, in reset_ctx
>     "has not been initialized."%self.name)
> ValueError: Cannot reset context for Parameter 'mobilenet0_conv0_weight' because it has not been initialized.
**Fix**
To set the cpu context if num of …
> Fix in object detection task to support train and predict on cpu node.

- Jenkinsfile
- autogluon/setup.py
- docs/ReleaseInstructions.md
- docs/config.ini
- docs/root_index.html
- extra/setup.py
- mxnet/setup.py
- tabular/setup.py
- text/setup.py
- vision/setup.py
* master branch will no longer publish docs into the root https://autogluon.mxnet.io/ 
* master branch will publish all docs to https://autogluon.mxnet.io/dev/
* master branch will publish root_index.html (new file) into root index.html. The only thing this file is going to do is to immediately redirect into https://autogluon.mxnet.io/stable/
* docs updated
* restricted internal cross-module versions to a specific version
* doc links in headers are now replaced dynamically to a correct branch during the build time
> [CI refactoring] Updated docs publication process

- CONTRIBUTING.md
- Jenkinsfile
- README.md
- docs/ReleaseInstructions.md
- docs/config.ini
- docs/index.rst
- docs/install-warning.rst
- docs/root_index.html
- docs/versions.rst
- Updated autogluon.mxnet.io -> auto.gluon.ai
- Updated links to point to /dev/ or /stable/ appropriately, instead of root.
> Fixed website links to point to stable release docs

- core/src/autogluon/core/scheduler/fifo.py
- core/src/autogluon/core/task/base/base_task.py
- core/tests/unittests/test_base_task.py
https://github.com/awslabs/autogluon/issues/488
Found the root error during another experiment. There are two issues with existing BaseTask
- If logging level not properly set, the stacktrace of failed task won't be displayed
- If training config with best config failed, `None` object is returned, causing #488 
The solution is to ensure the stacktrace will be printed, and catch the `None.update` issue
> [Bug Fix] BaseTask: fix silent exception, handle None in best config result

- core/src/autogluon/core/task/task.py
Added random jitter delay for task id generation - this naturally makes simultaneous state updates/requests less likely.
*Tasks start logs*
Task with id 4 was scheduled multiple times. The problem relatively easy to reproduce without this change on ubuntu, 8-core machine.
``` plain
Scheduling Task (task_id: 0,
fn: <function lgb_trial at 0x7fa83ace9b00>,
args: {args: {'util_args': {'dataset_train_filename': 'dataset_train.bin', 'dataset_val_filename': 'dataset_val.b.., config: {'feature_fraction': 1.0, 'learning_rate': 0.1, 'min_data_in_leaf': 20, 'num_leaves': 31}, reporter: DistStatusReporter, },
resource: DistributedResource(
Node = Remote REMOTE_ID: 0,
<Remote: 'inproc://<ip_here>/18386/1' processes=1 threads=8, memory=33.19 GB>
nCPUs = 1, CPU_IDs = {[0]})) …
```
> [Scheduler][Stability] Adding random jitter to address duplicate task ids occurrence

- examples/tabular/example_custom_model_tabular.py
- tabular/src/autogluon/tabular/features/feature_metadata.py
- tabular/src/autogluon/tabular/models/abstract/abstract_model.py
- tabular/src/autogluon/tabular/models/catboost/catboost_model.py
- tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
- tabular/src/autogluon/tabular/models/knn/knn_model.py
- tabular/src/autogluon/tabular/models/lgb/lgb_model.py
- tabular/src/autogluon/tabular/models/lr/lr_model.py
- tabular/src/autogluon/tabular/models/rf/rf_model.py
- tabular/src/autogluon/tabular/models/tabular_nn/tabular_nn_model.py
#580 
- Added object dtype to the ignored type list of all tabular models, as they should be converted to category first.
- This enables text features in object type form to not crash tabular models, they will be dropped instead.
- Added get_features_kwargs and get_features_kwargs_extra aux model params to enable full flexibility of which feature types a model accepts.
> Tabular: Added dropping of object type features in tabular models

- core/src/autogluon/core/scheduler/hyperband.py
- core/src/autogluon/core/scheduler/hyperband_promotion.py
- core/src/autogluon/core/scheduler/hyperband_stopping.py
- core/src/autogluon/core/searcher/bayesopt/autogluon/gp_multifidelity_searcher.py
- core/src/autogluon/core/searcher/gp_searcher.py
- core/tests/unittests/test_checkpoint_resume.py
- examples/hpo/mlp.py
Apart from clean-ups (unify common code), this is contributing two new variants of Hyperband:
- Allow jobs in different brackets to compete with each other for promotions
- Allow user to specify rung levels (in case the exponential spacing is not appropriate)
*Testing:*
Apart from unit test, I ran some before/after comparisons. Results are exactly the same for random searchers, and very close for bayesopt searchers (where optimization introduces uncontrollable randomness).
> Refactor and extend HyperbandScheduler

- tabular/src/autogluon/tabular/models/abstract/abstract_model.py
- tabular/src/autogluon/tabular/trainer/abstract_trainer.py
- tabular/src/autogluon/tabular/trainer/auto_trainer.py
- tabular/src/autogluon/tabular/trainer/model_presets/presets.py
- tabular/src/autogluon/tabular/trainer/model_presets/presets_distill.py
- Addressed duplicate model name issue, now when models share the same name, one will have a unique suffix appended to it. This is a pre-req for repeated fit functionality to work smoothly. Prior, the model would overwrite the earlier model it shared a name with, leading to major bugs with stackers having their base models overwritten. This bug did not happen in current usage, but could start to happen if users were allowed to call fit repeatedly.
- Removed duplicate stack trace print on model exception, before the stack trace was being printed twice.
- Simplified hyperparameters argument in `Trainer.train_multi_levels` to handle the same input format as users provide in task.fit(hyperparameters), in preparation for repeated fit …
> Tabular: Ensure unique model names

- Jenkinsfile
- core/tests/test_check_style.py
- extra/tests/test_check_style.py
- mxnet/tests/test_check_style.py
- tabular/tests/test_check_style.py
- text/tests/test_check_style.py
- vision/tests/test_check_style.py
- Fixed Jenkinsfile typo: aut**u**gluon-py3 -> aut**o**gluon-py3
- Updated test_check_style.py to correctly fail if PEP8 warnings exceeded.
> Fixed Jenkinsfile typo

- autogluon/setup.py
- core/setup.py
- extra/setup.py
- mxnet/setup.py
- tabular/setup.py
- text/setup.py
- vision/setup.py
Builds happening near midnight have a chance of a date flip in build minor version as a result earlier built dependencies could not be found on a date change and the build fails. This change fixes the minor version across all namespace packages.
> [CI] Fixing build version across modules to core version

- tabular/src/autogluon/tabular/features/generators/auto_ml_pipeline.py
- tabular/src/autogluon/tabular/features/generators/drop_unique.py
Add the "enable_raw_text_features" flag to feature generator so that the raw text column will be used as a feature. This will benefit the NLP models like BERT/FastText.
> [Feature Generator][Tabular] Add the ability to generate raw text

- core/src/autogluon/core/utils/utils.py
- tabular/src/autogluon/tabular/learner/abstract_learner.py
- tabular/src/autogluon/tabular/task/tabular_prediction/predictor.py
- tabular/src/autogluon/tabular/task/tabular_prediction/tabular_prediction.py
- tabular/src/autogluon/tabular/trainer/abstract_trainer.py
- tabular/src/autogluon/tabular/trainer/auto_trainer.py
- Cleaned abstract_trainer.py in preparation for repeated fit implementation.
- Replaced model_levels functionality with simplified calls to model_graph.
- Added numerous type hints.
- Fixed defect when calling predictor.delete_models when keeping only refit_full models, previously raised exception.
> Tabular: Cleaned abstract_trainer.py

- core/src/autogluon/core/constants.py
- tabular/src/autogluon/tabular/models/abstract/abstract_model.py
- tabular/src/autogluon/tabular/models/ensemble/bagged_ensemble_model.py
- tabular/src/autogluon/tabular/models/ensemble/greedy_weighted_ensemble_model.py
- tabular/src/autogluon/tabular/models/ensemble/stacker_ensemble_model.py
- tabular/src/autogluon/tabular/models/ensemble/weighted_ensemble_model.py
- tabular/src/autogluon/tabular/task/tabular_prediction/tabular_prediction.py
- tabular/src/autogluon/tabular/trainer/abstract_trainer.py
- tabular/src/autogluon/tabular/trainer/model_presets/presets.py
Added functionality to specify that a model should not be used as a stacker and that a model should not use the original features.
Example:
```
'GBM': [
{},
{'AG_args': {'valid_stacker': False}},
{'AG_args': {'valid_base': False}},
{'AG_args_ensemble': {'use_orig_features': False}}
],
}
```
TODO:
> Added AG_ARGS_STACK functionality

- tabular/src/autogluon/tabular/task/tabular_prediction/predictor.py
NA
It is to add a function to Tabular predictor which visualizes the stacking ensemble model. It does not take any parameter, and it saves the generated graph into the model directory.
This function relies on graphviz and pygraphviz. These libraries can be installed via;
```
sudo apt-get install graphviz
pip install graphviz
```
> adding stack ensemble visualization

- core/src/autogluon/core/utils/files.py
In several scheduler code, lines like
mkdir(os.path.dirname(checkpoint))
raise exceptions if checkpoint is a filename without a directory.
> Avoid mkdir raising exception if path is empty string

- core/src/autogluon/core/metrics/__init__.py
- tabular/src/autogluon/tabular/learner/abstract_learner.py
- tabular/src/autogluon/tabular/models/abstract/abstract_model.py
- tabular/src/autogluon/tabular/models/catboost/catboost_model.py
- tabular/src/autogluon/tabular/models/ensemble/bagged_ensemble_model.py
- tabular/src/autogluon/tabular/models/ensemble/weighted_ensemble_model.py
- tabular/src/autogluon/tabular/models/lgb/lgb_model.py
- tabular/src/autogluon/tabular/models/tab_transformer/tab_transformer_model.py
- tabular/src/autogluon/tabular/models/tabular_nn/tabular_nn_model.py
- tabular/src/autogluon/tabular/models/xgboost/xgboost_model.py
- tabular/src/autogluon/tabular/task/tabular_prediction/predictor.py
- tabular/src/autogluon/tabular/task/tabular_prediction/tabular_prediction.py
- tabular/src/autogluon/tabular/trainer/abstract_trainer.py
- tabular/src/autogluon/tabular/tuning/feature_pruner.py
- tabular/src/autogluon/tabular/utils.py
- tabular/tests/unittests/test_tabular.py
- Optimized feature importance calculation speed by 10x+ in expensive situations involving many features (3000s -> 250s on dual-core mac laptop with identical final result, likely larger gains with more CPU cores).
- Refactored and standardized feature importance calculations to stem from a single function.
- Added `time_limit` and `num_shuffle_sets` functionality to feature importance.
- Fixed XGBoost `transformed_model` feature importance causing exceptions.
- Added stddev and z-score calculations and outputs to feature importance.
TODO:
> Tabular: Optimize feature importance

- tabular/src/autogluon/tabular/learner/default_learner.py
- tabular/src/autogluon/tabular/models/ensemble/stacker_ensemble_model.py
- tabular/src/autogluon/tabular/task/tabular_prediction/predictor.py
- tabular/src/autogluon/tabular/task/tabular_prediction/tabular_prediction.py
- tabular/src/autogluon/tabular/trainer/abstract_trainer.py
- tabular/src/autogluon/tabular/trainer/auto_trainer.py
- tabular/src/autogluon/tabular/trainer/model_presets/presets.py
- Added `AG_args` and `AG_args_ensemble` arguments to task.fit, this allows users to do interesting things like disable stackers from using original features (only use stack features) via `AG_args_ensemble={'use_orig_features': False}`, or give all models a prefix in their name via `AG_args={'name_prefix': 'CustomPrefix_'}`.
- Fixed `unlabeled_data` error during stack ensembling.
- Enabled user overrides for `stack_ensemble_levels` and `num_bagging_folds` when `presets` or `auto_stack` are enabled (previously was confusing as user values were being silently ignored in these cases).
- Improved sanity checking for `stack_ensemble_levels` and `num_bagging_folds` values and compatibility (e.g. `stack_ensemble_levels` cannot be 1 if …
> Tabular: Added AG_args and AG_args_ensemble arguments to task.fit

- core/setup.py
- core/src/autogluon/core/scheduler/remote/cli.py
- core/src/autogluon/core/scheduler/remote/remote.py
- core/src/autogluon/core/scheduler/scheduler.py
- core/src/autogluon/core/utils/multiprocessing_utils.py
- core/tests/unittests/test_search_space.py
- docs/api/autogluon.core.rst
- docs/index.rst
- tabular/src/autogluon/tabular/models/abstract/abstract_model.py
- tabular/src/autogluon/tabular/models/ensemble/stacker_ensemble_model.py
- tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
- tabular/src/autogluon/tabular/models/knn/knn_model.py
- tabular/src/autogluon/tabular/models/lgb/lgb_model.py
- tabular/src/autogluon/tabular/models/lr/lr_model.py
- tabular/src/autogluon/tabular/models/rf/rf_model.py
- tabular/src/autogluon/tabular/models/tabular_nn/tabular_nn_dataset.py
- tabular/src/autogluon/tabular/models/tabular_nn/tabular_nn_model.py
- tabular/src/autogluon/tabular/task/tabular_prediction/tabular_prediction.py
- fixes issues with threads locking
- fixes issues with CUDA - [#620](https://github.com/awslabs/autogluon/issues/602)
- fixes to scheduler tests to enable pickling
- use forkserver only for HPO; dataloader updates
- force thread_pool usage for forkserver to prevent GIL locks
- Added GPU control options; added docs
- Added stdout/stderr capture
Updated version of #767 
> Enable forkserver as a default forking mode for HPO

- text/src/autogluon/text/text_prediction/column_property.py
- text/src/autogluon/text/text_prediction/preprocessing.py
- text/tests/unittests/test_text_prediction.py
Fix the handling of empty sentences. In the old version, if the text column contains None, it will raise the following error:
```python
--> 185             column_properties[col_name].parse(df[col_name])
186             continue
187         # Raise error if we find an entity column
~/autogluon/text/src/autogluon/text/text_prediction/column_property.py in parse(self, column_data)
276     def parse(self, column_data: pd.Series):
277         super().parse(column_data)
--> 278         lengths = column_data.apply(len)
279         self._min_length = lengths.min()
280         self._avg_length = lengths.mean()
/usr/local/lib/python3.6/dist-packages/pandas/core/series.py in apply(self, func, convert_dtype, args, **kwds)
4198             else:
4199                 values = …
```
> [TextPrediction] Fix empty sentence handling

- tabular/src/autogluon/tabular/models/catboost/hyperparameters/parameters.py
- tabular/src/autogluon/tabular/models/catboost/hyperparameters/searchspaces.py
- tabular/src/autogluon/tabular/models/lgb/hyperparameters/parameters.py
- tabular/src/autogluon/tabular/models/lgb/hyperparameters/searchspaces.py
Halved the learning rate of default LGB and CAT models.
This significantly improves medium-quality as seen below (and very slightly improves best-quality)
`AutoGluon_1h_2020_12_30_gbm` is this PR's medium-quality
`AutoGluon_1h_2020_12_25` is mainline's medium-quality
```
AutoGluon_1h_2020_12_25 VS all
framework  > AutoGluon_1h_2020_12_25  < AutoGluon_1h_2020_12_25  = AutoGluon_1h_2020_12_25  % Less Avg. Errors Than AutoGluon_1h_2020_12_25  time_train_s  metric_error  time_infer_s  loss_rescaled      rank  rank=1_count  rank=2_count  rank=3_count  rank>3_count  error_count
0  AutoGluon_1h_2020_12_30_gbm                         59                         34                          8                                         0.975875 …
```
> Tabular: Updated LGB and CAT default learning rates from 0.1 to 0.05

- Jenkinsfile
- docs/build_pip_install.sh
- tabular/setup.py
- tabular/src/autogluon/tabular/task/tabular_prediction/hyperparameter_configs.py
- tabular/src/autogluon/tabular/task/tabular_prediction/tabular_prediction.py
- tabular/tests/unittests/models/test_tabular_nn_fastai.py
Adds FastAI NN to default models. Also adds `torch` and `fastai` dependencies to Tabular. Plan is to move these into optional dependencies prior to v0.1 release.
Benchmark results:
`AutoGluon_bestquality_1h_2020_12_25` : Mainline
`AutoGluon_bestquality_fastai_1h_2020_12_30_fai` : This PR
```
AutoGluon_bestquality_1h_2020_12_25 VS all
framework  > AutoGluon_bestquality_1h_2020_12_25  < AutoGluon_bestquality_1h_2020_12_25  = AutoGluon_bestquality_1h_2020_12_25  % Less Avg. Errors Than AutoGluon_bestquality_1h_2020_12_25  time_train_s  metric_error  time_infer_s  loss_rescaled      rank  rank=1_count  rank=2_count  rank=3_count  rank>3_count  error_count
0  AutoGluon_bestquality_fastai_1h_2020_12_30_fai                                     53 …
```
> Tabular: Added FastAI NN to default models

- tabular/src/autogluon/tabular/features/generators/category.py
- tabular/src/autogluon/tabular/models/tabular_nn/categorical_encoders.py
- tabular/src/autogluon/tabular/models/tabular_nn/tabular_nn_model.py
- Optimized NN category embedding logic from O(n) -> O(1) where n is the number of categories.
- Added improved time limit control to NN.
- Optimized category handling for FeatureGenerator when minimum_cat_count is set from O(n) -> O(1).
This change results in a 4x speedup on small-medium category features between 5-15, and 100x+ speedup for extreme category count features during transformation.
The [albert](https://www.openml.org/d/41147) dataset had categorical features with 150,000 unique values:
Previously, NN took 1.5 hrs to transform the categorical features prior to fit. (ignoring time limits while doing so)
Now, NN takes only 30 seconds on the same data.
By submitting this pull request, I confirm that you can use, modify, copy, …
> Tabular: Optimized NN category embedding logic

- core/src/autogluon/core/utils/utils.py
- tabular/src/autogluon/tabular/models/knn/knn_model.py
- Added time_limit usage to KNN
- Fixed very rare crash when label column was category type and not all categories had rows and eval_metric was log_loss.
Previously on the KDDCup99 dataset, KNN would train for >10hrs regardless of time limit.
Now, it trains while respecting the time limit:
```
Fitting model: KNeighbors ... Training model for up to 561.84s of the 561.84s of remaining time.
Dropped 9 of 40 features.
0.56s 	= Train Time (Using 10000 of 4365529 samples) (559.12s remaining time)
0.86s 	= Train Time (Using 20000 of 4365529 samples) (558.26s remaining time)
1.55s 	= Train Time (Using 40000 of 4365529 samples) (556.71s remaining time)
20.25s 	= Train Time (Using 80000 of 4365529 samples) (536.46s remaining time)
62.91s 	= Train …
```
> Tabular: Added time_limit usage to KNN

- docs/tutorials/tabular_prediction/tabular-multimodal-text-others.md
- text/src/autogluon/text/text_prediction/models/basic_v1.py
- text/src/autogluon/text/text_prediction/text_prediction.py
This bug was introduced in https://github.com/awslabs/autogluon/pull/770 when I switched to use the metric scorer in the core package. The root cause is that the metric scorer will multiply the sign in the calculation. Thus, the RMSE scorer will actually give you -RMSE.
I corrected the logic in this PR. The bug affects the evaluation code while the training was still correct. The evaluation result will be negative for RMSEs. For example:
```
score = predictor.evaluate(train_df, metric='rmse')
```
And the score can be `-0.7`. The training won't be affected.
> [Bug][Fix] TextPrediction Metric Fix + Fix the default ELECTRA-base config

- core/src/autogluon/core/scheduler/fifo.py
- text/src/autogluon/text/text_prediction/models/basic_v1.py
- text/src/autogluon/text/text_prediction/text_prediction.py
- text/tests/unittests/test_text_prediction.py
```
predictor = TextPrediction.fit(train_data, label='Sentiment', visualizer='tensorboard')
```
> [Fix] Disable TextPrediction when GPU is not available + Fix Tensorboard Integration

- tabular/src/autogluon/tabular/models/catboost/catboost_model.py
- Temporarily disabled CatBoost GPU to avoid crash when time_limit is not None.
- This will be re-enabled once the defect is fixed and the 'auto' setting is implemented for per-model GPU usage.
> Tabular: Temporarily disabled CatBoost GPU to avoid crash when time_limit is not None

- core/src/autogluon/core/scheduler/fifo.py
- core/src/autogluon/core/scheduler/managers.py
Added  a quick check if resources are available before we check the time limit. This is required to prevent booking of the next job while we are waiting for a resource, which results in going over the time limit.
> [Scheduler][Bugfix] Added resources availability check before time limit is checked

- .github/workflows/codeql.yml
Addressed the following warning annotated when running CodeQL-Build:
> 1 issue was detected with this workflow: git checkout HEAD^2 is no longer necessary. Please remove this step as Code Scanning recommends analyzing the merge commit for best results.
Sample:
https://github.com/awslabs/autogluon/actions/runs/499961099
> Resolve warnings when running CodeQL-Build

- core/src/autogluon/core/task/base/base_task.py
- core/src/autogluon/core/utils/utils.py
- docs/tutorials/tabular_prediction/tabular-multimodal-text-others.md
- tabular/src/autogluon/tabular/models/abstract/abstract_model.py
- tabular/src/autogluon/tabular/models/ensemble/bagged_ensemble_model.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/src/autogluon/tabular/trainer/abstract_trainer.py
- tabular/src/autogluon/tabular/trainer/auto_trainer.py
- tabular/src/autogluon/tabular/trainer/model_presets/presets.py
- tabular/src/autogluon/tabular/trainer/model_presets/presets_custom.py
- tabular/src/autogluon/tabular/trainer/model_presets/presets_distill.py
- tabular/tests/unittests/models/test_text_prediction_v1_model.py
- Enables per model HPO control
- Now each model can specify its own scheduler (or lack of one) as an `ag_args` value.
- Enabled usage of 'custom' models when HPO is enabled. (custom models have HPO disabled so they just train normally)
Example:
```
'GBM': {'ag_args': {'hyperparameter_tune_kwargs': None}},
'CAT': {'ag_args': {'hyperparameter_tune_kwargs': 'bayesopt'}},
'NN': {},
}
```
In this example:
1. GBM model will not perform any HPO because of `{'hyperparameter_tune_kwargs': None}`
2. CAT model will perform HPO with bayesopt
3. NN model will perform HPO based on the predictor.fit `hyperparameter_tune_kwargs` value (or not do HPO if not specified).
4. predictor.fit `hyperparameter_tune_kwargs` value acts as the …
> Tabular: Per model HPO control

- core/src/autogluon/core/models/abstract/abstract_model.py
- Fixed bug causing models that use default HPO code to fail.
> Fix abstract_model HPO

- core/setup.py
- extra/setup.py
- features/setup.py
- mxnet/setup.py
- tabular/setup.py
- text/setup.py
- vision/setup.py
A new version of numpy (1.20.0) was released on Jan 30th. It is causing compatibility issues with pyarrow.
```
tests/unittests/test_text_prediction.py:248: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../../miniconda3/envs/autogluon-text-py3-v2/lib/python3.7/site-packages/mxnet/util.py:297: in _with_np_shape
return func(*args, **kwargs)
../../../../miniconda3/envs/autogluon-text-py3-v2/lib/python3.7/site-packages/mxnet/util.py:481: in _with_np_array
return func(*args, **kwargs)
src/autogluon/text/text_prediction/text_prediction.py:533: in fit
ignore_warning=verbosity <= 2)
../../../../miniconda3/envs/autogluon-text-py3-v2/lib/python3.7/site-packages/mxnet/util.py:297: in _with_np_shape
return func(*args, **kwargs) …
```
> [Dependencies] Constraining numpy to <1.20.0 due to pyarrow compatibility issues

- features/src/autogluon/features/generators/pipeline.py
- tabular/src/autogluon/tabular/learner/abstract_learner.py
- tabular/src/autogluon/tabular/learner/default_learner.py
https://github.com/awslabs/autogluon/issues/899
- Improved support for passing kwargs into feature generators fit_transform
- Added `y` and `problem_type` arguments to `.fit_transform` calls in `learner` to enable more advanced feature generation functionality.
> Improved support for passing kwargs into feature generators fit_transform

- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/models/abstract/model_trial.py
- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- core/src/autogluon/core/utils/plots.py
- tabular/src/autogluon/tabular/models/catboost/catboost_model.py
- tabular/src/autogluon/tabular/models/lgb/hyperparameters/lgb_trial.py
- tabular/src/autogluon/tabular/task/tabular_prediction/predictor_legacy.py
- tabular/src/autogluon/tabular/trainer/abstract_trainer.py
- tabular/src/autogluon/tabular/trainer/model_presets/presets.py
> Tabular: HPO bag fix

- features/src/autogluon/features/generators/auto_ml_pipeline.py
- features/src/autogluon/features/generators/text_ngram.py
*Issue #, if available:* 
https://github.com/awslabs/autogluon/issues/899
add option to pre-filter tokens according to correlation with the label: if `prefilter_tokens=True`, then only keep the `prefilter_token_count` most correlated tokens.
Use this option by parsing `AutoMLPipelineFeatureGenerator(prefilter_tokens=True, prefilter_token_count=10)`
into .fit().
Note that in the current form this will not work for multi-class classification problems.
> NLP token prefilter

- core/src/autogluon/core/data/label_cleaner.py
- core/src/autogluon/core/utils/savers/save_pd.py
- Fixes crash on leaderboard when multiclass problem is converted to binary internally, label cleaner was incorrectly using the internal problem type instead of the external problem type when converting internal pred_proba to external pred in leaderboard.
- Added support in save_pd to save without needing a directory. Aka: `save_pd.save('file.csv')` did not work before, but now does, because before it was trying to create a directory at `''`, which wasn't valid.
> Tabular: Fixed rare crash on leaderboard

- .gitignore
- Jenkinsfile
- core/setup.py
- extra/setup.py
- tabular/setup.py
- text/setup.py
- ConfigSpace must be installed after numpy is updated so it is not using 1.20.x coming from conda when installing - this is causing numpy compatibility errors:
```ValueError: numpy.ffff size changed, may indicate binary incompatibility. Expected xxx from C header, got yyy from zzz```
> [CI] ConfigSpace stability on CI

- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- tabular/src/autogluon/tabular/models/lgb/lgb_model.py
- tabular/src/autogluon/tabular/trainer/abstract_trainer.py
- tabular/src/autogluon/tabular/trainer/auto_trainer.py
- Moved HPO artifacts when bagging under the bagged model directory so they never conflict with future models, and the resulting directory layout is less cluttered.
- Added extra edge case handling for banned model names to avoid `.fit_extra` calls overwriting model names if both original `fit` and `fit_extra` used HPO with the same model types. Now this will never happen.
- If resource not specified in HPO kwargs, it will no longer override resources set in the original model to `'auto'`, but instead use the original model's values (could be values other than `'auto'`).
> Tabular: Refined HPO code / edge case handling

- core/src/autogluon/core/utils/compression_utils.py
- core/src/autogluon/core/utils/loaders/load_pkl.py
- core/src/autogluon/core/utils/savers/save_pkl.py
- core/tests/unittests/test_compression_utils.py
*[Issue # 581](https://github.com/awslabs/autogluon/issues/581)*
In an effort to break up the larger, outdated [Tabular pkl compression PR](https://github.com/awslabs/autogluon/pull/654) into smaller chunks, this PR takes the first step by adding `compression_fn` and `compression_fn_kwargs` to `load_pkl.py` and `save_pkl.py` as well as unit tests and utility functions.
> Part 1 of Tabular pkl compression PR: https://github.com/awslabs/autogluon/pull/654 

- vision/src/autogluon/vision/detector/detector.py
- vision/src/autogluon/vision/predictor/predictor.py
- vision/src/autogluon/vision/utils/__init__.py
- vision/src/autogluon/vision/utils/error_handler.py
https://github.com/awslabs/autogluon/issues/945
Catch MXNet errors, provide highlights and solutions to common errors.
Reproduce the error in #945, the new error message becomes:
```
File "test.py", line 4, in <module>
predictor.fit(train_dataset, hyperparameters={'epochs': 1}, hyperparameter_tune_kwargs={'num_trials': 2})
File "/home/ubuntu/test_mxnet_error_catcher/autogluon/vision/src/autogluon/vision/configs/presets_configs.py", line 15, in _call
return f(*gargs, **gkwargs)
File "/home/ubuntu/test_mxnet_error_catcher/autogluon/vision/src/autogluon/vision/predictor/predictor.py", line 321, in fit
raise RuntimeError(err.exc_value + err.hint)
RuntimeError: 'MXNetError: GPU is not enabled\n',
MXNet is not …
```
> [mxnet] Catch mxnet exception

- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/models/abstract/model_trial.py
- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- core/src/autogluon/core/models/greedy_ensemble/ensemble_selection.py
- core/src/autogluon/core/models/greedy_ensemble/greedy_weighted_ensemble_model.py
- core/src/autogluon/core/utils/utils.py
- tabular/src/autogluon/tabular/learner/abstract_learner.py
- tabular/src/autogluon/tabular/learner/default_learner.py
- tabular/src/autogluon/tabular/models/catboost/catboost_model.py
- tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
- tabular/src/autogluon/tabular/models/fasttext/fasttext_model.py
- tabular/src/autogluon/tabular/models/knn/knn_model.py
- tabular/src/autogluon/tabular/models/lgb/lgb_model.py
- tabular/src/autogluon/tabular/models/lr/lr_model.py
- tabular/src/autogluon/tabular/models/rf/rf_model.py
- tabular/src/autogluon/tabular/models/tab_transformer/tab_transformer_model.py
- tabular/src/autogluon/tabular/models/tabular_nn/tabular_nn_model.py
- tabular/src/autogluon/tabular/models/text_prediction/text_prediction_v1_model.py
- tabular/src/autogluon/tabular/models/xgboost/xgboost_model.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/src/autogluon/tabular/trainer/abstract_trainer.py
- tabular/src/autogluon/tabular/trainer/auto_trainer.py
- tabular/tests/unittests/test_tabular.py
Related Issues: #33 
Sample-weights functionality added. Example script:
```
from autogluon.tabular import TabularDataset, TabularPredictor
import numpy as np
train_data = TabularDataset('https://autogluon.s3.amazonaws.com/datasets/Inc/train.csv')
subsample_size = 100  # subsample subset of data for faster demo, try setting this to much larger values
train_data = train_data.sample(n=subsample_size, random_state=0)
train_data_noweight = train_data.copy()  # training data without weights
pos_class = ' >50K'
sample_weight = 'weight'
weights = np.zeros((len(train_data),))
weights[train_data[label]==pos_class] = 1  # models that can handle sample weights will only learn to predict positive class this way.
train_data[sample_weight] = weights …
```
> sample weights functionality

- features/src/autogluon/features/generators/drop_duplicates.py
#949 
- Added sample_size_init and sample_size_final params to DropDuplicatesFeatureGenerator.
- This enables virtually identical results as before, but with 100x+ fit time speedup for large datasets (1MM+).
- 1MM rows with 100 near-duplicate and 100 exact-duplicate features gets same result, but fit time reduced from 1500s -> 10s
- Added advanced detection of duplicate categoricals, even if their class names differ superficially.
> Features: Optimize DropDuplicates fit speed by 100x+ on large datasets.

- tabular/src/autogluon/tabular/models/tabular_nn/tabular_nn_model.py
If NN detects NaN validation score during training, will break and revert to last checkpoint with non-NaN validation score (or raise RuntimeError if no checkpoint exists yet). 
*Issue #, if available:* https://github.com/awslabs/autogluon/issues/932
> Fix NaN score issue in NN model

- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/src/autogluon/tabular/trainer/abstract_trainer.py
- tabular/src/autogluon/tabular/trainer/model_presets/presets.py
- tabular/src/autogluon/tabular/trainer/model_presets/presets_distill.py
#782 -> Implements Proposal 4. 
- Added +1 to all stack level values in code
- This means base models are now considered 'L1' instead of 'L0'. This improves clarity and aligns with common naming schemes outside of AG for multi-layer stacking.
> Tabular: Added +1 to all stack level values (No functional change)

- docs/tutorials/text_prediction/customization.md
- docs/tutorials/text_prediction/multimodal_text.md
- examples/text_prediction/README.md
- text/src/autogluon/text/__init__.py
- text/src/autogluon/text/text_prediction/presets.py
Somehow the MachineHack competitions cannot be directly accessed via the link and we must provide the instruction about how to go to the page.
> [Text Fix] Fix the competition link + Fix docs

- core/src/autogluon/core/data/label_cleaner.py
- core/src/autogluon/core/utils/utils.py
- docs/tutorials/tabular_prediction/tabular-faq.md
- docs/tutorials/tabular_prediction/tabular-kaggle.md
- docs/tutorials/tabular_prediction/tabular-quickstart.md
- tabular/src/autogluon/tabular/learner/abstract_learner.py
- tabular/src/autogluon/tabular/learner/default_learner.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/src/autogluon/tabular/trainer/auto_trainer.py
- tabular/tests/unittests/test_tabular.py
#976 
- Updated predict_proba as_multiclass default to True
- Refactored evaluate_predictions to be much nicer to use (auto convert pred_proba -> pred instead of crashing, helpful error message, etc.)
- Applied as_multiclass=True standard across other methods in Tabular such as get_oof_pred_proba
- Fixed get_oof_pred_proba in a variety of nasty rare edge cases: duplicated rows, dropped rows, internal binary/external multiclass
- Disabled usage of tuning_data while bagging (raises an exception), otherwise get_oof_pred_proba becomes very confusing and misleading.
> Tabular: Updated predict_proba as_multiclass default to True

- tabular/src/autogluon/tabular/predictor/predictor.py
- text/src/autogluon/text/text_prediction/predictor/predictor.py
- Changed predictor loading so it doesn't alter logger verbosity by default.
- Previously TextPredictor would forcibly change root logger to verbosity 3 when loaded, now it can be controlled (and by default it won't change logger on load).
> Improved logging verbosity when loading predictors

- tabular/src/autogluon/tabular/models/tab_transformer/tab_transformer_model.py
Fixes bug where progress bar of TabTransformer could be stuck at [0/200] so it looked like it wasn't training even though it actually was.
> fix progress bar for TabTransformer

- core/src/autogluon/core/models/ensemble/stacker_ensemble_model.py
#1033 
When `preprocess` was renamed to `preprocess_nonadaptive`, this usage was not updated to the new name, meaning it would default to `preprocess_nonadaptive=True` during stacking, which would cause exceptions in LightGBM during repeated bagging with time_limit set when invalid column names existed.
This PR fixes this bug.
> Tabular: Fixed bug with preprocess_nonadaptive during stacking

- core/src/autogluon/core/models/_utils.py
- core/src/autogluon/core/models/abstract/abstract_model.py
- tabular/src/autogluon/tabular/models/catboost/catboost_model.py
- tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
- tabular/src/autogluon/tabular/models/fasttext/fasttext_model.py
- tabular/src/autogluon/tabular/models/knn/knn_model.py
- tabular/src/autogluon/tabular/models/lgb/lgb_model.py
- tabular/src/autogluon/tabular/models/rf/rf_model.py
- tabular/src/autogluon/tabular/models/rf/rf_rapids_model.py
- tabular/src/autogluon/tabular/models/tabular_nn/tabular_nn_model.py
- tabular/src/autogluon/tabular/models/xgboost/callbacks.py
- tabular/src/autogluon/tabular/models/xgboost/hyperparameters/searchspaces.py
- tabular/src/autogluon/tabular/models/xgboost/xgboost_model.py
Now users can specify how many rounds of early stopping should be used via `ag.es` parameter in models.
This is not yet documented to user as it is very advanced and likely isn't something we want users to be worrying about. Especially since long term we probably want to move towards adaptive learning rate strategies.
The plan after merge is to begin experimenting with alternative early stopping strategies. Currently for large datasets, we only have **10** early stopping rounds. This is far too few. For example, in the Airlines dataset (115M rows), Airlines required an early stopping rounds value of **10,000** to get to the best num_boost_rounds of **~275,000**. With only 10 early stopping rounds, it stopped around iteration 2000, with a …
> Tabular: Added support for specifying early stopping rounds in GBM, CAT, XGB

- core/src/autogluon/core/_setup_utils.py
- vision/src/autogluon/vision/configs/presets_configs.py
- vision/src/autogluon/vision/detector/detector.py
- vision/src/autogluon/vision/predictor/predictor.py
- vision/tests/unittests/test_image_classification.py
- vision/tests/unittests/test_object_detection.py
Add early stopping control for ImagePredictor and ObjectDetector.
New hyperparameters that controls the early stopping bahavior:
```python
"""
early_stop_patience : int, default=-1
Number of epochs with no improvement after which train is early stopped. Use -1 to disable.
early_stop_min_delta : float, default=1e-4
The small delta value to ignore when evaluating the metric. A large delta helps stablize the early
stopping strategy against tiny fluctuation, e.g. 0.5->0.49->0.48->0.499->0.500001 is still considered as
a good timing for early stopping.
early_stop_baseline : float, default=0.0
The minimum(baseline) value to trigger early stopping. For example, with `early_stop_baseline=0.5`,
early stopping won't be triggered if the metric is …
```
> [Vision] add early stopping strategies

- text/setup.py
RAPIDS depends on a special version of pyarrow not available via pip install, so if autogluon.text was installed after RAPIDS, RAPIDS would break. This change allows the RAPIDS version of pyarrow to remain.
@sxjscience What do you think about removing pyarrow as a dependency? Could it be moved to optional?
> Removed version specification on pyarrow to allow RAPIDS install

- extra/setup.py
#1051
Removes bokeh dependency in autogluon.extra, which was only used optionally for plots. Since it caused numerous issues related to tornado dependencies in Kaggle (crash on importing AutoGluon), better to have it be purely optional, as a warning is shown to users who try to make plots telling them to install it.
> Remove bokeh dependency

- tabular/src/autogluon/tabular/trainer/model_presets/presets.py
Now that we use FastAI V2, FastAI has become much faster than in V1. This PR is for experimentation with training FastAI before MXNet in Tabular.
TODO:
> Tabular: Re-order NN model priority

- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- tabular/src/autogluon/tabular/models/rf/rf_model.py
- tabular/src/autogluon/tabular/models/rf/rf_rapids_model.py
- Added efficient OOF functionality to RF/XT models
- This should give a 10x train/infer speed-up and 10x disk space reduction in bagged modes, with roughly equivalent model quality.
- DAAL and RAPIDS don't support the necessary methods to do this, so only raw sklearn is accelerated at present.
- Fixed efficient OOF KNN crashing on regression problems.
TODO:
> Tabular: Added efficient OOF functionality to RF/XT models

- core/src/autogluon/core/scheduler/fifo.py
- core/src/autogluon/core/searcher/bayesopt/autogluon/constrained_gp_fifo_searcher.py
- core/src/autogluon/core/searcher/bayesopt/autogluon/gp_fifo_searcher.py
- core/src/autogluon/core/searcher/bayesopt/autogluon/gp_multifidelity_searcher.py
- core/src/autogluon/core/searcher/bayesopt/autogluon/searcher_factory.py
- core/src/autogluon/core/searcher/bayesopt/models/gp_model.py
- core/src/autogluon/core/searcher/bayesopt/models/gpmodel_transformers.py
- core/src/autogluon/core/searcher/bayesopt/models/meanstd_acqfunc.py
- core/src/autogluon/core/searcher/bayesopt/models/meanstd_acqfunc_impl.py
- core/src/autogluon/core/searcher/bayesopt/models/model_base.py
- core/src/autogluon/core/searcher/bayesopt/tuning_algorithms/base_classes.py
- core/src/autogluon/core/searcher/bayesopt/tuning_algorithms/bo_algorithm_components.py
- core/src/autogluon/core/searcher/bayesopt/tuning_algorithms/defaults.py
- core/src/autogluon/core/searcher/bayesopt/utils/comparison_gpy.py
- core/src/autogluon/core/searcher/bayesopt/utils/test_objects.py
- core/src/autogluon/core/searcher/gp_searcher.py
- core/src/autogluon/core/searcher/searcher.py
- core/src/autogluon/core/searcher/searcher_factory.py
- core/tests/unittests/bayesopt/gpautograd/test_comparison_gpy.py
- core/tests/unittests/bayesopt/test_bayesopt_cei.py
- core/tests/unittests/bayesopt/test_bayesopt_eipu.py
- core/tests/unittests/bayesopt/test_checkpointing.py
- core/tests/unittests/bayesopt/test_common.py
- core/tests/unittests/bayesopt/test_gaussproc.py
- core/tests/unittests/bayesopt/test_gp_components.py
- core/tests/unittests/test_multi_output_searcher.py
Extends the acquisition function to handle multiple outputs and implements constrained Bayesian optimization.
This is useful to tackle problems such as optimizing accuracy with an upper bound on memory requirements or on unfairness.
The main change is meanstd_acqfunc.py. The acquisition function now internally operates with a dictionary Dict[str, SurrogateModel], allowing for a model for each output metric. The standard case is a dictionary with a single model but the change is backward compatible: if a plain SurrogateModel is passed, the acquisition function automatically turns it into a one-key dictionary.
Other key changes: 
* Implemented CEIAcquisitionFunction and EIpuAcquisitionFunction, two multi-output acquisition functions. These require the predictions …
> Constrained Bayesian optimization

- tabular/src/autogluon/tabular/models/rf/rf_model.py
Enable efficient OOB by default.
- ~2.3x faster inference speed, large disk usage reduction, slightly worse quality on datasets <10,000 rows, better quality on datasets >10,000 rows.
- Increases OOF info leakage, will want to investigate work-arounds in follow-up PRs. Added current findings to code comments.
> Tabular: RF/XT Efficient OOB

- core/src/autogluon/core/utils/utils.py
- docs/api/autogluon.predictor.rst
- docs/tutorials/tabular_prediction/tabular-indepth.md
- docs/tutorials/tabular_prediction/tabular-quickstart.md
- examples/tabular/example_advanced_tabular.py
- tabular/src/autogluon/tabular/learner/abstract_learner.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/tests/unittests/test_tabular.py
- Refactored evaluate and evaluate_predictions to cause less confusion with users and act more consistently across eval metrics and problem types.
- evaluate is now purely a wrapper around evaluate_predictions, making the logic much less disjoint.
- evaluate_predictions now can always handle pred_proba input, and can evaluate pred and pred_proba metrics at the same time (previously this didn't work).
- Made the return types always dictionaries to reduce confusion.
> Tabular: Refactored evaluate/evaluate_predictions

- core/src/autogluon/core/_setup_utils.py
Restricted sklearn to >=0.23.2, 0.22 crashes during efficient OOB.
> Restricted sklearn to >=0.23.2

- tabular/src/autogluon/tabular/trainer/model_presets/presets.py
quantile-regression RF/XT is incompatible with use_child_oof strategy, so need to override this ag_ensemble_arg if problem_type==QUANTILE in order to utilize bagging.
> RF oof bugfix for quantile-regression

- core/src/autogluon/core/metrics/__init__.py
- core/src/autogluon/core/metrics/classification_metrics.py
- core/tests/unittests/metrics/test_classification_metrics.py
Add Quadratic Kappa as a metric. Reference: https://www.kaggle.com/aroraaman/quadratic-kappa-metric-explained-in-5-simple-steps
Quadratic Kappa is designed for rating predictions, when predicting 1 with 2 will have smaller penalty than predicting 1 with 5.
FYI @sallypannn
> [Metric] Add quadratic kappa

- vision/src/autogluon/vision/predictor/predictor.py
CV models dataloaders throw a `TimeoutError` in fork multiprocessing mode - setting `nthreads_per_trial=0` when it's not provided and the multiprocessing mode is `fork`
see also: https://github.com/apache/incubator-mxnet/issues/11872
```python
import autogluon.core as ag
from autogluon.vision import ImagePredictor
import multiprocessing
print(f'Start modes available: {multiprocessing.get_all_start_methods()}')
multiprocessing.set_start_method('fork', force=True)
print(f'Active start mode: {multiprocessing.get_start_method(allow_none=True)}')
train_dataset, _, test_dataset = ImagePredictor.Dataset.from_folders('https://autogluon.s3.amazonaws.com/datasets/shopee-iet.zip')
predictor = ImagePredictor()
predictor.fit(train_dataset, hyperparameters={'epochs': 2})some …
```
> [CV][Bugfix] Addressing multiprocessing.context.TimeoutError in fork mode

- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- core/src/autogluon/core/models/ensemble/fold_fitting_strategy.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/src/autogluon/tabular/trainer/abstract_trainer.py
- vision/src/autogluon/vision/predictor/predictor.py
This PR does 2 things: 
1. moves folds training code into separate strategy class to isolate fold training code from bagging part
1. changes processing model to map-reduce (schedule all jobs first, then wait to get the results) - this is needed for distributed training where scheduling is happening asynchronously.
Custom strategies can be plugged via:
```python
predictor = TabularPredictor(label=label, path='/Users/ashyrkou/Projects/autogluon/temp/').fit(
...
fold_fitting_strategy=SequentialLocalFoldFittingStrategy,
...
)
```
> [Bagging][Refactoring] Refactoring bagged training code into separate class to enable distributed strategies

- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- Fixed an exception that is raised when using bagging. After calling `predictor.save_space()`, calls to `predictor.persist_models` and `predictor.info()` will raise exceptions.
- This PR fixes that issue so they still work correctly.
> Tabular: Fix predictor.info() exception

- tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
- Previously, r2 metric optimization was flipped, causing the model to pick the worst epoch as the final model, rather than the best.
> Tabular: Fixed r2 metric sign in FastAI model

- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- core/src/autogluon/core/models/greedy_ensemble/greedy_weighted_ensemble_model.py
- tabular/setup.py
- tabular/src/autogluon/tabular/models/catboost/catboost_model.py
- tabular/src/autogluon/tabular/models/fastainn/fastai_helpers.py
- tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
- tabular/src/autogluon/tabular/models/fasttext/fasttext_model.py
- tabular/src/autogluon/tabular/models/lr/lr_model.py
- tabular/src/autogluon/tabular/models/rf/rf_model.py
- tabular/src/autogluon/tabular/models/tabular_nn/tabular_nn_model.py
- tabular/src/autogluon/tabular/models/tabular_nn/tabular_nn_quantile.py
#1158 
- Fixed FastAI accuracy on regression problems by adding StandardScaler to target variable and dropping features that contain only one unique value in model `_preprocess` logic. Features with only one unique value in all training rows destroy the FastAI NN.
TODO:
> Tabular: Fixed FastAI NN accuracy on regression datasets

- vision/src/autogluon/vision/predictor/predictor.py
#1175
- Fix set_index crash if index is not named `'index'` in input DataFrame to `predict` and `predict_proba`.
> Vision: Fix set_index in `predict` and `predict_proba`

- vision/src/autogluon/vision/predictor/predictor.py
- vision/tests/unittests/test_image_classification.py
#1147 
- Fixed bug causing train_data and tuning_data to both use all the training data if tuning_data is not specified in ImagePredictor.
- Improved usage of data splitting. Now it is deterministic and splits the exact specified proportion of data (rather than applying that proportion as a probability independently to each sample of being included in train vs val).
- Data splitting now performs stratification if applicable.
NOTE:
- A **major** bug still exists in `ImageDataset.to_mxnet()` that causes severe issues downstream by ignoring upstream data splits. This PR does not fix this bug, but rather avoids it for the specific instance of `ImagePredictor.fit()`.
By submitting this pull request, I confirm that you can use, modify, copy, …
> Vision: Fix major bug when tuning_data is not specified

- core/src/autogluon/core/scheduler/seq_scheduler.py
- vision/src/autogluon/vision/detector/detector.py
Fixing
```
~/anaconda3/envs/mxnet_latest_p37/lib/python3.7/site-packages/autogluon/vision/detector/detector.py in fit(self, train_data, tuning_data, time_limit, presets, hyperparameters, **kwargs)
241             self._detector._logger.propagate = True
242             self._fit_summary = self._detector.fit(train_data, tuning_data, 1 - holdout_frac, random_state, resume=False)
--> 243             if hasattr(self._classifier, 'fit_history'):
244                 self._fit_summary['fit_history'] = self._classifier.fit_history()
245             return self
AttributeError: 'ObjectDetector' object has no attribute '_classifier'
```
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …
> [Bugfix][CV] - fixing  'ObjectDetector' object has no attribute '_classifier'

- vision/src/autogluon/vision/predictor/predictor.py
- vision/tests/unittests/test_image_classification.py
https://github.com/awslabs/autogluon/pull/1168
Fix a bug when `tuning_data` is not specified, the validation acc will always be 0. This doesn't affect the trained model, nor the final test accuracy, but the searching metric will be messed since the searcher will always get 0 as feedback.
This is caused by applying validation to the (already) validated `tuning_data` split from `train_data`
> [Vision] fix duplicate class mapping

- core/src/autogluon/core/__init__.py
- core/tests/unittests/test_import_version.py
- extra/src/autogluon/extra/__init__.py
- features/src/autogluon/features/__init__.py
- mxnet/src/autogluon/mxnet/__init__.py
- tabular/src/autogluon/tabular/__init__.py
- text/src/autogluon/text/__init__.py
- vision/src/autogluon/vision/__init__.py
#1121 
- Now users can access version via `autogluon.{submodule}.__version__`
- Open question: Do we want to refactor `version.py` to be `_version.py` so users don't get confused? Should it be a python file at all? LightGBM uses `VERSION.txt` and loads from file in `__init__.py`.
> Improved access method for `__version__`

- core/src/autogluon/core/features/infer_types.py
- features/src/autogluon/features/generators/astype.py
- Speedup type inference of datetime features by 100x+ via sampling and optimized function calls (adult goes from 18.2s -> 0.1s in preprocessing fit time). The 18.2s time was caused by a performance degradation after enabling `errors='coerce'` in #1182. This PR makes up the performance gap and improves on the speed pre-degradation.
- Speedup type inference of text features via sampling.
> Features: Optimized type inference speed by 100x+ for datetime and text

- vision/src/autogluon/vision/predictor/predictor.py
- Fixed bug causing incorrect prediction rows to be output from predict_proba if the same image is present in multiple rows.
> Vision: Fixed defect when image is present multiple times during pred_proba

- features/src/autogluon/features/generators/astype.py
- Previously, if user manually set different raw types in FeatureMetadata from what the real dtypes are in Pandas, the Pandas dtype would be used. Now, the FeatureMetadata type is used and the dtypes are converted.
> Features: Force dtype conversion if FeatureMetadata differs from actual dtype

- docs/tutorials/image_prediction/beginner.md
- docs/tutorials/image_prediction/dataset.md
- docs/tutorials/image_prediction/hpo.md
- docs/tutorials/image_prediction/kaggle.md
- vision/src/autogluon/vision/configs/presets_configs.py
- vision/src/autogluon/vision/detector/detector.py
- vision/src/autogluon/vision/predictor/predictor.py
- vision/tests/unittests/test_image_classification.py
- Presets specified `search_strategy` which is not a valid key, therefore searcher was always `random`.
- This PR removes the incorrect keys, replacing with `searcher`. `searcher` cannot be `bayesopt` due to a bug causing the run to crash.
- Fixed missing `Int` import causing GPU memory check to fail.
- Standardized usage of `ImageDataset` to align with `TabularDataset`.
> Vision: Fix searcher presets and GPU memory check

- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- core/src/autogluon/core/models/ensemble/fold_fitting_strategy.py
- core/src/autogluon/core/models/ensemble/stacker_ensemble_model.py
- core/src/autogluon/core/models/ensemble/weighted_ensemble_model.py
- tabular/src/autogluon/tabular/trainer/abstract_trainer.py
- Added experimental refit_folds option to BaggedEnsembleModel. This enables performing refit_full automatically in a single .fit call. This can be used as a more expensive (in training time) alternative to efficient OOB / LOO bagging that produces less information leakage in OOF predictions.
- Fixed bug in BaggedEnsembleModel that did not respect `save_bag_folds=False` (10x disk-space reduction after fix for situations where refit was going to be called later, such as high_quality and good_quality presets).
> Tabular: Added experimental refit_folds option to BaggedEnsembleModel

- Jenkinsfile
- core/src/autogluon/core/_setup_utils.py
- Fix CI: Limit ipykernel<6.0.0 during tutorial build
- Temporarily capped pandas version to pass CI, plan to revert later in #1228
> Fix CI: Limit ipykernel<6.0.0 during tutorial build

- docs/tutorials/tabular_prediction/tabular-multilabel.md
- Fixed undefined `labels` variable to `self.labels`. Tutorial succeeded because it defined `labels` in the script, but code would crash otherwise.
- Fixed user-specified eval_metric, previously it would crash if specified due to incorrect key access.
> Tabular: Fixed bugs in multilabel code

- README.md
- docs/tutorials/course/fairbo.md
Fix to FairHPO tutorial: remove sign flip when passing the objective to the reporter + minor improvements.
> Fix: flip sign in FairHPO tutorial

- core/src/autogluon/core/models/abstract/abstract_model.py
- Fixed user-specified aux params being ignored.
- This was caused by the refactoring of arguments in AbstractModel.
> Tabular: Fixed user-specified aux params being ignored

- core/src/autogluon/core/models/abstract/model_trial.py
- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- core/src/autogluon/core/utils/utils.py
- tabular/src/autogluon/tabular/learner/abstract_learner.py
- tabular/src/autogluon/tabular/learner/default_learner.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/src/autogluon/tabular/trainer/abstract_trainer.py
- tabular/src/autogluon/tabular/trainer/auto_trainer.py
#1174, #1120, #617, #901
- Added user-specified groups parameter to enable custom fold-splits.
- Fixed HPO for RF and KNN (previously it would crash and not train the models if HPO is specified).
> Tabular: Added user-specified groups parameter, fixed HPO for RF and KNN

- tabular/src/autogluon/tabular/models/knn/knn_rapids_model.py
- tabular/src/autogluon/tabular/models/lr/lr_rapids_model.py
- tabular/src/autogluon/tabular/models/rf/rf_rapids_model.py
N/A
Tested RF, LR, and KNN with RAPIDS 21.06. The RFRapidsModel accuracy issue has been resolved; however, depending on the max_depth parameter, the RFRapidsModel may be slower than the RFModel (see comment in rf_rapids_model.py). 
> Update with RAPIDS 21.06

- core/src/autogluon/core/scheduler/seq_scheduler.py
- core/src/autogluon/core/task/base/base_task.py
- docs/tutorials/image_prediction/hpo.md
- docs/tutorials/object_detection/beginner.md
- vision/src/autogluon/vision/detector/detector.py
- vision/src/autogluon/vision/predictor/predictor.py
- vision/tests/unittests/test_image_classification.py
- vision/tests/unittests/test_image_regression.py
- vision/tests/unittests/test_object_detection.py
#1247
- Added error if kwarg is not valid in fit call to ImagePredictor and ObjectDetector. Previously, the invalid kwarg was silently ignored.
- Fixed typo in object detection tutorial causing incorrect hpo behavior.
- Fixed bug in HPO causing crash if all configurations have been tried and another trial is attempted.
- Fixed vision specific bug in HPO that caused bayesopt to crash by attempting to train the same config twice.
- Removed unusable HPO options from vision documentation.
- Fixed typos in various other tutorials that had incorrect HPO options specified.
> Vision: Added exception if invalid kwargs specified

- Jenkinsfile
- core/src/autogluon/core/_setup_utils.py
- docs/tutorials/course/object.md
- docs/tutorials/image_prediction/beginner.md
- docs/tutorials/image_prediction/hpo.md
- tabular/src/autogluon/tabular/models/image_prediction/image_predictor.py
- tabular/tests/unittests/models/test_image_predictor.py
- vision/setup.py
- vision/src/autogluon/vision/configs/presets_configs.py
- vision/src/autogluon/vision/predictor/predictor.py
- vision/src/autogluon/vision/utils/plot_network.py
- vision/tests/unittests/test_image_classification.py
- vision/tests/unittests/test_image_regression.py
Add torch/timm backed image predictor, now either mxnet or torch is optional, as long as one of them is available, image predictor can automatically choose the best strategy for fit.
The underneath framework is dispatched by type of model, all models are available as `image_predictor._SUPPORTED_MODELS`, note that depending on the availability of mxnet/torch(timm, torchvision), you will get different model list.
```python
predictor = ImagePredictor()
predictor.fit(train_dataset, hyperparameters={'model': 'efficientnet_b0'})  # to torch backend
predictor.fit(train_dataset, hyperparameters={'model': 'resnest200'})  # to mxnet backend
```
The default presets have been updated accordingly.
By submitting this pull request, I confirm that you …
> [Vision] Add torch/timm backed image predictor

- core/src/autogluon/core/task/base/base_task.py
https://github.com/awslabs/autogluon/issues/1279
This issue was caused by final_fit not being properly passed to ImagePredictor. ImagePredictor will retrieve the best model so far if final_fit is true. Passed final_fit as True to ImagePredictor's train_fn.
Updating the args won't really update what's being used by the train_fn as the scheduler is actually doing a deepcopy of the kwvars and convert that as the args passed to train_fn. Therefore, an update to the kwvars is needed. I updated the args as well as an indication of what the code is doing. 
This is only a quick fix. We should consider refactor base_task instead later on
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …
> fix final_fit

- tabular/src/autogluon/tabular/models/fastainn/callbacks.py
- tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
- Fixed issue where FastAI NN would take too long to train because it would train an epoch even if it had a fraction of a second of time remaining, which may result in the model going over time limit. This can cause rare edge case issues during bagging where FastAI uses a lot of training time but eventually fails due to time limit instead of failing immediately before using the time budget.
TODO:
> Tabular: Improved handling of time limit in FastAI NN

- core/src/autogluon/core/models/ensemble/stacker_ensemble_model.py
- Fixed incorrect ensemble weights in refit_full
This fixes a MAJOR bug introduced in v0.3 release via #1105 that caused the ensemble weights of `_FULL` WeightedEnsemble models to be incorrectly ordered. This meant that `high_quality` and `good_quality` presets became far worse, often worse than `medium_quality`.
The inner bug that caused the wrong functionality was introduced in January 2020 via #177, but did not have any negative effect until #1105 was merged which made the assumption that base_model_names would stay in the same order as when they were initialized when performing refit_full.
This bug was not detected prior to v0.3.0 release due to no benchmark runs being done on `high_quality` and `good_quality` presets. Future releases …
> Tabular: Fixed incorrect ensemble weights in refit_full

- tabular/src/autogluon/tabular/models/knn/knn_model.py
- Removes KNN from stacker models.
This change is because KNN as a stacker model does not work all that well, as it depends on the scaling of the other features whether it improves at all. Better to avoid having as a stacker in the first place.
TODO:
> Tabular: Remove KNN from stacker models

- README.md
- docs/tutorials/text_prediction/beginner.md
- docs/tutorials/text_prediction/customization.md
- text/src/autogluon/text/text_prediction/config.py
- text/src/autogluon/text/text_prediction/mx/models.py
- text/src/autogluon/text/text_prediction/mx/modules.py
- text/src/autogluon/text/text_prediction/mx/preprocessing.py
- text/src/autogluon/text/text_prediction/predictor/predictor.py
- text/tests/unittests/test_config.py
- text/tests/unittests/text_prediction/test_predictor.py
Enable to call `predictor.fit()` again after it's loaded or have been trained on a dataset.
Following are the examples of these two usages:
- Usage-1:
```python
from autogluon.text import TextPredictor
from autogluon.core.utils.loaders import load_pd
train_data = load_pd.load('https://autogluon-text.s3-accelerate.amazonaws.com/glue/sts/train.parquet')
dev_data = load_pd.load('https://autogluon-text.s3-accelerate.amazonaws.com/glue/sts/dev.parquet')
predictor = TextPredictor(label='score')
predictor.fit(train_data)
predictions1 = predictor.predict(dev_data)
predictor.fit(train_data)
predictions2 = predictor.predict(dev_data)
```
- Usage-2:
```python
from autogluon.text import TextPredictor
from autogluon.core.utils.loaders import load_pd
train_data = …
```
> Enable continuous training for TextPredictor + Add paper references to the homepage

- text/src/autogluon/text/text_prediction/mx/models.py
This is to fix the issue introduced by the previous PR https://github.com/awslabs/autogluon/pull/1299 . Need to join the configuration with `, ` instead of `. `
> [Fix] Update the logic for upgrading the configuraiton file

- core/src/autogluon/core/_setup_utils.py
- tabular/setup.py
Updati
```
+============================+===========+==========================+==========+
| package                    | installed | affected                 | ID       |
+============================+===========+==========================+==========+
| pillow                     | 8.3.1     | >=7.1.0,<8.3.2           | 41277    |
+==============================================================================+
| Pillow 8.3.2 fixes a 6-byte out-of-bounds (OOB) read. The previous bounds    |
| check in FliDecode.c incorrectly calculated the required read buffer size    |
| when copying a chunk, potentially reading six extra bytes off the end of the |
| allocated buffer from the heap. Present since Pillow 7.1.0.                  | …
```
> Fixing Pillow min version to address CVE

- core/src/autogluon/core/utils/utils.py
when splits are generated by generate_train_test_split() function the name of the label gets removed from the series.
> put label column name back into splits

- core/src/autogluon/core/utils/loaders/load_str.py
- core/src/autogluon/core/utils/savers/save_str.py
- tabular/src/autogluon/tabular/learner/abstract_learner.py
- tabular/src/autogluon/tabular/learner/default_learner.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- Added caching of AG version during save of predictor.
- Adding comparison of cached AG version during load of predictor prior to loading the actual predictor itself.
- This avoids errors when there is a version mismatch that could occur before the actual warning of version incompatibility was triggered, leading to a lot of confusion from users.
- Added error-by-default when versions are incompatible. This should reduce the chances of users missing the warning message.
- Added Python Version and Operating System to the Learner logs at start of fit.
> Tabular: Cache AG version

- core/src/autogluon/core/_setup_utils.py
- Remove Python 3.6 support
- Require sklearn>=1.0
> Require Python 3.7, Sklearn >=1.0

- tabular/src/autogluon/tabular/predictor/predictor.py
`fit_extra` current crashes, because there's no default set for `calibrate`
added `calibrate` to `_validate_fit_extra_kwargs`
> calibrate needs to be added to fit_extra otherwise causes crash

- core/src/autogluon/core/models/_utils.py
- core/src/autogluon/core/utils/early_stopping.py
- tabular/src/autogluon/tabular/models/catboost/callbacks.py
- tabular/src/autogluon/tabular/models/catboost/catboost_model.py
- tabular/src/autogluon/tabular/models/xgboost/callbacks.py
- tabular/src/autogluon/tabular/models/xgboost/xgboost_model.py
- Updated ES Logic: min_patience 10->20, max_patience 150->300, adaptive_rate 0.2->0.3
- Added Adaptive ES support to CatBoost and XGBoost, enabled by default.
TODO:
> Tabular: Updated ES logic, added adaptive ES to CAT and XGB

- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- core/tests/unittests/models/test_bagged_ensemble_model.py
- Improved method structure
- Moved initialization and passing of fold configs of fold fitting strategy to after the creation of the configs, rather than during the creation of the configs.
- Added assert statement to ensure expected number of fold models are being trained.
- Fixed minor bug where `is_last_fold` was the opposite value it should have been for all configs.
- Added unit test to sanity check configs are generally correct. (A full unit test would be more complicated as it would require checking every kfold split in the configs.)
> Tabular: Improved readability and testability of BaggedEnsembleModel._fit_folds

- core/src/autogluon/core/features/infer_types.py
- core/src/autogluon/core/features/types.py
- features/src/autogluon/features/generators/__init__.py
- features/src/autogluon/features/generators/_experimental/one_hot_encoder.py
- features/src/autogluon/features/generators/one_hot_encoder.py
- tabular/src/autogluon/tabular/models/xgboost/xgboost_utils.py
- tabular/tests/unittests/features/generators/test_one_hot_encoder.py
- Minor optimizations to XGBoost OHE + bugfix for custom metrics.
- Added sparse DataFrame dtype support for infer_types.
- Major optimizations to OHE via the experimental code. The code uses 8x less memory and is ~4x faster than NN/XGBoost implementation (16x faster than LR implementation), along with offering additional flexibility of how we represent infrequent categories (such as grouping with NaN). However, writing the code was very time consuming and has gotten to the point where a fully integrated version that replaces the usage across the package is a lot of effort that I would rather save for a later time.
TODO:
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under …
> OHE Optimization

- tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
- Enables FastAI HPO
- Fixes bug in fname that caused FastAI to crash during HPO
- Optimized FastAI fit preprocessing by avoiding redundant checks and using sets for comparisons. This saves a lot of preprocessing time on datasets with many features.
> [Tabular] Enable FastAI HPO

- core/src/autogluon/core/utils/try_import.py
- vision/src/autogluon/vision/_gluoncv/__init__.py
- vision/src/autogluon/vision/_gluoncv/image_classification.py
- vision/src/autogluon/vision/_gluoncv/object_detection.py
- vision/src/autogluon/vision/_gluoncv/utils.py
- vision/src/autogluon/vision/detector/detector.py
- vision/src/autogluon/vision/predictor/predictor.py
- vision/tests/unittests/test_gluoncv.py
- vision/tests/unittests/test_hybrid_gluoncv.py
- vision/tests/unittests/test_torch_gluoncv.py
Having auto logic in gluoncv that also depends on autogluon is not a good design choice. It prevents autogluon's to modify non-user exposed code. This migration would make the design cleaner by having the auto logic resides in autogluon, and gluoncv will purely be the model provider and trainer
> Migrate gluoncv/auto/task to autogluon

- core/src/autogluon/core/models/greedy_ensemble/ensemble_selection.py
- tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
- Fix GPU specification in FastAI to respect num_gpus
- Previously if GPU was present, it would always be used regardless of num_gpus setting
- Fixed edge case inefficiency in ensemble_selection when identical models caused selection to choose all of them due to rounding error instead of choosing just a single one.
- Optimized ensemble selection to prioritize models already in ensemble when ties occur.
> Tabular: Fix GPU specification in FastAI to respect num_gpus

- CONTRIBUTING.md
- features/src/autogluon/features/generators/datetime.py
- features/tests/features/generators/test_auto_ml_pipeline.py
- features/tests/features/generators/test_bulk.py
- features/tests/features/generators/test_datetime.py
- features/tests/features/generators/test_pipeline.py
1436
Add multiple additional features for datetimes : year, month, day, hour, minute, second, dayofweek, dayofyear, quarter, is_month_end.  There are others in the pandas datetime.dt object, but they can all be inferred from the above.  Holiday logic is not attempted because working out what is a public holiday in a location is highly non-trivial (lunar calendars such as Eid, working weekends as replacement for Chinese New Year, the list is endless)
> Issue 1436 - improved datetime feature handling

- tabular/src/autogluon/tabular/predictor/predictor.py
- Added improved error message in predictor methods prior to being fit
Example:
```
AssertionError: Predictor is not fit. Call `.fit` before calling `.leaderboard`.
```
> Added improved error message in predictor methods prior to being fit

- common/src/autogluon/common/utils/compression_utils.py
- common/tests/unittests/test_compression_utils.py
- Added lazy imports to compression algorithms
- This sidesteps an issue if a user has an incomplete python installation, as importing lmza might cause a crash.
> Added lazy imports to compression algorithms

- docs/install-faq.rst
- docs/install-include.rst
#1442
- Updates doc to correct install instructions for libomp on MacOS to avoid segfault.
> Update doc for installing libomp on MacOS

- common/src/autogluon/common/utils/multiprocessing_utils.py
- core/src/autogluon/core/utils/try_import.py
- tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
- tabular/src/autogluon/tabular/models/tabular_nn/tabular_nn_dataset.py
- text/setup.py
- text/src/autogluon/text/text_prediction/mx/models.py
- vision/setup.py
- vision/src/autogluon/vision/predictor/predictor.py
- Make d8 an optional dependency
- Cleanup dependencies that are unused (tqdm in text, pytest in text, vision)
- Remove outdated multiprocessing code
> Make d8 an optional dependency

- .github/workflows/platform_tests-command.yml
- .github/workflows/slash_command_dispatch.yml
* PR: https://github.com/awslabs/autogluon/pull/1464 is not able to trigger SCD.
SCD seems to require the master branch to have at least a workflow to be dispatched to work properly(you can even delete it afterwards, which is weird). This fix works in my fork:https://github.com/yinweisu/autogluon/pull/2, so worth trying out.
* Also updated SCD to the latest version and added error msg
This change needs to be merged to take effect.
> Create dummy platform tests

- tabular/src/autogluon/tabular/models/catboost/catboost_model.py
- tabular/src/autogluon/tabular/models/lgb/lgb_model.py
- tabular/src/autogluon/tabular/models/xgboost/xgboost_model.py
#1440
- Optimize LightGBM, XGBoost, CatBoost to use optimal num_cpus during training
- LightGBM  and XGBoost show large speedups.
- CatBoost shows no speedup/slowdown but now uses half as much CPU resources.
- No difference to bagging with parallel fold training.
TODO:
> Optimize GBM models num_cpus

- core/src/autogluon/core/data/label_cleaner.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/tests/unittests/data/test_label_cleaner.py
- vision/src/autogluon/vision/predictor/predictor.py
* Try to recover original dtype when inverse_transform
* Assign smaller dtype when possible when doing transform to save memory usage
The fix is now able to pass label cleaner test on windows machine.
> Fix label cleaner test failure on Windows

- common/src/autogluon/common/__init__.py
- common/src/autogluon/common/utils/log_utils.py
- Previously, AutoGluon logs would be hidden in Kaggle because by default `logger.log(...)` would be redirected to a tmp file.
- This PR adds logic to add a StreamHandler to AutoGluon's logger when in a Kaggle Notebook (not impacting other package's loggers) to ensure the logs are shown as expected to users in Kaggle.
> Fix Logging in Kaggle

- core/src/autogluon/core/trainer/abstract_trainer.py
- docs/tutorials/tabular_prediction/tabular-indepth.md
- docs/tutorials/tabular_prediction/tabular-quickstart.md
- examples/tabular/example_advanced_tabular.py
1483
Clarify that eval_metric has moved from fit() to Predictor() 
> Clarify that eval_metric has moved from fit() to Predictor() (#1483)

- tabular/src/autogluon/tabular/models/tabular_nn/torch/torch_network_modules.py
https://github.com/awslabs/autogluon/issues/1510 -  NN_TORCH incorrectly implements use_batchnorm=True
Removed `track_running_stats=False` from batchnorm layers, which is forcing always using batch statistics. This fails with a single row. Default will preserve running statistics from the training time.
> [issue#1510] fix - NN_TORCH model is incorrectly handling crashing during inference because no batchnorm statistics recorded

- tabular/src/autogluon/tabular/models/catboost/callbacks.py
- tabular/src/autogluon/tabular/models/catboost/catboost_model.py
* Decrease threshold for adding mem check callback 
* Add dynamic mem check period. Will always do mem check in the first couple period and whenever the model is large enough to potentially cause OOM
> Fix catboost mem callback

- tabular/src/autogluon/tabular/models/tabular_nn/torch/torch_network_modules.py
The existing code is using CPU tensor type, which is causing a transfer of GPU tenser to CPU and failing with the exception:
```
Fitting model: NeuralNetTorch ...
Warning: Exception caused NeuralNetTorch to fail during training... Skipping this model.
Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument target in method wrapper_nll_loss_forward)
Detailed Traceback:
File "/home/ubuntu/venv/lib/python3.7/site-packages/autogluon/core/trainer/abstract_trainer.py", line 979, in _train_and_save
model = self._train_single(X, y, model, X_val, y_val, **model_fit_kwargs)
File "/home/ubuntu/venv/lib/python3.7/site-packages/autogluon/core/trainer/abstract_trainer. …
```
> [bugfix] NN_TORCH model is incorrectly casting types when used on GPU

- vision/src/autogluon/vision/predictor/predictor.py
- vision/src/autogluon/vision/utils/pickle.py
https://github.com/awslabs/autogluon/issues/1426
Previous changes in GluonCV only solved the estimator loading. Still need to handle the pickle logic. Added a cpu unpickler to handle the special logic. Refer to: https://github.com/pytorch/pytorch/issues/16797
> Fix image cpu loading

- tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
- tabular/src/autogluon/tabular/models/tabular_nn/torch/tabular_nn_torch.py
https://github.com/awslabs/autogluon/issues/1519
Making sure TorchNN and FASTAI are using the correct number of threads. This would address issues when other models modify the global thread setting.
Only updated this logic for fit because we find out that the overhead of setting the thread is not worth it during inference after some experiments.
> Set num_threads for torch nn models

- Jenkinsfile
- core/src/autogluon/core/metrics/softclass_metrics.py
- core/tests/unittests/metrics/test_classification_metrics.py
- docs/tutorials/tabular_prediction/tabular-multimodal-text-others.md
- tabular/src/autogluon/tabular/models/image_prediction/image_predictor.py
- tabular/src/autogluon/tabular/models/text_prediction/text_prediction_v1_model.py
- tabular/tests/unittests/models/test_image_predictor.py
- text/tests/unittests/text_prediction/test_predictor_mxnet.py
- vision/src/autogluon/vision/_gluoncv/image_classification.py
- vision/src/autogluon/vision/detector/detector.py
- vision/tests/unittests/test_gluoncv_image_classification.py
- vision/tests/unittests/test_gluoncv_object_detection.py
- vision/tests/unittests/test_object_detection.py
Disabled unit tests for MXNet ObjectDetector, ImagePredictor, and TextPredictor, fixed Tabular multi-modal logging
- Fixed major bug in Jenkinsfile for Text unittests: Wrong conda environment was being deleted, meaning that stale conda environment artifacts were being sometimes incorporated into testing. Fixing should make CI much more stable for text unittests.
- Disabled unit tests for MXNet ObjectDetector, ImagePredictor, and TextPredictor, fixed Tabular multi-modal logging
- Added deprecation warnings for ImagePredictor MXNet models and ObjectDetector.
- Removed installation of MXNet for Vision, Text, and Tabular unit tests in Jenkinsfile.
- Fixed logging verbosity level in multi-modal TabularPredictor mode (previously would …
> Disabled unit tests for MXNet

- text/src/autogluon/text/automm/constants.py
- text/src/autogluon/text/automm/optimization/lit_module.py
- text/src/autogluon/text/automm/optimization/utils.py
- text/src/autogluon/text/automm/predictor.py
- text/src/autogluon/text/automm/utils.py
- text/tests/unittests/automm/test_metrics.py
*This PR is to separate users' provided evaluation metric and the internal validation metric. If a user provides metric `r2`, we will use `rmse` as the internal validation metric since `torchmetrics.R2Score` encounters errors for batch size 1.*
1. Always keep the evaluation metric provided by users. It can be used in `.evaluate()`.
2. Use a separate internal validation metric, which may be different from the provided evaluation metric.
3. Rename the names of evaluation and validation metrics so that their names are both distinguishable and accurate, especially in the context of deep learning.
4. Clean some unused log keys.
> [PR #1537 Patch 4] Separate users' evaluation metric and the internal validation metric

- core/src/autogluon/core/models/abstract/abstract_model.py
- docs/tutorials/tabular_prediction/tabular-custom-model.md
- tabular/src/autogluon/tabular/models/catboost/catboost_model.py
- tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
- tabular/src/autogluon/tabular/models/knn/knn_model.py
- tabular/src/autogluon/tabular/models/lgb/lgb_model.py
- tabular/src/autogluon/tabular/models/lr/lr_model.py
- tabular/src/autogluon/tabular/models/rf/rf_model.py
- tabular/src/autogluon/tabular/models/tabular_nn/mxnet/tabular_nn_mxnet.py
- tabular/src/autogluon/tabular/models/tabular_nn/torch/tabular_nn_torch.py
- tabular/src/autogluon/tabular/models/text_prediction/text_prediction_v1_model.py
- tabular/src/autogluon/tabular/models/vowpalwabbit/vowpalwabbit_model.py
- tabular/src/autogluon/tabular/models/xgboost/xgboost_model.py
Updated models to primarily use include-lists instead of exclude-lists
#1469 
- Use include-list for specifying valid model feature types as a best practice.
- No functional change at present, but reduces defects in future when adding new types and makes contributing models simpler (no need to understand all types, only ones that are relevant to the model).
> Updated models to primarily use include-lists instead of exclude-lists

- core/src/autogluon/core/utils/utils.py
`os.statvfs` is not available on windows. Return None for now.
> Fix show_versions on windows

- core/src/autogluon/core/_setup_utils.py
numpy downgrade - py3.7 is required
open CVEs present, but fixes in 1.22.x is python 3.8 only: CVE-2021-41496 | CVE-2021-34141
> numpy downgrade - py3.7 is required

- core/src/autogluon/core/models/abstract/_tags.py
- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- core/src/autogluon/core/trainer/abstract_trainer.py
- tabular/src/autogluon/tabular/models/catboost/catboost_model.py
- tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
- tabular/src/autogluon/tabular/models/fasttext/fasttext_model.py
- tabular/src/autogluon/tabular/models/image_prediction/image_predictor.py
- tabular/src/autogluon/tabular/models/knn/knn_model.py
- tabular/src/autogluon/tabular/models/lgb/lgb_model.py
- tabular/src/autogluon/tabular/models/rf/rf_model.py
- tabular/src/autogluon/tabular/models/tabular_nn/mxnet/tabular_nn_mxnet.py
- tabular/src/autogluon/tabular/models/tabular_nn/torch/tabular_nn_torch.py
- tabular/src/autogluon/tabular/models/text_prediction/text_prediction_v1_model.py
- tabular/src/autogluon/tabular/models/vowpalwabbit/vowpalwabbit_model.py
- tabular/src/autogluon/tabular/models/xgboost/xgboost_model.py
#991 
This PR addresses 4 issues:
1. Previously, for models TextPredictorModel and ImagePredictorModel when used in Tabular, if the user called refit_full, the refit models would ignore the best epoch found in the models and instead train all epochs. This could result in much worse model quality and could take many times longer to train than expected.
2. Additionally, models that already are effectively `_FULL` such as RandomForest in bag mode would be trained again as an identical copy, instead of simply copying the original model (same end result, avoids doubling training time).
3. Finally, new models contributed by users had to address the refit_full functionality of their model, which often was very complex (the most complex part of …
> Improved refit_full support, refactored refit_full logic

- docs/tutorials/tabular_prediction/tabular-indepth.md
- Cleanup infer_limit doc to reuse variable
> Cleanup infer_limit doc

- features/src/autogluon/features/generators/one_hot_encoder.py
- tabular/setup.py
- tabular/src/autogluon/tabular/configs/hyperparameter_configs.py
- tabular/src/autogluon/tabular/configs/presets_configs.py
- tabular/src/autogluon/tabular/models/knn/knn_model.py
- tabular/src/autogluon/tabular/models/lr/lr_model.py
- tabular/src/autogluon/tabular/models/lr/lr_preprocessing_utils.py
- tabular/src/autogluon/tabular/models/rf/rf_model.py
- Upgrade sklearnex version
- Added workaround to use sklearnex RF via setting `oob_score=True`
- Refactor LinearRegression -> Add time_limit support, speedup inference by 10x, speedup training by 20x+
- Enable sklearnex in LR -> 20x+ train speedup
- Refactor OHE in LR -> 10x inf speedup
- Refactor Preprocessing in LR -> 10x inf speedup
- Fix boolean feature handling in LR
> Upgrade sklearnex

- Jenkinsfile
- text/src/autogluon/text/automm/constants.py
- text/src/autogluon/text/automm/predictor.py
- text/src/autogluon/text/text_prediction/predictor.py
1. Turned off logging in prediction by default. Users can turn on logging by increasing the verbosity.
2. Used a tutorial mode for whether to disable the progress bar and filter logging info in .load().
3. Removed a redundant progress bar setup in the text predictor.
> [PR #1537 Patch 9] Clean AutoMM logs in tutorials

- tabular/src/autogluon/tabular/models/catboost/catboost_model.py
#1358 
- Fix CatBoost on GPU, previously crashed.
- This is a hack workaround because GPU CatBoost doesn't support callbacks.
- I've added the logic we used in v0.3.1 back in for GPU which trains a dummy model to estimate memory and training time usage.
- This isn't ideal but there is no better solution until CatBoost addresses issues with callbacks in GPU mode.
> Fix CatBoost on GPU

- tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
Fixes crash in FastAI preprocessing when cat_cols_to_drop is not empty since it would be a numpy array and starting in numpy 1.21 checking `if cat_cols_to_drop` will error.
```
File "/repo/frameworks/AutoGluon/lib/autogluon/tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py", line 134, in _preprocess
if cat_cols_to_drop:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
> [Tabular] Fix crash in FastAI

- tabular/src/autogluon/tabular/models/tabular_nn/mxnet/tabular_nn_mxnet.py
- tabular/src/autogluon/tabular/trainer/model_presets/presets.py
- Add deprecation warnings for MXNet NN
- Instead of raising exception when user specifies 'NN' in hyperparameters, instead warn and treat as 'NN_MXNET'. This avoids breaking scripts which specify 'NN' in custom hyperparameters dictionaries when upgrading to v0.4.0.
> Add deprecation warnings for MXNet NN

- text/src/autogluon/text/automm/configs/data/default.yaml
- text/src/autogluon/text/automm/configs/model/fusion_mlp_image_text_tabular.yaml
- text/src/autogluon/text/automm/constants.py
- text/src/autogluon/text/automm/data/dataset.py
- text/src/autogluon/text/automm/data/infer_types.py
- text/src/autogluon/text/automm/data/preprocess_dataframe.py
- text/src/autogluon/text/automm/data/process_image.py
- text/src/autogluon/text/automm/data/process_text.py
- text/src/autogluon/text/automm/models/clip.py
- text/src/autogluon/text/automm/models/timm_image.py
- text/src/autogluon/text/automm/predictor.py
- text/src/autogluon/text/automm/utils.py
1. Added multiple images support for CLIP.
2. Made the data loader more robust by handling exceptions in loading one sample. Previously, failure of opening missing images could crash training.
3. Added the choice of using a zero image if an image is missing.
4. Improved init_data_processors. Modalities with empty data processors are dropped.
5. Set to use the default AutoMM logger in preprocess_dataframe.py, process_image.py, and process_text.py.
6. Converted metric names to lower case before calling the metric function.
> Make CLIP support multiple images per sample

- docs/cheatsheet.rst
- docs/index.rst
Add cheat sheet to our documentation site.
Inserting html directly results in weird format. Use a combination of image and link to pdf instead.
> [WIP]Add cheat sheet to website

- docs/whats_new/v0.4.1.md
- text/setup.py
#1607 
- Fixes error if user tries the following in v0.4:
```
pip install autogluon.text
```
```
import autogluon.text
```
This is because `autogluon.text` is missing dependency `autogluon.features` in setup.py.
> Fix pip install of standalone Text module

- core/src/autogluon/core/_setup_utils.py
Pillow security patching.
```
+============================+===========+==========================+==========+
| package                    | installed | affected                 | ID       |
+============================+===========+==========================+==========+
| pillow                     | 9.0.0     | <9.0.1                   | 44487    |
+==============================================================================+
| Pillow 9.0.1 includes a fix for CVE-2022-22817: PIL.ImageMath.eval in Pillow |
| before 9.0.0 allows evaluation of arbitrary expressions, such as ones that   |
| use the Python exec method. A first patch was issued for version 9.0.0 but   |
| it did not prevent builtins available to lambda expressions.                 |
| …
```
> [WIP][security] Updated pillow to 9.0.1+

- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- core/src/autogluon/core/searcher/local_searcher.py
- core/tests/unittests/searcher/test_local_searcher.py
- tabular/src/autogluon/tabular/trainer/model_presets/presets.py
- Added get_results to searchers, useful for debugging and for future extensions to HPO functionality.
- Added new way to init a BaggedEnsembleModel that avoids having to init the base model prior to initing the bagged ensemble model.
> Add get_results, add model_base_kwargs

- text/src/autogluon/text/automm/predictor.py
- text/src/autogluon/text/automm/utils.py
1. Stopped using pytorch lightning's model checkpoint template in saving AutoMMPredictor's final model checkpoint.
2. Improved the logic of continuous training. We pass the `ckpt_path` argument to pytorch lightning's trainer only when `resume=True`.
> Simplify checkpoint template and improve continuous training logic

- text/src/autogluon/text/automm/constants.py
- text/src/autogluon/text/automm/models/categorical_mlp.py
- text/src/autogluon/text/automm/models/clip.py
- text/src/autogluon/text/automm/models/fusion.py
- text/src/autogluon/text/automm/models/huggingface_text.py
- text/src/autogluon/text/automm/models/numerical_mlp.py
- text/src/autogluon/text/automm/models/timm_image.py
- text/src/autogluon/text/automm/optimization/lit_module.py
- text/src/autogluon/text/automm/utils.py
- text/tests/unittests/automm/test_automm_predictor.py
1. Now each model's output is dictionary with the model prefix as the first level key. The format is uniform between single model and fusion model.
2. Now users can customize model names by using the internal registered names (`timm_image`, `hf_text`, `clip`, `numerical_mlp`, `categorical_mlp`, and `fusion_mlp`) as prefixes. This is helpful when users want to simultaneously use two models of the same type, e.g., `hf_text`. They can just use names `hf_text_0` and `hf_text_1`.
> Unify AutoMM's model output format and support customizing model names

- text/src/autogluon/text/automm/utils.py
- text/src/autogluon/text/text_prediction/mx_predictor.py
- text/src/autogluon/text/text_prediction/predictor.py
- text/tests/unittests/text_prediction/test_predictor_pytorch.py
*Issue #, if available:* https://github.com/awslabs/autogluon/issues/1115#issuecomment-1090598217
*Description of changes:* 
1. Support `standalone` feature in `TextPredictor`. This is an extension of previous PR in https://github.com/awslabs/autogluon/pull/1575.
2. Fix bug of calling `save_pretrained_configs` in `AutoMMPrediction.save(standalone=True)` when no fusion model exists ([here](https://github.com/awslabs/autogluon/blob/5a323641072431091d2be5e6dbef5a87b646a408/text/src/autogluon/text/automm/utils.py#L644 )). 
3. Add test case.
> Support saving with standalone in TextPredictor

- tabular/src/autogluon/tabular/learner/abstract_learner.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/tests/conftest.py
- Fix evaluate when weight_evaluation=True
- Previously, AutoGluon would crash if the user specified `predictor.evaluate(...)` or `predictor.evaluate_predictions(...)` when `self.weight_evaluation==True`, this fixes this so it works properly.
> Fix evaluate when weight_evaluation=True

- docs/tutorials/tabular_prediction/tabular-indepth.md
Fix doc so that the correct predictor is called for leaderboard.
> Doc fix to use correct predictor when calling leaderboard

- text/src/autogluon/text/automm/configs/optimization/adamw.yaml
- text/src/autogluon/text/automm/constants.py
- text/src/autogluon/text/automm/predictor.py
- text/src/autogluon/text/automm/utils.py
- text/tests/unittests/automm/test_automm_predictor.py
1. Following paper: https://arxiv.org/pdf/2203.05482.pdf to update top-k checkpoint average names: `union_soup` -> `uniform_soup` and `best_soup` -> `best`.
2. Support customizing model names for the terminal input.
3. deepcopy data processors in _predict() to avoid potential issues.
4. Update function names (`customize_config_names` -> `customize_model_names` and `verify_config_names` -> `verify_model_names`) to make it easier to understand them.
> Update the names of top-k checkpoint average methods and support customizing model names for terminal input

- text/src/autogluon/text/automm/models/categorical_mlp.py
- text/src/autogluon/text/automm/models/clip.py
- text/src/autogluon/text/automm/models/fusion.py
- text/src/autogluon/text/automm/models/huggingface_text.py
- text/src/autogluon/text/automm/models/numerical_mlp.py
- text/src/autogluon/text/automm/models/timm_image.py
Use class property to set keys in model classes. In this way, if we customize the `prefix` key, other keys are automatically updated.
> Use class property to set keys

- text/src/autogluon/text/automm/configs/distiller/default.yaml
- text/src/autogluon/text/automm/constants.py
- text/src/autogluon/text/automm/data/datamodule.py
- text/src/autogluon/text/automm/data/dataset.py
- text/src/autogluon/text/automm/data/infer_types.py
- text/src/autogluon/text/automm/optimization/lit_distiller.py
- text/src/autogluon/text/automm/optimization/lit_module.py
- text/src/autogluon/text/automm/predictor.py
- text/src/autogluon/text/automm/utils.py
- text/tests/unittests/automm/test_automm_predictor.py
1. Design the distillation API for AutoMMPredictor. Knowledge distillation reuses the .fit() function. Here is an example to use distillation.
```
from autogluon.text.automm import AutoMMPredictor
teacher_predictor = AutoMMPredictor(label="label_column").fit(train_data)
student_predictor = AutoMMPredictor(label="label_column").fit(
train_data, 
hyperparameters=student_and_distiller_hparams, 
teacher_predictor=teacher_predictor,
)
```
2. Add distillation loops for training and validation.
3. Add a setup function in AutoMMPredictor to prepare for distillation.
4. Reduce the memory usage for top k checkpoints averaging.
> Enable knowledge distillation for AutoMM

- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- tabular/src/autogluon/tabular/models/image_prediction/image_predictor.py
- tabular/src/autogluon/tabular/models/text_prediction/text_prediction_v1_model.py
https://github.com/awslabs/autogluon/issues/1675
* Added a method to validate resources before bagging is started. Image/text predictor model would require minimum of 1 gpu.
> Disable image/text in tabular predictor when gpu is not avaialble

- core/src/autogluon/core/trainer/abstract_trainer.py
#1684 
autogluon/core/trainer/abstract_trainer.py", line 2436, in _get_feature_prune_proxy_model
for model_name, type_inner in candidate_models_type_inner.items():
**RuntimeError: dictionary changed size during iteration**
> fix [BUG] #1684

- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- core/src/autogluon/core/trainer/abstract_trainer.py
#1689 (Introduced first bug, but 2nd and 3rd were already present but rare / inactive)
- Fix repeated bagging failing to fit repeats beyond the first when time limit is specified due to `self.model_base` being None in the loaded model (need to use `self._get_model_base()`).
- Fixed HPO not working for bagged models if the bagged model is loaded from disk (same issue as above).
- Fixed Feature importance erroring if `self.model_best` is None (can happen if no Weighted Ensemble is fit). Now it does same logic as `predict` to find best model if `self.model_best` is None.
> Fix repeated bagging

- tabular/src/autogluon/tabular/learner/abstract_learner.py
- tabular/src/autogluon/tabular/predictor/predictor.py
Updated subsample_size 1000 -> 5000, num_shuffle_sets 3 -> 5
This will greatly improve the quality of the feature importance values by default, especially the 99% confidence bounds.
This will increase the time taken by ~8x, but this is acceptable because of the numerous inference speed optimizations done since these defaults were first introduced.
Comparison on Adult dataset:
Notice the dramatically more powerful p values and tighter stddev and p99_high p99_low.
Further, when compared to an extreme setting that is highly accurate, the new defaults are very close to the results of the extreme setting, whereas the old setting was quite far off on several importance scores.
Old (subsample 1000, sets 3):
```
Computing feature importance via …
```
> Updated feature importance defaults

- text/src/autogluon/text/automm/constants.py
- text/src/autogluon/text/automm/data/dataset.py
- text/src/autogluon/text/automm/data/preprocess_dataframe.py
- text/src/autogluon/text/automm/data/process_categorical.py
- text/src/autogluon/text/automm/data/process_image.py
- text/src/autogluon/text/automm/data/process_label.py
- text/src/autogluon/text/automm/data/process_numerical.py
- text/src/autogluon/text/automm/data/process_text.py
- text/src/autogluon/text/automm/predictor.py
- text/src/autogluon/text/automm/utils.py
- text/tests/unittests/automm/test_automm_predictor.py
To do feature column level distillation, we need to let AutoMM dataloader return feature column information.
1. Add feature column names in data processors.
2. Dataframe preprocessor outputs dictionary instead of list.
3. Data processors's return contains feature column information.
4. Use property for return keys in data processors.
5. CLIP uses eos token as the cls token. So avoid using eos as the sep token for CLIP.
> Make AutoMM dataloader return feature column information

- tabular/src/autogluon/tabular/models/rf/rf_model.py
Limit RF/XT max_leaf_nodes to 15000 (previously uncapped).
Previously, for very large datasets RF/XT memory and disk usage would quickly become unreasonable. This ensures that at a certain point RF and XT will no longer become larger given more rows of training data.
Benchmark results show that the change is an improvement, particularly for the high quality preset.
Benchmark Results:
Good Quality is mostly unaffected as it already used smaller trees.
High Quality has superior win-rate (56%) while having 43% faster inference speed on datasets with >=50,000 rows of training data due to this change:
```
AutoGluon_hq_1h8c_2022_03_25 VS all
framework   winrate    >    <    =  % Less Avg. Errors  Avg Inf Speed Diff  time_train_s  time_infer_s …
```
> Limit RF max_leaf_nodes to 15000

- text/src/autogluon/text/automm/configs/environment/default.yaml
- text/src/autogluon/text/automm/predictor.py
- text/tests/unittests/automm/test_backward_compatibility.py
1. Fix a unit test by cleaning up saving path.
2. Support resuming top k averaging if encountering failures.
3. Replace `per_gpu_batch_size_evaluation` with `eval_batch_size_ratio`. Users only needs to override `per_gpu_batch_size`. `per_gpu_batch_size_evaluation` would be automatically updated.
> Fix a unit test and improve top k averaging

- tabular/src/autogluon/tabular/models/knn/knn_model.py
#1020
- Limit KNN to 32 CPUs to avoid OpenBLAS error when many CPUs are available.
> Limit KNN to 32 CPUs to avoid OpenBLAS error

- forecasting/src/autogluon/forecasting/dataset/ts_dataframe.py
- forecasting/tests/unittests/common.py
- forecasting/tests/unittests/test_ts_dataset.py
Add a frequency property to time series data frames. The field is inferred directly via pandas from the multiindex. + minor fixes and additions.
> Add frequency field to time series dataframes

- core/src/autogluon/core/models/abstract/abstract_model.py
- features/src/autogluon/features/generators/abstract.py
- features/tests/features/generators/test_identity.py
- Fix scenario where feature is both excluded due to type incompatibility and contains only 1 unique value causing a crash in feature generators.
- Add `banned_feature_special_types` to make it easier for users to exclude features from feature generators.
> Fix useless features

- text/src/autogluon/text/automm/optimization/lit_module.py
- text/src/autogluon/text/automm/optimization/utils.py
- text/src/autogluon/text/automm/utils.py
We avoid computing the metric score at each validation step through the following:
1. logging metric object instead of score at each validation step. 
2. using `metric.update()` instead of `metric()`.
In this way, we can solve the previous issues regarding the `r2` (error with batch size 1) and `roc_auc` (wrong score and warning: No positive/negative samples in targets, false negative/positive value should be meaningless.)
Now, it's safe to use the validation metrics `r2`, `roc_auc`, etc.
> Improve AutoMM's validation metric computation

- forecasting/src/autogluon/forecasting/dataset/ts_dataframe.py
- forecasting/src/autogluon/forecasting/models/abstract/abstract_forecasting_model.py
- forecasting/src/autogluon/forecasting/models/gluonts/abstract_gluonts.py
- forecasting/tests/unittests/models/test_gluonts.py
- forecasting/tests/unittests/models/test_models.py
- forecasting/tests/unittests/trainer/test_trainer.py
Integrates `TimeSeriesDataFrame` format with forecasting `Model`s and `Trainer`, making the forecasting library available for testing e2e except for learner and predictor objects. 
> integrate forecasting models and trainer to time series dataframe format

- text/src/autogluon/text/automm/configs/data/default.yaml
- text/src/autogluon/text/automm/optimization/utils.py
- text/src/autogluon/text/automm/predictor.py
- text/src/autogluon/text/automm/utils.py
- text/tests/unittests/automm/test_auto_model.py
- text/tests/unittests/automm/test_metrics.py
- text/tests/unittests/automm/test_utils.py
Previously, AutoMM always used label 1 as the positive label in computing the `roc_auc` and `average_precision` metrics in binary classification. However, 1, corresponding to class name label_encoder.classes_[1], may not always be the semantically positive class's label for specific tasks. For example, users provide string class names `a` and `b`, and wants `a` to be the semantically positive class. This PR makes it possible for users to customize their positive classes.
Related discussions:
https://github.com/scikit-learn/scikit-learn/issues/15303
https://github.com/scikit-learn/scikit-learn/pull/15405
1. Add a hyper-parameter `pos_label` (positive class name) in data config. We use `pos_label` to align with sklearn's APIs, e.g., …
> Improve AutoMM's binary classification's metrics by supporting customizing positive class

- Jenkinsfile
- core/setup.py
- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
* Version cap Protobuf
Protobuf introduced breaking change: https://github.com/protocolbuffers/protobuf/issues/10051
Ray didn't upper cap the version of protobuf and caused this issue. They've merged in the fix: https://github.com/ray-project/ray/pull/25211.
Similar issue happens to Pytorch Lightning as well.
This would also affect released autogluon(0.4.0, 0.4.1)
* Also updated ray import error msg, which wasn't correct.
> [CI] Try fix protobuf

- forecasting/src/autogluon/forecasting/dataset/ts_dataframe.py
- forecasting/src/autogluon/forecasting/predictor.py
- forecasting/tests/unittests/test_ts_dataset.py
- Add convenience method and override `_constructor` in `TimeSeriesDataFrame`. This prevents type inconsistencies in DataFrame methods that return copies.
- Add `"label"` alias to Predictor.
> Fix TimeSeriesDataFrame type inconsistencies

- text/src/autogluon/text/automm/configs/data/default.yaml
- text/src/autogluon/text/automm/configs/optimization/adamw.yaml
- text/src/autogluon/text/automm/data/preprocess_dataframe.py
- text/src/autogluon/text/automm/optimization/lit_module.py
- text/src/autogluon/text/automm/optimization/utils.py
- text/src/autogluon/text/automm/predictor.py
- text/tests/unittests/automm/test_metrics.py
Adding BCEloss into automm regression. It is a special method for dealing with regression problems.
Add BCEloss. It will be active if the problem_type = binary and the eval_metrics belong to regression.
This requires the label to be converted to [0,1].
So the default standardization should be modified. Now users can choose "minmaxscaler", "standardscaler" or nothing to do in the data default.
> Support using BCELoss for training regression models in AutoMM + Support MinMaxScaler

- docs/cheatsheet.rst
- Update cheatsheet links to GitHub instead of S3.
- One minor downside to this is that the PDF link immediately downloads on chrome when using the GitHub link instead of previewing like it does with the S3 link. Thoughts on how to enable preview for the GitHub artifact are welcome.
- Note: We should do the same update to branch `0.4.1` and `0.4.0` but instead link the v0.4.0 GitHub artifacts (instead of stable).
> Update cheatsheet links to GitHub instead of S3

- core/src/autogluon/core/models/abstract/abstract_model.py
- Avoid dropping features with two unique values when one unique value is NaN. This feature can still provide signal.
> Avoid dropping features with two unique values + NaN

- core/src/autogluon/core/utils/try_import.py
#1763
- Previously, the pip install instructions given in logs would not necessarily lead to the correct version install of packages such as XGBoost. With this change we tie the version to the AutoGluon install.
- Removed 2 unused try import functions: cv2 and skopt
> Improve import failure messages

- Jenkinsfile
- docs/build.yml
Move lint check to separate stage so the unit-test won't be triggered if the lint is failing.
> Move lint check to separate stage

- timeseries/src/autogluon/timeseries/dataset/ts_dataframe.py
- timeseries/tests/unittests/test_ts_dataset.py
- Adds the option of inferring data frame frequency from the first element's index. This handles edge cases where pandas cannot tell the inferred frequency of multiple concatenated date time indices -- an edge case we discovered during benchmarking.
- Temporarily disables "uniform time series index" check, since pandas appears to sometimes get confused by timedeltas of e.g., months (some months have 30 days and others 31, so not uniform). This led the benchmarks to spuriously fail.
- Moves inner logic of `from_***` constructors out of the constructor methods. This is because we used the constructor methods also in `__init__`, which led to an (inadvertent) recursion.
cc: @huibinshen 
By submitting this pull request, I confirm that you can …
> Fix time series dataframe freq inference

- multimodal/src/autogluon/multimodal/optimization/lit_distiller.py
- multimodal/tests/unittests/test_distiller.py
1. Use `.update()` in computing the validation metric to compute `roc_auc` more accurately and avoid errors for `r2`.
2. Add one unit test for distillation.
> Improve computing validation metric in AutoMM distiller

- multimodal/src/autogluon/multimodal/constants.py
- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/utils.py
- multimodal/tests/unittests/test_metrics.py
1. Since `autogluon.core.metrics`'s `f1` metric doesn't support passing the `pos_label` argument, we choose to directly use `sklearn`'s `f1_score`. We use `pos_label` instead of a customized label encoder to be backward compatible because checkpoints saved in 0.4.0 still use `sklearn`'s label encoder.
2. Add a unit test for `f1`.
> Support f1 in AutoMM

- core/src/autogluon/core/trainer/abstract_trainer.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/tests/unittests/test_tabular.py
- Previously, if `best_model` was not able to predict (aka not saved), calling `get_oof_pred_proba` would error even if the oof_pred_proba was technically available.
- This PR fixes this.
- Refit models can now be called in `get_oof_pred_proba` without crashing. The `oof_pred_proba` of their parent (original) model will be used as a proxy.
- Code cleanup to maintain parent <-> refit relationship in DAG instead of in a separate dictionary.
> Improve get_oof_pred_proba for refit models

- multimodal/src/autogluon/multimodal/optimization/utils.py
- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/utils.py
- multimodal/tests/unittests/test_metrics.py
`torchmetrics.F1Score` (https://torchmetrics.readthedocs.io/en/stable/classification/f1_score.html) doesn't provide the `pos_label` to return the f1 score of one specific class. However, sklearn's `f1_score` has this argument (https://scikit-learn.org/stable/modules/generated/sklearn.metrics.f1_score.html). In this PR, we define CustomF1Score to inherit from `torchmetrics.F1Score` and add the `pos_label` argument.
> Support customizing class label for torchmetrics.F1Score

- docs/tutorials/text_prediction/automm.md
- multimodal/src/autogluon/multimodal/configs/optimization/adamw.yaml
- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/presets.py
- multimodal/src/autogluon/multimodal/registry.py
- multimodal/src/autogluon/multimodal/utils.py
- multimodal/tests/unittests/test_config.py
- multimodal/tests/unittests/test_presets.py
- multimodal/tests/unittests/test_registry.py
- text/src/autogluon/text/text_prediction/presets.py
1. Add presets: `default`, `medium_quality_faster_train`, `high_quality`, and `best_quality` in AutoMM.
2. add the `preset` argument in `.fit()` and use it in `get_config()`.
3. Use registry for presets.
4. Add a function to return AutoMM's basic config.
5. Update some function names to be specific for AutoMM.
> Update AutoMM presets

- timeseries/src/autogluon/timeseries/dataset/ts_dataframe.py
- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- timeseries/tests/unittests/common.py
- timeseries/tests/unittests/models/test_models.py
- timeseries/tests/unittests/models/test_sktime.py
~~**Depends on:** #1841 #1839~~
Removes the constraint of specifying only integer type item indices in time series panel data frames, improving user experience.
cc: @huibinshen 
> Allow generic item indices in time series dataframe

- timeseries/src/autogluon/timeseries/models/presets.py
- timeseries/src/autogluon/timeseries/models/sktime/abstract_sktime.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/src/autogluon/timeseries/trainer/abstract_trainer.py
- timeseries/tests/unittests/models/test_models.py
- timeseries/tests/unittests/models/test_sktime.py
- timeseries/tests/unittests/test_trainer.py
Depends on #1859 , subsumes #1857 
- update model names and priority configs
- fix Trainer.score, which ignored non-GluonTS models
> Add sktime to model types, fix sktime model scoring on test data

- core/src/autogluon/core/trainer/abstract_trainer.py
- Add no time log at start of trainer
- This provides a more informative error message in case the time limit was exceeded during feature preprocessing.
> Add no time log at start of trainer

- docs/tutorials/multimodal/index.rst
- docs/tutorials/multimodal/multimodal_text_tabular.md
- docs/tutorials/text_prediction/index.rst
- multimodal/src/autogluon/multimodal/predictor.py
1. Clean the `index.rst` in the `text_prediction` folder since some docs are removed.
2. Filter two messages in prediction/evaluation.
3. Unify tutorial titles with card titles.
> Clean tutorial printing and indexes

- docs/tutorials/timeseries/forecasting-quickstart.md
- timeseries/setup.py
- timeseries/src/autogluon/timeseries/__init__.py
Right now after install time series errors with `no module found: mxnet`. This fixes it back to fail more gracefully.
> fix mxnet warning in timeseries

- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/presets.py
- multimodal/src/autogluon/multimodal/utils.py
- multimodal/tests/unittests/test_distiller.py
- multimodal/tests/unittests/test_presets.py
- text/src/autogluon/text/text_prediction/predictor.py
- text/src/autogluon/text/text_prediction/presets.py
- text/tests/unittests/text_prediction/test_distiller.py
- text/tests/unittests/text_prediction/test_text_presets.py
1. Support distillation for the text predictor.
2. Previous adding default for distill is not optimal. This is to improve the design.
3. Add unit tests for passing a predictor object or a a predictor path.
> Support distillation for text predictor and add default for distiller

- multimodal/tests/unittests/datasets.py
- multimodal/tests/unittests/test_hpo.py
- multimodal/tests/unittests/test_predictor.py
1. HPO tests fail sometimes in AutoMM due to that no best trial is found. This is to fix the issue by reducing the training data size.
2. Separate HPO tests into a new test file.
> Fix HPO tests in AutoMM

- multimodal/tests/unittests/test_predictor.py
- vision/src/autogluon/vision/predictor/predictor.py
#1890. Problem is caused by using GluonCV image classifier [`predict_proba` function](https://github.com/dmlc/gluon-cv/blob/master/gluoncv/auto/estimators/image_classification/image_classification.py#L601). In this function, the [returned predicted probabilities](https://github.com/dmlc/gluon-cv/blob/master/gluoncv/auto/estimators/image_classification/image_classification.py#L631) are flattened into `BC x 1`. However, in most of the cases, the output should be in `B x C` format. B indicates batch size and C indicates number of classes. This error only happens when input data type is torch.Tensor. When input data type is str, list of strs, dataframe, etc, existing code works fine. So I added an `if` statement.
Add an `if` statement: if …
> Fix predict_proba bug in image predictor

- multimodal/tests/unittests/test_hpo.py
HPO testing sometimes fails due to RuntimeError: CUDA error: out of memory, but the GPU memory usage is low. Seems something is wrong with ray. Need to investigate the reasons. Skip the tests for now. @yinweisu
> Skip AutoMM HPO tests temporarily

- timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
- timeseries/tests/unittests/test_predictor.py
Fixes models ignoring custom target field names during HPO.
> fix custom target issue in time series HPO, close #1892

- tabular/setup.py
- tabular/src/autogluon/tabular/models/_utils/torch_utils.py
- tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
- tabular/src/autogluon/tabular/models/tabular_nn/torch/tabular_nn_torch.py
- Optimize NN Inference Speed by altering torch threads during predict calls.
- A bug was causing inference to get slower with more CPU cores in a machine due to a bug in XGBoost altering the global OpenMP thread limit.
- Affected both `FASTAI` and `NN_TORCH`
- NN speedup is based on number of CPUs. ~2x speedup with 8 vCPUs, ~6x speedup with 64 vCPUs.
Special thanks to @willsmithorg for highlighting this issue in his performance benchmarking!
Benchmark is AutoMLBenchmark filtered to datasets with >=10,000 rows.
**Benchmark Results Summary:**
Given 4h64c (4 hour training time, m5.16xlarge), this PR matches mainline in model quality and training speed with the following benefits:
- 6x faster inference speed for `FASTAI` and `NN_TORCH` …
> [Tabular] Optimize NN Inference Speed

- tabular/src/autogluon/tabular/learner/abstract_learner.py
- tabular/src/autogluon/tabular/learner/default_learner.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- Disable multilayer stacking in binary when `auto_stack=True`
- This avoids the stack info leakage problem that can commonly occur in binary classification.
- While this makes results worse on some datasets, it greatly improves results on others.
- In general, inference speed is improved significantly for binary problems.
Benchmark: 172 Binary datasets with >=10,000 rows
```
AutoGluon_bq_4h64c_2022_06_25_nn VS all
framework   winrate   >   <    =  % Less Avg. Errors  Avg Inf Speed Diff  time_train_s  time_infer_s  loss_rescaled  time_train_s_rescaled  time_infer_s_rescaled      rank  rank=1_count  rank=2_count  rank=3_count  rank>3_count  error_count
0  AutoGluon_bq_4h64c_2022_06_26_binary  0.531977  88  77    7            1.754443 …
```
> Disable multilayer stacking in binary

- timeseries/src/autogluon/timeseries/evaluator.py
- timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
- timeseries/src/autogluon/timeseries/models/ensemble/greedy_ensemble.py
- timeseries/src/autogluon/timeseries/trainer/abstract_trainer.py
- timeseries/src/autogluon/timeseries/utils/warning_filters.py
- timeseries/tests/conftest.py
- timeseries/tests/test_check_style.py
- timeseries/tests/unittests/common.py
- timeseries/tests/unittests/models/test_gluonts.py
- timeseries/tests/unittests/models/test_models.py
- timeseries/tests/unittests/models/test_sktime.py
- timeseries/tests/unittests/test_evaluator.py
- timeseries/tests/unittests/test_learner.py
- timeseries/tests/unittests/test_predictor.py
- timeseries/tests/unittests/test_trainer.py
- timeseries/tests/unittests/test_ts_dataset.py
- Streamline unit tests, with a 2x speedup to ~10-15 minutes, with no drop in test coverage.
- Take care of warnings during testing, and address style issues
- black the `tests/` folder. this is the last commit in this PR and can be ignored during the review.
test coverage:
```
---------- coverage: platform linux, python 3.7.10-final-0 -----------
Name                                                                    Stmts   Miss  Cover
-------------------------------------------------------------------------------------------
src/autogluon/__init__.py                                                   1      1     0%
src/autogluon/timeseries/__init__.py                                       15      4    73%
src/autogluon/timeseries/configs/__init__.py …
```
> [TimeSeries] streamline unit tests

- core/src/autogluon/core/trainer/abstract_trainer.py
- Added caching y_pred_proba_val in TabularPredictor.
- Previously, if using a holdout/validation set, each model's predictions of the val data would not be cached. This mean't at minimum that the model would have to predict on the val data (1) to compute val score, (2) during weighted ensembling, (3) during each higher multi-layer stacking call. In the typical case, this meant that we were predicting on val data twice. This caused issues for models that require a great deal of time to predict, causing us to go over time limit in some rare cases. This was a huge problem if `use_bag_holdout=True` and `num_stack_levels` was high, as every model trained prior would need to predict on the val data again for every new stack layer trained.
- …
> Added caching y_pred_proba_val

- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- Cleanup HPO artifacts
- Previously, train and val datasets were pickled to disk and not removed for every model that underwent HPO. This led to >20 copies of the train and val data cached to disk. With this PR, the dataset caches are deleted directly after HPO for a given model, ensuring only 1 copy is saved to disk at a time, and 0 copies are saved after training is completed.
- Previously when HPO was conducted with bagging enabled, the HPO artifact of the first fold model of each trial would be duplicated on disk and not deleted. Now the duplicate is deleted after HPO finishes for a given model.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
> Cleanup HPO artifacts

- core/src/autogluon/core/trainer/abstract_trainer.py
#1920 
- Fix bug in #1920 causing a crash if cached_y_pred_proba_val == False (Never the case, but could happen in future).
> Fix y_pred_proba lookup when cached_y_pred_proba_val == False

- multimodal/setup.py
Due to the upgrade of nlpaug (https://github.com/makcedward/nlpaug), specifying model.hf_text.text_train_augment_types with a list of augmentation operators causes exceptions. We temporarily cap the version to the last one to workaround this. Will investigate the reasons later.
> Cap nlpaug version

- core/src/autogluon/core/metrics/__init__.py
- core/tests/unittests/metrics/test_metric_kwargs.py
- Add kwargs support to metrics
- Now can specify values at call time such as `pos_label` for F1 metric.
> Add kwargs support to metrics

- multimodal/src/autogluon/multimodal/data/infer_types.py
- multimodal/src/autogluon/multimodal/data/preprocess_dataframe.py
- multimodal/src/autogluon/multimodal/data/process_image.py
- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/presets.py
- multimodal/src/autogluon/multimodal/utils.py
1. Get data types based on model types.
2. Filter auto-detected columns types to make sure all types are allowed. Replace the invalid types with a default fallback type.
3. Use the CLIP large@336 in zero-shot learning by default.
> Improve column type detection by supporting fallback type

- .github/workflows/platform_tests-command.yml
* Github action started to install libomp by default, previous script didn't remove the existing installation. So the libomp 11.1 wasn't correctly installed and caused segfault.
* Set fail fast to be false, so that different OS won't be affected by failure status of each other.
Tested on the fork:
https://github.com/yinweisu/autogluon/actions/runs/2659133804
> Fix nightly platform test

- multimodal/src/autogluon/multimodal/data/infer_types.py
1. Only allow numerical and categorical labels by default since we only do predictions currently.
2. If other label types (probably text) are detected falsely, then fallback to the categorical type.
3. We can customize the `allowable_label_types ` and `fallback_label_type ` for new user cases.
> Add the fallback label type in AutoMM

- .github/workflow_scripts/build_all_docs.sh
* While building the doc, we don't need to substitute the branch when saving to our private bucket, for example, 'master' -> 'dev'. We only need to do it when we move docs to our official web bucket. Previously, doing this cause docs got written to PRIVATE_BUCKET/dev/xxx when it's on master branch, and the copy docs script will try to look at PRIVATE_BUCKET/master/xxx, which doesn't exists. This PR should fix this issue.
> Fix build docs saving path

- multimodal/src/autogluon/multimodal/models/timm_image.py
- multimodal/src/autogluon/multimodal/models/utils.py
- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/utils.py
- multimodal/tests/unittests/test_zero_shot.py
1. Use timm to create head to cover the case that, if the provided `num_classes` is the same as the pre-trained `num_classes`, we can reuse the pre-trained head.
2. Move the timm head outside since we need to get the pooled features for late fusion sometimes.
3. Output logits only if the `num_classes` > 0.
4. Add a unit test for timm zero shot learning.
> Support timm zero shot learning

- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/utils.py
- multimodal/tests/unittests/test_backward_compatibility.py
- multimodal/tests/unittests/test_data_augmentation.py
- multimodal/tests/unittests/test_predictor.py
- multimodal/tests/unittests/test_save_path.py
- text/tests/unittests/test_backward_compatibility.py
*Issue #1969 *
1. Support generating random paths in continuous training if `save_path` is not specified.
2. Avoid overwriting if old paths are detected.
3. Add unit tests.
> Improve AutoMM's save_path logic

- tabular/src/autogluon/tabular/models/knn/_knn_loo_variants.py
- tabular/src/autogluon/tabular/models/knn/knn_model.py
KNN will crash when predicting if loaded in a separate process after fitting if using scikit-learn-intelex backend. This PR fixes this issue by avoiding creating a new KNN class for efficient LOO and instead directly using the intelex knn class and not patching.
Colab notebook showcasing fix: https://colab.research.google.com/drive/1RQpmftn51jdmrwA1KxUTRPkMdIt27uyH?usp=sharing
> Fix KNN skex bug

- .github/workflows/platform_tests-command.yml
* https://github.com/awslabs/autogluon/pull/1991 unified the script being used by CI and platform tests but introduced an issue. mxnet cannot be installed on Windows; hence failing install test. 
* Changes will only take effect after merging in
> Remove mxnet install in platform tests

- core/src/autogluon/core/trainer/abstract_trainer.py
- core/src/autogluon/core/utils/utils.py
*Issue #, if available:* https://github.com/awslabs/autogluon/issues/1794
- Just passes `quantile_levels` to `compute_permutation_feature_importance` like how we do it in `AbstractTrainer.score`
> Fix calculation of feature importances on Quantile Models

- timeseries/src/autogluon/timeseries/models/presets.py
- timeseries/src/autogluon/timeseries/models/sktime/abstract_sktime.py
- timeseries/src/autogluon/timeseries/models/sktime/models.py
- timeseries/tests/unittests/models/test_sktime.py
This PR fixes several problems with `sktime` models (`ThetaModel`, `TBATSModel`, `AutoETSModel`, `ARIMAModel`, `AutoARIMAModel`) in the timeseries module:
- Suppress `RuntimeWarning`s during prediction that flooded the model output in some cases.
- Add docstrings for `sktime` models. These describe the possible hyperparameters that can be passed to the models.
- A warning is made if user provides a hyperparameter that isn't recognized by the model.
- New method `AbstractSktimeModel._get_skt_forecaster_init_args` 
- allows us to decouple the API exposed to AG users (via `hyperparameters`) from the API of `sktime` that sometimes uses inconsistent / cryptic parameter names.
- gives us flexibility to change the hyperparameters in some cases to make the model more robust (e.g., turn off …
> Improve sktime models API

- common/src/autogluon/common/utils/log_utils.py
- common/tests/unittests/test_log_utils.py
- core/src/autogluon/core/trainer/abstract_trainer.py
- tabular/src/autogluon/tabular/learner/default_learner.py
- Improved logging of infer_limit
Mainline logs:
```
0.0s	= Feature Preprocessing Time (1 row | 10000 batch size)
Feature Preprocessing requires 14.02% of the overall inference constraint (5e-05s)
0.0s inference time budget remaining for models...
Fitting model: LightGBMLarge ...
0.9078	 = Validation score   (roc_auc)
0.57s	 = Training   runtime
0.01s	 = Validation runtime
0.004ms	 = Validation runtime (1 row | 10000 batch size)
0.004ms	 = Validation runtime (1 row | 10000 batch size | FULL)
Removing 6/13 base models to satisfy inference constraint (constraint=0.0s) ...
0.0001s -> 0.0001s (KNeighborsUnif)
0.0001s -> 0.0001s (KNeighborsDist)
0.0001s -> 0.0001s (NeuralNetTorch)
0.0001s -> 0.0001s (NeuralNetFastAI)
0.0001s -> 0.0s …
```
> Improved logging of infer_limit

- multimodal/src/autogluon/multimodal/data/infer_types.py
Training encounters error if the label column has only 1 label class. Since training with 1 label is meaningless, we can raise error if detecting so.
> Fix single label error

- timeseries/src/autogluon/timeseries/dataset/ts_dataframe.py
- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- timeseries/src/autogluon/timeseries/models/gluonts/models.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/tests/unittests/test_predictor.py
- timeseries/tests/unittests/test_ts_dataset.py
AG-TS failed silently on irregularly sampled time series that also can't be inferred as business day-frequency by pandas. As we depend on pandas for frequency inference, this will continue to be the case. However, we can also add a `fit` argument to the predictor called `ignore_time_indexes` to enable customers using irregular timestamps as is (as if they are irregularly sampled), but this would somewhat break API semantics during predict (where a "dummy" time index will be output). 
> Fix timeseries failing silently on irregularly sampled time series

- timeseries/src/autogluon/timeseries/dataset/ts_dataframe.py
- timeseries/src/autogluon/timeseries/models/sktime/abstract_sktime.py
- timeseries/tests/unittests/test_ts_dataset.py
Several changes to `autogluon.timeseries.dataset.ts_dataframe.TimeSeriesDataFrame`
- Speed up `slice_by_timestep` - use a Boolean mask instead of slicing each series individually in a for loop
- Train / val split for the `m4_quarterly` dataset (24000 time series) is now ~1000x faster (used to be 178 seconds, now 0.15 seconds).
- Add method `num_timesteps_per_item` that returns the length of each individual time series in the dataset.
- Slightly cleaner code for `_item_index`.
- Refer to index levels using their names `ITEMID` and `TIMESTAMP` (instead of `0` and `1`).
> Speed up TimeSeriesDataFrame.slice_by_timestep

- common/src/autogluon/common/utils/utils.py
- common/tests/unittests/test_setup_outputdir.py
- tabular/src/autogluon/tabular/predictor/predictor.py
*Issue #, if available:* https://github.com/awslabs/autogluon/issues/2022
*Description of changes:* 
* assert that types of path are `str` or `pathlib.Path` to avoid unwanted conversion from weird types to string
* add unit-tests to check the path logic
* update doc to mention that pathlib.Path are supported
> Assert that path have the right types and test path logic

- timeseries/setup.py
- timeseries/src/autogluon/timeseries/models/presets.py
This PR contains two changes:
1. It bumps the `sktime` dependency to `~=0.13,>=0.13.1`, which will allow us to also bump the `numpy` version.
2. It rolls back the presets to the version that we had in `0.5.2` release of AG. I discovered some problems with high disk/memory usage of the current version of the presets (last modified in #2001 but not included in any release yet). I want to fix these problems before we update the presets to avoid impacting the user experience in a negative way.
> Bump sktime to 0.13.1 and roll back presets for time series

- tabular/src/autogluon/tabular/models/lgb/lgb_model.py
- Optimize LightGBM DART retraining by not calculating stopping metric scores on val data on each iteration, since we aren't using early stopping and are training to a fixed number of iterations.
> Optimize LightGBM DART retraining

- timeseries/src/autogluon/timeseries/dataset/ts_dataframe.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/src/autogluon/timeseries/splitter.py
- timeseries/tests/unittests/test_splitter.py
- timeseries/tests/unittests/test_ts_dataset.py
Currently, if no `tuning_data` is passed to `autogluon.timeseries.TimeSeriesPredictor.fit`, we use the last `prediction_length` timesteps of `train_data` as hold-out validation set. This PR enables new train / val splitting strategies for timeseries datasets, such as multi-window backtesting.
- New abstract class `autogluon.timeseries.splitter.AbstractTimeSeriesSplitter` that encapsulates the train / val split logic in its `split` method.
- Two currently supported strategies:
- `LastWindowSplitter` - reserve last `prediction_length` steps (default, same as before)
- `SlidingWindowSplitter` - reserve multiple windows of length `prediction_length` (potentially overlapping) for validation
- `autogluon.timeseries.TimeSeriesPredictor` now accepts an optional argument `splitter`.
- …
> Multi-window backtesting for TimeSeriesPredictor

- timeseries/src/autogluon/timeseries/models/presets.py
- timeseries/src/autogluon/timeseries/splitter.py
- timeseries/src/autogluon/timeseries/utils/seasonality.py
- timeseries/tests/unittests/test_predictor.py
- timeseries/tests/unittests/test_splitter.py
Minor fixes for problems revealed by the latest benchmarking run for timeseries:
- Keep `_cached_freq` during splitting with `MultiWindowSplitter`
- Fix bug in `get_seasonality`
- Add test for the `validation_splitter` argument in `TimeSeriesPredictor`
- Use presets that don't lead to OOM issues on large datasets with ARIMA (band-aid fix until we implement better local models)
> Fix MultiWindowSplitter for timeseries and use faster presets

- docs/tutorials/multimodal/customization.md
- multimodal/src/autogluon/multimodal/configs/model/fusion_mlp_image_text_tabular.yaml
Add more hyper-parameters of the `hf_text` model in the AutoMM customization tutorial.
> Add more customizations for the hf_text model

- .github/workflow_scripts/env_setup.sh
- multimodal/setup.py
- multimodal/src/autogluon/multimodal/configs/environment/default.yaml
- multimodal/src/autogluon/multimodal/configs/model/fusion_mlp_image_text_tabular.yaml
- multimodal/src/autogluon/multimodal/constants.py
- multimodal/src/autogluon/multimodal/data/process_image.py
- multimodal/src/autogluon/multimodal/models/__init__.py
- multimodal/src/autogluon/multimodal/models/mmdet_image.py
- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/presets.py
- multimodal/src/autogluon/multimodal/utils.py
- multimodal/tests/unittests/test_object_detection.py
NA
This PR aims to enable object detection in MultimodalPredictor by integrating MMdetection. 
```
from autogluon.multimodal import MultiModalPredictor
od = MultiModalPredictor(pipeline="object_detection")
results = od.predict({"image": ["demo.jpg"]})
from mmdet.apis import show_result_pyplot
show_result_pyplot(
od._model.model,
'demo.jpg',
results[0][0],
palette='coco',
out_file='./demo_results.jpg')
```
Will add data handling and model training in following PRs. 
> MMdetection integration - inference

- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/utils.py
1. Fix AutoMM CPU inference. Users may customize `config.env.num_gpus` when using GPUs in training. Later, they would encounter an error if they do CPU inference.
2. Make saved `num_gpus`, `precision`, and `strategy` consistent with those used in training.
3. Add the `column_types` property to support the cloud predictor.
> Fix AutoMM CPU inference

- timeseries/src/autogluon/timeseries/evaluator.py
- timeseries/src/autogluon/timeseries/learner.py
- timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
- timeseries/src/autogluon/timeseries/models/sktime/models.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/src/autogluon/timeseries/trainer/abstract_trainer.py
- timeseries/tests/unittests/models/test_gluonts.py
- timeseries/tests/unittests/models/test_models.py
- timeseries/tests/unittests/models/test_sktime.py
Clean up warnings that appear in `test_check_style` run. 
> clean up flake and pep8 warnings in timeseries

- timeseries/src/autogluon/timeseries/evaluator.py
- timeseries/src/autogluon/timeseries/learner.py
- timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
- timeseries/src/autogluon/timeseries/models/ensemble/greedy_ensemble.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/src/autogluon/timeseries/trainer/abstract_trainer.py
- timeseries/tests/unittests/test_learner.py
- timeseries/tests/unittests/test_predictor.py
- timeseries/tests/unittests/test_trainer.py
This PR removes duplicated code from the timeseries module for the weighted ensemble, and refactors the ensemble APIs to be simpler and safer. It also adds an option to the predictor (public API change) to disable the ensemble (currently the ensemble is still enabled by default and for all presets), and automatically disables ensemble fitting if only one model was fitted. We also make minor changes to the evaluator for simpler handling of coefficients and `higher_is_better`. 
TODO:
> Refactor time series ensemble

- multimodal/src/autogluon/multimodal/models/clip.py
- multimodal/src/autogluon/multimodal/models/huggingface_text.py
- multimodal/src/autogluon/multimodal/models/utils.py
- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/utils.py
- text/src/autogluon/text/text_prediction/predictor.py
1. Change `standalone=True` by default to support the cloud predictors.
2. If `standalone=True`, save only the pretrained model config instead of the model weights. This can significantly reduce the disk usages.
> Improve AutoMM loading checkpoints offline

- common/setup.py
- common/src/autogluon/common/loaders/load_json.py
- common/src/autogluon/common/utils/utils.py
- common/tests/unittests/utils/test_compare_autogluon_metadata.py
- tabular/src/autogluon/tabular/predictor/predictor.py
#2047
- Added a variety of checks and logs that detect differences in environment between fit time and inference time.
- Raise exception by default if Python minor version differs during predictor load.
Example output (created by manually editing the metadata.json file contents to force mismatches):
```
predictor = TabularPredictor.load(path=path, check_packages=True)
```
```
Found 15 mismatches between original and current metadata:
WARNING: AutoGluon version mismatch (original=0.5.8, current=0.3.2b20211216)
WARNING: AutoGluon Python version mismatch (original=3.10, current=3.8)
WARNING: System mismatch (original=Windows, current=Darwin)
WARNING: Package version diff 'regex'	(original=2025.11.10, current=2021.11.10)
WARNING: Package …
```
> Add metadata.json file to check python and package versions

- timeseries/src/autogluon/timeseries/dataset/ts_dataframe.py
- timeseries/src/autogluon/timeseries/models/gluonts/models.py
- timeseries/src/autogluon/timeseries/models/presets.py
- timeseries/src/autogluon/timeseries/trainer/abstract_trainer.py
- revise minimum context length to 10 for gluonts models. this doesn't lead to a major change in benchmarks as all baseline datasets default to greater than 10. longer minimums did not lead to improvements.
- add `epochs` to gluonts docstrings.
> revise timeseries presets to minimum context length of 10

- timeseries/src/autogluon/timeseries/models/ensemble/greedy_ensemble.py
- Fix a bug in `TimeSeriesEnsembleSelection._calculate_regret` where the sign of the regret was flipped
> Fix regret calculation in TimeSeriesEnsembleSelection

- timeseries/src/autogluon/timeseries/learner.py
- timeseries/src/autogluon/timeseries/models/ensemble/greedy_ensemble.py
- timeseries/src/autogluon/timeseries/trainer/abstract_trainer.py
- timeseries/tests/unittests/models/test_ensemble.py
- timeseries/tests/unittests/test_predictor.py
Currently, if some model raises an exception during prediction (inside `AbstractTimeSeriesTrainer.predict`) the whole program crashes. This PR allows us to handle such model failures gracefully.
Changes:
- Add try/catch block in `AbstractTimeSeriesTrainer.predict` + instructions about what other models are available to the user if the best model failed.
- Re-normalize the weights in `SimpleTimeSeriesWeightedEnsemble.weight_pred_proba` in case some input models failed during prediction.
> Handle timeseries model failures during the prediction phase

- cloud/src/autogluon/cloud/predictor/cloud_predictor.py
- cloud/src/autogluon/cloud/predictor/multimodal_cloud_predictor.py
- cloud/src/autogluon/cloud/predictor/tabular_cloud_predictor.py
- cloud/src/autogluon/cloud/scripts/image_serve.py
- cloud/src/autogluon/cloud/scripts/multimodal_serve.py
- cloud/src/autogluon/cloud/scripts/tabular_serve.py
- cloud/src/autogluon/cloud/scripts/text_serve_automm.py
- cloud/src/autogluon/cloud/scripts/train.py
- cloud/tests/unittests/test_tabular_cloud_predictor.py
- cloud/tests/unittests/utils.py
* This PR removes FeatureMetadata as a required input to train tabular with image modality as this would force Tabular to be a dependency of Cloud module.
* Added `image_column` parameter to `fit()` api instead.
* Updated training script to accommodate 0.5.2 container seg fault issue.
* Updated multimodal serving script to include `'image'` as valid `image_path` too.
* Updated serving script to force `as_pandas = True` while doing inference to avoid bugs.
* Fixed an issue in previous tabular multimodality unit tests where the hyperparameter is not correctly set.
* The updated tests revealed two issues from multimodal module:
1. Tabular predictor in multimodal setting trained on gpu machine cannot be loaded on cpu machine. Discussed with …
> [Cloud] Remove feature meatadata from tabular cloud predictor

- core/src/autogluon/core/models/abstract/model_trial.py
- tabular/tests/unittests/test_tabular.py
Bug introduced in #1954 
- Fix error when doing HPO with KNN, RF, or XT due to type error.
- Ensure RF, XT, and KNN are unit tested when HPO is enabled.
Mainline:
```
Hyperparameter tuning model: KNeighborsUnif ... Tuning model for up to 24.91s of the 359.82s of remaining time.
No hyperparameter search space specified for KNeighborsUnif. Skipping HPO. Will train one model based on the provided hyperparameters.
File "/home/ubuntu/.conda/envs/autogluon/lib/python3.8/code.py", line 90, in runcode
exec(code, self.locals)
File "<input>", line 1, in <module>
File "/home/ubuntu/.cache/JetBrains/RemoteDev/dist/3c8721a60180e_pycharm-professional-2021.3.3/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", …
```
> Fix error when doing HPO with KNN, RF, or XT

- common/src/autogluon/common/utils/file_utils.py
- docs/tutorials/index.rst
- docs/tutorials/tabular_prediction/index.rst
- docs/tutorials/tabular_prediction/tabular-deployment.md
- docs/tutorials/tabular_prediction/tabular-indepth.md
- docs/tutorials/tabular_prediction/tabular-quickstart.md
- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/tests/unittests/test_tabular.py
- Add predictor clone support to make a perfect replica of a predictor in a new location on disk
- Add predictor optimized clone support to make an optimized version of the original predictor in a new location on disk
- Add tutorial on deployment optimization + usage of clone
- Add unit tests for clone
- Add get_size_disk method
- Add get_size_disk_per_file method
Refer to tutorial for example usage: http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-2071/0daed4a/tutorials/tabular_prediction/tabular-deployment.html
> Add predictor clone support

- timeseries/setup.py
- timeseries/src/autogluon/timeseries/models/__init__.py
- timeseries/src/autogluon/timeseries/models/presets.py
- timeseries/src/autogluon/timeseries/models/sktime/__init__.py
- timeseries/src/autogluon/timeseries/models/sktime/models.py
- timeseries/src/autogluon/timeseries/models/statsmodels/__init__.py
- timeseries/src/autogluon/timeseries/models/statsmodels/abstract_statsmodels.py
- timeseries/src/autogluon/timeseries/models/statsmodels/models.py
- timeseries/src/autogluon/timeseries/utils/warning_filters.py
- timeseries/tests/unittests/common.py
- timeseries/tests/unittests/models/test_ensemble.py
- timeseries/tests/unittests/models/test_models.py
- timeseries/tests/unittests/models/test_sktime.py
- timeseries/tests/unittests/models/test_statsmodels.py
- timeseries/tests/unittests/test_learner.py
- timeseries/tests/unittests/test_predictor.py
- timeseries/tests/unittests/test_splitter.py
- timeseries/tests/unittests/test_trainer.py
This PR introduces local models (ETS, ARIMA) from the `statsmodels` package to AutoGluonTS. This takes care of a few problems that we currently have when using `sktime`
- Correctly handles datasets with multiple time series of different lengths (`sktime` used to have problems with estimating `cutoff` for such datasets and sometimes produced wrong results).
- High disk usage - models now take a few KB instead of many MB/GB when saved to disk.
Other changes:
- Training and prediction are parallelized over CPU cores with `joblib`
- `statsmodels` models are used as default local models; `sktime` models received a `Sktime` prefix and were removed from the default presets.
Comparison of `statsmodels` and `sktime` versions of ETS and ARIMA on the `artificial_seasonal` dataset (parallelizing over …
> Implement wrappers for local models from statsmodels

- multimodal/src/autogluon/multimodal/configs/model/fusion_mlp_image_text_tabular.yaml
- multimodal/src/autogluon/multimodal/presets.py
Follow-up revision PR of https://github.com/awslabs/autogluon/pull/2032 . Now "t-few" is enabled in the default config
https://github.com/awslabs/autogluon/blob/e3fda1fc9d84ded0c612bc13c7472194503089f0/multimodal/src/autogluon/multimodal/configs/model/fusion_mlp_image_text_tabular.yaml#L2-L9
We need to explicitly set "model.names" in the presets.
> [Multimodal] Fix presets by constraining modal.names

- core/src/autogluon/core/hpo/executors.py
- tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
https://github.com/awslabs/autogluon/issues/2069
This PR addresses point 4 in the above issue. To be notice, I cannot reproduce point 3 now for some reason even though I was able to last week.
* Handle layer as tuple passed to fastai. `nn_torch` doesn't have layers as as nested list so it doesn't have this issue
* Disable tensorboard logging for tabular hpo tune until ray tune handles hyperopt tune issue correctly
* Added `super().__init__()`, which was missing previously
> Fix ray tune layer warning

- timeseries/src/autogluon/timeseries/models/ensemble/greedy_ensemble.py
- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- timeseries/tests/unittests/common.py
- timeseries/tests/unittests/models/test_models.py
- timeseries/tests/unittests/test_learner.py
- timeseries/tests/unittests/test_predictor.py
- timeseries/tests/unittests/test_trainer.py
- timeseries/tests/unittests/test_ts_dataset.py
Currently `AbstractGluonTSModel.predict` automatically sorts the predictions according to the `item_id` (even if the original `item_id`s are not sorted). This leads to problems downstream inside `TimeSeriesEnsembleSelection`, where all predictions are expected to have the exact same index. This PR fixes this problem and adds safeguards that should prevent similar problems in the future.
Side note: This was the source of the performance regressions that we saw compared to the 0.5.1 release of AGTS.
- Ensure that the order of `item_id`s in predictions in the same as in `data` for `AbstractGluonTSModel`
- Add sanity check to `TimeSeriesEnsembleSelection` to ensure that the index of all predictions has the same order
- Modified the tests to catch incorrect item …
> Fix item order in GluonTS models predictions

- timeseries/src/autogluon/timeseries/utils/seasonality.py
- timeseries/tests/unittests/models/test_statsmodels.py
Set the period of daily time series to 7, replacing the original default 1 inherited from GluonTS.
> Fix timeseries daily frequency inferred period

- timeseries/src/autogluon/timeseries/dataset/ts_dataframe.py
- timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
- timeseries/src/autogluon/timeseries/splitter.py
- timeseries/tests/unittests/test_ts_dataset.py
- `TimeSeriesDataFrame.slice_by_timestep` now accepts `(start_index: Optional[int] = None, end_index: Optional[int] = None)` as input instead of a `slice` object.  
- Passing a `slice` object is still supported; a deprecation warning is made in this case.
- `TimeSeriesDataFrame.subsequence` is renamed to `TimeSeriesDataFrame.slice_by_time`, old method is deprecated
> Clean up the TimeSeriesDataFrame public API

- timeseries/src/autogluon/timeseries/models/__init__.py
- timeseries/src/autogluon/timeseries/models/gluonts/__init__.py
- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- timeseries/src/autogluon/timeseries/models/gluonts/models.py
- timeseries/src/autogluon/timeseries/models/presets.py
- timeseries/tests/unittests/models/test_gluonts.py
- timeseries/tests/unittests/models/test_models.py
Thanks to Lorenzo's fix from https://github.com/awslabs/gluon-ts/issues/2264  we can add TFT to AutoGluon (the model should work both on CPU and GPU).
- Add `TemporalFusionTransformerModel` to `timeseries.models`, wrapping `TemporalFusionTransformerEstimator` from GluonTS.
The model will be added to the default presets later after we complete benchmarking.
> Add TemporalFusionTransformer time series model

- tabular/src/autogluon/tabular/models/xgboost/hyperparameters/searchspaces.py
Tested on adult dataset and saw that 50 trials with old config 0/50 were able to get better test score than default. 10/50 trials were able to beat default with new config. Until we do more testing with HPO, it is better to have simple search spaces as it avoids wasting most trials due to a poor hyperparameter value being present in a trial. This change aligns XGBoost search space with LightGBM search space in terms of complexity.
(Side note: @yinweisu this old search space is maybe why you saw parallel HPO was worse for trees, because it didn't use the default config during HPO and that was stronger than the vast majority of random configs.) …
> Simplify XGBoost HPO search space to be stronger with fewer trials

- core/src/autogluon/core/hpo/executors.py
- core/src/autogluon/core/hpo/ray_hpo.py
- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/models/abstract/model_trial.py
- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- core/src/autogluon/core/models/ensemble/fold_fitting_strategy.py
- core/src/autogluon/core/ray/resources_calculator.py
- core/src/autogluon/core/trainer/abstract_trainer.py
- tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
- tabular/tests/unittests/test_tabular.py
* Update bagging hpo logic to be training each bag as a trial, and the underneath trial will then train folds in parallel.
* With the above setting, models using ray tune can do parallel folds within parallel trials.
* Example of new logic output:
```bash
Fitting 3 L1 models ...
Hyperparameter tuning model: LightGBM_BAG_L1 ... Tuning model for up to 44.96s of the 49.95s of remaining time.
0%|                                                                                                                | 0/4 [00:00<?, ?it/s]Fitting 2 child models (S1F1 - S1F2) | Fitting with ParallelLocalFoldFittingStrategy
25%|██████████████████████████                                                                              | 1/4 [00:03<00:11, …
```
> Tabular Bagging HPO Logic Update

- examples/automm/kaggle_feedback_prize/README.md
- examples/automm/kaggle_feedback_prize/kaggle_feedback_prize_preprocess.py
- examples/automm/kaggle_feedback_prize/kaggle_feedback_prize_submit.py
- examples/automm/kaggle_feedback_prize/kaggle_feedback_prize_train.py
This PR provides a working example of applying normalization to text prediction tasks such as the [Predicting Effective Arguments Competition](https://www.kaggle.com/competitions/feedback-prize-effectiveness) in Kaggle. 
> Add Kaggle normalization example

- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/utils.py
- multimodal/tests/unittests/test_predictor_advanced.py
1. Decouple weight sharing in checkpoint averaging. Convert weights to float64 to improve averaging robustness.
2. Refactor previous `create_model` into `create_model` and `create_fusion_model` to improve modularization. `create_model` is only in charge of creating a single model, which will be used in creating models in the siamese matcher.
> Improve averaging checkpoints and creating model

- multimodal/src/autogluon/multimodal/data/datamodule.py
- multimodal/src/autogluon/multimodal/predictor.py
Make sure data is shuffled automatically in the single-gpu training.
> Fix data shuffling for 1-gpu training

- core/src/autogluon/core/hpo/ray_hpo.py
- core/src/autogluon/core/hpo/ray_tune_searcher_factory.py
https://github.com/awslabs/autogluon/issues/2068
* Added the ability to use default hyperparameter when doing HPO with ray tune.
Example log with `NN_TORCH` and `FASTAI`, which use ray tune as backend. You can see default hyperparameters are correctly used by the single trial. Not shown by the log but same applies to multiple trials, where the first trial would use the default hyperparameters.
```python
Fitting 2 L1 models ...
Hyperparameter tuning model: NeuralNetFastAI ... Tuning model for up to 44.96s of the 99.9s of remaining time.
(model_trial pid=14381) {'layers': None, 'emb_drop': 0.1, 'ps': 0.1, 'bs': 256, 'lr': 0.01, 'epochs': 30, 'early.stopping.min_delta': 0.0001, 'early.stopping.patience': 20, 'smoothing': 0.0}
Fitted model: …
```
> Enable Default Hyperparamenter with Ray Tune

- timeseries/src/autogluon/timeseries/evaluator.py
The current implementation of TimeSeriesEvaluator is rather slow because of a for loop over individual time series. This was especially damaging for the `WeightedEnsemble`, where we need to re-compute the metrics multiple times each iteration.
- Vectorize all metric computations using `pandas.groupby`.
With this PR, fitting time for `WeightedEnsemble` in the quickstart tutorial went from 207s to 13.5s. There were also minor speedups of `prediction runtime` for all models, as this time includes metric computation. Expand details for full comparison (p3.8xlarge).
<details>
Old version
```
Training timeseries model ETS.
-0.3132       = Validation score (-MAPE)
7.82    s     = Training runtime
1.13    s     = Validation (prediction) runtime
Training timeseries model …
```
> Speed up TimeSeriesEvaluator

- .github/workflows/continuous_integration.yml
* Added the ability to detect if changes are only made to files under `docs/`. If so, we'll skip unit test and build website directly. This should make doc site only changes to iterate much quicker.
* Changes won't take effect until merging in and cannot be tested within this PR because this PR involves changes outside `docs/`. Tried it on my fork with minimized examples, where **lint check** should not build on aws if there are only doc changes and **temp** should always be executed(like build docs): 
1. changes outside doc: https://github.com/yinweisu/autogluon/actions/runs/3101782203. Lint check build on aws and temp triggered
2. changes under doc only: https://github.com/yinweisu/autogluon/actions/runs/3101784234. Lint check skipped …
> [CI] Add Path Check for Docs

- multimodal/src/autogluon/multimodal/data/dataset.py
- multimodal/src/autogluon/multimodal/data/utils.py
- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/utils.py
This PR is to modularize some logic shared by the realtime inference and dataloader. This modularization can also benefit the ONNIX export by @FANGAreNotGnu.
1. Add util `apply_df_preprocessor` shared by the realtime inference and dataloader.
2. Add util `apply_data_processor` shared by the realtime inference and dataloader.
3. Add util `infer_batch` for realtime inference.
> Modularize realtime inference

- timeseries/src/autogluon/timeseries/evaluator.py
- Fixes a minor bug introduced in #2147, where the metrics can become `NaN` if the dataset contains constant time series.
> Avoid division by zero errors in TimeSeriesEvaluator

- CI/batch/submit-job.py
* Observed throttling issue when `submit-job` script calling batch apis https://github.com/awslabs/autogluon/actions/runs/3107583630/jobs/5036849384. Increase retry limit to ease the issue.
> Fix CI Throttling

- multimodal/src/autogluon/multimodal/models/utils.py
- multimodal/src/autogluon/multimodal/optimization/lit_module.py
- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/utils.py
Add `model_postprocess_fn` to process the model output for inference. This is to handle the cases where the training loss function includes some operations that are also required to transform predictions in inference. For example, if we use the `nn.BCEWithLogitsLoss` on a regression task, we need to use sigmoid to transform the logits in inference.
> Add the model post-processing function

- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- core/src/autogluon/core/trainer/abstract_trainer.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- Moved calibration method from predictor to trainer
- Removed temperature_scalar attribute from AbstractModel, moved to params_aux so it can propagate correctly to refit_full models.
- No functional change except that now refit model will inherit the temperature scaling term from the parent (this is good, previously it was not inherited which caused inconsistency between settings which applied calibration prior to refitting and after refitting). No impact to presets, only if user manually called refit_full.
> Cleanup Temperature Scaling code

- cloud/src/autogluon/cloud/job/sagemaker_job.py
- cloud/src/autogluon/cloud/predictor/cloud_predictor.py
- cloud/src/autogluon/cloud/scripts/train.py
- cloud/src/autogluon/cloud/utils/ag_sagemaker.py
This PR enable CloudPredictor to skip repacking step when doing batch inference and deployment. This could save a lot of time when the model artifact is large and the network speed is slow
* Adding inference script into model artifacts to avoid repack it with model afterwards.
* Instead of using `MxnetModel` implementation, now we inherit from `Model`. Also updated estimator to inherit from base `Estimator` instead of `Framework`
> [Cloud] Cloud Batch Inference Optimization

- core/src/autogluon/core/trainer/abstract_trainer.py
- core/src/autogluon/core/utils/infer_utils.py
- tabular/src/autogluon/tabular/learner/abstract_learner.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/tests/conftest.py
- tabular/tests/unittests/models/test_cascade.py
- Updated version of #1682
The goal of a cascade ensemble is to expand the Accuracy - Inference Latency Pareto Frontier by finding a middle ground between single models and full ensembles that gets the majority of the accuracy improvement of ensembles combined with the majority of the inference speed of single models.
Currently, usage / existence of cascade ensemble support is not user-facing. It will be documented once it has been further tested and optimized. Currently the cascade threshold is fixed at 0.9 and the cascade must be manually defined. Next steps are to automatically define the cascade and the thresholds.
The below example script shows how to use cascades to get 80% of the log loss improvement (97% of the accuracy …
> Added cascade ensemble foundation logic

- docs/install-include.rst
- docs/tutorials/tabular_prediction/tabular-interpretability.md
- tabular/src/autogluon/tabular/models/imodels/imodels_models.py
#2107 
- Fixed missing init of `self._ohe`.
- Improved documentation clarity on how to install and use imodels.
> Fixed bug in imodels when no categorical features

- multimodal/src/autogluon/multimodal/constants.py
- multimodal/src/autogluon/multimodal/data/datamodule.py
- multimodal/src/autogluon/multimodal/data/process_image.py
- multimodal/src/autogluon/multimodal/data/utils.py
- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/utils/__init__.py
- multimodal/src/autogluon/multimodal/utils/data.py
- multimodal/src/autogluon/multimodal/utils/environment.py
- multimodal/src/autogluon/multimodal/utils/inference.py
- multimodal/tests/unittests/test_object_detection.py
- multimodal/tests/unittests/test_text_detection.py
- multimodal/tests/unittests/test_text_recognition.py
1. Move the `per_gpu_batch_size ` from image processor initialization to `get_collate_fn()`. In this way, batch size no longer needs to bound with image processor, which allows dynamic batch size in inference. 
2. Add `MMCV_MODELS` constant. We could put all the mmcv models here.
3. Improve the precision context manager.
4. Consider batch size in determining whether to use the realtime inference.
> Fix realtime inference for mmcv models

- multimodal/setup.py
* https://github.com/awslabs/autogluon/actions/runs/3195498402/jobs/5216230879
macos doesn't have the required onnx package; therefore, add platform check to avoid installing it on macos
@FANGAreNotGnu Feel free to update this PR to add necessary warning or try import onnx functionality in case user tries to export onnx on a mac but onnx is not installed
> Remove ONNX Install on Macos

- multimodal/setup.py
- multimodal/tests/unittests/test_hpo.py
Lightning 1.7 seems not fully compatible with ray tune, which causes the AutoMM HPO tests to get stuck. Temporarily skip the AutoMM HPO tests. Need to investigate how to make ray tune or ray lightning work with lightning 1.7.  
> Temporarily skip AutoMM HPO tests (lightning 1.7)

- docs/tutorials/timeseries/forecasting-indepth.md
- docs/tutorials/timeseries/forecasting-quickstart.md
- timeseries/src/autogluon/timeseries/configs/presets_configs.py
- timeseries/src/autogluon/timeseries/models/presets.py
- timeseries/src/autogluon/timeseries/models/statsmodels/models.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/src/autogluon/timeseries/trainer/auto_trainer.py
- timeseries/tests/unittests/test_learner.py
- timeseries/tests/unittests/test_predictor.py
- Update `default` and `default_hpo` hyperparameter configurations
- Remove `high_quality` and `good_quality` presets for time series (these were rather meaningless, only changing the # of random search runs in HPO)
- Rename `low_quality` -> `fast_training` that now only contains local models
> Deprecate high, good and low quality presets for time series

- core/src/autogluon/core/models/abstract/abstract_model.py
- timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
- timeseries/src/autogluon/timeseries/models/presets.py
- timeseries/src/autogluon/timeseries/trainer/abstract_trainer.py
- timeseries/tests/unittests/test_predictor.py
- Simplifies the logic for constructing the hyperparameter dict
- Fixes a bug where the HPO space was incorrectly bigger than the user-specified HPO space
- Enable training with fixed configs (some models have HP search spaces while others have fixed HPs)
For example the code below now only does HPO on the `num_cells` parameters.
```python
import autogluon.core as ag
TimeSeriesPredictor().fit(
data,
hyperparameters={
"DeepAR": {"num_cells": ag.space.Categorical(10, 20)},
},
hyperparameter_tune_kwargs="random",
```
Before the same code used to do HPO on all hyperparameters of DeepAR specified in the `default_hpo` dict.
> Fix hyperparameter overloading in HPO for time series models

- docs/tutorials/multimodal/semantic_search.md
The Multimodal tutorials were taking a bit long to run, and the bottleneck is embedding extraction, which doubles that of bm25 scoring time. We can speed up bm25 after `gensim`'s next release.
CI time prior to this tutorial: 51m
https://github.com/awslabs/autogluon/actions/runs/3162536464/jobs/5149621835
CI time after creating the semantic search tutorial: 60m
https://github.com/awslabs/autogluon/actions/runs/3206902710/jobs/5241212884
CI time with this PR: 53m
https://github.com/awslabs/autogluon/actions/runs/3262724015/jobs/5360313191
By sampling 1/5 of the dataset, we get to demonstrate the same trend(improvements) as before, but save around 10% in CI time. …
> speed up semantic search tutorial

- timeseries/src/autogluon/timeseries/splitter.py
- timeseries/tests/unittests/test_splitter.py
Some models (e.g. DeepAR) expect training time series to have at least `prediction_length + 1` time steps. This constraint was violated by the old implementation of the `MultiWindowSplitter`, which led to GluonTS models failing. 
- `MultiWindowSplitter` now ensures that no training time series gets cut shorter than `prediction_length + 1` (but if the original series already was shorter, it stays that way).
- Removed the `overlap` parameter from `MultiWindowSplitter` as it wasn't used, but unnecessarily complicates the logic.
- Improved exception message & tests.
> Make sure that time series splitter doesn't trim training series shorter than prediction_length + 1

- .github/workflow_scripts/env_setup.sh
- .github/workflow_scripts/test_eda.sh
- eda/setup.py
- eda/src/autogluon/eda/analysis/__init__.py
- eda/src/autogluon/eda/analysis/base.py
- eda/src/autogluon/eda/analysis/dataset.py
- eda/src/autogluon/eda/auto/__init__.py
- eda/src/autogluon/eda/auto/simple.py
- eda/src/autogluon/eda/state.py
- eda/src/autogluon/eda/visualization/__init__.py
- eda/src/autogluon/eda/visualization/base.py
- eda/src/autogluon/eda/visualization/layouts.py
- eda/tests/conftest.py
- eda/tests/unittests/analysis/test_base.py
- eda/tests/unittests/analysis/test_dataset.py
- eda/tests/unittests/auto/test_simple.py
- eda/tests/unittests/test_state.py
- eda/tests/unittests/visualization/test_base.py
Added `Sampler` wrapper
```python
from autogluon.eda.analysis import Sampler
from autogluon.eda.analysis.base import BaseAnalysis
analysis = BaseAnalysis(train_data=df_train, test_data=df_test, children=[
Sampler(sample=5, children=[
])
])
```
`auto.analyze()` shortcut allows quickly define a fit-render pipeline and add sampling if needed
```python
state = auto.analyze(
train_data=df_train, label=target_col, return_state=True,
anlz_facets=[
eda.dataset.DatasetSummary(),
eda.dataset.RawTypesAnalysis(),
eda.dataset.VariableTypeAnalysis(),
eda.dataset.SpecialTypesAnalysis(),
eda.missing.MissingValuesAnalysis(),
],
viz_facets=[
viz.dataset.DatasetStatistics()
]
)
```
By submitting this pull request, I confirm that you can use, …
> [EDA] Added Sampler and analyze loop shortcut

- core/src/autogluon/core/hpo/executors.py
- core/src/autogluon/core/searcher/searcher_factory.py
- timeseries/src/autogluon/timeseries/models/abstract/model_trial.py
- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- timeseries/src/autogluon/timeseries/models/gluonts/models.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/src/autogluon/timeseries/trainer/abstract_trainer.py
- timeseries/tests/unittests/models/test_models.py
- timeseries/tests/unittests/test_learner.py
- timeseries/tests/unittests/test_trainer.py
- Use Ray Tune as default HPO backend for GluonTS models. We don't use Ray for other models (e.g., local models from Statsmodels) since 
1. their searchspace is just a grid
2. they don't benefit from being trained in parallel
3. they are deterministic, so always training `num_trials` models with repeated hyperparameters (as done by Ray) doesn't make sense.
- Update HPO results reporting logic in `abstract_trainer.py`
- Update `searcher` mapping in `autogluon.core`
*To do:*
> Enable Ray Tune backend for time series models

- tabular/src/autogluon/tabular/models/xgboost/xgboost_model.py
Removing deprecated eval_metric from fit - causing segfaults on M1 w/ xgboost 1.4.2
> [M1] Removing deprecated eval_metric from fit - causing segfaults on M1 w/ xgboost 1.4.2

- docs/tutorials/multimodal/index.rst
- docs/tutorials/multimodal/ner.md
- multimodal/src/autogluon/multimodal/data/infer_types.py
- multimodal/src/autogluon/multimodal/data/labelencoder_ner.py
- multimodal/src/autogluon/multimodal/data/utils.py
- multimodal/src/autogluon/multimodal/predictor.py
1. Add a tutorial for NER.
2. The seqeval lib will remove the first two characters for non-BIO format and cause non-readable result report, [issue](https://github.com/chakki-works/seqeval/issues/75). We fix it be adding prefix 'b-' or 'i-'.
3. Fix output shape inconsistency in continuous training.
4. Convert labels/metrics to lowercase.
> Add tutorial and fix issues for NER 

- tabular/src/autogluon/tabular/models/rf/rf_quantile.py
- Replace for loops over samples with vectorized code / pandas operations to speed up training and prediction time.
- Minor fixes to `tabular/models/rf/rf_quantile.py` (e.g., remove unused parameters from docstrings)
Runtime comparison:
Attached is a Jupyter notebook that runs a sanity check ensuring that both old and new versions produce identical results & generates runtime plots. [compare_rf_quantile.zip](https://github.com/awslabs/autogluon/files/9764286/compare_rf_quantile.zip)
> Speed up RandomForestQuantileRegressor and ExtraTreesQuantileRegressor

- timeseries/src/autogluon/timeseries/__init__.py
- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- timeseries/src/autogluon/timeseries/models/statsmodels/__init__.py
- timeseries/src/autogluon/timeseries/models/statsmodels/abstract_statsmodels.py
- timeseries/src/autogluon/timeseries/utils/warning_filters.py
- Fix statsmodels warning output, which made the logs/stdout unusable
- Fix gluonts tqdm, where our monkeypatch stopped working after the bump (?)
- Fix mxnet warning text
> Fix timeseries warnings and tqdm output

- tabular/src/autogluon/tabular/learner/default_learner.py
Added `Platform Machine` and `Platform Version` logging for initial autogluon debug info logging (see last 2 lines below).
```
Beginning AutoGluon training ...
AutoGluon will save models to "agModels-predictClass/"
AutoGluon Version:  0.5.3b20221020
Python Version:     3.9.13
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000
```
> Added platform machine and version logging

- common/src/autogluon/common/utils/log_utils.py
- core/src/autogluon/core/__init__.py
- tabular/src/autogluon/tabular/__init__.py
- timeseries/src/autogluon/timeseries/__init__.py
- timeseries/tests/unittests/models/test_sktime.py
- timeseries/tests/unittests/models/test_statsmodels.py
* Updated the logger logic so that we only modify autogluon module level logger instead of the root logger.
* Also fix the autogluon logging format issue on colab. For some context, Colab started to setup the root handler by default. Our method of setting the root logger doesn't work without `force` flag. The new method doesn't have this problem with `propagate` set to false
> Avoid Modify Root Logger

- tabular/src/autogluon/tabular/predictor/predictor.py
#2252
- Fix incorrect reference to `hyperparameter_tune`
> Fix incorrect reference to `hyperparameter_tune`

- multimodal/src/autogluon/multimodal/models/ft_transformer.py
- multimodal/src/autogluon/multimodal/optimization/utils.py
1. According to the code from [FT_Transformer authors](https://github.com/puhsu/tabular-dl-pretrain-objectives/blob/master/lib/deep.py#:~:text=def%20default_zero_weight_decay_condition(module_name%2C%20module%2C%20parameter_name%2C%20parameter)%3A), tokenizers should be free from weight decay.  Worked slightly better on classification tasks (57% win rate).
2. Additive attention always init bias with zeros.
> always init bias with zeros and free tokens from weight decay

- core/src/autogluon/core/metrics/__init__.py
- core/src/autogluon/core/metrics/classification_metrics.py
- core/src/autogluon/core/trainer/abstract_trainer.py
- core/tests/unittests/metrics/test_classification_metrics.py
- core/tests/unittests/metrics/test_metric_kwargs.py
- core/tests/unittests/metrics/test_metrics.py
- docs/tutorials/tabular_prediction/tabular-custom-metric.md
- tabular/src/autogluon/tabular/learner/abstract_learner.py
- Add scorer error calculation via `Scorer.error`
- Majorly cleaned up scorer API, improved documentation
- Improved custom metric tutorial
- Added unit tests for scorer.optimum, we now confirm via unit tests that the optimum value for all metrics is set correctly, along with the `greater_is_better` flag. (No bugs in metrics found via this PR, so it appears our metrics are correctly implemented already)
- Fixed NeuralNetTorch using incorrect sign in HPO reporter for lower_is_better native metrics like log_loss and RMSE. This caused Bayesian Optimization and Hyperband to search poorly for NeuralNetTorch. Also fixed this issue for MXNet version of autogluon.text and Tabular's NeuralNetMXNet. (Fixed by correcting `Scorer.greater_is_better`) …
> Add Scorer error calculation plus code cleanup

- eda/setup.py
- eda/src/autogluon/eda/__init__.py
- eda/src/autogluon/eda/analysis/__init__.py
- eda/src/autogluon/eda/analysis/base.py
- eda/src/autogluon/eda/analysis/dataset.py
- eda/src/autogluon/eda/analysis/transform.py
- eda/src/autogluon/eda/state.py
- eda/tests/conftest.py
- eda/tests/unittests/analysis/test_transform.py
Applies `FeatureGenerator` and shadows outer scope with transformed data. This is needed for analysis like correlation since it requires numeric features. If `category_to_numbers` is `True` then categories will be translated into `cat.code`
```python
analysis = BaseAnalysis(train_data=df_train, test_data=df_test, label=target_label, children=[
ApplyFeatureGenerator(category_to_numbers=True, children=[
]),
])
```
> [eda] Added ApplyFeatureGenerator

- timeseries/src/autogluon/timeseries/models/autogluon_tabular/tabular_model.py
- timeseries/src/autogluon/timeseries/models/presets.py
- timeseries/tests/unittests/models/test_models.py
- This PR significantly speeds up training and prediction time for `AutoGluonTabularModel`. Internally, we now treat forecasting as a regression problem, and estimate the quantiles by fitting a zero-mean normal distribution to the residuals.
- Besides being much faster, the new model achieves significantly improved predictive accuracy of point forecasts on some datasets (e.g., `walmart`).
> Use regression problem type inside AutoGluonTabular forecasting model

- docs/tutorials/timeseries/forecasting-indepth.md
- timeseries/src/autogluon/timeseries/predictor.py
- Add a `DeprecationWarning` if `quantile_levels` are passed at prediction time.
- Update in-depth tutorial to reflect this change.
> Deprecate passing quantile_levels to TimeSeriesPredictor.predict

- multimodal/src/autogluon/multimodal/data/infer_types.py
`warnings.warning` is not supported, this PR updates to `warnings.warn` to fix training.
> fix warning method

- eda/setup.cfg
- eda/setup.py
- eda/src/autogluon/eda/analysis/base.py
- eda/src/autogluon/eda/analysis/dataset.py
- eda/src/autogluon/eda/analysis/shift.py
- eda/src/autogluon/eda/auto/simple.py
- eda/src/autogluon/eda/state.py
- eda/src/autogluon/eda/visualization/__init__.py
- eda/src/autogluon/eda/visualization/dataset.py
- eda/src/autogluon/eda/visualization/jupyter.py
- eda/tests/unittests/analysis/test_dataset.py
- eda/tests/unittests/auto/test_simple.py
- eda/tests/unittests/test_shift.py
- eda/tests/unittests/visualization/test_dataset.py
Dataset-level summary tooling. The output is a composite of a few analysis types. They can be present in any combination (assuming all the dependencies are satisfied: `VariableTypeAnalysis` requires `RawTypesAnalysis` to be present)
```python
state = auto.analyze(
train_data=df_train, label=target_col, return_state=True,
anlz_facets=[
eda.dataset.DatasetSummary(),
eda.dataset.RawTypesAnalysis(),
eda.dataset.VariableTypeAnalysis(),
eda.dataset.SpecialTypesAnalysis(),
],
viz_facets=[
viz.dataset.DatasetStatistics()
]
)
```
Output example:
---
Display mismatch between raw types between datasets provided. In case if mismatch found, mark the row with a warning.
```python
auto.analyze(
train_data=df_train, test_data=df_test,
anlz_facets=[ …
```
> [eda] Dataset summary analysis

- .gitignore
- timeseries/src/autogluon/timeseries/learner.py
- timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- timeseries/src/autogluon/timeseries/models/gluonts/mx/models.py
- timeseries/src/autogluon/timeseries/models/gluonts/torch/models.py
- timeseries/src/autogluon/timeseries/models/local/models.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/src/autogluon/timeseries/trainer/abstract_trainer.py
- timeseries/src/autogluon/timeseries/utils/features.py
- timeseries/src/autogluon/timeseries/utils/forecast.py
- timeseries/tests/unittests/common.py
- timeseries/tests/unittests/models/gluonts/mx/test_mx.py
- timeseries/tests/unittests/models/gluonts/test_gluonts.py
- timeseries/tests/unittests/test_learner.py
- timeseries/tests/unittests/test_predictor.py
- timeseries/tests/unittests/test_splitter.py
- Add `known_covariates_names` argument to `TimeSeriesPredictor` that contains the names of the columns in `TimeSeriesDataFrame` that are known at prediction time
- Add logic for checking & preprocessing the known covariates inside `TimeSeriesLearner`
- Add `known_covariates` argument to `TimeSeriesPredictor.predict` and `AbstractTimeSeriesModel.predict`. This argument contains the values of the known covariates during the forecast horizon
- Use the known covariates during training & prediction in `DeepARModel`, `DeepARMXNetModel`, `MQCNNMXNetModel` and `TemporalFusionTransformerMXNetModel`.
*To do:*
> Enable time-varying covariates (dynamic features) in time series models

- eda/src/autogluon/eda/analysis/__init__.py
- eda/src/autogluon/eda/analysis/missing.py
- eda/src/autogluon/eda/visualization/__init__.py
- eda/src/autogluon/eda/visualization/dataset.py
- eda/src/autogluon/eda/visualization/missing.py
- eda/tests/unittests/analysis/test_missing.py
- eda/tests/unittests/visualization/test_missing.py
This change introduces missingness analysis for datasets.
See also: [missingno github](https://github.com/ResidentMario/missingno)
```python
state = auto.analyze(
train_data=df_train, label=target_col, return_state=True,
anlz_facets=[
eda.dataset.DatasetSummary(),
eda.missing.MissingValuesAnalysis(),
],
viz_facets=[
viz.dataset.DatasetStatistics(),
viz.missing.MissingValues(graph_type='matrix'),
viz.missing.MissingValues(graph_type='bar'),
viz.missing.MissingValues(graph_type='heatmap'),
viz.missing.MissingValues(graph_type='dendrogram'),
]
)
```
nullity matrix is a data-dense display which lets you quickly visually pick out patterns in data completion. This visualization will comfortably accommodate up to 50 labelled variables. Past that range labels begin to …
> [eda] Missingness analysis

- timeseries/src/autogluon/timeseries/models/sktime/__init__.py
- Small missing safeguard for timeseries sktime module
Tested in isolated envs with and without sktime.
> add import error to timeseries sktime module

- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- timeseries/src/autogluon/timeseries/models/gluonts/mx/models.py
- timeseries/src/autogluon/timeseries/models/gluonts/torch/models.py
set DeepAR to 250 samples (2.2x slowdown in benchmarks)
> [timeseries] Increase the number of samples used by DeepAR at prediction time

- timeseries/src/autogluon/timeseries/models/autogluon_tabular/tabular_model.py
- timeseries/tests/unittests/models/test_autogluon_tabular.py
- Static features are added to the features dataframe, if available in TimeSeriesDataFrame
- Clean up typos in the tests
> Use static features in AutoGluonTabularModel forecasting model

- timeseries/src/autogluon/timeseries/learner.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/src/autogluon/timeseries/utils/random.py
- timeseries/tests/unittests/test_learner.py
- Add optional argument `random_seed` to `TimeSeriesPredictor.fit` and `TimeSeriesPredictor.predict`. This ensures that predictions for sampling-based models are now deterministic.
- Remove the `random_state` argument to `TimeSeriesLearner`.
> [timeseries] Fix random seed in TimeSeriesPredictor

- timeseries/src/autogluon/timeseries/models/autogluon_tabular/tabular_model.py
- timeseries/tests/unittests/models/test_autogluon_tabular.py
- Remove memory (and disk) heavy models RF, XT
- Mostly use the RMSE metric as it doesn't have a failure mode for datasets with target close to 0 (as MAPE)
- Limit the training set size
- Use batched prediction to limit memory usage
> [timeseries] Use mini-batch prediction for tabular forecasting model

- tabular/setup.py
For macOS, there isn't a onnxruntime-gpu package installed with skl2onnx.
Therefore, we install onnxruntime explicitly here just for macOS.
> [Tabular][Bugfix] fix onnxruntime dependency problem for macosx

- multimodal/setup.py
- multimodal/src/autogluon/multimodal/utils/metric.py
We removed the dependency on pytrec_eval and rewrite the information retrieval metrics including: precision, recall, ndcg, map, and mrr, with given cutoff values.
> Remove pytrec_eval and rewrite retrieval metrics

- timeseries/src/autogluon/timeseries/models/ensemble/greedy_ensemble.py
- timeseries/src/autogluon/timeseries/trainer/abstract_trainer.py
- timeseries/tests/unittests/test_trainer.py
- Currently, if one of the base models for the ensemble fails, the ensemble can `predict` but cannot `score`. This PR fixes this problem and adds tests covering such cases.
> [timeseries] Make WeightedEnsemble robust to base model failures

- docs/tutorials/multimodal/efficient_finetuning_basic.md
- docs/tutorials/multimodal/index.rst
- multimodal/setup.py
- multimodal/src/autogluon/multimodal/configs/model/fusion_mlp_image_text_tabular.yaml
- multimodal/src/autogluon/multimodal/models/huggingface_text.py
- multimodal/src/autogluon/multimodal/models/t_few.py
- multimodal/src/autogluon/multimodal/models/utils.py
- multimodal/src/autogluon/multimodal/utils/model.py
- multimodal/tests/unittests/test_predictor_advanced.py
[FLAN-T5](https://arxiv.org/abs/2210.11416) was released by Google. The model has been pretrained on a wide collection of tasks, and is performing very well on downstream applications. In this PR, we are adding FLAN-T5 in the test case of efficient finetuning and also change the backbone in our efficient finetuning tutorial as FLAN-T5.
Usually, loading the pytorch model will need you to 1) initialize the weight matrices, 2) load the pretrained model, and 3) overwrite the initialized matrices with the pretrained weights. Via the “low_cpu_mem_usage” flag, it will initialize the model into "meta device" that is available at pytorch 1.9. Meta tensors are just normal tensors without carrying out any memory. See the [related …
> Change backbone used in efficient finetuning tutorial to FLAN-T5 + Add flag for lowering peak CPU usage of large LMs.

- tabular/src/autogluon/tabular/models/automm/automm_model.py
- Disable parallel bagging with AutoMM
- It appears that parallel bagging with AutoMM hangs the process. Reverting to using sequential bagging which does work correctly.
> Disable parallel bagging with AutoMM

- tabular/src/autogluon/tabular/models/automm/automm_model.py
- Fixed a major bug causing the outer context to be altered when Tabular AutoMM model concatenates the label to the features. This caused future models to either crash or have the label in their training and validation data features.
> Fix AutoMM Tabular altering outer context

- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- timeseries/src/autogluon/timeseries/models/gluonts/mx/models.py
- timeseries/src/autogluon/timeseries/models/gluonts/torch/models.py
- We save the lightning logs `self.path / "lightning_logs"`. This folder gets deleted up after training. Now training PyTorch models doesn't produce a `lightning_logs` folder in the directory from where the script was run. 
- Perform all hyperparameter updates for all models in `_get_estimator_init_args` (some models did this inside `_get_estimator`).
> [timeseries] Save lightning_logs to model directory when training PyTorch models & clean up after training

- multimodal/src/autogluon/multimodal/models/utils.py
- multimodal/tests/unittests/test_auto_model.py
The current assigning layer ids logic can't handle all kinds of backbones. This PR is to support using the uniform layer ids for these backbones.
> Support fallback layer ids

- timeseries/src/autogluon/timeseries/learner.py
- timeseries/src/autogluon/timeseries/utils/forecast.py
- Make sure the `static_feature_pipeline` is applied also during `leaderboard` and `score` calls
- Fix a small bug in `get_forecast_horizon_index_ts_dataframe` when `item_id` is a string (not int)
> [timeseries] Fix several minor bugs in TimeSeriesLearner related to static_features handling

- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- timeseries/src/autogluon/timeseries/models/gluonts/torch/models.py
- Cache the transformation results & use GPU acceleration in PyTorch models if `torch.cuda.is_available()`. This leads to much faster training. For example, training time for DeepAR (PyTorch) on the `m4_yearly` dataset on `p3.8xlarge`:
- CPU, `cache_data=False`: 748s
- CPU, `cache_data=True`: 340s
- GPU, `cache_data=True`: 60s
- This doesn't lead to problems with other models. I re-ran the benchmark with this setting, all models complete training without crashing.
> [timeseries] Enable GPU and transform caching for GluonTS models

- timeseries/src/autogluon/timeseries/dataset/ts_dataframe.py
- timeseries/src/autogluon/timeseries/learner.py
- timeseries/src/autogluon/timeseries/models/autogluon_tabular/tabular_model.py
- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/src/autogluon/timeseries/splitter.py
- timeseries/src/autogluon/timeseries/utils/forecast.py
- timeseries/tests/unittests/test_learner.py
- Correctly handle the case when `ignore_time_index=True` and `known_covariates` are used by the predictor.
- Several minor updates to the `TimeSeriesPredictor` docstrings.
- Fix warnings emitted by the `TabularPredictor` inside `AutoGluonTabularModel`.
> [timeseries] Enable prediction with known_covariates when ignore_time_index=True

- core/src/autogluon/core/metrics/classification_metrics.py
#2318
Follow-up to #2318, speed up by an additional 25% by only performing the index optimization logic if the number of rows is >100K.
Benchmark:
```python3
import numpy as np
import sklearn
from autogluon.core.metrics import roc_auc, make_scorer
import time
roc_auc_sklearn = make_scorer('roc_auc',
sklearn.metrics.roc_auc_score,
greater_is_better=True,
needs_threshold=True)
for sample_size in [
10,
100,
1000,
10000,
100000,
]:
y_true = np.random.randint(low=0, high=2, size=sample_size)
y_score = np.random.random_sample(sample_size)
print(f'### sample_size={sample_size} ###')
ts = time.time()
for i in range(1000):
expected_score = roc_auc_sklearn(y_true, y_score)
te = time.time()
print(f'Sklearn: {round(te-ts, 2)}ms')
ts = time.time()
for …
```
> Speed up roc_auc_scorer by 25%

- tabular/src/autogluon/tabular/predictor/predictor.py
- `quantile_levels` is unused in fit call, it is specified in init.
- Clarified error message when user specifies unknown fit arg.
> Removed unused fit argument `quantile_levels`.

- core/src/autogluon/core/metrics/__init__.py
#2306
- Convert to float64 to avoid rounding error on the clip operation with epsilon
- float32 would not have enough granularity to handle the epsilon which would cause divide by zero warnings.
> Update log_loss to convert to float64

- tabular/src/autogluon/tabular/learner/default_learner.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- Fixed bug caused by tuning_data having a different dtype in the label column than train_data, which caused a crash due to holdout_frac being incorrectly specified. Now we correctly discard the tuning_data and split the train_data.
- Improved warning message when this scenario occurs so it is easier to understand.
Example updated output in this scenario:
```
No path specified. Models will be saved in: "AutogluonModels/ag-20221108_223519/"
WARNING: train_data and tuning_data have mismatched label column dtypes! train_label_type=object, tuning_data_type=int64.
You should ensure the dtypes match to avoid bugs or instability.
AutoGluon will attempt to convert the dtypes to align.
Beginning AutoGluon training ...
AutoGluon will save models to …
```
> Fix crash when tuning_data label dtype is invalid

- docs/tutorials/image_prediction/beginner.md
- docs/tutorials/multimodal/image_prediction/beginner_image_cls.md
- docs/tutorials/multimodal/multimodal_prediction/beginner_multimodal.md
- docs/tutorials/multimodal/text_prediction/beginner_text.md
- docs/tutorials/object_detection/beginner.md
- docs/tutorials/tabular_prediction/tabular-quickstart.md
- docs/tutorials/text_prediction/beginner.md
https://github.com/awslabs/autogluon/issues/2138
* Add load warning banners to the appearance of load in our quick start tutorials of each modality.
Example:
> [Doc] [Security] Add Warning Banners for Load

- multimodal/src/autogluon/multimodal/presets.py
NA
Add new presets for image classification, no HPO involved for now
1. best_quality_image_classification
2. high_quality_fast_inference_image_classification
3. medium_quality_faster_inference_image_classification
> Add presets in AutoMM for vision

- docs/api/autogluon.predictor.rst
- docs/tutorials/timeseries/forecasting-model-zoo.rst
- timeseries/src/autogluon/timeseries/models/autogluon_tabular/tabular_model.py
- timeseries/src/autogluon/timeseries/models/gluonts/mx/models.py
- timeseries/src/autogluon/timeseries/models/gluonts/torch/models.py
- timeseries/src/autogluon/timeseries/models/local/naive.py
- timeseries/src/autogluon/timeseries/models/local/statsmodels.py
- timeseries/src/autogluon/timeseries/predictor.py
- Update docstrings for TimeSeriesPredictor, several model docstrings, and update the Model Zoo to the reflect the current state of the code base.
[Rendered `Model Zoo` documentation webpage](https://github.com/awslabs/autogluon/files/9979136/forecasting_model_zoo.pdf)
> [timeseries] Update time series API documentation

- docs/tutorials/multimodal/matching/image2image_matching.md
- docs/tutorials/multimodal/matching/image_text_matching.md
- docs/tutorials/multimodal/matching/text2text_matching.md
- multimodal/src/autogluon/multimodal/predictor.py
1. Make image-to-image tutorial online runnable.
2. Fix the match_label docstring.
> Improve image-to-image matching tutorial

- tabular/setup.py
- sys import missing from setup.py, causing pre-release to fail (https://pypi.org/project/autogluon/#history). Also will crash any local install attempts.
Original bug from #2225 that added `if sys.platform == 'darwin'` logic.
Log showing error in pre-release build:
https://github.com/awslabs/autogluon/actions/runs/3392499510/jobs/5638772315#step:5:1061
```
File "setup.py", line 61, in <module>
] if sys.platform == 'darwin' else [
NameError: name 'sys' is not defined
Error: Process completed with exit code 1.
```
> Add missing import sys in setup.py

- core/src/autogluon/core/utils/infer_utils.py
- tabular/src/autogluon/tabular/learner/abstract_learner.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- Fixes crash when calculating infer_speed in `get_model_true_infer_speed_per_row_batch` when eval_metric isn't able to be calculated for a single row and batch_size=1. Now we avoid calculating the score on the batch (it isn't required to calculate inference speed).
- This has no impact on user functionality, it is purely a fix for benchmarking analytics to calculate genuine inference speed.
Error that has been fixed:
```
File "/Users/neerick/workspace/virtual/autogluon38/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3433, in run_code
exec(code_obj, self.user_global_ns, self.user_ns)
File "<ipython-input-2-7ea70903d95e>", line 3, in <module> …
```
> Minor fix to infer_speed calc

- tabular/src/autogluon/tabular/models/automm/automm_model.py
- tabular/src/autogluon/tabular/models/automm/ft_transformer.py
1, Set default ```env.num_workers=0``` to avoid the "too many open files error".
2, Fixed a bug with automm model save path. Checkpoints are saved as ```FTTransformer/automm_model/``` when called with ```TabularPredictor()```.
> Modified save path and FTT default parameter

- timeseries/src/autogluon/timeseries/models/local/abstract_local_model.py
- timeseries/src/autogluon/timeseries/utils/features.py
- timeseries/tests/unittests/test_splitter.py
replace usages of pandas `DataFrame.iteritems()` with `items()`, which is an [alias](https://github.com/pandas-dev/pandas/blob/91111fd99898d9dcaa6bf6bedb662db4108da6e6/pandas/core/frame.py#L1355) that replaces `iteritems`. 
> [timeseries] Fix use of dataframe.iteritems in timeseries

- core/src/autogluon/core/_setup_utils.py
- core/src/autogluon/core/utils/try_import.py
- core/src/autogluon/core/utils/utils.py
- tabular/setup.py
- tabular/src/autogluon/tabular/learner/default_learner.py
- tabular/src/autogluon/tabular/models/xgboost/callbacks.py
- tabular/src/autogluon/tabular/models/xgboost/hyperparameters/parameters.py
- tabular/src/autogluon/tabular/models/xgboost/xgboost_model.py
- tabular/src/autogluon/tabular/models/xgboost/xgboost_utils.py
Updated dependency versions.
TODO: 
Old:
```
'numpy': '>=1.21,<1.23',
'pandas': '>=1.2.5,!=1.4.0,<1.5',
'scikit-learn': '>=1.0.0,<1.1',
'scipy': '>=1.5.4,<1.8.0',
'catboost>=1.0,<1.1',
'xgboost>=1.4,<1.5',
```
New:
```
'numpy': '>=1.21,<1.24',
'pandas': '>=1.2.5,!=1.4.0,<1.6',
'scikit-learn': '>=1.0.0,<1.2',
'scipy': '>=1.5.4,<1.10.0',
'catboost>=1.0,<1.2',
'xgboost>=1.6,<1.8',
```
Beyond the version updates, I have added logic to address deprecation warnings, including:
- Removed the usage of Pandas `.append` which is deprecated, now using `.concat`.
- Removed usage of Pandas `.iteritems` which is deprecated.
- Refactored XGBoost custom metric logic to adhere to the API change in XGBoost 1.6+. I have tested this locally with a variety of metrics and problem …
> [v0.6] Updated dependency versions

- timeseries/src/autogluon/timeseries/learner.py
- timeseries/tests/unittests/test_learner.py
- Fixes a bug where the `.leaderboard()` method would fail if (1) training data contained static features and (2) no data was given at prediction time.
- Add a test to prevent this bug in the future.
> [timeseries] Fix leaderboard bug if training data contains static features

- timeseries/setup.py
Optional dependencies were missing from core and tabular dependency listings in time series. This can lead to errors (currently caught, but leads to failing models) in edge cases: if the user does not `pip install autogluon` or `full_install` but instead tries to do a bare install of time series. 
> [timeseries] make core and tabular dependencies explicit

- docs/tutorials/multimodal/advanced_topics/efficient_finetuning_basic.md
- docs/tutorials/multimodal/image_prediction/beginner_image_cls.md
- docs/tutorials/multimodal/multimodal_prediction/beginner_multimodal.md
- docs/tutorials/multimodal/multimodal_prediction/multimodal_text_tabular.md
- docs/tutorials/multimodal/object_detection/quick_start/quick_start_coco.md
- docs/tutorials/multimodal/text_prediction/ner.md
Currently, model load and save with hard coded filename which is prone to error for multiple runs
Added UUID to the model_path in case of multiple runs
> Fixed model save and load path with uuid for multiple runs

- multimodal/setup.py
There is an issue with `evaluate` before 0.3.0 concerning the Hugging Face hub integration. I suggest upgrading to `0.3.0` which should not have any breaking changes and be functionally equivalent since this version might break in a few months.
> bump evaluate to `0.3.0`

- .github/workflows/cloud_continuous_integration.yml
- cloud/setup.py
* https://github.com/awslabs/autogluon/actions/runs/3492726758/jobs/5846811139
* Not sure why the CI for the [PR](https://github.com/awslabs/autogluon/pull/2408) went through... But missing a colon there. Also ping the version of python in the ci.
> [CI][Cloud] Ping python version of cloud CI and fix cloud setup

- tabular/src/autogluon/tabular/models/tabular_nn/torch/tabular_nn_torch.py
- tabular/src/autogluon/tabular/models/tabular_nn/utils/categorical_encoders.py
- tabular/src/autogluon/tabular/models/tabular_nn/utils/data_preprocessor.py
This PR simplifies the feature transform function in tabular NN model.
1. avoid using string-based processing
2. leverage `numpy.isin(b, a, invert=True)` function instead of running `np.array([item in b for item in a])`
Benchmark results are shown below
> [Post 0.6][Tabular] Speed up feature transform in tabular NN model

- multimodal/src/autogluon/multimodal/matcher.py
Previously I only fixed the cpu inference bug (cpu cannot use "dp") in `predictor.py`. However, I just noticed that we should also fix `matcher.py`.
> [Bugfix] Fix matcher cpu inference bug

- timeseries/src/autogluon/timeseries/models/gluonts/__init__.py
- Silences a warning produced by GluonTS if either `orjson` or `ujson` are not installed. JSON loading is not used by AutoGluon, so it doesn't apply to us.
> [timeseries] Silence GluonTS JSON warning

- timeseries/src/autogluon/timeseries/dataset/ts_dataframe.py
- timeseries/src/autogluon/timeseries/evaluator.py
- timeseries/src/autogluon/timeseries/models/autogluon_tabular/tabular_model.py
- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- timeseries/src/autogluon/timeseries/models/sktime/abstract_sktime.py
- timeseries/src/autogluon/timeseries/utils/forecast.py
- timeseries/src/autogluon/timeseries/utils/hashing.py
- timeseries/tests/unittests/models/test_models.py
- timeseries/tests/unittests/models/test_sktime.py
- timeseries/tests/unittests/test_utils.py
- Fix where pandas groupby would sort item ids even when `sort=False`(related to https://github.com/pandas-dev/pandas/issues/17537)
- Fix incorrect forecast index generated by GluonTS and Sktime models in some cases.
- For example, if data has timestamps `"2022-01-01 12:00"`, `"2022-01-02 12:00"` (frequency is daily), GluonTS will produce forecasts with timestamps `"2022-01-01 00:00"`, `"2022-01-02 00:00"`, which results in an AssertionError inside the `TimeSeriesEvaluator` [here](https://github.com/awslabs/autogluon/blob/master/timeseries/src/autogluon/timeseries/evaluator.py#L203)
- Add tests covering these cases
> [timeseries] Fix pandas groupby bug + GluonTS index bug

- core/src/autogluon/core/utils/infer_utils.py
- Simplified infer speed throughput calculation when needing to compute multiple different batch size throughputs and plot them.
Example script:
```python3
from autogluon.tabular import TabularPredictor, TabularDataset
from autogluon.core.utils.infer_utils import get_model_true_infer_speed_per_row_batch_bulk
train_path = 'https://autogluon.s3.amazonaws.com/datasets/CoverTypeMulticlassClassification/train_data.csv'
test_path = 'https://autogluon.s3.amazonaws.com/datasets/CoverTypeMulticlassClassification/test_data.csv'
label = 'Cover_Type'
train_data = TabularDataset(train_path)
subsample_size = 1000  # subsample subset of data for faster demo, try setting this to much larger values
if …
```
> Simplified infer speed throughput calculation

- tabular/src/autogluon/tabular/models/tabular_nn/torch/tabular_torch_dataset.py
- tabular/src/autogluon/tabular/models/tabular_nn/torch/torch_network_modules.py
This PR converts map-based tabular nn dataset class into an iterable dataset, which makes batch-based data loading significantly faster. 
For instance, loading 9769 rows in [test.csv](https://autogluon.s3.amazonaws.com/datasets/Inc/test.csv) has been reduced from 49 ms to 9 ms.
Data loading time has been measured with following code snippet.
```python
tic = time.time()
subtotal = 0
for batch_idx, data_batch in enumerate(val_dataloader):
tik = time.time()
preds_batch = self.model.predict(data_batch)
preds_dataset.append(preds_batch)
subtotal += time.time() - tik
total = time.time()-tic
print(f"elapsed (dataloader): {(total-subtotal)*1000:.0f} ms")
print(f"elapsed (predict): {subtotal*1000:.0f} ms")
```
Under Linux, we are able to achieve 40% overall time savings …
> [Post 0.6][Tabular] make tabular nn dataset iterable

- .github/actions/setup-env-vars/action.yml
Fix the CI [failure](https://github.com/autogluon/autogluon/actions/runs/3562103876/jobs/5993588145) at copy_doc step
Moved `short_sha` from env variable to the running command
> [CI] Moved short_sha from env variable to the running command

- multimodal/src/autogluon/multimodal/constants.py
- multimodal/src/autogluon/multimodal/data/infer_types.py
- multimodal/src/autogluon/multimodal/data/preprocess_dataframe.py
- multimodal/src/autogluon/multimodal/data/process_image.py
- multimodal/src/autogluon/multimodal/utils/misc.py
- multimodal/tests/unittests/others/unittest_datasets.py
- multimodal/tests/unittests/others/utils.py
- multimodal/tests/unittests/predictor/test_predictor.py
This PR adds support for image bytearrays in AutoMM.
The DataFrame column can be either `bytearray` or `list[bytearray]`.
Benchmarking on the original `image_path` workflow with [dataset](https://automl-mm-bench.s3.amazonaws.com/petfinder_for_tutorial.zip) on SageMaker endpoint
test data:
100 x bytearray-encoded images 
data preprocess:
0.5s to decode and save to disk to generate `image_path` to pass in `MultiModalPredictor.fit()`
predict_proba:
0.1s
With the support of bytearray, we can save the time spent on data preprocessing, which majority of the time is on saving the image to disk.
> Support image bytearray in AutoMM

- .github/workflows/continuous_integration.yml
Object Detection Tutorial 403 at [here](http://autogluon-staging.s3-website-us-west-2.amazonaws.com/split_multimodal_tutorial/276767d/tutorials/multimodal/object_detection/quick_start/quick_start_coco.html)
Fixed the typo
> [CI] fix typo in object detection tutorial CI

- multimodal/src/autogluon/multimodal/data/preprocess_dataframe.py
`_image_bytearray_names` attribute doesn't exist in df preprocessor. So, `hasattr(self, "_image_bytearray_names")` is always False.  `hasattr(self, "_image_path_names")` is for backward compatibility since we used `_image_path_names` in the initial AutoMM versions. The image_bytearray is new and doesn't have backward compatible issues.
Removed the `hasattr(self, "_image_bytearray_names")` checks.
> Fix image properties in df preprocessor

- timeseries/src/autogluon/timeseries/learner.py
- timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/src/autogluon/timeseries/trainer/abstract_trainer.py
- timeseries/tests/unittests/models/test_models.py
- timeseries/tests/unittests/test_predictor.py
*Issue #, if available:* #2497 and #2498
- Change the implementation of `AbstractTimeSeriesModel.get_info()` and `TimeSeriesPredictor.fit_summary()`.
- Add tests covering these functions.
> [timeseries] Fix info and fit_summary for TimeSeriesPredictor

- timeseries/src/autogluon/timeseries/models/autogluon_tabular/tabular_model.py
- timeseries/src/autogluon/timeseries/trainer/abstract_trainer.py
- timeseries/src/autogluon/timeseries/utils/features.py
- timeseries/tests/unittests/test_trainer.py
- Fix a bug where prediction with `WeightedEnsemble` fails if component models use `known_covariates` + add a test case for this
- Make sure that static feature preprocessing doesn't introduce NaNs to the `static_features` dataframe
> [timeseries] Pass known_covariates to component models of the WeightedEnsemble

- timeseries/src/autogluon/timeseries/dataset/ts_dataframe.py
- timeseries/tests/unittests/test_ts_dataset.py
- Automatically convert the `static_features` to a `pd.DataFrame` if a `pd.Series` is provided
- Always rename the index of `static_features` to `"item_id"`. If we don't rename the index, we will run into an exception inside the splitter [here](https://github.com/awslabs/autogluon/blob/master/timeseries/src/autogluon/timeseries/splitter.py#L63).
> [timeseries] Gracefully handle inconsistencies in static_features provided by user

- .github/workflows/codeql.yml
CodeQL v1 deprecation [notice](https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/)
> [CI] upgrade codeql v1 to v2 as v1 will be deprecated

- timeseries/src/autogluon/timeseries/models/autogluon_tabular/tabular_model.py
- Save the `AutoGluonTabular` model to the correct model folder instead of the automatically generated folder in `AutogluonModels`.
> [timeseries] Save AutoGluonTabular model to the correct folder

- core/src/autogluon/core/models/abstract/abstract_model.py
Models that are fitted on v0.5.1 doesn't have attributes like `_compiler` and `compile_time`.
This PR checks whether the model itself has the compile-related attribute, before accessing its value.
> [Tabular] support predicting with model fitted on v0.5.1

- timeseries/src/autogluon/timeseries/dataset/ts_dataframe.py
- timeseries/tests/unittests/models/test_sktime.py
- timeseries/tests/unittests/test_ts_dataset.py
- Ensures that the timestamps are always sorted chronologically inside a `TimeSeriesDataFrame`
> [timeseries] Ensure that timestamps are sorted when creating a TimeSeriesDataFrame

- .github/workflow_scripts/build_all_docs.sh
* The cause is that `d2lbook` depends on `awscli`, which got updated yesterday and have a conflict dependency with `tox` version we depend on in `eda` . We were previously installing all AG modules in the `build_all_docs` step, though I doubt it's needed. Removed for now to see if it solves the issue
> [CI] Fix build all docs

- features/tests/features/conftest.py
- Add tests for preprocessing mutation
- This improves our certainty that a feature generator is not performing in-place operations on the data that alter the outer context of the input.
> Add tests for preprocessing mutation

- timeseries/src/autogluon/timeseries/predictor.py
GluonTS models only support a limited set of the [pandas frequencies](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases) and fail when given an unsupported frequency. For example, `M` (month end) is supported, but `MS` (month start) leads to failure.
- We warn the user is the provided data has an unsupported frequency. This is a temporary solution — we will implement automatic frequency conversion in v0.7, but that needs more testing first.
> [timeseries] Warn if provided data has a frequency that is not supported

- docs/install-include.rst
- docs/tutorials/multimodal/object_detection/index.rst
- multimodal/setup.py
- multimodal/src/autogluon/multimodal/utils/object_detection.py
AutoGluon installation issue. #2494 #2521 
pycocotools can't be easily built in some linux and windows distribution.
Remove pycocotools from setup.py. Given this is only used for object detection model evaluation, it is better to lazy import rather than effecting AG installation. 
> Remove pycocotools

- features/src/autogluon/features/generators/abstract.py
Avoid copying DataFrame when they are identical. This brings about 10% speedup of single-batch prediction on tabular models.
> [Tabular] Avoid copying identical dataframes

- core/src/autogluon/core/hpo/executors.py
- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/models/ensemble/fold_fitting_strategy.py
- tabular/tests/conftest.py
- tabular/tests/unittests/resource_allocation/test_bagging_resource_allocation.py
- tabular/tests/unittests/resource_allocation/test_hpo_resource_allocation.py
- tabular/tests/unittests/resource_allocation/test_resource_allocation_combined.py
- tabular/tests/unittests/resource_allocation/test_total_resource_allocation.py
https://github.com/autogluon/autogluon/issues/2446
* Fixed the case when user didn't specify total resources, but specified lower level resources. Previously would pass default value based on the model to the lower value as the total resources, which is incorrect. Now will check if user passed lower level requirements, and use those.
* Added a special case when user provide both `num_resource` and `ag_args_fit` when not doing bagging nor hpo. Might think about better way to handle it in the future...
* Updated unit tests and added two more tests to cover cases when no resource requirement is specified, we should be using the default value based on the model.
* Added end-to-end tests...
By submitting this pull request, I confirm that you …
> [Tabular] Resource Allocation Fix

- multimodal/src/autogluon/multimodal/utils/data.py
- multimodal/tests/unittests/others/test_classification.py
*Description of changes:* Adding support for str/list input for classification. Unit Test passed.
> [Merge After 0.6.1] Adding support for str/list input for classification

- cloud/src/autogluon/cloud/scripts/multimodal_serve.py
- common/src/autogluon/common/features/types.py
- features/src/autogluon/features/generators/auto_ml_pipeline.py
- features/src/autogluon/features/generators/category.py
- features/src/autogluon/features/generators/drop_unique.py
- features/src/autogluon/features/generators/text_ngram.py
- features/src/autogluon/features/generators/text_special.py
This PR adds bytearray support in cloud module multimodal inference script. 
Instead of saving encoded image bytearrays to disk and update the test data with `image_path`, we can now directly make calls to `MultiModalPredictor` with decoded bytearrays. 
We have also added `S_IMAGE_BYTEARRAY` to feature generator.
> Use bytearray in cloud server

- .github/workflow_scripts/build_all_docs.sh
- .github/workflow_scripts/env_setup.sh
- .github/workflow_scripts/test_common.sh
- .github/workflow_scripts/test_core.sh
- .github/workflow_scripts/test_eda.sh
- .github/workflow_scripts/test_fair.sh
- .github/workflow_scripts/test_features.sh
- .github/workflow_scripts/test_multimodal_others.sh
- .github/workflow_scripts/test_multimodal_predictor.sh
- .github/workflow_scripts/test_tabular.sh
- .github/workflow_scripts/test_text.sh
- .github/workflow_scripts/test_timeseries.sh
- .github/workflow_scripts/test_vision.sh
https://github.com/autogluon/autogluon/issues/2571
The `install_all` bash call in `build_all_docs` was removed in [this commit](https://github.com/autogluon/autogluon/commit/dfa96254773017b1bd51038f62a9b21c3b20dafb) because of a package dependency conflict between `tox` for testing in `eda` module and dependencies of the `d2lbook` tool.
Unfortunately `install_all` call was required to install modules that are used during autogen of docs, resulting in the website API documentation problem described in [the issue](https://github.com/autogluon/autogluon/issues/2571).
The fix here is to create a new `install_all_no_tests` call that avoids installing tests including the `tox` dependency when `eda/[tests]` is installed. In order to do this, I …
> [Bug] Fix missing Predictor API docs on Website

- cloud/setup.py
- cloud/src/autogluon/cloud/predictor/cloud_predictor.py
- cloud/src/autogluon/cloud/predictor/image_cloud_predictor.py
- cloud/src/autogluon/cloud/predictor/multimodal_cloud_predictor.py
- cloud/src/autogluon/cloud/predictor/tabular_cloud_predictor.py
- cloud/src/autogluon/cloud/scripts/train.py
- cloud/src/autogluon/cloud/utils/utils.py
- cloud/tests/conftest.py
- cloud/tests/unittests/image/test_image.py
- cloud/tests/unittests/multimodal/test_multimodal.py
- cloud/tests/unittests/tabular/test_tabular.py
- cloud/tests/unittests/text/test_text.py
* As discussed with @tonyhoo, we decide to unify the api for fit and inference when image modality is involved. Now we only ask for `image_column` for both cases, and we require user to have the `image_path` inside the csv file to be an absolute path in both cases.
* We've removed support for files in s3 as it would be extremely complicated when image modality is involved. This also makes sense as tabular/multimodal predictor doesn't support images living in s3 as well.
* Updated unit tests accordingly
> [Cloud] Unify input of image modality in fit and inference apis

- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- tabular/tests/unittests/resource_allocation/test_total_resource_allocation.py
https://github.com/autogluon/autogluon/issues/2581
* `model_base` is not available when doing repeated bagging. Use `_get_child_aux_val` to retrieve params instead.
* Added check of if `is_initialized()` check in `BaggedEnsembleModel._get_child_aux_val()`. @Innixma Let me know if it's missing intentionally.
> Fix Tabular Ensemble Folding

- core/src/autogluon/core/models/abstract/abstract_model.py
- tabular/src/autogluon/tabular/models/tabular_nn/compilers/native.py
- tabular/src/autogluon/tabular/models/tabular_nn/compilers/onnx.py
- tabular/src/autogluon/tabular/models/tabular_nn/torch/tabular_nn_torch.py
- tabular/src/autogluon/tabular/models/tabular_nn/utils/data_preprocessor.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/tests/unittests/models/test_tabular_nn.py
This PR converts the ColumnsTransformer in tabular NN model from sklearn to onnx, so that the processor in TabularNeuralNetTorchModel can be accelerated via onnxruntime.
While the impact to accuracy is minimal,
```
NeuralNetTorch:
{'accuracy': 0.8365236974101751, 'balanced_accuracy': 0.7532995553694549, 'mcc': 0.5305019485882506, 'roc_auc': 0.8815480292353528, 'f1': 0.6332950631458094, 'precision': 0.6769759450171822, 'recall': 0.594909404659189}
NeuralNetTorch_ONNX:
{'accuracy': 0.8362166035418159, 'balanced_accuracy': 0.7523552495805498, 'mcc': 0.5291951976581161, 'roc_auc': 0.8813204856717612, 'f1': 0.6320147194112237, 'precision': 0.6768472906403941, 'recall': 0.5927523727351165}
```
, the impact to overall online inference is …
> [Tabular] Convert ColumnTransformer in tabular NN from sklearn to onnx

- core/src/autogluon/core/constants.py
- core/src/autogluon/core/utils/utils.py
- core/tests/unittests/utils/test_utils.py
- tabular/src/autogluon/tabular/learner/default_learner.py
- tabular/tests/unittests/test_tabular.py
*Issue #, if available:* [2443](https://github.com/autogluon/autogluon/issues/2443)
After discussion with a customer, we decided that AutoGluon should crash if any un-representable value (`NaN`, `Inf`, `NINF`) is present in the label column, because prediction behavior is not well specified for these rows. Infinite values don't make sense for regression problems but could be treated as additional classes or ignored for classification problems. `NaN` values could be ignored for regression problems but could be treated as a separate class or ignored in regression problems. 
This set of commit changes the behavior of AutoGluon to always raise an Error if these values are present in the label column of `train_data` or `tune_data` so that the user has to explicitly …
> Error on non-finite values in label column

- timeseries/src/autogluon/timeseries/models/local/abstract_local_model.py
- Convert the target column into a `pd.Series` before splitting individual time series. This is much faster than calling `.loc` on a `TimeSeriesDataFrame`. For TSDF we end up subsetting the `static_features` for each iteration in the loop, but these static features aren't used by the underlying models.
Testing on a subset of 5000 items from the M5 competition dataset:
Using code currently on `master`:
```
Loaded dataset with 7559974 rows and 5000 items.
Fitting Naive: 35.2s
```
After current PR:
```
Loaded dataset with 7559974 rows and 5000 items.
Fitting Naive: 19.9s
```
<details>
<summary>Code for reproducing the results</summary>
```python
import time
from autogluon.timeseries import TimeSeriesDataFrame
from autogluon.timeseries.models …
```
> [timeseries] Speed up data preparation for local models

- timeseries/src/autogluon/timeseries/models/local/abstract_local_model.py
- timeseries/tests/smoketests/test_features_and_covariates.py
- Add smoke tests that ensure that all models can train & predict when different combinations of features / predictor configurations are present
> [timeseries] Add smoke tests for timeseries

- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- timeseries/src/autogluon/timeseries/models/gluonts/torch/models.py
- timeseries/src/autogluon/timeseries/utils/forecast.py
- timeseries/tests/unittests/test_evaluator.py
- Significantly speed up prediction for GluonTS models. The two main sources are:
- Use of `pd.Series` instead of `TimeSeriesDataFrame` inside `SimpleGluonTSDataset` to avoid copying the static features.
- Speed up `get_forecast_horizon_index_ts_dataframe` with a more efficient `groupby` operation
- Clean up redundant logic in `AbstractGluonTSModel. predict`.
(only training for 1 epoch / 1 batch, so the training time/performance are meaningless here)
**With this PR**
5K items / 7M rows
```
Training timeseries model DeepAR.
-0.9107       = Validation score (-mean_wQuantileLoss)
5.99    s     = Training runtime
47.57   s     = Validation (prediction) runtime
```
30K items / 47M rows
```
Training timeseries model DeepAR.
-0.7019       = Validation score …
```
> [timeseries] Speed up prediction for GluonTS models

- timeseries/src/autogluon/timeseries/dataset/ts_dataframe.py
- timeseries/src/autogluon/timeseries/splitter.py
- timeseries/tests/unittests/test_splitter.py
- Speed up the `append_suffix_to_item_id` function
- Replace the surprisingly slow `DataFrame.loc[index]` operation with `DataFrame.query("item_id in @index")`.
Testing on a subset of 5000 items from the M5 competition dataset:
Using code currently on `master`:
```
Loaded dataset with 7559974 rows and 5000 items.
df.slice_by_timestep(None, -prediction_length): 5.75s
LastWindowSplitter.split(df, prediction_length): 63.83s
```
After current PR:
```
Loaded dataset with 7559974 rows and 5000 items.
df.slice_by_timestep(None, -prediction_length): 1.38s
LastWindowSplitter.split(df, prediction_length): 8.30s
```
<details>
<summary>Code for reproducing the results</summary>
```python
import time
from autogluon.timeseries import TimeSeriesDataFrame …
```
> [timeseries] Speed up the train/val splitter

- timeseries/src/autogluon/timeseries/evaluator.py
- timeseries/src/autogluon/timeseries/models/ensemble/greedy_ensemble.py
- timeseries/tests/unittests/test_evaluator.py
- Avoid the costly `TimeSeriesDataFrame.slice_by_timestep` operation when computing the metrics while fitting an ensemble.
**M4-hourly (350K rows, 414 items)**
- Current `master` branch
```
Fitting simple weighted ensemble.
33.31   s     = Training runtime
```
- This PR
```
Fitting simple weighted ensemble.
4.59    s     = Training runtime
```
**M4-daily (10M rows, 4227 items)**
- Current `master` branch
```
Fitting simple weighted ensemble.
1120.93 s     = Training runtime
```
- This PR
```
Fitting simple weighted ensemble.
18.20   s     = Training runtime
```
> [timeseries] Speed up TimeSeriesEnsembleSelection.fit

- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- This PR fixes a bug introduced by the refactoring of `AbstractGluonTSModel` introduced by #2593 that caused, e.g., `TemporalFusionTransformerMXNet` model to fail. 
Background: Some GluonTS models always convert `item_id` to a string, while others keep the original dtype (e.g., int). With this PR, we ensure that we always convert `item_id` to a string internally, but return the correct dtype to the user.
> [timeseries] Fix inconsistent item_id handling by GluonTS

- docs/tutorials/index.rst
*Issue #, if available:* [2616](https://github.com/autogluon/autogluon/issues/2616)
This change updates broken tutorial links for Multimodal and Time Series tutorials on the `tutorialslindex.html` page that moved.
> [BUG] Fix broken tutorial index links

- timeseries/src/autogluon/timeseries/dataset/ts_dataframe.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/tests/unittests/test_predictor.py
- timeseries/tests/unittests/test_ts_dataset.py
This PR contains several potential improvements to the data loading process in `autogluon.timeseries`:
1. Automatically convert the `timestamp` columns to the `datetime64` format when constructing a `TimeSeriesDataFrame` from `pd.DataFrame` without multiindex.
2. Load a `TimeSeriesDataFrame` from path (local or remote), similar to `autogluon.tabular.TabularDataset`.
3. Accept `pd.DataFrame` as input to `TimeSeriesPredictor` and automatically convert to `TimeSeriesDataFrame` under the hood.
These changes make it possible to significantly shorten the code for training AGTS on a dataset. 
- Current minimal example
```python
from autogluon.timeseries import TimeSeriesPredictor, TimeSeriesDataFrame
raw_df = pd.read_csv( …
```
> [timeseries] Automatically convert timestamps to datetime & handle DataFrame inputs

- multimodal/src/autogluon/multimodal/matcher.py
- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/presets.py
- multimodal/src/autogluon/multimodal/utils/config.py
- multimodal/src/autogluon/multimodal/utils/pipeline.py
- multimodal/tests/unittests/others/test_presets.py
1. Let users use `presets` in predictor initialization. The presets is to control model quality: `best_quality`, `high_quality_fast_inference`, and `medium_quality_faster_inference`.
2. Fix ner presets. Use the registered ner presets rather than the default.
3. Add unit tests.
> Support presets in AutoMM predictor initialization

- core/src/autogluon/core/trainer/abstract_trainer.py
- tabular/src/autogluon/tabular/models/rf/rf_quantile.py
- tabular/tests/conftest.py
- tabular/tests/unittests/calibrate/test_calibrate.py
- tabular/tests/unittests/edgecases/test_edgecases.py
- tabular/tests/unittests/models/test_lightgbm.py
- tabular/tests/unittests/models/test_rf.py
Fixed crash during calibration due to incorrect predict_proba dimensions when problem_type='binary', eval_metric='log_loss', num_bag_folds>1
- This bug was first introduced in 0.6 release and impacts 0.6 and 0.6.1 releases.
- Bug caused due to making out-of-fold predictions and predict_proba outputs consistent in v0.6 (previously they had different dimensions in binary by default), however the calibrate code still treated them inconsistently in binary classification, leading to the error.
- Workaround prior to this fix: set `calibrate=False` in `predictor.fit(...)`
- Also fixed a bug that made quantile regression on RF crash due to removed fit parameter in sklearn & added unit tests
*Code to Reproduce*
```python3
from autogluon.tabular …
```
> Tabular: Fixed crash during calibration in binary stacking

- .github/workflow_scripts/env_setup.sh
- .github/workflow_scripts/test_tabular.sh
- .github/workflows/platform_tests-command.yml
* Security patches applied in https://github.com/autogluon/autogluon/pull/2588 is linux specific. For our platform tests, we install default torch.
* Platform tests are running in github hosted machine and doesn't contain credentials. Should be fine
> [CI]Fix torch install on platform tests

- multimodal/src/autogluon/multimodal/utils/environment.py
- Fix crash due to undefined DataContainer on MacOS without GPU
Example:
```
/Users/neerick/workspace/code/autogluon/multimodal/src/autogluon/multimodal/utils/environment.py:96: UserWarning: Only CPU is detected in the instance. This may result in slow speed for MultiModalPredictor. Consider using an instance with GPU support.
warnings.warn(
GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
| Name              | Type                | Params
----------------------------------------------------------
0 | model             | MultimodalFusionMLP | 109 M 
1 | validation_metric | AUROC               | 0     
2 | loss_func         | CrossEntropyLoss …
```
> AutoMM: Fix crash due to undefined DataContainer

- .github/workflow_scripts/test_eda.sh
- eda/setup.cfg
- eda/src/autogluon/eda/analysis/__init__.py
- eda/src/autogluon/eda/analysis/interaction.py
- eda/src/autogluon/eda/analysis/model.py
- eda/src/autogluon/eda/auto/__init__.py
- eda/src/autogluon/eda/auto/simple.py
- eda/src/autogluon/eda/visualization/__init__.py
- eda/src/autogluon/eda/visualization/model.py
- eda/tests/unittests/analysis/test_model.py
- eda/tests/unittests/auto/test_simple.py
- eda/tests/unittests/visualization/test_model.py
The component allows to fit a quick model using AutoGluon. `train_data`, `val_data` and `label` must be present in args.
Note: this component can be wrapped into :`TrainValidationSplit` and `Sampler` to perform automated sampling and train-test split. This whole logic is implemented in `quick_fit()` shortcut (see below).
```
Parameters
----------
problem_type: str, default = 'auto'
problem type to use. Valid problem_type values include ['auto', 'binary', 'multiclass', 'regression', 'quantile', 'softclass']
auto means it will be Auto-detected using AutoGluon methods.
estimator_args
kwargs to pass into estimator constructor (`TabularPredictor`)
parent: Optional[AbstractAnalysis], default = None
parent Analysis
children: Optional[List[AbstractAnalysis]], default …
```
> [eda] Quick Fit

- core/src/autogluon/core/models/abstract/_tags.py
- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/utils/try_import.py
- tabular/src/autogluon/tabular/models/automm/automm_model.py
- tabular/src/autogluon/tabular/models/automm/ft_transformer.py
- tabular/src/autogluon/tabular/models/fasttext/fasttext_model.py
- tabular/src/autogluon/tabular/models/text_prediction/text_prediction_v1_model.py
- tabular/src/autogluon/tabular/models/vowpalwabbit/vowpalwabbit_model.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/tests/unittests/models/test_automm.py
- Fixed case where AutoMM is specified as a model in TabularPredictor, but the global preprocessor does not keep raw text features in output, leading AutoMM to not use text features.
- Now this situation is fixed for all future models so long as they specify `handles_text=True` in `_class_tags`.
> Fix AutoMM usage of text in TabularPredictor

- eda/src/autogluon/eda/analysis/interaction.py
- eda/src/autogluon/eda/visualization/__init__.py
- eda/src/autogluon/eda/visualization/interaction.py
This PR introduces nonparametric independence tests to evaluate interactions between various tabular data types.  These tests are...
- Chi2 test: cat v cat
- Spearman R: numeric v numeric
- Kruskal-Wallace: numeric v cat
The adds the result of the test to the state (test statistic, p-value, test name).  The p-values can be compared between tests since they are pivotal statistics.  We can then produce a heatmap of these p-values as well, which is added to the visualization.
> [eda] add non-parametric interaction tests

- multimodal/setup.py
- multimodal/src/autogluon/multimodal/__init__.py
- multimodal/src/autogluon/multimodal/models/fusion.py
- multimodal/src/autogluon/multimodal/models/timm_image.py
- multimodal/src/autogluon/multimodal/models/utils.py
- multimodal/src/autogluon/multimodal/optimization/lit_matcher.py
- multimodal/src/autogluon/multimodal/optimization/lit_module.py
- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/utils/__init__.py
- multimodal/src/autogluon/multimodal/utils/inference.py
- multimodal/src/autogluon/multimodal/utils/onnx.py
- multimodal/tests/unittests/others/test_deployment.py
1. This PR exports the TIMM image models to onnx, and it's been tested on onnxruntime for checking correctness.
2. Downgrades onnx to 1.12.x (since https://github.com/autogluon/autogluon/pull/2567), due to conflict version range of protobuf against tensorboardx:
a. onnx 1.13.x requires protobuf >=3.12.2,<=3.20.1, (onnx 1.12.x requires protobuf >=3.12.2,<=3.20.1)
b. tensorboardx 2.5.1 requires protobuf >=3.8.0,<=3.20.1
> Export TIMM image models to onnx

- eda/src/autogluon/eda/analysis/model.py
- eda/src/autogluon/eda/auto/simple.py
- eda/tests/unittests/auto/test_simple.py
- eda/tests/unittests/test_shift.py
- Added `fig_args`/`chart_args` management for composite components
- Added tests and docs
Customizing and `fig_args` (figure properties) `chart_args` (chart properties inside the figure) for the `feature_distance` component:
```python
auto.dataset_overview(
train_data=df_train, test_data=df_test, label=target_col, 
fig_args={'feature_distance': dict(figsize=(6,6))},
chart_args={'feature_distance': dict(orientation='left')},
)
```
Customizing multiple components in a composite component (`confusion_matrix` and `feature_importance`):
```python
auto.quick_fit(
df_train, target_col,
show_feature_importance_barplots=True,
fig_args={
'confusion_matrix': dict(figsize=(3, 3)),
'feature_importance': dict(figsize=(4, 4)),
}
)
```
By submitting this pull request, I confirm …
> [eda] Helpers docs + refactor

- multimodal/src/autogluon/multimodal/matcher.py
- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/utils/save.py
- multimodal/tests/unittests/others/test_save_path.py
1. For object detection, if model_loaded=True, every time calling `.predict()`  would create a new save folder and change `_save_path`.
2. Creating saving folder in `init()` complicates the logic of save_path.
3. Predictor and matcher use different save_path logic.
1. Remove the creation of saving folder from `init()`. Create saving folder only when it's used.
2. Remove the `_model_loaded` flag. For saving the prediction results of object detection, we can directly save to the path `_save_path`, whether the model is loaded or fitted.
3. Let matcher use the same save_path logic as predictor.
> Improve save_path in AutoMM

- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/tests/unittests/edgecases/test_edgecases.py
- Add max_sets as an ag_args_ensemble option
- For example, for AG_AUTOMM, it can be useful to set `max_sets=1`, while keeping the cheaper models as is to benefit from repeated bagging.
> Tabular: Add max_sets

- core/src/autogluon/core/metrics/__init__.py
- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/tests/unittests/edgecases/test_edgecases.py
- Add num_folds ag_args_ensemble parameter
- Improved interpretability of ValueError in metrics to clarify which metric raised the error.
> Tabular: Add num_folds

- multimodal/src/autogluon/multimodal/data/preprocess_dataframe.py
> Fix null images

- multimodal/src/autogluon/multimodal/matcher.py
- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/utils/config.py
1. `_continuous_training` and `_fit_called` have duplicate functions.
2. Setting `_continuous_training`=True if resume=False is incorrect in the case that the predictor is saved without being fitted.
1. Replace `_continuous_training` with `_fit_called`.
2. Add hyperparameter filtering in matcher HPO.
> Improve continuous training+HPO

- eda/src/autogluon/eda/analysis/shift.py
- eda/src/autogluon/eda/auto/__init__.py
- eda/src/autogluon/eda/auto/simple.py
- eda/tests/unittests/auto/test_simple.py
- eda/tests/unittests/test_shift.py
This is a shortcut for analyze and visualize steps encapsulated in a single call.
```
Parameters
----------
train_data: Optional[DataFrame]
training dataset
test_data: Optional[DataFrame]
test dataset
label: : Optional[str]
target variable
state: Union[None, dict, AnalysisState], default = None
pass prior state if necessary; the object will be updated during `anlz_facets` `fit` call.
sample: Union[None, int, float], default = None
sample size; if `int`, then row number is used;
`float` must be between 0.0 and 1.0 and represents fraction of dataset to sample;
`None` means no sampling
See also :func:`autogluon.eda.analysis.dataset.Sampler`
path: Optional[str], default = None,
path for models saving
return_state: bool, default = False
return state if `True` …
```
> [eda] shortcut for covariate shift detection

- core/src/autogluon/core/models/__init__.py
- core/src/autogluon/core/models/dummy/_dummy_quantile_regressor.py
- core/src/autogluon/core/models/dummy/dummy_model.py
- tabular/src/autogluon/tabular/trainer/model_presets/presets.py
- tabular/tests/unittests/configs/test_config_helper.py
- tabular/tests/unittests/edgecases/test_edgecases.py
- tabular/tests/unittests/models/test_dummy.py
- Add DummyModel
- DummyModel allows us to test new functionality without having to wait for model training to occur or have to worry about model training interacting with the new functionality during debugging.
- Also helps speed up unit tests for logic that requires going through the predictor.fit path, but that doesn't care about the model quality.
> Tabular: Add DummyModel

- docs/index.rst
- docs/tutorials/timeseries/forecasting-quickstart.md
- timeseries/src/autogluon/timeseries/dataset/ts_dataframe.py
- Significantly shorten the quickstart tutorial to match the style of other modules
- Add a 3-line time series example to the landing page
> [timeseries] Shorten the quickstart tutorial + add time series example to the landing page

- tabular/src/autogluon/tabular/models/tabular_nn/compilers/onnx.py
- tabular/src/autogluon/tabular/models/tabular_nn/torch/tabular_nn_torch.py
```python
from autogluon.tabular import TabularDataset, TabularPredictor
train_data = TabularDataset('https://autogluon.s3.amazonaws.com/datasets/Inc/train.csv')
train_data = train_data.head(500)  # subsample for faster demo
print(train_data.head())
label = 'class'  # specifies which column do we want to predict
save_path = 'ag_models/'  # where to save trained models
if os.path.exists(save_path):
shutil.rmtree(save_path, ignore_errors=True)
predictor = TabularPredictor(label=label, path=save_path). \
fit(train_data, presets='good_quality', time_limit=120)
```
Training with `presets='good_quality'` will result in an error. 
The fundamental reason is that `_ray_predict_oof` would delete `fold_model.model`, see
```python
def _ray_predict_oof(fold_model, X_val_fold, …
```
> [tabular][bugfix] fix tabular NN working with _ray_predict_oof

- multimodal/src/autogluon/multimodal/optimization/utils.py
- multimodal/tests/unittests/others/test_metrics.py
Normalize the accumulated recall to (0, 1) to satisfy the stopping threshold.
> Fix matcher recall threshold

- eda/src/autogluon/eda/analysis/interaction.py
- eda/src/autogluon/eda/auto/__init__.py
- eda/src/autogluon/eda/auto/simple.py
- eda/src/autogluon/eda/visualization/dataset.py
- eda/src/autogluon/eda/visualization/interaction.py
- eda/src/autogluon/eda/visualization/layouts.py
- eda/src/autogluon/eda/visualization/missing.py
- eda/src/autogluon/eda/visualization/model.py
- eda/src/autogluon/eda/visualization/shift.py
- eda/tests/unittests/analysis/test_interaction.py
- eda/tests/unittests/auto/test_simple.py
- eda/tests/unittests/visualization/test_interaction.py
- eda/tests/unittests/visualization/test_model.py
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1LfgSKSTVWfF_IgTYEcaK6GjdfRqffgl0?usp=sharing)
- Added `target_analysis` - target variable composite analysis
- Added feature distance for `dataset_overview`
- Added `distribution_fit` for `analyze_interaction` shortcut
- Added distribution plots for `covariate_shift_detection` when shift is detected
- Dynamic `figargs` setting for various components; adjusted fontsize and colors
- Added parameters names for distribution fit analysis
```python
auto.analyze_interaction(train_data=df_train, x='Age', fit_distributions=True) 
auto.analyze_interaction(train_data=df_train, x='Age', …
```
> [eda] Added target_analysis - target variable composite analysis

- eda/src/autogluon/eda/analysis/interaction.py
- eda/src/autogluon/eda/analysis/transform.py
- eda/src/autogluon/eda/visualization/interaction.py
- Added line plots support for date-numeric feature interaction
- Fixed feature interaction issue when label is not provided (label is not used in the plot)
```python
auto.analyze_interaction(train_data=df_train, x='date', y='members_who_viewed')
```
> [eda] Line plots support for date-numeric feature interaction

- core/src/autogluon/core/trainer/abstract_trainer.py
- tabular/src/autogluon/tabular/predictor/predictor.py
#2685 
- Tabular: Add FutureWarning to predict_proba for regression
- This will align Tabular with Multimodal.
- Minor log cleanup / doc improvement
> Tabular: Add FutureWarning to predict_proba for regression

- core/src/autogluon/core/_setup_utils.py
- timeseries/setup.py
*Issue #, if available:* #2689, #2697
- Ensure that the pandas version is >= 1.4.0 for [`GroupBy.nth`](https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.GroupBy.nth.html) to work with `slice` objects. This is required for https://github.com/autogluon/autogluon/blob/master/timeseries/src/autogluon/timeseries/dataset/ts_dataframe.py#L572
> [timeseries] Bump pandas dependency to >=1.4.0

- features/src/autogluon/features/generators/abstract.py
- features/tests/features/generators/test_auto_ml_pipeline.py
resolves #2688
- Previously the change added in #2532 created a subtle bug when only text features were present in the data due to the inplace renaming operation for raw text.
- Because we didn't test for this specific scenario where only text features are provided, we did not catch this issue.
- This fixes the bug by setting inplace=False during feature renaming
- Also adds a unit test to check that the bug is fixed.
- v0.6.2 workaround: Avoid only passing text features to TabularPredictor, instead include the text features with other features or create dummy features to pass alongside the text features.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
> Tabular: Fix edge-case text preprocessing bug

- tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
- tabular/src/autogluon/tabular/models/lgb/lgb_model.py
- tabular/src/autogluon/tabular/models/tabular_nn/torch/tabular_nn_torch.py
1. Predict tabular NN without modifying num_thread, since we are upgrade xgboost to >=1.6
2. removed the hack that changes num_thread in lightgbm, since the bug (https://github.com/microsoft/LightGBM/issues/4607) in lightgbm has been fixed
a. See original topic: https://github.com/autogluon/autogluon/pull/1329#discussion_r730063716
For an ensemble model with both TabularFastAI model and XGBoost model, the overall inference speed is reduced from 49 ms to 33 ms (batch size=1). Because of the removal of TorchThreadManager, XGBoost prediction time reduced from 16 ms to 1.6 ms. (Tested on Linux with AdultIncomeBinaryClassification task trained with high_quality preset.)
Code snippet to reproduce the results:
```python
import time
from …
```
> [Tabular] Remove TorchThreadManager in TabularNN and hack in LightGBM

- common/src/autogluon/common/utils/lite.py
- common/src/autogluon/common/utils/utils.py
- Clean up lite flag code
- Now we don't repeatedly call `get_autogluon_metadata` during autogluon import just to get the lite status
- Now developers don't need to re-run setup when pulling the lite commit to avoid crashing. We now wrap the `__lite__` import in a try/except.
> Cleanup lite flag

- multimodal/src/autogluon/multimodal/data/trivial_augmenter.py
- multimodal/src/autogluon/multimodal/data/utils.py
- multimodal/src/autogluon/multimodal/utils/nlpaug.py
https://github.com/autogluon/autogluon/issues/2706
> Move nlpaug to lazy import

- core/src/autogluon/core/_setup_utils.py
- Add Python 3.10 to PyPi classifiers
> Add Python 3.10 to PyPi classifiers

- core/src/autogluon/core/trainer/abstract_trainer.py
- tabular/tests/unittests/edgecases/test_edgecases.py
resolves #2674 
- Fixes edge case bug where use_bag_holdout=True and calibrate=True (such as by setting log_loss as the eval metric).
- `self.bagged_mode` did not provide sufficient information to use the correct data for calibration when `use_bag_holdout=True`, so created `self.has_val` which captures the correct information necessary.
> Fix calibrate=True, use_bag_holdout=True

- tabular/src/autogluon/tabular/models/rf/rf_model.py
- Previously, if n_estimators was searched, it would error during HPO initialization due to a memory check causing a type error. Fixed by first checking the type during the type check.
> Fix RF HPO n_estimators

- core/src/autogluon/core/utils/try_import.py
- tabular/src/autogluon/tabular/models/automm/automm_model.py
- tabular/src/autogluon/tabular/models/image_prediction/image_predictor.py
- tabular/tests/unittests/models/test_image_predictor.py
#2694 
- Remove usage of autogluon.vision in autogluon.tabular, switch to using autogluon.multimodal
- Not identical from prior functionality since previously Tabular was using the gluoncv backend of autogluon.vision.
- Note that the special null image handling logic has been preserved, can be revisited if it makes sense to remove.
> Remove usage of autogluon.vision in autogluon.tabular
