autogluon/autogluon

- features/src/autogluon/features/generators/text_special.py
These changes update the logic for processing special text features in AG-Tabular. Previously the features were generated by static python functions that were applied to pandas column entries in a list comprehension. Now identical features are being generated using pandas built-in functions and regex support when possible. This provides some immediate performance gains, as well as will benefit from future performance improvements from the pandas library.
I did some other cleanup while I was touching this area of code such as updating a few python style best practices and renaming a few variables that made more sense to me as a reader of the code (not original author).
I verified these changes pass the existing unit tests for special test feature generation. I also ran with and without …
> Generate special text features with pandas built-in functions

- timeseries/src/autogluon/timeseries/predictor.py
This PR fixes several factually incorrect statements & improves wording in the documentation of the `TimeSeriesPredictor` API.
> Update documentation for TimeSeriesPredictor

- .github/workflows/cloud_continuous_integration.yml
- cloud/src/autogluon/cloud/predictor/image_cloud_predictor.py
- cloud/src/autogluon/cloud/scripts/image_serve.py
* Update ImageCloudPredictor to Encode Decode to match multimodal predictor
* Minor fix on the CI trigger
> [Cloud] Update ImageCloudPredictor to Encode Decode

- tabular/src/autogluon/tabular/learner/abstract_learner.py
- tabular/src/autogluon/tabular/learner/default_learner.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/tests/unittests/test_tabular.py
https://github.com/awslabs/autogluon/issues/2134
* Add original training data features
> Add Original Features

- core/src/autogluon/core/trainer/abstract_trainer.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/src/autogluon/tabular/trainer/auto_trainer.py
- tabular/tests/conftest.py
- tabular/tests/unittests/models/test_lightgbm.py
- Adds ability to disable fitting the weighted ensemble. This is useful when the user does not wish to use any kind of ensembled solution.
> Add fit_weighted_ensemble toggle

- docs/index.rst
- docs/static/managed_solutions.html
- docs/tutorials/cloud_fit_deploy/index.rst
- docs/tutorials/index.rst
> Fix autopilot link

- docs/index.rst
- docs/tutorials/cloud_fit_deploy/autopilot-autogluon.md
> side banner and one more link

- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/utils.py
Add one util function to infer precision. Reduce boilerplate code.
> Add precision inference

- .github/workflows/codeguru-reviewer.yml
> Codeguru Master Branch Only

- multimodal/src/autogluon/multimodal/data/datamodule.py
- multimodal/src/autogluon/multimodal/data/utils.py
- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/utils.py
- multimodal/tests/unittests/test_predictor.py
1. Enable realtime inference without trainer. This can reduce 10x inference time in the online deployment scenario where each time only a small batch comes for inference.
2. Add unit tests.
3. Add one util to move objects to device.
4. Move `get_collate_fn ` outside of `datamodule` to make it easier to use in more places.
Below are some initial performance comparisons with the electra-base model on the SST dataset.
Default prediction time:
batch size 1, inference time 0.6611239910125732
batch size 2, inference time 0.6466214656829834
batch size 3, inference time 0.6647155284881592
batch size 4, inference time 0.6407644748687744
batch size 5, inference time 0.6691045761108398
batch size 6, inference time 0.6658930778503418
batch size 7, inference time 0.6808614730834961
batch size 8, …
> Enable realtime inference in AutoMM

- cloud/src/autogluon/cloud/predictor/cloud_predictor.py
- cloud/src/autogluon/cloud/utils/aws_utils.py
* Noticed cloud predictor would encounter throttling issue when training multiple predictors in parallel. Add custom configuration to ease this issue.
> [Cloud] Sagemaker Session Config

- docs/tutorials/multimodal/customization.md
- examples/automm/kaggle_feedback_prize/README.md
- examples/automm/kaggle_feedback_prize/kaggle_feedback_prize_preprocess.py
- examples/automm/kaggle_feedback_prize/kaggle_feedback_prize_submit.py
- examples/automm/kaggle_feedback_prize/kaggle_feedback_prize_train.py
- multimodal/setup.py
- multimodal/src/autogluon/multimodal/configs/data/default.yaml
- multimodal/src/autogluon/multimodal/data/process_text.py
- multimodal/src/autogluon/multimodal/data/utils.py
- multimodal/src/autogluon/multimodal/utils.py
*Issue #2036 
This PR adds a text normalization option to multimodal `TextProcessor` to incorporate the suggestion proposed in the issue
> Add normalize_text option

- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/utils/__init__.py
- multimodal/src/autogluon/multimodal/utils/inference.py
- multimodal/tests/unittests/test_object_detection.py
- multimodal/tests/unittests/test_text_detection.py
- multimodal/tests/unittests/test_text_recognition.py
*Issue #2143*
1. Add `use_realtime()` to infer whether to use the realtime inference. The current inference is based on the sample number and data modalities.
3. Temporarily turn realtime off for mmcv models. Need to fix bugs later.
Some results on the text+tabular benchmarks:
Format:
"realtime_{batch size}": inference time (seconds)
"default_{batch size}": inference time (seconds)
AE dataset with model electra-base:
"realtime_1": 0.2978856563568115,
"default_1": 0.7800061702728271,
"realtime_10": 0.41648244857788086,
"default_10": 0.9077305793762207,
"realtime_100": 1.4684016704559326, 
"default_100": 2.094505786895752,
"realtime_200": 2.719512462615967,
"default_200": 3.2722744941711426,
"realtime_300": 3.9930036067962646,
"default_300": 4.402777433395386
AE dataset with model …
> Automate realtime inference

- docs/tutorials/cloud_fit_deploy/cloud-aws-sagemaker-deployment.md
- docs/tutorials/cloud_fit_deploy/cloud-aws-sagemaker-training.md
* Added info on how to train/deploy/batch inference with other predictor types.
* Updated the doc to reflect latest changes.
> [Docs] Refine Cloud Tutorials

- docs/tutorials/timeseries/forecasting-indepth.md
The in depth tutorial looks great thanks @shchur ! Just a few minor edits. 
> Minor edits to time series in depth tutorial

- multimodal/setup.py
* Had a hard dependency of protobuf because our dependencies didn't handle protobuf well when it had a major version upgrade. Try removing it now
> Try Removing Protobuf as A Direct Dependency

- docs/tutorials/multimodal/index.rst
- docs/tutorials/multimodal/semantic_search.md
This PR provides a tutorial for implementing different search ranking scoring methods, i.e. BM25, semantic embedding, and the proposed `Hybrid BM25`.
> Semantic Search Tutorial

- core/setup.py
- core/src/autogluon/core/hpo/executors.py
- core/src/autogluon/core/hpo/ray_hpo.py
- core/src/autogluon/core/hpo/ray_tune_searcher_factory.py
- core/src/autogluon/core/models/abstract/model_trial.py
- core/src/autogluon/core/utils/try_import.py
- core/tests/unittests/hpo/test_ray_hpo.py
- docs/requirements_doc.txt
- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/utils/config.py
* Upgrade ray to 2.0 and adapted new API. Three things need to be addressed in a later PR (notes for @yinweisu):
* checkpoint warning from ray tune
* analysis warning from ray tune
* check compatibility with PL 1.7 and update multimodal accordingly. Then enable the tests
> Upgrade to Ray 2.0

- .github/workflow_scripts/env_setup.sh
- .github/workflow_scripts/test_eda.sh
- .github/workflows/continuous_integration.yml
- .github/workflows/platform_tests-command.yml
> [eda] CI workflow changes

- .github/actions/submit-job/action.yml
> [CI] Increase CI role session time

- .github/workflow_scripts/env_setup.sh
- .github/workflow_scripts/test_eda.sh
- .gitignore
- eda/setup.py
- eda/src/autogluon/__init__.py
- eda/src/autogluon/eda/__init__.py
- eda/src/autogluon/eda/analysis/__init__.py
- eda/src/autogluon/eda/analysis/base.py
- eda/src/autogluon/eda/state.py
- eda/src/autogluon/eda/visualization/__init__.py
- eda/src/autogluon/eda/visualization/base.py
- eda/src/autogluon/eda/visualization/jupyter.py
- eda/src/autogluon/eda/visualization/layouts.py
- eda/tests/conftest.py
- eda/tests/test_check_style.py
- eda/tests/unittests/analysis/test_base.py
- eda/tests/unittests/test_state.py
- eda/tests/unittests/visualization/test_base.py
- full_install.sh
- setup.cfg
Added basic constructs and APIs for EDA package
> [eda] Initial PR to add constructs

- core/src/autogluon/core/hpo/ray_hpo.py
- core/src/autogluon/core/models/ensemble/fold_fitting_strategy.py
* Suppress ray 2.0 incorrectly generated warnings per ray team suggestion because there are warnings being incorrectly produced.
> suppress ray warning

- .github/workflows/continuous_integration.yml
* Forgot to add eda as a dependency of doc building stage. Add it now.
> [CI] Add eda in dependency graph

- .github/workflow_scripts/test_common.sh
- common/setup.py
- common/src/autogluon/common/features/feature_metadata.py
- common/src/autogluon/common/features/infer_types.py
- common/src/autogluon/common/loaders/_utils.py
- common/src/autogluon/common/loaders/load_pd.py
- common/src/autogluon/common/loaders/load_pkl.py
- common/src/autogluon/common/loaders/load_pointer.py
- common/src/autogluon/common/loaders/load_s3.py
- common/src/autogluon/common/savers/save_json.py
- common/src/autogluon/common/savers/save_pd.py
- common/src/autogluon/common/savers/save_pkl.py
- common/src/autogluon/common/savers/save_pointer.py
- common/src/autogluon/common/utils/log_utils.py
- common/src/autogluon/common/utils/pandas_utils.py
- common/src/autogluon/common/utils/s3_utils.py
- common/src/autogluon/common/utils/utils.py
- common/tests/conftest.py
- common/tests/unittests/test_common.py
- common/tests/unittests/test_compression_utils.py
- common/tests/unittests/test_log_utils.py
- common/tests/unittests/test_setup_outputdir.py
- common/tests/unittests/utils/test_compare_autogluon_metadata.py
- core/setup.py
- core/tests/conftest.py
- eda/src/autogluon/eda/__init__.py
Code quality improvements: flake8 and mypy fixes
Enable mypy enforcement
> [code quality] flake8 + mypy checks

- cloud/src/autogluon/cloud/predictor/cloud_predictor.py
- cloud/src/autogluon/cloud/utils/constants.py
- cloud/src/autogluon/cloud/utils/iam.py
* Add prefix to sagemaker tasks to scope down permission even more
> [Cloud] Add Prefix to SageMaker Tasks to Scope Down Permission

- cloud/src/autogluon/cloud/job/sagemaker_job.py
- cloud/src/autogluon/cloud/predictor/cloud_predictor.py
- cloud/src/autogluon/cloud/utils/constants.py
* Handle SageMaker local mode where apis to fetch job related info are unavailable.
> [Cloud] SageMaker Local Mode

- docs/tutorials/image_prediction/index.rst
- docs/tutorials/object_detection/index.rst
- vision/src/autogluon/vision/detector/detector.py
- vision/src/autogluon/vision/predictor/predictor.py
NA
Add deprecation warning for AutoGluon vision module, and suggest users to switch to MultiModalPredictor for a more unified API.
> Add deprecation warning for AutoGluon vision module

- timeseries/src/autogluon/timeseries/learner.py
- timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
- timeseries/src/autogluon/timeseries/models/abstract/model_trial.py
- timeseries/src/autogluon/timeseries/models/statsmodels/abstract_statsmodels.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/src/autogluon/timeseries/trainer/abstract_trainer.py
- Improve wording for several logger outputs & make the wording consistent across the library (e.g., HPO vs. single model training)
> Fix logger messages for time series

- .github/workflow_scripts/env_setup.sh
- .github/workflow_scripts/test_eda.sh
- eda/setup.cfg
- eda/setup.py
- eda/src/autogluon/eda/auto/simple.py
[eda][code quality] enabled tox
> [eda][code quality] enabled tox

- multimodal/src/autogluon/multimodal/utils/data.py
- multimodal/tests/unittests/test_ner.py
Fix the dataprocessor nonetype issue 
> fix hpo issue for NER

- cloud/src/autogluon/cloud/predictor/cloud_predictor.py
- common/src/autogluon/common/utils/utils.py
- core/src/autogluon/core/hpo/executors.py
- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
> Replace string concatenation of path to os.path.join

- .github/workflow_scripts/test_eda.sh
- eda/src/autogluon/eda/analysis/base.py
- eda/src/autogluon/eda/analysis/dataset.py
- eda/src/autogluon/eda/analysis/missing.py
- eda/src/autogluon/eda/analysis/shift.py
- eda/src/autogluon/eda/analysis/transform.py
- eda/src/autogluon/eda/auto/simple.py
- eda/src/autogluon/eda/state.py
- eda/src/autogluon/eda/visualization/base.py
- eda/src/autogluon/eda/visualization/dataset.py
- eda/src/autogluon/eda/visualization/jupyter.py
- eda/src/autogluon/eda/visualization/layouts.py
- eda/src/autogluon/eda/visualization/missing.py
- eda/src/autogluon/eda/visualization/shift.py
- eda/tests/conftest.py
- eda/tests/test_check_style.py
- eda/tests/unittests/analysis/test_base.py
- eda/tests/unittests/analysis/test_dataset.py
- eda/tests/unittests/analysis/test_missing.py
- eda/tests/unittests/analysis/test_transform.py
- eda/tests/unittests/auto/test_simple.py
- eda/tests/unittests/test_shift.py
- eda/tests/unittests/test_state.py
- eda/tests/unittests/visualization/test_base.py
- eda/tests/unittests/visualization/test_dataset.py
- eda/tests/unittests/visualization/test_missing.py
Applied black formatter; enabled build-time format check.
> [eda][code cleanup] Enabled formatter

- timeseries/tests/unittests/test_trainer.py
Fix previously failing test on name collisions, adding test case for most pathological cases currently possible. 
> [timeseries] fix trainer name collision test

- common/tests/unittests/test_setup_outputdir.py
- eda/tests/unittests/analysis/test_transform.py
- multimodal/tests/unittests/test_save_path.py
> Fixed platform tests

- multimodal/src/autogluon/multimodal/data/utils.py
- multimodal/src/autogluon/multimodal/models/ner_text.py
1. Some checkpoints do not specify the model_max_length
2. Some tokenizers treat space in sentences differently
1. We specify model_max_length in the model.
2. We resolved the inconsistency.
> [NER] fix issues with some checkpoints 

- core/src/autogluon/core/metrics/__init__.py
- core/src/autogluon/core/metrics/classification_metrics.py
- core/tests/unittests/metrics/test_classification_metrics.py
- Optimized roc_auc_scorer to be 5x faster with no downside on binary problems.
> Optimized roc_auc_scorer speed by 5x

- multimodal/src/autogluon/multimodal/models/utils.py
This PR handles corner case that some timm models has multi-layer head.
> handle multi-layer head

- docs/tutorials/multimodal/advanced_topics/efficient_finetuning_basic.md
- multimodal/tests/unittests/test_predictor.py
> Accelerate tutorial + CI

- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/utils/utils.py
- core/src/autogluon/core/utils/version_utils.py
- core/tests/unittests/hpo/test_ray_hpo.py
- core/tests/unittests/test_parallel_local_folding.py
- tabular/src/autogluon/tabular/models/_utils/rapids_utils.py
- tabular/src/autogluon/tabular/models/automm/automm_model.py
- tabular/src/autogluon/tabular/models/catboost/catboost_model.py
- tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
- tabular/src/autogluon/tabular/models/image_prediction/image_predictor.py
- tabular/src/autogluon/tabular/models/knn/knn_model.py
- tabular/src/autogluon/tabular/models/lgb/lgb_model.py
- tabular/src/autogluon/tabular/models/tabular_nn/torch/tabular_nn_torch.py
- tabular/src/autogluon/tabular/models/text_prediction/text_prediction_v1_model.py
- tabular/src/autogluon/tabular/models/xgboost/xgboost_model.py
- tabular/tests/conftest.py
- tabular/tests/unittests/resource_allocation/test_resources_mocking.py
- tabular/tests/unittests/resource_allocation/test_total_resource_allocation.py
- text/src/autogluon/text/text_prediction/mx/models.py
- vision/src/autogluon/vision/_gluoncv/image_classification.py
- vision/src/autogluon/vision/_gluoncv/object_detection.py
- vision/src/autogluon/vision/configs/presets_configs.py
- vision/src/autogluon/vision/detector/detector.py
- vision/src/autogluon/vision/predictor/predictor.py
* Add resource manager to report sys info for easier mocking in the unit tests.
* Updated unit test mocking method
> Resource Manager

- docs/tutorials/multimodal/advanced_topics/efficient_finetuning_basic.md
- docs/tutorials/tabular_prediction/tabular-faq.md
- docs/tutorials/tabular_prediction/tabular-gpu.md
* Updated doc about how to control resources provided to AG
* Added section on advance resource control
> [Doc] Tabular Resource Doc Updates

- multimodal/src/autogluon/multimodal/data/process_ner.py
- multimodal/src/autogluon/multimodal/models/ner_text.py
- multimodal/src/autogluon/multimodal/utils/data.py
- multimodal/tests/unittests/test_matcher.py
allow user specified max length
> fix max len issue

- docs/tutorials/multimodal/matching/image_text_matching.md
- docs/tutorials/multimodal/matching/index.rst
> Image text matching tutorial

- docs/tutorials/multimodal/advanced_topics/hyperparameter_optimization.md
- docs/tutorials/multimodal/advanced_topics/index.rst
> add automm hpo tutorial

- docs/tutorials/multimodal/matching/image2image_matching.md
- docs/tutorials/multimodal/matching/index.rst
NA
Add image2image matching tutorial using Stanford Online Products dataset.
> Image-to-image matching tutorial

- .github/workflow_scripts/env_setup.sh
- .github/workflow_scripts/test_install.sh
- .github/workflows/platform_tests-command.yml
https://github.com/awslabs/autogluon/issues/2368
* Added build step in `install` tests
* `platform_test` won't take effect before merging. Need to merge then have a follow-up PR to check if it's working...
> [CI] Add building test to CI

- docs/tutorials/multimodal/matching/semantic_search.md
Refactor the text semantic search tutorial with the matcher APIs.
> Refactor text semantic search tutorial

- tabular/src/autogluon/tabular/models/automm/ft_transformer.py
Modified default parameters for FTT as discussed with Nick
> Modified default parameters for FTT

- docs/tutorials/multimodal/object_detection/data_preparation/prepare_coco17.md
- docs/tutorials/multimodal/object_detection/data_preparation/prepare_voc.md
- docs/tutorials/multimodal/object_detection/evaluation/detection_eval_fasterrcnn_voc.md
- docs/tutorials/multimodal/object_detection/evaluation/detection_eval_yolov3_coco.md
NA
Update some hyperlinks. And change python file link to raw content link, so that users can directly download or copy the link.
> Update tutorial links

- tabular/src/autogluon/tabular/models/automm/automm_model.py
- tabular/src/autogluon/tabular/models/automm/ft_transformer.py
- Fix FTTransformer errors, add max_features
- path was not defined, caused error when fitting, now using self.path
- Now warn when no GPU
- Now skip fitting if >300 features, to avoid OOM
- Created https://github.com/awslabs/autogluon/issues/2390 to track hack
> Fix FTTransformer errors, add max_features

- multimodal/src/autogluon/multimodal/predictor.py
> Create save_path in init and remove warning in fit

- docs/tutorials/timeseries/forecasting-faq.md
- docs/tutorials/timeseries/forecasting-indepth.md
- docs/tutorials/timeseries/forecasting-quickstart.md
- Use M4-hourly dataset in the quickstart tutorial
- Use M4-daily dataset in in-depth tutorial to showcase static and dynamic features
- Update tutorial contents to reflect the current state of the library
> [timeseries] Update the quickstart and in-depth tutorials

- docs/install-include.rst
- docs/install-macos-apple-silicon.rst
- docs/install-macos-no-gpu.rst
Added information regarding Apple Silicon M1/M2 hardware discussions.
> [docs] Apple Silicon Instructions

- multimodal/src/autogluon/multimodal/configs/environment/default.yaml
- multimodal/src/autogluon/multimodal/data/infer_types.py
- multimodal/src/autogluon/multimodal/data/labelencoder_ner.py
- multimodal/src/autogluon/multimodal/presets.py
- multimodal/src/autogluon/multimodal/utils/metric.py
> Remove warnings

- docs/tutorials/multimodal/index.rst
> Fix multimodal tutorial index link

- multimodal/src/autogluon/multimodal/data/process_image.py
- multimodal/src/autogluon/multimodal/models/mmdet_image.py
- multimodal/src/autogluon/multimodal/models/utils.py
- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/utils/__init__.py
> Remove warnings and duplicate function

- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/tests/unittests/others/test_zero_shot.py
Fix the bug that `dp` is not supported in CPU-only instance
> Fix cpu inference bug

- multimodal/src/autogluon/multimodal/presets.py
> Fix NER best quality preset

- docs/tutorials/multimodal/advanced_topics/hyperparameter_optimization.md
- docs/tutorials/multimodal/image_prediction/beginner_image_cls.md
- multimodal/src/autogluon/multimodal/utils/__init__.py
- multimodal/src/autogluon/multimodal/utils/misc.py
NA
This PR is to remove dependency on vision.imagedataset in tutorials.
> Remove dependency on vision.imagedataset

- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- tabular/src/autogluon/tabular/configs/hyperparameter_configs.py
- tabular/src/autogluon/tabular/configs/presets_configs.py
- tabular/src/autogluon/tabular/models/automm/automm_model.py
- tabular/src/autogluon/tabular/models/automm/ft_transformer.py
- Add FTT preset as experimental
- Add logic to enable FTT parallel with ray during bagging if no GPU is present.
> FTT preset

- multimodal/src/autogluon/multimodal/utils/save.py
- multimodal/tests/unittests/others/test_save_path.py
> [Release 0.6] [Multimodal] Check if folder is empty before raise

- docs/ReleaseInstructions.md
- docs/whats_new/v0.6.0.md
> 0.6.0 Release notes

- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/tests/unittests/others/test_object_detection.py
> Add finetune/eval tests for AutoMM detection

- docs/tutorials/timeseries/timeseries_quick_start.ipynb
- docs/tutorials/timeseries/timeseries_quick_start.md
- Update the time series quickstart notebook (`timeseries_quick_start.ipynb`) to correctly collapse sections
- Add notebook in markdown format
> Update timeseries quick start notebook

- .github/workflow_scripts/test_fair.sh
> [CI][Fair] Add path check for fair

- docs/api/index.rst
- docs/cheatsheet.rst
- docs/index.rst
- docs/root_index.html
- docs/tutorials/timeseries/forecasting-quickstart.md
> add time series cheat sheet, add time series to doc titles

- README.md
> security test

- README.md
Reverts autogluon/autogluon#2480
> Revert "security test"

- .github/actions/setup-env-vars/action.yml
> [CI][security] fixes to env variables in CI

- eda/src/autogluon/eda/analysis/__init__.py
- eda/src/autogluon/eda/analysis/base.py
- eda/src/autogluon/eda/analysis/dataset.py
- eda/src/autogluon/eda/analysis/interaction.py
- eda/src/autogluon/eda/analysis/missing.py
- eda/src/autogluon/eda/analysis/shift.py
- eda/src/autogluon/eda/visualization/__init__.py
- eda/src/autogluon/eda/visualization/interaction.py
- eda/tests/unittests/analysis/test_interaction.py
- eda/tests/unittests/visualization/test_interaction.py
This change introduces Correlation and Correlation Significance Analysis
```python
import autogluon.eda.analysis as eda
import autogluon.eda.visualization as viz
state = auto.analyze(
train_data=df_train, label=target_col, return_state=True,
anlz_facets=[eda.interaction.Correlation(method='spearman')],
viz_facets=[viz.interaction.CorrelationVisualization(headers=True)]
)
```
We can also add focus so that only with correlations with absolute value greater than threshold are displayed:
```python
state = auto.analyze(
train_data=df_train, label=target_col, return_state=True,
anlz_facets=[eda.interaction.Correlation(method='spearman', focus_field='Fare', focus_field_threshold=0.4)], …
```
> [eda] Correlation and Correlation Significance Analysis

- cloud/setup.py
* Remove opencv dependency as it's not used anymore
> [Cloud] Remove opencv

- tabular/setup.py
> [MERGE BEFORE 0.6.1] Cap imodel version

- features/src/autogluon/features/generators/datetime.py
Fix int32/int64 difference between windows and other platforms; fix inputs mutation issue
> Fix int32/int64 difference between windows and other platforms; fix inputs mutation issue

- docs/tutorials/tabular_prediction/tabular-faq.md
> [Doc] Ray FAQ

- multimodal/src/autogluon/multimodal/data/collator.py
- multimodal/src/autogluon/multimodal/data/process_categorical.py
- multimodal/src/autogluon/multimodal/data/process_image.py
- multimodal/src/autogluon/multimodal/data/process_label.py
- multimodal/src/autogluon/multimodal/data/process_ner.py
- multimodal/src/autogluon/multimodal/data/process_numerical.py
- multimodal/src/autogluon/multimodal/data/process_text.py
- multimodal/src/autogluon/multimodal/data/utils.py
- multimodal/tests/unittests/others/test_data_collator.py
Some previous collator names, e.g., Dict and List, have conflicts with the type hint names.
Update the collator names to avoid the conflicts.
> [Merge after 0.6.1]Update collator names

- cloud/src/autogluon/cloud/predictor/cloud_predictor.py
> [Cloud] Logging Fix for Custom Image

- multimodal/setup.py
- tabular/setup.py
Upgrade onnx version to 1.13.x
> Upgrade onnx version to 1.13.x

- core/src/autogluon/core/utils/utils.py
- Add defensive assert to split code for problem type argument
> [Post 0.6] Add defensive assert to split code

- multimodal/src/autogluon/multimodal/cli/voc2coco.py
- multimodal/src/autogluon/multimodal/predictor.py
- Remove image without bounding boxes from annotation file to speed up mAP calculation.
- Fix a bug in image path extraction
> Fix COCO dataset conversion CLI tool for AutoMM detection

- tabular/setup.py
https://github.com/csinva/imodels/issues/147 The maintainer of imodels added `complexity_` back in 1.3.9
> Update imodels cap

- docs/tutorials/timeseries/forecasting-indepth.md
> Fix typo: spitter -> splitter

- .github/workflow_scripts/build_object_detection_tutorial.sh
- .github/workflow_scripts/build_tabular_prediction_tutorial.sh
- .github/workflow_scripts/build_text_prediction_tutorial.sh
- .github/workflow_scripts/build_timeseries_tutorial.sh
- .github/workflow_scripts/env_setup.sh
- .github/workflow_scripts/test_install.sh
- .github/workflow_scripts/test_multimodal_others.sh
- .github/workflow_scripts/test_multimodal_predictor.sh
- .github/workflow_scripts/test_tabular.sh
- .github/workflow_scripts/test_text.sh
- .github/workflow_scripts/test_timeseries.sh
- CI/batch/docker/Dockerfile.cpu
- CI/batch/docker/Dockerfile.gpu
- CI/docker/Dockerfile.cpu-inference
- CI/docker/Dockerfile.cpu-training
- CI/docker/Dockerfile.gpu-inference
- CI/docker/Dockerfile.gpu-training
- docs/install-cpu-pip.rst
- docs/install-cpu-source.rst
- docs/install-gpu-pip-windows.rst
- docs/install-gpu-pip.rst
- docs/install-gpu-source-windows.rst
- docs/install-gpu-source.rst
- docs/install-windows-gpu.rst
Updating torch in containers to address security issues.
> [CI][security] update torch

- eda/setup.py
- eda/src/autogluon/eda/analysis/__init__.py
- eda/src/autogluon/eda/analysis/interaction.py
- eda/src/autogluon/eda/auto/__init__.py
- eda/src/autogluon/eda/auto/simple.py
- eda/src/autogluon/eda/visualization/__init__.py
- eda/src/autogluon/eda/visualization/interaction.py
- eda/tests/unittests/analysis/test_interaction.py
- eda/tests/unittests/visualization/test_interaction.py
This change introduces Feature Interaction Analysis
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1OsX0ASnXpCRXQuEuB_j59JIr7wP7ZBWy?usp=sharing)
`key` is used to link analysis and visualization - this allows to have multiple analyses/visualizations in one composite analysis; other variables are passed as `x`, `y` and `hue`. Depending on the variable types combination in `x`/`y`/`hue`, different types of charts will be selected:
```python
import autogluon.eda.analysis as eda
import autogluon.eda.visualization as viz
auto.analyze(train_data=df_train, anlz_facets=[
eda.dataset.RawTypesAnalysis(),
eda.interaction.FeatureInteraction(key='categorical', …
```
> [eda] Feature Interaction Analysis

- tabular/src/autogluon/tabular/models/tabular_nn/compilers/onnx.py
https://github.com/autogluon/autogluon/actions/runs/3747457242/jobs/6363705204
fix windows int32 issue on skl2onnx
> [Tabular][Bugfix] Fix windows int32 issue on skl2onnx

- eda/setup.cfg
- eda/setup.py
- eda/src/autogluon/eda/analysis/__init__.py
- eda/src/autogluon/eda/analysis/base.py
- eda/src/autogluon/eda/analysis/dataset.py
- eda/src/autogluon/eda/analysis/interaction.py
- eda/src/autogluon/eda/analysis/missing.py
- eda/src/autogluon/eda/analysis/model.py
- eda/src/autogluon/eda/analysis/shift.py
- eda/src/autogluon/eda/analysis/transform.py
- eda/src/autogluon/eda/auto/simple.py
- eda/src/autogluon/eda/visualization/__init__.py
- eda/src/autogluon/eda/visualization/dataset.py
- eda/src/autogluon/eda/visualization/interaction.py
- eda/src/autogluon/eda/visualization/jupyter.py
- eda/src/autogluon/eda/visualization/layouts.py
- eda/src/autogluon/eda/visualization/missing.py
- eda/src/autogluon/eda/visualization/model.py
- eda/src/autogluon/eda/visualization/shift.py
- eda/tests/test_check_style.py
- eda/tests/unittests/analysis/test_dataset.py
- eda/tests/unittests/analysis/test_interaction.py
- eda/tests/unittests/visualization/test_interaction.py
- eda/tests/unittests/visualization/test_model.py
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1Oecs3fBI5QqHCMwjl34ZylAy1oVE5REm?usp=sharing)
The component performs feature correlation distance analysis using Spearman rank correlation and hierarchical clustering for the data passed in `train_data` excluding `label`. The near duplicates grouping is automatically suggested given `near_duplicates_threshold`.The results can be visualized using `FeatureDistanceAnalysisVisualization`.
Note: it is recommended to apply `ApplyFeatureGenerator` before the analysis to ensure correlations are calculated for categorical variables.
```
Parameters
----------
near_duplicates_threshold: float, default = 0.01
defines feature distance to be considered as near …
```
> [eda] Feature Interaction - Feature Distance

- core/src/autogluon/core/models/abstract/abstract_model.py
- Improve resource error readability
- Additionally added specific messages for errors when system resources are not sufficient.
- Added sanity check that system resources are >= the planned resources to use
> Improve resource error readability

- .github/workflow_scripts/copy_docs.sh
* Excluded the incorrect file. Should be html
> [CI] Minor fix of cloud exclude

- core/src/autogluon/core/calibrate/temperature_scaling.py
> [Tabular] Fix int32/int64 difference on windows for calibration

- tabular/tests/unittests/models/test_tabular_nn.py
(cherry picked from commit 4473a5ae77ca78be18488043bb968af76b739b5e)
#2650
Testing with good_quality to ensure tabularNN work well with ParallelLocalFoldFittingStrategy
> [tabular] test good_quality with tabularNN

- tabular/tests/unittests/models/test_tabular_nn.py
fix good_quality related ci failure
> [tabular] fix good_quality related ci failure

- docs/tutorials/multimodal/text_prediction/ner.md
- multimodal/src/autogluon/multimodal/constants.py
- multimodal/src/autogluon/multimodal/data/labelencoder_ner.py
- multimodal/src/autogluon/multimodal/optimization/utils.py
- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/utils/metric.py
1. Change validation loss to F1 loss.
> [NER] Change Validation loss to F1

- core/setup.py
- core/src/autogluon/core/_setup_utils.py
- tabular/setup.py
- timeseries/setup.py
fixes autogluon build on MacOS 12.6 and Arm64
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of Apache-2.0 license.
> allow psutil < 6

- tabular/src/autogluon/tabular/trainer/auto_trainer.py
#2666
- Improve logging of use_bag_holdout logic
> Improve logging of use_bag_holdout logic

- docs/README.md
- docs/tutorials/multimodal/text_prediction/ner.md
- multimodal/src/autogluon/multimodal/data/labelencoder_ner.py
- multimodal/src/autogluon/multimodal/utils/misc.py
- multimodal/tests/unittests/others/test_ner_chinese.py
- multimodal/tests/unittests/others/test_utils.py
Improve the NER visualization tool to accept json-encoded string.
Improve document
> [Doc] Improve NER visualization + document

- core/src/autogluon/core/_setup_utils.py
- docs/build.yml
- docs/build_contrib.yml
- docs/build_contrib_gpu.yml
- docs/build_gpu.yml
- pyproject.toml
#2686 
- WIP PR to add Python 3.10 Support, currently untested
> [WIP] Add Python 3.10 Support

- multimodal/src/autogluon/multimodal/utils/misc.py
- multimodal/tests/unittests/others/test_utils.py
> [NER] fix an issue in merging BIO data

- multimodal/src/autogluon/multimodal/matcher.py
- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/utils/__init__.py
- multimodal/src/autogluon/multimodal/utils/data.py
Add util `split_train_tuning_data()` to support both predictor and matcher.
> [AutoMM] Refactor splitting train/val data

- docs/badges.rst
- docs/index.rst
**Prior to the change**
**Post the change**
> [stable website] updated the doc release badge version to 0.6.2

- .github/workflows/continuous_integration.yml
* Tested [here](https://github.com/yinweisu/hello-github-actions/actions/runs/3952970490/jobs/6768697769)
> [CI] Add branch check

- .github/workflows/continuous_integration.yml
> [CI] Fix branch check

- core/src/autogluon/core/_setup_utils.py
- pyproject.toml
> Drop Python 3.7 Support

- tabular/src/autogluon/tabular/models/automm/automm_model.py
- tabular/src/autogluon/tabular/models/image_prediction/image_predictor.py
ImagePredictor was not properly trained in multimodal preset after the transition to MultiModalPredictor.
This issue wasn't caught by our unit test because it doesn't crash AG training. An example for the failure could be found in our [documentation site](http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-2731/579b5dd/tutorials/tabular_prediction/tabular-multimodal.html) 
* Filtered the dataframe to contain only image features prior to call `_fit`
> [Tabular] Fix ImagePredictor

- .github/workflows/README.md
- .github/workflows/pypi_release.yml
- .github/workflows/pythonpublish.yml
- .github/workflows/pythonpublish_testpypi.yml
- autogluon/setup.py
- docs/tutorials/multimodal/object_detection/data_preparation/prepare_pothole.md
#2695 
- Remove autogluon.text PyPi release
- Release and dependency cleanup PR prior to code removal
> Remove autogluon.text PyPi release

- .github/workflow_scripts/copy_docs.sh
- docs/tutorials/cloud_fit_deploy/autogluon-cloud.md
> [Web] Link cloud tutorial to the new link

- docs/tutorials/tabular_prediction/tabular-multimodal.md
#2744 was impacted by tabular-multimodal running into timeout error.
Reduce runtime of tabular-multimodal tutorial
> Reduce tabular-multimodal tutorial runtime

- .github/workflow_scripts/copy_docs.sh
- docs/tutorials/cloud_fit_deploy/autogluon-cloud.md
> Add cloud tutorial to stable

- .github/workflows/pythonpublish.yml
- .github/workflows/pythonpublish_testpypi.yml
Enabled nightly pypi builds for eda
> [eda] enable nightly pypi builds

- timeseries/src/autogluon/timeseries/models/autogluon_tabular/tabular_model.py
- Obtain the quantiles using the empirical distribution of the residuals (instead of fitting a 0-mean normal distribution to the residuals)
> [timeseries] Obtain quantiles for the tabular model using the empirical distribution

- .github/workflow_scripts/build_eda_tutorial.sh
- .github/workflows/continuous_integration.yml
- docs/tutorials/eda/eda-auto-dataset-overview.md
- docs/tutorials/eda/index.rst
> [WIP][DO NOT MERGE][EDA] docs

- multimodal/setup.py
Relevant to conda support of multimodal: https://github.com/autogluon/autogluon/issues/612#issuecomment-1409349122
> [Version] Loose version bound of nlpaug

- eda/src/autogluon/eda/analysis/base.py
- eda/src/autogluon/eda/analysis/dataset.py
- eda/src/autogluon/eda/analysis/interaction.py
- eda/src/autogluon/eda/analysis/missing.py
- eda/src/autogluon/eda/analysis/shift.py
- eda/src/autogluon/eda/analysis/transform.py
- eda/src/autogluon/eda/visualization/layouts.py
Apply updated `black` formatting rules
> Apply updated formatting rules

- multimodal/src/autogluon/multimodal/models/fusion.py
- multimodal/src/autogluon/multimodal/models/huggingface_text.py
- multimodal/src/autogluon/multimodal/models/ner_text.py
- multimodal/src/autogluon/multimodal/models/timm_image.py
- multimodal/src/autogluon/multimodal/models/utils.py
- multimodal/src/autogluon/multimodal/optimization/lit_distiller.py
- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/utils/onnx.py
- multimodal/tests/unittests/others/test_deployment.py
enable jit.trace and export HF_TEXT model to onnx
> [multimodal] enable jit.trace and export HF_TEXT model to onnx

- autogluon/setup.py
- full_install.sh
* Previous PR: https://github.com/autogluon/autogluon/pull/2803 didn't remove vision from autogluon setup.py
> Remove vision from autogluon setup.py

- tabular/setup.py
- Fix torch version range, support 1.13
- Increase lower bound to 1.9
> Fix torch version range, support 1.13

- tabular/setup.py
#2821 
- Include ray in tabular[all] install
> Include ray in tabular[all] install

- .github/workflow_scripts/build_eda_tutorial.sh
- .github/workflows/continuous_integration.yml
- docs/build_pip_install.sh
- docs/index.rst
- docs/tutorials/eda/eda-auto-analyze-interaction.md
- docs/tutorials/eda/eda-auto-covariate-shift.md
- docs/tutorials/eda/eda-auto-dataset-overview.md
- docs/tutorials/eda/eda-auto-quick-fit.md
- docs/tutorials/eda/eda-auto-target-analysis.md
- docs/tutorials/eda/index.rst
- docs/tutorials/index.rst
- eda/src/autogluon/eda/auto/__init__.py
- eda/src/autogluon/eda/auto/simple.py
- eda/src/autogluon/eda/visualization/dataset.py
- eda/src/autogluon/eda/visualization/interaction.py
- eda/src/autogluon/eda/visualization/jupyter.py
- eda/src/autogluon/eda/visualization/missing.py
- eda/src/autogluon/eda/visualization/shift.py
- eda/tests/unittests/auto/test_simple.py
- eda/tests/unittests/visualization/test_interaction.py
- eda/tests/unittests/visualization/test_missing.py
- eda/tests/unittests/visualization/test_model.py
See docs here: https://auto.gluon.ai/2023_01_25_eda_docs/tutorials/eda/index.html
- [doc]Missing values analysis + visualization/formatting fixes
- [doc] analyze_interaction showcase tutorial
- [doc] Added Covariate Shift Analysis
- [doc]Added quick-fit tutorial
- [doc] Target variable analysis tutorial
- [fix] Formatting fixes for shift
- [fix] Removed not useful information
- [CI] resolve tox-awscli dependencies conflict
> [eda][docs] Tutorials and UX improvements

- .github/workflow_scripts/env_setup.sh
- .github/workflows/pypi_release.yml
- .github/workflows/pythonpublish.yml
- .github/workflows/pythonpublish_testpypi.yml
- add `autogluon.eda` package to release scripts 
- update python version of the workflow
> [eda][build] enable autogluon.eda package in release scripts

- .github/workflow_scripts/setup_hf_model_mirror.py
> Quiet aws s3 cp when setting up hf mirror

- eda/setup.py
- eda/src/autogluon/eda/visualization/jupyter.py
- eda/tests/unittests/auto/test_simple.py
- eda/tests/unittests/visualization/test_missing.py
> [eda][build] dependencies cleanup, CI stability fixes, removed unused code

- multimodal/src/autogluon/multimodal/models/fusion/fusion_mlp.py
- multimodal/src/autogluon/multimodal/models/fusion/fusion_transformer.py
- multimodal/src/autogluon/multimodal/models/utils.py
- multimodal/src/autogluon/multimodal/utils/inference.py
#2835
1. Fix multi-gpu inference for `run_model`.
> [AutoMM] Fix multi-gpu realtime inference

- tabular/src/autogluon/tabular/models/rf/rf_model.py
> Fix time_elapsed being 0

- multimodal/src/autogluon/multimodal/constants.py
- multimodal/src/autogluon/multimodal/optimization/utils.py
- multimodal/src/autogluon/multimodal/utils/object_detection.py
Add constants for detection evaluation metrics and parsing the output for pycocotools output. Naming follows torchmetric.
> [multimodal] Refine detection evaluation output

- docs/tutorials/eda/autogluon.eda.auto.rst
- docs/tutorials/eda/autogluon.eda.base-apis.rst
- docs/tutorials/eda/autogluon.eda.dataset.rst
- docs/tutorials/eda/autogluon.eda.interaction.rst
- docs/tutorials/eda/autogluon.eda.missing.rst
- docs/tutorials/eda/autogluon.eda.model.rst
- docs/tutorials/eda/autogluon.eda.shift.rst
- docs/tutorials/eda/autogluon.eda.transform.rst
- docs/tutorials/eda/eda-auto-covariate-shift.md
- docs/tutorials/eda/eda-auto-dataset-overview.md
- docs/tutorials/eda/eda-auto-quick-fit.md
- docs/tutorials/eda/eda-auto-target-analysis.md
- docs/tutorials/eda/index.rst
- eda/src/autogluon/eda/analysis/base.py
- eda/src/autogluon/eda/analysis/interaction.py
- eda/src/autogluon/eda/analysis/model.py
- eda/src/autogluon/eda/analysis/transform.py
- eda/src/autogluon/eda/visualization/missing.py
- Added API doc pages
- link fixes
- docstrings fixes
> [eda]  API docs

- docs/install-faq.rst
#2777 #2572 #2870 
Add documentation to inform users how to upgrade python version in Kaggle in order to correctly install AutoGluon.
> Documentation - Install AG in Kaggle

- multimodal/src/autogluon/multimodal/data/preprocess_dataframe.py
- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/utils/data.py
- multimodal/tests/unittests/others/test_classification.py
- multimodal/tests/unittests/others_2/test_images.py
- multimodal/tests/unittests/predictor/test_predictor.py
#2671 
Support prediction with image path or list.
```
predictor.predict("/path/to/image")
predictor.predict(["/path/to/image_0", "/path/to/image_1", "/path/to/image_2"])
```
> [AutoMM] Support prediction with image str or list

- .github/workflows/platform_tests-command.yml
Expanded platform tests to run different python version
> [WIP][DNM] Expanded platform tests to run different python version

- .github/workflows/platform_tests-command.yml
> Expanded platform tests to run different python version

- .github/workflows/platform_tests-command.yml
Expanding platform tests to include ubuntu instances. This will enable different python versions testing for linux.
> Adding ubuntu to the platform test matrix

- docs/tutorials/multimodal/advanced_topics/index.rst
- docs/tutorials/multimodal/advanced_topics/presets.md
- docs/tutorials/multimodal/index.rst
> [Tutorial] AutoMM Presets

- tabular/src/autogluon/tabular/models/knn/knn_model.py
- tabular/src/autogluon/tabular/predictor/predictor.py
resolves #1435 
- Add refit_full logging
- Improve logging when KNN memory limit is breached to tell the user the maximum safe percentage.
> Add refit_full logging

- core/setup.py
resolves https://github.com/autogluon/autogluon/issues/2917
> Add hyperopt notes

- .github/workflow_scripts/test_timeseries.sh
- timeseries/tests/smoketests/test_features_and_covariates.py
> [DRAFT] [timeseries] fix smoke tests and remove mxnet from CI

- multimodal/src/autogluon/multimodal/presets.py
> [AutoMM] Lazy import ray

- docs/tutorials/multimodal/document/document_classification.md
- docs/tutorials/multimodal/document/index.rst
- docs/tutorials/multimodal/index.rst
> [Tutorial] Add pre-requisite on Tesseract installation

- docs/tutorials/multimodal/object_detection/finetune/detection_fast_finetune_coco.md
- docs/tutorials/multimodal/object_detection/finetune/detection_high_performance_finetune_coco.md
- docs/tutorials/multimodal/object_detection/quick_start/quick_start_coco.md
- multimodal/tests/hf_model_list.yaml
> [multimodal] [tutorial] update quick start tutorial for detection

- CI/batch/docker/Dockerfile.gpu
> Add tesseract-ocr to CI image

- multimodal/setup.py
- multimodal/src/autogluon/multimodal/matcher.py
- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/utils/__init__.py
- multimodal/src/autogluon/multimodal/utils/environment.py
resolves #2934 
Refer to PR: https://github.com/Lightning-AI/lightning/pull/16147
> [AutoMM] Fix a lightning warning

- docs/install-cpu-pip.rst
- docs/install-faq.rst
- docs/install-gpu-pip-windows.rst
- docs/install-gpu-pip.rst
- docs/install-include.rst
- tabular/src/autogluon/tabular/models/knn/knn_rapids_model.py
- tabular/src/autogluon/tabular/models/lr/lr_rapids_model.py
- tabular/src/autogluon/tabular/models/rf/rf_rapids_model.py
> Remove pre-release doc warnings / instructions in 0.7.0 branch

- CONTRIBUTING.md
- docs/badges.rst
- docs/index.rst
- docs/install-faq.rst
> Remove Python 3.7 support from doc and website

- CONTRIBUTING.md
- docs/badges.rst
- docs/index.rst
- docs/install-faq.rst
> Remove Python 3.7 support from doc and website (#2940)

- docs/whats_new/v0.6.1.md
- docs/whats_new/v0.7.0.md
> Release notes for version 0.7.0

- docs/install-cpu-source.rst
- docs/install-include.rst
- docs/install-windows-gpu.rst
- pyproject.toml
* Upgrade version of torch and torchvision in installation guide
* Remove torchtext
* Remove Python 3.7 and added Python 3.10
> Upgrade torch and torchvision in installation guide

- docs/cheatsheet.rst
Update multimodal cheatsheet to the version of 0.7.0.
PNG version: https://automl-mm-bench.s3.amazonaws.com/cheatsheet/v0.7.0/AutoGluon_Multimodal_Cheatsheet_v0.7.0.png
PDF version: https://automl-mm-bench.s3.amazonaws.com/cheatsheet/v0.7.0/AutoGluon_Multimodal_Cheatsheet_v0.7.0.pdf
> Update Multimodal Cheatsheet to 0.7.0

- docs/tutorials/timeseries/forecasting-indepth.ipynb
- Fix several typos in the forecasting in-depth tutorial
> Fix typos in forecasting-indepth

- docs/tutorials/cloud_fit_deploy/autogluon-cloud.md
> Fix cloud link

- docs/ReleaseInstructions.md
> Update release instruction

- multimodal/tests/unittests/predictor/test_predictor.py
* removed clip in fusion_mlp models
> [Post 0.7][multimodal] remove clip in fusion models

- .github/workflow_scripts/build_timeseries_tutorial.sh
- .github/workflow_scripts/env_setup.sh
> Remove mxnet from CI

- docs/cheatsheet.rst
> Fix typo in timeseries cheatsheet link

- eda/setup.cfg
- eda/src/autogluon/eda/analysis/dataset.py
- eda/src/autogluon/eda/analysis/model.py
- eda/src/autogluon/eda/analysis/transform.py
- eda/src/autogluon/eda/auto/simple.py
- eda/src/autogluon/eda/visualization/model.py
- eda/src/autogluon/eda/visualization/shift.py
- eda/tests/unittests/analysis/test_dataset.py
- eda/tests/unittests/analysis/test_model.py
- eda/tests/unittests/auto/test_simple.py
- eda/tests/unittests/visualization/test_model.py
- fixed Sampler error when dataset is less than sample length of the sample size
- Model evaluator for regression now can handle test_data; plots will have both val_data and test_data plotted in results charts
- added verbosity support for ApplyFeatureGenerator
- dataset_overview is now not plotting category vs category charts since they don't add value
- covariate shift detection shows only top 5 feature importance items to reduce clutter and actionability
> [eda] various fixes and quality of life improvements

- docs/_static/custom.css
https://github.com/autogluon/autogluon/issues/3012
CSS updates that change navigation car scroll behavior. In development environment, this makes navigation bar changes more snappy with no smooth scroll animation.
> Change scroll-behavior smooth -> auto for snappier response

- multimodal/src/autogluon/multimodal/cli/prepare_detection_dataset.py
- multimodal/src/autogluon/multimodal/utils/download.py
CI builds after website merge to stable are [failing a lint check](https://github.com/autogluon/autogluon/actions/runs/4408134607). These changes already on master will fix the lint issue.
> Fix lint check (#3026)

- .github/workflow_scripts/test_tabular_lite.sh
- CI/batch/docker/Dockerfile.pyodide
- CI/batch/docker/autogluon_job.sh
- tabular/tests/conftest.py
- tabular/tests/regressiontests/test_tabular_lite.py
> change to run pyodide test under autogluon dir

- docs/tutorials/eda/eda-auto-dataset-overview.ipynb
- docs/tutorials/eda/eda-auto-quick-fit.ipynb
- docs/tutorials/eda/eda-auto-target-analysis.ipynb
- eda/src/autogluon/eda/visualization/interaction.py
This change includes a few small fixes and wording tweaks in EDA tutorials and logging that I found while reviewing the website.
> Wording updates in EDA tutorials and logging

- .github/workflow_scripts/env_setup.sh
tensorrt installation timeout, see https://github.com/autogluon/autogluon/actions/runs/4432440600/jobs/7776524054?pr=3048
remove tensorrt from setup_torch_gpu
> [multimodal] remove tensorrt from setup_torch_gpu

- multimodal/src/autogluon/multimodal/configs/pretrain/detection/yolox/yolox_m_8x8_300e_coc.py
- multimodal/src/autogluon/multimodal/configs/pretrain/detection/yolox/yolox_tiny_8x8_300e_coco.py
- multimodal/src/autogluon/multimodal/models/mmdet_image.py
> [multimodal] Add yoloxm and yoloxtiny

- CONTRIBUTING.md
- common/src/autogluon/common/utils/try_import.py
- core/src/autogluon/core/calibrate/temperature_scaling.py
- core/src/autogluon/core/hpo/ray_hpo.py
- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- core/src/autogluon/core/models/ensemble/fold_fitting_strategy.py
- core/src/autogluon/core/trainer/abstract_trainer.py
- core/src/autogluon/core/utils/__init__.py
- tabular/src/autogluon/tabular/models/automm/automm_model.py
- tabular/src/autogluon/tabular/models/catboost/catboost_model.py
- tabular/src/autogluon/tabular/models/fastainn/imports_helper.py
- tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
- tabular/src/autogluon/tabular/models/fasttext/fasttext_model.py
- tabular/src/autogluon/tabular/models/imodels/imodels_models.py
- tabular/src/autogluon/tabular/models/knn/knn_rapids_model.py
- tabular/src/autogluon/tabular/models/knn/knn_utils.py
- tabular/src/autogluon/tabular/models/lgb/lgb_model.py
- tabular/src/autogluon/tabular/models/lgb/lgb_utils.py
- tabular/src/autogluon/tabular/models/lr/lr_rapids_model.py
- tabular/src/autogluon/tabular/models/rf/rf_rapids_model.py
- tabular/src/autogluon/tabular/models/tab_transformer/tab_transformer_model.py
- tabular/src/autogluon/tabular/models/tabular_nn/mxnet/tabular_nn_mxnet.py
- tabular/src/autogluon/tabular/models/tabular_nn/torch/tabular_nn_torch.py
- tabular/src/autogluon/tabular/models/vowpalwabbit/vowpalwabbit_model.py
- tabular/src/autogluon/tabular/models/xgboost/xgboost_model.py
> Move try import to common

- common/src/autogluon/common/loaders/load_pd.py
- common/src/autogluon/common/loaders/load_s3.py
- common/src/autogluon/common/savers/save_pd.py
> Cleanup save/load code

- docs/conf.py
Cleanup `docs/conf.py` file:
- Added a comment explaining a line that only works because of some hidden sphinx functionality
- Removed a few other unneeded pieces of code
> Cleanup of docs conf.py file

- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/utils/load.py
- multimodal/tests/unittests/others_2/test_doc_standalone.py
Support standalone loading and add unit test.
> [DocumentAI] support standalone model loading

- .github/ISSUE_TEMPLATE/bug_report.md
- Clean up bug report issue template
- Hide instruction text from the final GitHub issue and make it only visible while creating the issue to reduce clutter.
> Clean up bug report issue template

- docs/conf.py
- docs/requirements_doc.txt
https://github.com/autogluon/autogluon/issues/3084
Added sphinx opengraph plugin
> [WIP] Added sphinx opengraph meta tags support

- AWESOME.md
> Add AWESOME.md

- eda/src/autogluon/eda/analysis/anomaly.py
- eda/src/autogluon/eda/analysis/explain.py
Hot-patches SHAP's use of deprecated numpy APIs
> patch SHAP use of old numpy APIs

- .github/workflows/platform_tests-command.yml
- common/tests/unittests/test_s3_utils.py
- tabular/tests/unittests/resource_allocation/test_hpo_resource_allocation.py
* Fix common test on windows to use correct path saperator
* Wrap resource test with mock system manager to avoid the CI machine having fewer resource than total resource passed in
> Fix platform tests

- timeseries/src/autogluon/timeseries/predictor.py
- Remove the code scheduled to be deprecated in v0.8
- Fix typo in docstring
> [timeseries] Remove deprecations scheduled for v0.8

- common/src/autogluon/common/utils/try_import.py
* Remove usage of distutils as it's being deprecated
> Remove distutils

- core/src/autogluon/core/hpo/executors.py
* Add preset mapping so user don't specify `local`, which is weird, when using distributed hpo in cloud
> [Tabular] Update hpo preset mapping

- multimodal/src/autogluon/multimodal/data/dataset_mmlab/multi_image_mix_dataset.py
> [bug][multimodal] fix import error in object detection

- tabular/setup.py
- Update scikit-learn-intelex to 2023.1
> Update scikit-learn-intelex to 2023.1

- multimodal/setup.py
- multimodal/src/autogluon/multimodal/models/timm_image.py
Upgrade timm to the latest stable version 0.9.2 (https://github.com/huggingface/pytorch-image-models/releases).
> [AutoMM] Upgrade timm

- timeseries/src/autogluon/timeseries/dataset/ts_dataframe.py
- timeseries/src/autogluon/timeseries/models/autogluon_tabular/direct_tabular.py
- timeseries/src/autogluon/timeseries/models/gluonts/torch/models.py
- timeseries/src/autogluon/timeseries/models/local/statsforecast.py
- Make docstrings more consistent for forecasting models.
- This is the first part of the documentation update for v0.8 - split into a separate PR to speed up building for the second part that only involves the docs.
> [timeseries] Update docstrings for forecasting models

- docs/tutorials/multimodal/advanced_topics/continuous_training.ipynb
- docs/tutorials/multimodal/advanced_topics/index.md
- docs/tutorials/multimodal/index.md
- docs/tutorials/multimodal/text_prediction/beginner_text.ipynb
> Continuous learning tutorial

- docs/index.md
> Add missing doc pages

- common/src/autogluon/common/space.py
- docs/api/autogluon.common.space.rst
- docs/conf.py
- docs/index.md
- docs/tutorials/tabular/tabular-indepth.ipynb
> [Doc] Add Search Space Page

- docs/tutorials/multimodal/multimodal-faq.md
> [Doc] AutoMM FAQ Updates

- docs/tutorials/tabular/tabular-indepth.ipynb
- Add calibrate_decision_threshold tutorial
> Add calibrate_decision_threshold tutorial

- docs/api/autogluon.tabular.models.rst
> Add model keys doc

- README.md
> Add Discord Link

- docs/index.md
- Add community section to website front page
Will wait for CI to pass to check that website renders correctly.
TODO:
> Add community section to website front page

- docs/tutorials/multimodal/document/pdf_classification.ipynb
- multimodal/setup.py
- multimodal/src/autogluon/multimodal/data/process_document.py
> Move PyMuPDF to optional (#3331)

- core/setup.py
> Pin dependencies

- eda/src/autogluon/eda/analysis/anomaly.py
> Fix log suppression workaround for print statements in suod

- multimodal/src/autogluon/multimodal/presets.py
Some backbone combinations may require small per gpu batch size to avoid OOM.
> [AutoMM] Update per gpu batch size for HPO

- docs/whats_new/v0.8.1.md
> 0.8.1 release notes

- .github/workflows/codespell.yml
- common/src/autogluon/common/savers/save_pd.py
- common/src/autogluon/common/utils/resource_utils.py
- common/src/autogluon/common/utils/s3_utils.py
- core/src/autogluon/core/ray/resources_calculator.py
- docs/whats_new/v0.4.1.md
- eda/src/autogluon/eda/analysis/base.py
- multimodal/src/autogluon/multimodal/data/process_mmlab/process_mmdet.py
- multimodal/src/autogluon/multimodal/data/randaug.py
- multimodal/src/autogluon/multimodal/utils/config.py
- multimodal/src/autogluon/multimodal/utils/onnx.py
- pyproject.toml
- timeseries/setup.py
I saw that there was a recent glorious release.  so I have decided to contribute to make the next one even more glorious ;)  From now on `codespell` action would warn you if a known typo introduced to the code base.
> codespell: action, config + some typos fixed

- core/setup.py
https://github.com/ray-project/ray/issues/36990
> Pin pydantic

- docs/whats_new/v0.8.2.md
> 0.8.2 release notes

- multimodal/src/autogluon/multimodal/data/process_text.py
Make construct_text_augmenter be part of TextProcessor. This is to align with other processors. 
> [AutoMM] Clean up text processor

- multimodal/src/autogluon/multimodal/models/categorical_mlp.py
- multimodal/tests/unittests/predictor/test_predictor.py
> [AutoMM] Fix the input keys of categorical MLP

- docs/tutorials/multimodal/multimodal-faq.md
> [Doc] Add AutoMM FAQs

- docs/tutorials/multimodal/index.md
- docs/tutorials/multimodal/object_detection/index.md
> [FIX] fix detection tutorial index

- multimodal/src/autogluon/multimodal/data/process_text.py
- multimodal/tests/unittests/others/test_utils.py
> [AutoMM] Add unit tests for trimming sequence lengths

- .github/workflow_scripts/test_core.sh
- CI/docker/full_install_image.sh
- common/src/autogluon/common/utils/try_import.py
- core/setup.py
- core/src/autogluon/core/hpo/executors.py
- core/src/autogluon/core/hpo/ray_hpo.py
- core/src/autogluon/core/ray/resources_calculator.py
- core/tests/unittests/hpo/test_ray_hpo.py
- core/tests/unittests/ray/test_resource_calculator.py
- multimodal/src/autogluon/multimodal/matcher.py
- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/utils/environment.py
* Remove ray lightning as it has been deprecated by ray.
> Remove ray lightning

- core/tests/unittests/searcher/test_local_random_searcher.py
This PR is to fix the floating point calculations which causes the core platform tests to fail on some operating systems due to the way floating point numbers are handled.
> PR to fix core platform tests

- CI/docker/Dockerfile.cpu-inference
- CI/docker/Dockerfile.cpu-training
- CI/docker/Dockerfile.gpu-inference
- CI/docker/Dockerfile.gpu-training
> Fix nightly image

- .github/workflows/build_latest_image.yml
> [CI] Free more space for nightly image

- CI/docker/Dockerfile.cpu-inference
- CI/docker/Dockerfile.gpu-inference
> Pin numpy in nightly inference image

- .github/workflows/benchmark-command.yml
- .github/workflows/build_latest_image.yml
- CI/docker/Dockerfile.cpu-training
- CI/docker/Dockerfile.gpu-training
> Update free disk space

- common/src/autogluon/common/utils/try_import.py
- core/setup.py
> upgrade ray and unpin grpcio

- multimodal/setup.py
> [AutoMM] Pin datasets

- .github/workflow_scripts/env_setup.sh
- multimodal/src/autogluon/multimodal/__init__.py
- multimodal/src/autogluon/multimodal/configs/environment/default.yaml
- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/utils/__init__.py
- multimodal/src/autogluon/multimodal/utils/environment.py
- multimodal/src/autogluon/multimodal/utils/inference.py
- multimodal/src/autogluon/multimodal/utils/log.py
- multimodal/src/autogluon/multimodal/utils/model.py
- Supported multi-gpu training in notebook. It can automatically detect interactive env and switch to use ddp_fork.
- Removed the AutoMMPrediction API as warned before.
- Did local tests on notebook with 4 gpus.
> [AutoMM] Support multi-gpu training in notebook

- timeseries/src/autogluon/timeseries/evaluator.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/tests/unittests/test_evaluator.py
- Add WAPE metric as defined in https://docs.aws.amazon.com/forecast/latest/dg/metrics.html#metrics-WAPE
> [timeseries] add WAPE metric

- tabular/tests/unittests/test_tabular.py
Skips plotting in the case of a Windows runner
Test Run (Check only Tabular) - https://github.com/prateekdesai04/autogluon/actions/runs/6004767002
> Fix for tabular platform tests on Windows runner

- eda/src/autogluon/eda/analysis/anomaly.py
- eda/src/autogluon/eda/auto/simple.py
See https://github.com/autogluon/autogluon/issues/3401
https://github.com/autogluon/autogluon/issues/3401
Applied suggested changes
> [eda][bugfix] fixed IndexError: positional indexers are out-of-bounds

- docs/tutorials/timeseries/forecasting-indepth.ipynb
- docs/tutorials/timeseries/forecasting-quick-start.ipynb
*Description of changes:* 
- Same as in #3522
> [timeseries] Fix time series tutorials on Colab

- core/src/autogluon/core/calibrate/_decision_threshold.py
- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- core/src/autogluon/core/trainer/abstract_trainer.py
- docs/tutorials/cloud_fit_deploy/index.md
- docs/whats_new/v0.4.1.md
- eda/src/autogluon/eda/auto/simple.py
- tabular/tests/regressiontests/utils.py
- timeseries/tests/unittests/models/test_local.py
- Fix spelling errors in the code that cause the `Codespell / Check for spelling errors` CI action to fail. 
> Fix spelling errors

- .github/workflows/platform_tests-command.yml
- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- timeseries/tests/unittests/models/test_mlforecast.py
- timeseries/tests/unittests/test_trainer.py
- timeseries/tests/unittests/test_ts_dataset.py
- Include tests for time series in the platform tests
> Add timeseries to platform tests

- core/src/autogluon/core/calibrate/temperature_scaling.py
- core/src/autogluon/core/models/abstract/abstract_model.py
- Removed scipy dependency on the temperature scaling logic by reimplementing in numpy (same logic)
- Cleanup temperature scaling logic
- Saves a few milliseconds on a predict call
- Reference scipy implementation: https://github.com/scipy/scipy/blob/v1.11.3/scipy/special/_logsumexp.py#L131-L225
> Cleanup temperature scaling logic

- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
> Enable Deterministic OOF Predictions 

- docs/index.md
- docs/whats_new/index.md
- docs/whats_new/v0.4.0.md
- docs/whats_new/v0.4.1.md
- docs/whats_new/v0.5.1.md
- docs/whats_new/v0.6.0.md
- docs/whats_new/v0.6.1.md
- docs/whats_new/v0.6.2.md
- docs/whats_new/v0.7.0.md
- docs/whats_new/v0.8.0.md
- docs/whats_new/v0.8.1.md
- docs/whats_new/v0.8.2.md
resolves #3429 
- Add whats_new pages to website
- Fix versions page to ensure it is up to date
> Add What's New to website docs

- docs/tutorials/multimodal/advanced_topics/continuous_training.ipynb
- docs/tutorials/multimodal/advanced_topics/index.md
- docs/tutorials/multimodal/document/document_classification.ipynb
- docs/tutorials/multimodal/image_prediction/clip_zeroshot.ipynb
- docs/tutorials/multimodal/index.md
- docs/tutorials/multimodal/matching/index.md
- docs/tutorials/multimodal/multimodal_prediction/index.md
- docs/tutorials/multimodal/multimodal_prediction/multimodal_ner.ipynb
- docs/tutorials/multimodal/text_prediction/chinese_ner.ipynb
- docs/tutorials/multimodal/text_prediction/index.md
- docs/tutorials/multimodal/text_prediction/ner.ipynb
- Fixed some broken tutorial links.
- Made some card names and titles consistent.
> [AutoMM] Fix tutorial links and titles

- docs/index.md
- Add GitHub link to website
- Follow-up from #3430
> Add GitHub link to website

- core/src/autogluon/core/models/abstract/abstract_model.py
Fix model memory usage calculation. The bug was introduced in #3033.
The bug makes it so that models are treated as requiring `1/mem_error_threshold` the memory as was intended.
For XGBoost and CatBoost whose `mem_error_threshold` was 1, this had no impact.
For RandomForest/ExtraTrees, whose `mem_error_threshold=0.5`, this caused the models to be treated as requiring 2x the memory as was intended.
For KNN, whose `mem_error_threshold=0.2`, this caused KNN to be treated as requiring 5x the memory.
This PR fixes this bug.
This PR (correctly trains):
```
Fitting model: RandomForest ...
Warning: Potentially not enough memory to safely train model. Estimated to require 250.000 GB out of 516.989 GB available memory (48.357%)... (50.000% of avail …
```
> Fix model memory usage calculation

- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- core/src/autogluon/core/trainer/abstract_trainer.py
- tabular/src/autogluon/tabular/learner/abstract_learner.py
- Add `from_children` toggle for bagged feature importance to be able to get importance for the children models.
- Code cleanup
> Add `from_children` toggle for bagged feature importance

- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- core/src/autogluon/core/utils/utils.py
- tabular/tests/conftest.py
- tabular/tests/unittests/models/test_advanced.py
- Add predict_children and predict_proba_children methods to enable future advanced ensembling techniques
- Various documentation and typing improvements
- Added several helper methods such as `self.n_children` and `predict_from_proba`
> Add predict_children

- CONTRIBUTING.md
- Add pytest-pycharm install recommendation
> Add pytest-pycharm install recommendation

- docs/whats_new/v0.5.1.md
- docs/whats_new/v0.6.0.md
- docs/whats_new/v0.7.0.md
- release_instructions/ReleaseInstructions.md
#3603 
Fix additional broken links on the whats_new files.
> Fix additional broken links

- .github/workflows/benchmark_master.yml
Runs AutoGluon in best setting on all 104 datasets, i.e. preset - best and benchmark - full
> Resetting master branch benchmark constraints

- .github/workflows/platform_tests-command.yml
Disabling static args for triggering platform tests.
> Fixing platform tests trigger

- multimodal/src/autogluon/multimodal/presets.py
#3637 
Just remove ".py" in name
> [AutoMM] Fix wrong checkpoint name in object detection

- core/src/autogluon/core/metrics/__init__.py
- core/tests/unittests/metrics/test_metrics.py
- Add convert_error_to_score method to Scorer class
> Add convert_error_to_score

- tabular/src/autogluon/tabular/models/automm/ft_transformer.py
- Update FT-Transformer to work post-refactor
- After the FT-Transformer refactor, the FT-Transformer model in Tabular no longer worked. This fixes that.
> Update FT-Transformer to work post-refactor

- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- core/src/autogluon/core/models/ensemble/fold_fitting_strategy.py
- core/tests/unittests/test_parallel_local_folding.py
- tabular/tests/unittests/resource_allocation/test_bagging_resource_allocation.py
https://github.com/autogluon/autogluon/issues/3492
* Dynamically adjust number of folds to be trained in parallel based on memory available
> Dynamic folds

- multimodal/src/autogluon/multimodal/constants.py
- multimodal/src/autogluon/multimodal/learners/base.py
- multimodal/src/autogluon/multimodal/learners/matching.py
- multimodal/src/autogluon/multimodal/learners/object_detection.py
- multimodal/src/autogluon/multimodal/utils/__init__.py
- multimodal/src/autogluon/multimodal/utils/cache.py
- multimodal/src/autogluon/multimodal/utils/environment.py
- multimodal/src/autogluon/multimodal/utils/inference.py
- multimodal/src/autogluon/multimodal/utils/log.py
- multimodal/tests/unittests/others/test_matcher.py
> [WIP][AutoMM] Fix multi GPU issues

- multimodal/src/autogluon/multimodal/utils/inference.py
- multimodal/tests/unittests/others/test_object_detection.py
> [AutoMM] Refactor object detection tests

- multimodal/tests/unittests/others_2/test_few_shot.py
Test loading a few shot predictor without Internet access.
> [AutoMM] Test few shot standalone

- docs/tutorials/multimodal/advanced_topics/customization.ipynb
- multimodal/src/autogluon/multimodal/configs/environment/default.yaml
- multimodal/src/autogluon/multimodal/learners/base.py
- multimodal/src/autogluon/multimodal/learners/matching.py
- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/utils/environment.py
- multimodal/src/autogluon/multimodal/utils/export.py
- multimodal/tests/unittests/predictor/test_predictor.py
> [AutoMM] Fix CPU only training

- multimodal/src/autogluon/multimodal/models/utils.py
- multimodal/tests/unittests/others/test_semantic_segmentation.py
> [WIP] Modify LoRA insertion logic.

- tabular/src/autogluon/tabular/models/lr/hyperparameters/searchspaces.py
- tabular/src/autogluon/tabular/models/lr/lr_model.py
- Update linear model to add search space and fix error when `proc.skew_threshold=None`.
> Update linear model

- .github/workflow_scripts/env_setup.sh
- .github/workflows/continuous_integration.yml
To run multimodal multi-gpu tests please label your PRs with {run-multi-gpu}.
Otherwise the test will be skipped.
Link to test run: https://github.com/prateekdesai04/autogluon/actions/runs/6882529898
> [Fix] Add label to Skip CI

- common/src/autogluon/common/utils/resource_utils.py
- common/src/autogluon/common/utils/system_info.py
- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/utils/version_utils.py
- docs/tutorials/tabular/advanced/tabular-deployment.ipynb
- features/src/autogluon/features/generators/pipeline.py
- tabular/src/autogluon/tabular/learner/default_learner.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/tests/unittests/test_tabular.py
- timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
- Add system info logging utility
- Change `disk_size` to `disk_usage`
Example output of calling `get_ag_system_info()`:
```
=================== System Info ===================
AutoGluon Version:  0.8.3b20231009
Python Version:     3.8.16
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #21~20.04.1-Ubuntu SMP Fri Aug 5 11:44:14 UTC 2022
CPU Count:          128
Memory Avail:       474.15 GB / 495.96 GB (95.6%)
Disk Space Avail:   1078.87 GB / 1938.76 GB (55.6%)
===================================================
```
> Add system info logging utility

- .github/workflow_scripts/run_benchmark.sh
Fix a minor issue to enable copying of eval results.
Link to test run: https://github.com/prateekdesai04/autogluon/actions/runs/6886843862/job/18735878665
> Minor eval logic change for benchmarking 

- tabular/src/autogluon/tabular/models/lr/lr_model.py
> Fix LinearModel crash

- docs/tutorials/multimodal/image_segmentation/beginner_semantic_seg.ipynb
- docs/tutorials/multimodal/index.md
- multimodal/src/autogluon/multimodal/learners/base.py
- multimodal/src/autogluon/multimodal/utils/config.py
- multimodal/src/autogluon/multimodal/utils/data.py
- multimodal/tests/unittests/others/test_semantic_segmentation.py
- Make it possible to call `predict` and `evaluate` alternately for SAM zero-shot.
- Fix SAM tutorial index issues. 
> [AutoMM] Fix SAM zero-shot

- docs/tutorials/multimodal/advanced_topics/few_shot_learning.ipynb
- docs/tutorials/multimodal/advanced_topics/hyperparameter_optimization.ipynb
- docs/tutorials/multimodal/image_prediction/beginner_image_cls.ipynb
- docs/whats_new/v0.5.1.md
- timeseries/src/autogluon/timeseries/models/local/statsforecast.py
Fix broken links reported at [here](https://github.com/autogluon/autogluon-brokenlinks/blob/master/Broken%20Links%20Dev.csv)
Update broken links reported
> fix broken links reported

- multimodal/src/autogluon/multimodal/presets.py
- Updated tabular data model presets from numerical/categorical MLP to ft-transformer.
> [AutoMM] Update model presets

- common/src/autogluon/common/utils/system_info.py
- docs/tutorials/multimodal/image_segmentation/beginner_semantic_seg.ipynb
- docs/tutorials/multimodal/index.md
- multimodal/src/autogluon/multimodal/learners/base.py
- multimodal/src/autogluon/multimodal/learners/matching.py
- multimodal/src/autogluon/multimodal/utils/__init__.py
- multimodal/src/autogluon/multimodal/utils/environment.py
- multimodal/src/autogluon/multimodal/utils/hpo.py
- multimodal/src/autogluon/multimodal/utils/log.py
- multimodal/src/autogluon/multimodal/utils/save.py
- Add system log info as tabular and timeseries.
- Simplify other AutoMM logging logic.
- Align matcher and base learner logging and some logic in `fit`.
Logging example:
```
=================== System Info ===================
AutoGluon Version:  0.8.3b20231027
Python Version:     3.9.18
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #91~18.04.1-Ubuntu SMP Sun Aug 14 01:24:43 UTC 2022
CPU Count:          16
Pytorch Version:    2.0.1+cu117
CUDA Version:       11.7
Memory Avail:       54.29 GB / 62.03 GB (87.5%)
Disk Space Avail:   81.01 GB / 992.61 GB (8.2%)
===================================================
AutoGluon infers your prediction problem is: 'multiclass' (because dtype of label-column == int, but few …
```
> [AutoMM] Align logging and align matcher logic with base learner

- docs/tutorials/multimodal/advanced_topics/customization.ipynb
> [Tutorial] Add object detection customize tutorial

- docs/tutorials/multimodal/advanced_topics/focal_loss.ipynb
- docs/tutorials/multimodal/advanced_topics/index.md
- docs/tutorials/multimodal/advanced_topics/presets.ipynb
- docs/tutorials/multimodal/advanced_topics/tensorrt.ipynb
- docs/tutorials/multimodal/image_prediction/beginner_image_cls.ipynb
- docs/tutorials/multimodal/index.md
- multimodal/src/autogluon/multimodal/presets.py
- Updated image backbone presets from `Swin Transformer` to [`Caformer`](https://arxiv.org/pdf/2210.13452.pdf).
- Updated tutorials because of changes of presets.
> [AutoMM] Update image backbone presets and tutorials

- docs/tutorials/multimodal/advanced_topics/presets.ipynb
- Update time limit in the preset tutorial.
> [AutoMM] Update time limit in the preset tutorial

- docs/tutorials/multimodal/object_detection/advanced/finetune_coco.ipynb
- docs/tutorials/multimodal/object_detection/quick_start/quick_start_coco.ipynb
- docs/tutorials/multimodal/object_detection/quick_start/quick_start_ovd.ipynb
add `remove-cell` tag
remove `_total_train_time`
> [AutoMM] Fix Object Detection Tutorials

- docs/tutorials/multimodal/object_detection/quick_start/quick_start_ovd.ipynb
- multimodal/src/autogluon/multimodal/learners/object_detection.py
- multimodal/src/autogluon/multimodal/predictor.py
> [AutoMM] Fix OVD

- common/setup.py
- Update setup.py to remove s3fs
- Can add back later after we figure out how to avoid slowing down install
> Update setup.py to remove s3fs

- timeseries/src/autogluon/timeseries/models/autogluon_tabular/mlforecast.py
- timeseries/tests/unittests/models/test_mlforecast.py
- Currently, `DirectTabular` model trained with point forecast metric applies scaling twice when computing quantile forecasts. This results in extremely wide prediction intervals.
- This PR fixes this bug and ensures that scaling is applied once for all models.
> [timeseries] Fix incorrect scale used by DirectTabular model

- docs/tutorials/multimodal/advanced_topics/customization.ipynb
Added torch.compile related hyperparamters in the customization tutorial.
> [AutoMM] Add torch.compile hyperparameters in tutorial

- multimodal/tests/unittests/others_2/test_hpo.py
Removed the time_limit as the training is capped by max_epochs=1.
> [AutoMM] Fix HPO tests

- tabular/setup.py
- tabular/src/autogluon/tabular/models/xgboost/xgboost_model.py
Resolves #3759 
Implements the work-around proposed in https://github.com/dmlc/xgboost/issues/9807#issuecomment-1827395975
- Adds support for XGBoost v2.x
- Implements work-around to resolve a bug in XGBoost v2.0.2 (https://github.com/dmlc/xgboost/issues/9807)
> Update XGBoost to `>=1.6,<2.1`

- tabular/src/autogluon/tabular/experimental/__init__.py
- tabular/src/autogluon/tabular/experimental/_scikit_mixin.py
- tabular/src/autogluon/tabular/experimental/_tabular_classifier.py
- tabular/src/autogluon/tabular/experimental/_tabular_regressor.py
- tabular/tests/conftest.py
- tabular/tests/unittests/experimental/test_scikit_api.py
Resolves #1493 
- Add Scikit-learn compatible API to Tabular (experimental)
Note: I haven't heavily tested this, so I don't know if there are edge cases where it fails.
> Tabular: Add experimental scikit-learn API support

- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/problem_types.py
> [AutoMM] Improve API doc

- .github/workflows/continuous_integration.yml
- multimodal/tests/unittests/others_2/test_hpo.py
> [Post 1.0?] Change AutoMM multi gpu tests to use only 2 gpu

- multimodal/tests/unittests/others_2/test_hpo.py
Skipped the multi-gpu tests for distillation.
> [AutoMM] Fix multi-gpu test

- multimodal/src/autogluon/multimodal/learners/base.py
- multimodal/src/autogluon/multimodal/learners/matching.py
- multimodal/src/autogluon/multimodal/learners/object_detection.py
- multimodal/src/autogluon/multimodal/utils/log.py
- Refactor warning filters and add one more filter for object detection
- Remove messaging in DDP subprocesses
> [1.0?] Fix AutoMM warnings

- multimodal/src/autogluon/multimodal/configs/pretrain/detection/coco_detection.py
- multimodal/src/autogluon/multimodal/configs/pretrain/detection/dino/dino-4scale_r50_8xb2-12e_coco.py
- multimodal/src/autogluon/multimodal/configs/pretrain/detection/dino/dino-5scale_swin-l_8xb2-12e_coco.py
- multimodal/src/autogluon/multimodal/configs/pretrain/detection/dino/dino-5scale_swin-l_8xb2-36e_coco.py
- multimodal/src/autogluon/multimodal/configs/pretrain/detection/dino/dino_swinl_tta.py
- multimodal/src/autogluon/multimodal/configs/pretrain/detection/dino/dino_tta.py
- multimodal/src/autogluon/multimodal/models/mmdet_image.py
Usage: `model.mmdet_image.checkpoint_name="dino_tta"`
> [1.0?] Add Test Time Augmentation for DINO

- core/src/autogluon/core/trainer/abstract_trainer.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- Fix dynamic_stacking with optimize_for_deployment preset
> Fix dynamic_stacking with optimize_for_deployment preset

- docs/whats_new/index.md
- docs/whats_new/v1.0.0.md
- Add v1.0.0 release notes
TODO:
> Add v1.0.0 release notes

- docs/whats_new/v1.0.0.md
- Update v1.0.0 release note by adding a link to more info on experiment results.
> Update v1.0.0 release note

- multimodal/src/autogluon/multimodal/data/process_semantic_seg_img.py
- multimodal/src/autogluon/multimodal/learners/semantic_segmentation.py
- multimodal/src/autogluon/multimodal/problem_types.py
- Modify the logic of get_semantic_segmentation_class_num function.
- Update supported evaluation metrics.
> [AutoMM] Fix bugs of semantic segmentation.

- docs/cheatsheet.md
Update cheatsheet of AutoMM to v1.0
> Update automm cheatsheet to v1.0.0

- docs/tutorials/tabular/tabular-essentials.ipynb
- docs/tutorials/tabular/tabular-indepth.ipynb
- tabular/src/autogluon/tabular/predictor/_deprecated_methods.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- Move deprecated methods to mixin
TODO: Also merge into `stable`.
> Tabular: Move deprecated methods to mixin

- multimodal/src/autogluon/multimodal/optimization/semantic_seg_metrics.py
- Call the reset function after computing the metric.
> [AutoMM] Fix the bug of COD_Pred metric in semantic_seg_metrics.py

- .github/ISSUE_TEMPLATE/feature_request.md
- Add GitHub issue template for feature request
> Add GitHub issue template for feature request

- timeseries/src/autogluon/timeseries/predictor.py
- Similar to #3555, but for `TimeSeriesPredictor`
> [timeseries] Add method for generating the simulation artifact

- docs/install-linux-conda-gpu.md
- docs/install.md
This PR updates conda gpu installation instructions due to dependency incompatibility of torchvision and cuda. 
> update conda instructions

- tabular/src/autogluon/tabular/models/lgb/lgb_model.py
*Issue #, if available:* Fixes #3815
- Fix LightGBM model failing for quantile regression if len(quantile_levels) < 3
> [tabular] Fix LightGBM model failing for quantile regression if len(quantile_levels) < 3

- docs/tutorials/cloud_fit_deploy/cloud-aws-sagemaker-train-deploy.ipynb
*Issue #, if available:* Fix the Colab and Studio tutorial links which were not working
> [Tutorials][Fix] Colab and studio links

- docs/install-conda-full.md
- docs/install-linux-conda-gpu.md
- docs/install-mac-conda.md
- docs/install-windows-conda-gpu.md
- docs/install.md
> update install instruction

- .github/workflows/continuous_integration.yml
Skip `test_multimodal_*` and `test_tabular_*` whenever any changes related to Timeseries is done.
> [Timeseries][CI]Refactor CI to skip AutoMM and Tabular tests w.r.t timeseries changes

- features/src/autogluon/features/generators/datetime.py
Add note on pd.to_datetime describing when it can be slow.
> Add note on pd.to_datetime

- examples/automm/Conv-LoRA/README.md
- examples/automm/Conv-LoRA/prepare_semantic_segmentation_datasets.py
- examples/automm/Conv-LoRA/run_semantic_segmentation.py
> [AutoMM] Add the example of Conv-LoRA.

- docs/install-cpu-pip.md
- docs/install-cpu-source.md
- docs/install-gpu-pip.md
- docs/install-gpu-source.md
- docs/tutorials/multimodal/index.md
1. Remove the installation of gpu version since it's automatically handled by autogluon.
2. Update the cpu version.
> [Doc] Update torch installation

- examples/automm/Conv-LoRA/README.md
- examples/automm/Conv-LoRA/prepare_semantic_segmentation_datasets.py
Update readme by putting the installation at the beginning since downloading the datasets also requires the installation.
> [AutoMM] Update conv-lora readme

- CI/bench/evaluate.py
This PR fixes the evaluation in CI due to the [change](https://github.com/autogluon/autogluon-bench/pull/73/commits/a5fac6b602cebada33379026946f8cf785f3c769) in Autogluon.Bench.
> Fix CI evaluation 

- examples/automm/Conv-LoRA/README.md
- examples/automm/Conv-LoRA/run_semantic_segmentation.py
Update the default batch_size and per_gpu_batch_size to be consistent with the paper.
> [AutoMM] Update default in the conv-lora example

- AWESOME.md
- README.md
- docs/install.md
- docs/whats_new/index.md
- Add 2024 competition results
- Add Articles section
- Update Kaggle Install Instructions
- Other minor improvements
> Add AWESOME.md competition results, other doc improvements

- docs/tutorials/timeseries/forecasting-indepth.ipynb
- docs/tutorials/timeseries/forecasting-quick-start.ipynb
- timeseries/src/autogluon/timeseries/predictor.py
*Issue #, if available:* fixes #4050
- Clearly describe that test data must include both historic & future time series values
> [timeseries] Clarify documentation related to `test_data`

- timeseries/setup.py
#4044
Update optimum and optimum-intel dependencies.
> [timeseries] Bump optimum dependency ranges

- timeseries/setup.py
- timeseries/tests/unittests/models/test_chronos.py
Remove openvino from "all" dependencies as it will not be required by 99% of users.
> [timeseries] remove openvino from all dependencies and tests

- .github/workflows/benchmark-command.yml
- .github/workflows/continuous_integration.yml
- .github/workflows/platform_tests-command.yml
- .github/workflows/slash_command_dispatch.yml
Urgent update of all slash-command-dispatch actions versions.
> [Fix] Update slash command dispatch actions 

- README.md
- core/src/autogluon/core/_setup_utils.py
- docs/index.md
- Update Project Tagline
Changed to `Fast and Accurate ML in 3 Lines of Code`
> Update Project Tagline

- .github/workflows/platform_tests-command.yml
- timeseries/src/autogluon/timeseries/models/autogluon_tabular/mlforecast.py
- timeseries/tests/unittests/models/test_mlforecast.py
- Avoid in-place modifying the dataframe, which causes platform tests to fail on certain platforms
> [timeseries] Fix platform tests failing because of inplace dataframe modifications

- .github/workflows/benchmark_master.yml
- CI/bench/evaluate.py
This is an enhancement PR which gives out a more detailed report of all the benchmarks of Master vs v1.0.
Initially, the report had `Winrate`, `training time`, `inference time` and `rank`.
This may not provide sufficient information to determine if the framework is necessarily better hence this PR is to give out a more detailed report (upload the entire evaluation as a zipped artifact for every module).
P.S. We can add it as a 1.1 milestone item if required, may not be necessary.
> [Enhancement][AutoBench] Adding more columns for detailed report 

- multimodal/setup.py
https://github.com/autogluon/autogluon/issues/4000
> Update jsonschema version

- core/src/autogluon/core/utils/feature_selection.py
- features/src/autogluon/features/generators/drop_duplicates.py
- tabular/src/autogluon/tabular/learner/default_learner.py
- tabular/src/autogluon/tabular/models/rf/rf_quantile.py
- tabular/src/autogluon/tabular/models/tabular_nn/compilers/onnx.py
- tabular/src/autogluon/tabular/models/tabular_nn/utils/nn_architecture_utils.py
- tabular/src/autogluon/tabular/predictor/predictor.py
Resolves #2904
- Fix Pandas 2.2 FutureWarning
> [tabular] Fix Pandas 2.2 FutureWarning

- docs/versions.rst
- docs/whats_new/index.md
- docs/whats_new/v1.1.0.md
- Add v1.1.0 Release Notes
TODO:
> Add v1.1.0 Release Notes

- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
Resolves #4104 
- Fix groups logic for use_child_oof
> Fix groups logic for use_child_oof

- docs/tutorials/multimodal/advanced_topics/tensorrt.ipynb
> Fix tensorrt notebook failure

- docs/tutorials/multimodal/document_prediction/document_classification.ipynb
- docs/tutorials/multimodal/document_prediction/pdf_classification.ipynb
1. Fixed the missing installation command in the Colab notebook.
2. Removed developer's local environment info from the notebook.
> [AutoMM] Fix pdf classficiation tutorial

- CITING.md
- docs/tutorials/multimodal/index.md
> [Doc] Add automm paper citation

- multimodal/tests/unittests/others/test_dump_model.py
This is to fix the OOM issue on CI `test_dump_hf_text`  https://github.com/autogluon/autogluon/actions/runs/9274764166/job/25518041355
> update test to use smaller hf_text model

- docs/tutorials/multimodal/image_prediction/beginner_image_cls.ipynb
- docs/tutorials/multimodal/image_segmentation/beginner_semantic_seg.ipynb
- docs/tutorials/multimodal/multimodal_prediction/beginner_multimodal.ipynb
- docs/tutorials/multimodal/text_prediction/beginner_text.ipynb
- docs/tutorials/tabular/tabular-essentials.ipynb
- multimodal/src/autogluon/multimodal/predictor.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- timeseries/src/autogluon/timeseries/predictor.py
- Update the pickle warning for `predictor.load` method in all modules.
> [docs] Update pickle warning for all modules

- docs/tutorials/multimodal/image_prediction/beginner_image_cls.ipynb
- docs/tutorials/multimodal/image_segmentation/beginner_semantic_seg.ipynb
- docs/tutorials/multimodal/multimodal_prediction/beginner_multimodal.ipynb
- docs/tutorials/multimodal/text_prediction/beginner_text.ipynb
- docs/tutorials/tabular/tabular-essentials.ipynb
- multimodal/src/autogluon/multimodal/predictor.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- timeseries/src/autogluon/timeseries/predictor.py
> [codespell] unsecure -> insecure

- tabular/src/autogluon/tabular/models/tabular_nn/torch/tabular_nn_torch.py
- Improve NN_TORCH runtime estimate.
When running NN_TORCH in a `ray` process, the first batch includes significant time overhead to initialize torch. This leads to the mainline time requirement estimate to be vastly pessimistic as the data becomes larger because it multiplies this time overhead by the number of batches in an epoch. This caused extreme estimates for large datasets, skipping the neural network training entirely in many cases where it would have been useful.
The fix avoids using the first batch as part of the runtime estimate of future batches. This allows the `v2` time estimate to be far more accurate.
Example on the adult income dataset:
```
(_ray_fit pid=1972457) v1 estimate: 46.5966s | v2 estimate: 2.3756s
(_ray_fit …
```
> [tabular] Improve NN_TORCH runtime estimate

- multimodal/src/autogluon/multimodal/utils/environment.py
https://github.com/autogluon/autogluon/issues/4126
> [AutoMM] Add the pytorch version requirement for object detection in error message

- tabular/src/autogluon/tabular/predictor/predictor.py
- Enable ray logging by default when using DyStack
- Improve logging quality
- Rename `force_ray_logging` -> `enable_ray_logging`
- Add ray private API call hack to stop ray from logging in the main process after logging in DyStack.
> [tabular] Improve logging with DyStack and ray

- common/src/autogluon/common/utils/try_import.py
- docs/install-cpu-pip.md
- docs/install-cpu-source.md
- docs/install-windows-gpu.md
- Update torch version in install docs
- Remove try_import_d8, as we removed this dependency a long time ago
> Update torch version in install docs

- docs/whats_new/index.md
- docs/whats_new/v0.8.2.md
- docs/whats_new/v0.8.3.md
- docs/whats_new/v1.1.0.md
- docs/whats_new/v1.1.1.md
- Add v1.1.1 and v0.8.3 release notes
> Add v1.1.1 and v0.8.3 release notes

- .github/workflows/continuous_integration.yml
Disabling package diff feature, follow-up PR will be put out in some days to enable it again.
> [CI] Disable package diff

- release_instructions/ReleaseInstructions.md
> add link for conda release

- .github/SECURITY.md
- SECURITY.md
- release_instructions/ReleaseInstructions.md
Resolves #4191
Add SECURITY.md for vulnerability reporting
> Add SECURITY.md for vulnerability reporting

- docs/versions.rst
Users reported that our stable version doc is not up to date.
Update versions accordingly for stable branch
> [stable] update documentation version for 1.1.1 release

- features/src/autogluon/features/generators/text_ngram.py
Related: #4333 (This ensures that the soft-limit added in the mentioned PR is applied for `TextNgramFeatureGenerator`.)
- Make TextNgramFeatureGenerator use the ResourceManager instead of psutil. Now all usage of psutil is handled by ResourceManager throughout AutoGluon.
> [tabular] Use ResourceManager for text_ngram.py

- tabular/src/autogluon/tabular/models/tabular_nn/torch/tabular_torch_dataset.py
This pull request addresses unexpected torch seed behavior observed when using the autogluon `TabularTorchDataset` object, which leverages Torch Dataloaders. Using different seeds for the data loading process can lead to unexpected behavior when various functions rely on data loader behavior. For instance, in the `TabularNeuralNetTorchModel` training code, calling `self.score()` multiple times led to different results, despite calculating the same metric on the same datasets. This issue was caused because of differences in the batch loading process utilized within `self.score()`.
To address these issues, the following PyTorch article on ensuring reproducibility was implemented: https://pytorch.org/docs/stable/notes/randomness.html
> Addressed Unexpected Torch Seed Behavior with Dataloader

- common/src/autogluon/common/utils/s3_utils.py
This pull request introduces a new function `copy_s3_file` for copying s3 files from one s3 location to another s3 location. Also added documentation for other s3 util methods.
> Added Copy Files s3 Util Function

- tabular/tests/unittests/models/test_rf.py
- Add RF ONNX compilation unit test
> [tabular] Add RF ONNX compilation unit test

- tabular/src/autogluon/tabular/predictor/predictor.py
Resolves #4377
- Fix log_to_file docstring
- Minor code cleanup
> [tabular] Fix log_to_file docstring

- common/src/autogluon/common/features/feature_metadata.py
- Add utility methods to FeatureMetadata. These methods will be helpful in a future refactor of FeatureMetadata to be more user friendly when specifying custom feature metadata, and for debugging within the Trainer class.
> [common] Add utility methods to FeatureMetadata

- docs/tutorials/multimodal/object_detection/advanced/finetune_coco.ipynb
- docs/tutorials/multimodal/object_detection/quick_start/quick_start_coco.ipynb
https://github.com/autogluon/autogluon/issues/3963
> [Tutorial] Add Installation Guide for Object Detection in Tutorial

- .github/actions/submit-job/action.yml
Regular housekeeping and maintenance of CI.
> [CI] Update Actions

- .github/workflows/continuous_integration.yml
Disable CI/CD for non-master branches
> [temp] Disable CI/CD for non-master branches

- core/src/autogluon/core/callbacks/_early_stopping_callback.py
- Fix Early Stopping Callback exception
> Fix Early Stopping Callback exception

- core/src/autogluon/core/models/_utils.py
- core/src/autogluon/core/utils/early_stopping.py
- pyproject.toml
- tabular/src/autogluon/tabular/models/tabular_nn/hyperparameters/parameters.py
- tabular/src/autogluon/tabular/models/tabular_nn/torch/tabular_nn_torch.py
- Add AdaptiveES support to NN_TORCH
- Switch default ES to use adaptive early stopping
- Update default num_epochs from 500 to 1000
- Code cleanup & documentation
> [tabular] Add AdaptiveES support to NN_TORCH

- .github/workflows/continuous_integration.yml
This reverts commit 5248ef97101607850b1f43f6e8c6e2210491efbe.
> Revert "[temp] Disable CI/CD for non-master branches (#4471)"

- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/models/ensemble/fold_fitting_strategy.py
- Minor logging improvement on verbosity=4
- Avoiding log spam for messages that provide little to no value
> [tabular] Minor logging improvement on verbosity=4

- .github/workflows/benchmark-command.yml
- .github/workflows/benchmark_master.yml
Benchmark workflow was breaking due to deprecated GitHub Actions.
This PR is a fix + upkeep.
> [CI] Update benchmark actions

- core/src/autogluon/core/_setup_utils.py
- eda/setup.py
> Update Matplotlib range

- .github/workflows/continuous_integration.yml
Update the CICD of stable branch to run on stable branch only
> [CICD]Changed the CICD of stable branch to run on stable branch only

- .github/workflows/continuous_integration.yml
Fix issue where stable branch doc building picks up master branch changes.
> fix stable doc picks up master branch changes

- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- timeseries/tests/unittests/models/test_models.py
Fix IntegerArray to ndarray Conversion in Value Counts Cumsum Calculation
#4522 
Fix IntegerArray to ndarray Conversion in Value Counts Cumsum Calculation
> [timeseries] Fix IntegerArray to ndarray

- tabular/tests/unittests/data/test_learning_curves.py
- Speed up learning_curves tests by ~15x, saving around 20 minutes on the CI.
> [tabular] Speed up learning_curves tests

- tabular/tests/unittests/test_tabular.py
- Speed up hpo tests by ~2-5 minutes
- Remove unused and invalid tests
> [tabular] Speed up hpo tests

- .github/workflows/continuous_integration.yml
PR https://github.com/autogluon/autogluon/pull/4549 breaks changes.
This PR fixes it by removing it from build_docs actions.
> [CI] Fix failure in triggering CI

- core/src/autogluon/core/_setup_utils.py
- tabular/setup.py
Updating various packages for v1.2
> [Upgrade] Bulk package upgrade for v1.2

- docs/install-conda-full.md
- docs/install-cpu-pip.md
- docs/install-cpu-source.md
- docs/install-linux-conda-gpu.md
- docs/install-mac-conda.md
- docs/install-windows-conda-gpu.md
- docs/install-windows-cpu.md
- docs/install-windows-gpu.md
> Update install instructions

- full_install.sh
- Update full_install.sh to be simultaneous by running the uv install in a single line containing all submodules
- This is faster and ensures that dependency resolution can be done optimally.
> Update full_install.sh to be simultaneous

- core/setup.py
- docs/install-cpu-pip.md
- docs/install-gpu-pip.md
- docs/install-mac-cpu.md
- docs/install.md
- full_install.sh
> [Stable] Add missing stable commits

- core/src/autogluon/core/_setup_utils.py
- multimodal/src/autogluon/multimodal/models/ft_transformer.py
update the range to ">=0.21.0,<0.34.0"
> update accelerate version range

- CI/bench/generate_bench_config.sh
Add @Innixma's changes until PR - https://github.com/openml/automlbenchmark/pull/643 is merged.
Will revert to using stable branch post merge.
> [CI-Bench] Add AMLB changes

- full_install.sh
- multimodal/setup.py
Fix https://github.com/autogluon/autogluon/issues/4556
Bound nltk version to avoid verbose logging issue
> Bound nltk version to avoid verbose logging issue

- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/trainer/abstract_trainer.py
- tabular/src/autogluon/tabular/models/tabular_nn/hyperparameters/parameters.py
- tabular/src/autogluon/tabular/predictor/predictor.py
> Add TODOs/FIXMEs

- tabular/src/autogluon/tabular/models/tabular_nn/torch/tabular_nn_torch.py
- Add AdamW support to NN_TORCH
> Add AdamW support to NN_TORCH

- CI/batch/docker/Dockerfile.cpu
- CI/batch/docker/Dockerfile.gpu
- CI/docker/Dockerfile.cpu-inference
- CI/docker/Dockerfile.cpu-training
- CI/docker/Dockerfile.gpu-inference
- CI/docker/Dockerfile.gpu-training
This is a PR similar to https://github.com/autogluon/autogluon/pull/4123
But includes the updated image changes, and these images are also built and pushed to AG's ECR repo which will be used by the CI.
Before this PR was raised the CI was having Torch 2.2 + cu12.1 for GPU and Torch 2.2 for CPU
The moment this PR was raised, CI has Torch 2.4 + cu12.4 for GPU and Torch 2.4 for CPU
> [Docker - v1.2] Update all images

- .github/workflow_scripts/env_setup.sh
- .github/workflow_scripts/setup_mmcv.sh
- core/src/autogluon/core/_setup_utils.py
Update core dependencies to the latest versions of related packages to ensure we're up to date! 
> Key dependency updates in _setup_utils.py for v1.2 release

- docs/tutorials/multimodal/advanced_topics/continuous_training.ipynb
- docs/tutorials/multimodal/text_prediction/chinese_ner.ipynb
- docs/whats_new/v0.8.0.md
- timeseries/src/autogluon/timeseries/models/chronos/model.py
https://github.com/autogluon/autogluon/issues/3603
Fixed broken links in the tutorial and codes
> [Doc] Fixed broken links in the tutorial

- docs/tutorials/multimodal/advanced_topics/hyperparameter_optimization.ipynb
- multimodal/src/autogluon/multimodal/utils/hpo.py
> Configurable Number of Checkpoints to Keep per HPO Trial

- .github/workflow_scripts/lint_check.sh
> [AutoMM] Skip MMDet Config Files While Checking with bandit

- docs/tutorials/timeseries/forecasting-model-zoo.md
- timeseries/setup.py
- timeseries/src/autogluon/timeseries/models/gluonts/torch/models.py
- timeseries/tests/unittests/models/test_gluonts.py
- Update to GluonTS v0.16.0
- Use known_covariates in the PatchTST model
> [timeseries] Update to GluonTS v0.16.0

- docs/tutorials/multimodal/advanced_topics/index.md
- docs/tutorials/multimodal/advanced_topics/problem_types_and_metrics.ipynb
- docs/tutorials/multimodal/index.md
- multimodal/src/autogluon/multimodal/constants.py
- multimodal/src/autogluon/multimodal/problem_types.py
> Refactor Metrics for Each Problem Type

- docs/tutorials/multimodal/object_detection/advanced/finetune_coco.ipynb
- docs/tutorials/multimodal/object_detection/quick_start/quick_start_coco.ipynb
> [Tutorial] Fix Torch Version and Colab Installation for Object Detection

- multimodal/src/autogluon/multimodal/utils/metric.py
> [AutoMM] Fix Logloss Bug and Refine Compute Score Logics

- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- timeseries/src/autogluon/timeseries/models/gluonts/torch/models.py
- timeseries/tests/conftest.py
- timeseries/tests/smoketests/test_all_models.py
- timeseries/tests/unittests/models/test_gluonts.py
- timeseries/tests/unittests/models/test_models.py
- timeseries/tests/unittests/models/test_multi_window_model.py
- timeseries/tests/unittests/test_learner.py
- timeseries/tests/unittests/test_metrics.py
- timeseries/tests/unittests/test_predictor.py
- timeseries/tests/unittests/test_trainer.py
> [timeseries] refactor GluonTS default parameter handling, update TiDE parameters

- multimodal/src/autogluon/multimodal/utils/metric.py
- multimodal/tests/unittests/others/test_classification.py
https://github.com/autogluon/autogluon/pull/4629 follow up
> [AutoMM] Fix Proba Metrics for Multiclass

- timeseries/src/autogluon/timeseries/models/chronos/model.py
- timeseries/tests/unittests/models/chronos/pipeline/test_utils.py
- timeseries/tests/unittests/models/chronos/test_model.py
*Description of changes:* This PR adds new tests for Chronos fine-tuning HPs.  
> [timeseries] Improve Chronos fine-tuning test coverage

- timeseries/src/autogluon/timeseries/models/chronos/model.py
*Description of changes:* This PR updates the default fine-tuning hyperparameters for Chronos models. 
TODOs:
> [timeseries] Change fine-tuning defaults of Chronos

- .github/workflow_scripts/run_benchmark.sh
- CI/bench/evaluate.py
Get autogluon-dashboard working for v1.2, resolved several CORS issues in the backend.
Removed Loss reduction (median) and Fit Speed Diff columns, as they are not accepted by the dashboard schema (v0.0.1).
Schema may be updated in next release as we also plan to make some modifications to the evaluation scripts.
There will be a unique link after every Benchmark pull-request workflow action.
This link gives out the dashboard for that run - i.e., if tabular is benchmarked then there will be a link for that run, if automm-image is benchmarked then there will be a link for that run and so on. 
> Fix AutoGluon Dashboard

- timeseries/src/autogluon/timeseries/models/presets.py
- Update high_quality, best_quality and medium_quality presets
> [timeseries] Update presets

- timeseries/src/autogluon/timeseries/models/chronos/model.py
*Description of changes:* This PR updates the default fine-tuning HPs for Chronos.
> [timeseries] Update Chronos fine-tuning defaults

- timeseries/src/autogluon/timeseries/models/chronos/model.py
- timeseries/src/autogluon/timeseries/models/chronos/pipeline/utils.py
- Clean up the logging & warning outputs for Chronos models at different verbosity levels
> [timeseries] Change verbosity of warnings for Chronos models

- common/src/autogluon/common/features/infer_types.py
#4602 
Modified `check_if_nlp_feature` to convert `X_unique` to strings.
> fix: Convert unique values to strings in `check_if_nlp_feature`

- tabular/src/autogluon/tabular/predictor/predictor.py
- Remove unused experimental predictor
> Remove unused experimental predictor

- tabular/setup.py
- Bump LightGBM minimum version to 4.0
- Bump skex version
> bump lightgbm and skex versions

- tabular/src/autogluon/tabular/models/catboost/callbacks.py
- remove private catboost call, as it is now available through the public API.
Possibly related to #3249
> remove private catboost call

- common/src/autogluon/common/utils/try_import.py
- core/setup.py
Resolves #4668 
- Try bumping ray max version to 2.39
> bump ray to <2.40

- timeseries/src/autogluon/timeseries/dataset/ts_dataframe.py
- timeseries/src/autogluon/timeseries/metrics/point.py
- timeseries/src/autogluon/timeseries/models/chronos/model.py
- timeseries/src/autogluon/timeseries/models/chronos/pipeline/base.py
- timeseries/src/autogluon/timeseries/models/chronos/pipeline/chronos.py
- timeseries/src/autogluon/timeseries/models/chronos/pipeline/utils.py
- timeseries/src/autogluon/timeseries/trainer/abstract_trainer.py
- timeseries/src/autogluon/timeseries/trainer/auto_trainer.py
- timeseries/src/autogluon/timeseries/utils/datetime/lags.py
- timeseries/src/autogluon/timeseries/utils/datetime/seasonality.py
- timeseries/src/autogluon/timeseries/utils/datetime/time_features.py
- timeseries/src/autogluon/timeseries/utils/features.py
- timeseries/src/autogluon/timeseries/utils/forecast.py
- timeseries/src/autogluon/timeseries/utils/warning_filters.py
- timeseries/tests/unittests/common.py
- timeseries/tests/unittests/models/chronos/test_model.py
- timeseries/tests/unittests/models/test_gluonts.py
- timeseries/tests/unittests/test_learner.py
- timeseries/tests/unittests/utils/test_features.py
- timeseries/tests/unittests/utils/test_utils.py
Addresses some mypy issues and other housekeeping. Primarily,
- Address mypy issues in Chronos
- Address mypy issues in utils
- Address all LSP violations (i.e., `override` error type in mypy)
- Ignore type checker issues where justified..
- Other cleanup
> [timeseries] address static type checker issues in Chronos and utils

- core/src/autogluon/core/utils/plots.py
A potential one-liner fixing https://github.com/autogluon/autogluon/issues/4708.
> fix: plot_tabular_models save under dir

- timeseries/src/autogluon/timeseries/predictor.py
- Fix a few typos on the docstring for TimeSeriesPredictor
> [timeseries] Update predictor docstring

- docs/whats_new/index.md
- docs/whats_new/v1.2.0.md
Add the v1.2 release notes
Section Owners:
Tabular -> @Innixma 
TimeSeries -> @shchur @canerturkmen @abdulfatir 
Multimodal -> @FANGAreNotGnu @cheungdaven 
> v1.2 release notes

- docs/whats_new/index.md
- docs/whats_new/v1.2.0.md
Co-authored-by: Oleksandr Shchur <oleks.shchur@gmail.com>
Co-authored-by: FANGAreNotGnu <kevinfang97@gmail.com>
Co-authored-by: Abdul Fatir <Abdulfatirs@gmail.com>
(cherry picked from commit c1181326cf6b7e3b27a7420273f1a82808d939e2)
> v1.2 release notes (#4693)

- docs/tutorials/tabular/advanced/tabular-custom-metric.ipynb
> tabular-custom-metric.ipynb: fixed a typo in a link

- core/src/autogluon/core/metrics/__init__.py
- core/src/autogluon/core/metrics/classification_metrics.py
- core/tests/unittests/metrics/test_metrics.py
Resolves #4590 
Closes #4750
Fix balanced_accuracy edge-case exception detailed in #4590.
Additionally adds many metric unit tests to better detect bugs like this in future. The new unit tests catch the previous bug.
> [tabular] Fix balanced_accuracy edge-case

- multimodal/tests/unittests/others_2/test_ner_chinese.py
- multimodal/tests/unittests/others_2/test_predictor_advanced.py
> Fix AutoMM tests

- .github/workflow_scripts/lint_check.sh
- common/src/autogluon/common/features/feature_metadata.py
- common/src/autogluon/common/loaders/_utils.py
- common/src/autogluon/common/utils/path_converter.py
- common/src/autogluon/common/utils/try_import.py
- common/src/autogluon/common/utils/utils.py
- core/setup.py
- features/src/autogluon/features/generators/astype.py
- features/tests/features/conftest.py
- multimodal/tests/unittests/others_2/test_ner_chinese.py
- multimodal/tests/unittests/others_2/test_predictor_advanced.py
- timeseries/src/autogluon/timeseries/models/chronos/pipeline/chronos.py
- timeseries/tests/unittests/test_trainer.py
> update ray to include 2.40

- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
Resolves #3611
Fix HPO logging verbosity to match the predictor's verbosity level
> [tabular] Fix HPO logging verbosity

- docs/tutorials/timeseries/advanced/forecasting-custom-model.ipynb
- docs/tutorials/timeseries/advanced/index.md
- docs/tutorials/timeseries/index.md
- Add a tutorial describing how to add a custom time series forecasting model
> [timeseries] Add custom forecasting model tutorial

- pyproject.toml
- timeseries/src/autogluon/timeseries/dataset/ts_dataframe.py
- timeseries/src/autogluon/timeseries/metrics/__init__.py
- timeseries/src/autogluon/timeseries/metrics/abstract.py
- timeseries/src/autogluon/timeseries/metrics/point.py
- timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
- timeseries/src/autogluon/timeseries/models/ensemble/abstract_timeseries_ensemble.py
- timeseries/src/autogluon/timeseries/models/ensemble/greedy_ensemble.py
- timeseries/src/autogluon/timeseries/models/presets.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/src/autogluon/timeseries/splitter.py
- timeseries/src/autogluon/timeseries/trainer/abstract_trainer.py
- timeseries/src/autogluon/timeseries/trainer/auto_trainer.py
- timeseries/tests/unittests/test_trainer.py
Start addressing static type checker (pyright) issues in AbstractTrainer and the metrics module.
> [timeseries] address type checker issues in metrics and trainer

- CONTRIBUTING.md
Update CONTRIBUTORS.md to reference Python 3.12 and remove Python 3.8.
This is my first contribution to AutoGluon, and also serves as a test for submitting commits.
> Updating Python version requirements in CONTRIBUTORS.md

- core/src/autogluon/core/learner/abstract_learner.py
- timeseries/src/autogluon/timeseries/dataset/ts_dataframe.py
- timeseries/src/autogluon/timeseries/learner.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/src/autogluon/timeseries/regressor.py
- timeseries/src/autogluon/timeseries/trainer/abstract_trainer.py
- timeseries/src/autogluon/timeseries/trainer/auto_trainer.py
- timeseries/src/autogluon/timeseries/transforms/covariate_scaler.py
- timeseries/src/autogluon/timeseries/transforms/target_scaler.py
- timeseries/tests/unittests/test_learner.py
```
pyright timeseries/src/autogluon/timeseries/{configs,trainer,metrics,transforms,regressor.py,splitter.py,learner.py,evaluator.py}
```
> [timeseries] address type checker issues in transforms, learner and others

- examples/automm/tabular_dl/dataset.py
- multimodal/tests/unittests/others_2/test_backward_compatibility.py
- multimodal/tests/unittests/utils/utils.py
Fixes https://github.com/autogluon/autogluon/issues/4806
> Update s3 path to public URL for AutoMM unit tests

- common/src/autogluon/common/utils/utils.py
- common/tests/unittests/test_setup_outputdir.py
Fixes https://github.com/autogluon/autogluon/issues/4733
> Fix setup_outputdir

- tabular/src/autogluon/tabular/models/catboost/callbacks.py
- Refactor the `memory_check` function in the CatBoost model to improve clarity and simplify memory checks.
> Refactor CatBoost memory_check function

- features/src/autogluon/features/binning.py
- tabular/src/autogluon/tabular/models/_utils/rapids_utils.py
- tabular/src/autogluon/tabular/predictor/predictor.py
> fix codespell errors

- tabular/src/autogluon/tabular/experimental/_tabular_classifier.py
- tabular/src/autogluon/tabular/experimental/_tabular_regressor.py
- tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
- tabular/src/autogluon/tabular/models/lgb/lgb_utils.py
- tabular/src/autogluon/tabular/models/tab_transformer/modified_transformer.py
- tabular/src/autogluon/tabular/models/tab_transformer/tab_transformer_encoder.py
- tabular/src/autogluon/tabular/predictor/_deprecated_methods.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/src/autogluon/tabular/trainer/auto_trainer.py
´PEP585 with support for python >= 3.9 and <=3.12
> [tabular] update code with PEP585

- .github/workflow_scripts/test_timeseries.sh
- timeseries/src/autogluon/timeseries/predictor.py
Add pytest-xdist for accelerating time series tests.
> Add xdist to timeseries

- multimodal/setup.py
*Issue #, if available:* #4719
Bumped torchmetrics install range to "torchmetrics>=1.2.0,<1.6.1"
> Bump torchmetrics version range

- .github/workflows/benchmark-command.yml
- .github/workflows/benchmark_master.yml
- .github/workflows/pypi_release.yml
- .github/workflows/pythonpublish.yml
- .github/workflows/pythonpublish_testpypi.yml
Update GitHub Actions
- Update python version from 3.8 to 3.9
- Update setup-python from v1 and v4 to v5
Closes #4841 
> Update GitHub Actions

- README.md
- docs/conf.py
- docs/index.md
[Master] Update readme and website index page
> [Master] Update readme and website index page

- common/src/autogluon/common/utils/try_import.py
- core/setup.py
Closes: https://github.com/autogluon/autogluon/issues/4883
> bump ray to latest version 2.42

- tabular/src/autogluon/tabular/experimental/plot_leaderboard.py
- Add experimental plot_leaderboard.py, with functions to visualize AutoGluon's performance over time for a given task.
```python
from autogluon.tabular.experimental.plot_leaderboard import plot_leaderboard_with_predictor
data_root = 'https://autogluon.s3.amazonaws.com/datasets/Inc/'
predictor_example = TabularPredictor(label="class").fit(train_data=data_root + "train.csv", time_limit=60)
figure, lb = plot_leaderboard_from_predictor(predictor=predictor_example, test_data=data_root + "test.csv", ensemble=True)
with pd.option_context("display.max_rows", None, "display.max_columns", None, "display.width", 1000):
print(lb)
figure.savefig("example_leaderboard_plot.png")
```
```
model …
```
> [tabular] Add plot_leaderboard.py

- SECURITY.md
Update SECURITY.md for 1.2.0 version
> Update SECURITY.md for 1.2.0 version

- timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
- timeseries/src/autogluon/timeseries/models/autogluon_tabular/mlforecast.py
- timeseries/src/autogluon/timeseries/models/autogluon_tabular/transforms.py
- timeseries/src/autogluon/timeseries/models/ensemble/abstract_timeseries_ensemble.py
- timeseries/src/autogluon/timeseries/models/multi_window/multi_window_model.py
- timeseries/src/autogluon/timeseries/regressor.py
- timeseries/src/autogluon/timeseries/transforms/__init__.py
- timeseries/src/autogluon/timeseries/transforms/covariate_scaler.py
- timeseries/src/autogluon/timeseries/transforms/target_scaler.py
- timeseries/tests/unittests/models/test_abstract.py
- timeseries/tests/unittests/models/test_gluonts.py
- timeseries/tests/unittests/models/test_models.py
- timeseries/tests/unittests/models/test_multi_window_model.py
- timeseries/tests/unittests/test_regressor.py
- timeseries/tests/unittests/test_transforms.py
> [timeseries] remove lazy init from model, decouple regressor and transforms

- tabular/setup.py
N/A
* Updated LightGBM dependency to require version 4.6.x (previously 4.0.x-4.5.x)
* Fixed code formatting issues in `setup.py`
> upgrade lightgbm version

- tabular/setup.py
- tabular/tests/unittests/models/test_tabpfn.py
Remove TabPFN to fix source install
> Remove TabPFN to fix source install

- timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- timeseries/src/autogluon/timeseries/models/gluonts/torch/models.py
Pyright typing improvements for abstract models and gluonts models
> [timeseries] typing improvements for gluonts models

- .github/workflows/slash_command_dispatch.yml
> fix slash command for benchmark

- timeseries/src/autogluon/timeseries/models/chronos/pipeline/chronos_bolt.py
*Description of changes:* See https://github.com/amazon-science/chronos-forecasting/pull/294.
> [timeseries] Chronos-Bolt: Fix scaling that affects constant series

- .github/workflow_scripts/env_setup.sh
This is a test PR to see if capping the bench version fixes the benchmark test
> [Fix] [Test] Test fix by capping bench version

- common/src/autogluon/common/utils/simulation_utils.py
> [Tabular] fix linting

- .github/workflow_scripts/env_setup.sh
> [Test] Source install AG-Bench

- timeseries/setup.py
- timeseries/src/autogluon/timeseries/dataset/ts_dataframe.py
- timeseries/src/autogluon/timeseries/utils/features.py
- timeseries/src/autogluon/timeseries/utils/warning_filters.py
> [timeseries] typing improvements for utils

- timeseries/tests/unittests/test_regressor.py
- Fix time series platform tests for py39 ([logs](https://github.com/autogluon/autogluon/actions/runs/14659809156/job/41141538019))
> [timeseries] Fix platform tests for py39

- timeseries/src/autogluon/timeseries/metrics/__init__.py
This PR fixes TS training on Python3.9.
> [timeseries] Fix typing compatibility with py39

- tabular/src/autogluon/tabular/models/lgb/callbacks.py
- tabular/src/autogluon/tabular/models/lgb/lgb_model.py
- Improve LightGBM memory estimate
> [tabular] Improve LightGBM memory estimate

- docs/whats_new/v0.4.0.md
- docs/whats_new/v0.4.1.md
- docs/whats_new/v0.5.1.md
- docs/whats_new/v0.6.0.md
- docs/whats_new/v0.6.1.md
- docs/whats_new/v0.6.2.md
- docs/whats_new/v0.7.0.md
- docs/whats_new/v0.8.0.md
- docs/whats_new/v0.8.1.md
- docs/whats_new/v0.8.2.md
- docs/whats_new/v0.8.3.md
- docs/whats_new/v1.0.0.md
- docs/whats_new/v1.1.0.md
- docs/whats_new/v1.1.1.md
- docs/whats_new/v1.2.0.md
- release_instructions/ReleaseInstructions.md
- release_instructions/add_links_to_release_notes.py
- Update all whats_new files with proper urls + add script to add urls to release notes
> Update all release notes with proper urls + add script to add urls

- docs/whats_new/v1.3.0.md
- release_instructions/ReleaseInstructions.md
- release_instructions/add_links_to_release_notes.py
Add release instructions for pasting whats_new release notes
> Add release instructions for pasting whats_new release notes

- docs/tutorials/multimodal/advanced_topics/presets.ipynb
- multimodal/setup.py
N/A
* Set upper bound of nltk for verbose logging issue
* Fix automm presets tutorial for new APIs in 1.3
> [Master] Fix multimodal tutorial issue after 1.3 release

- docs/tutorials/multimodal/advanced_topics/presets.ipynb
- multimodal/setup.py
N/A
* Set upper bound of nltk for verbose logging issue
* Fix automm presets tutorial for new APIs in 1.3
> [Stable] Fix multimodal tutorial issue after 1.3 release

- CI/batch/docker/Dockerfile.cpu
- CI/batch/docker/Dockerfile.gpu
- CI/docker/Dockerfile.cpu-inference
- CI/docker/Dockerfile.cpu-training
- CI/docker/Dockerfile.gpu-inference
- CI/docker/Dockerfile.gpu-training
> [CI] update docker image to use 1.3 release base

- docs/whats_new/index.md
- docs/whats_new/v1.3.1.md
- Draft of the release notes for v1.3.1
Section owners:
Tabular -> @Innixma
TimeSeries -> @shchur @canerturkmen @abdulfatir
Multimodal -> @FANGAreNotGnu @tonyhoo
> Add release notes for v1.3.1

- common/setup.py
- common/src/autogluon/common/loaders/load_pkl.py
- common/src/autogluon/common/savers/save_str.py
- Add load pickle from url support, fix save_str if root path.
- Add documentation to `load_pkl.load`
> Add load pickle from url support, fix save_str if root path.

- docs/tutorials/multimodal/multimodal_prediction/multimodal-quick-start.ipynb
- multimodal/setup.py
- multimodal/src/autogluon/multimodal/data/trivial_augmenter.py
Update NLTK dependency constraint to <3.10 
> Update NLTK dependency constraint to <3.10 to address CVE-2024-39705

- .github/workflow_scripts/env_setup.sh
- .github/workflow_scripts/test_multimodal.sh
- .github/workflow_scripts/test_tabular.sh
- .github/workflow_scripts/test_timeseries.sh
Fix CICD [failure](https://github.com/autogluon/autogluon/actions/runs/15449884138/job/44206490131)
> Fix Python syntax in CUDA library path detection

- timeseries/src/autogluon/timeseries/models/chronos/pipeline/utils.py
- timeseries/src/autogluon/timeseries/models/gluonts/__init__.py
- timeseries/src/autogluon/timeseries/models/gluonts/abstract.py
- timeseries/src/autogluon/timeseries/models/gluonts/dataset.py
- timeseries/src/autogluon/timeseries/models/gluonts/models.py
- timeseries/tests/unittests/models/common.py
- timeseries/tests/unittests/models/test_gluonts.py
- timeseries/tests/unittests/test_metrics.py
> [timeseries] reorganize gluonts namespace

- tabular/src/autogluon/tabular/models/lgb/lgb_model.py
fobj was removed from v4.0.0 in lgb
#5199 
fobj was removed from v4.0.0 in lgb‘
removed it and use params instead.
> [Fix] remove fobj in SOFTCLASS

- CI/bench/generate_bench_config.sh
Add time limit conversion to seconds in benchmark config script
> Add time limit conversion to seconds in benchmark config script

- tabular/src/autogluon/tabular/models/mitra/_internal/__init__.py
- tabular/src/autogluon/tabular/models/mitra/_internal/config/__init__.py
- tabular/src/autogluon/tabular/models/mitra/_internal/config/config_run.py
- tabular/src/autogluon/tabular/models/mitra/_internal/config/enums.py
- tabular/src/autogluon/tabular/models/mitra/_internal/core/__init__.py
- tabular/src/autogluon/tabular/models/mitra/_internal/core/get_loss.py
- tabular/src/autogluon/tabular/models/mitra/_internal/core/prediction_metrics.py
- tabular/src/autogluon/tabular/models/mitra/_internal/core/trainer_finetune.py
- tabular/src/autogluon/tabular/models/mitra/_internal/data/__init__.py
- tabular/src/autogluon/tabular/models/mitra/_internal/data/preprocessor.py
- tabular/src/autogluon/tabular/models/mitra/_internal/models/__init__.py
- tabular/src/autogluon/tabular/models/mitra/_internal/models/tab2d.py
- tabular/src/autogluon/tabular/models/mitra/_internal/utils/__init__.py
- tabular/src/autogluon/tabular/models/mitra/mitra_model.py
- tabular/src/autogluon/tabular/models/mitra/sklearn_interface.py
- tabular/src/autogluon/tabular/models/realmlp/realmlp_model.py
- tabular/src/autogluon/tabular/models/tabicl/tabicl_model.py
- tabular/src/autogluon/tabular/models/tabm/_tabm_internal.py
- tabular/src/autogluon/tabular/models/tabm/tabm_model.py
- tabular/src/autogluon/tabular/models/tabm/tabm_reference.py
- tabular/src/autogluon/tabular/models/tabpfnv2/tabpfnv2_model.py
* Python 3.9 Support
* Support device detection to work with CPU, MPS and CUDA
> [tabular] Mitra Python 3.9 Support

- tabular/src/autogluon/tabular/models/mitra/mitra_model.py
Remove MPS for Mitra due to precision issue
> Remove MPS for Mitra due to precision issue

- tabular/tests/unittests/configs/test_presets.py
> [tabular] Fix test

- tabular/src/autogluon/tabular/configs/zeroshot/zeroshot_portfolio_2025.py
- tabular/src/autogluon/tabular/models/mitra/mitra_model.py
- Enable Mitra on CPU
- Still require a GPU to fit Mitra in the new preset portfolio.
- Added a warning if trying to fine-tune Mitra on CPU.
> Enable Mitra on CPU

- docs/api/autogluon.tabular.models.rst
- docs/whats_new/index.md
- docs/whats_new/v1.4.0.md
- tabular/src/autogluon/tabular/predictor/predictor.py
- Draft of the release notes for v1.3.1
Section owners:
MLZero -> @FANGAreNotGnu  @boranhan 
MITRA -> @xiyuanzh 
TabArena -> @Innixma 
Tabular -> @Innixma @xiyuanzh 
TimeSeries -> @shchur @canerturkmen @abdulfatir
Multimodal -> @FANGAreNotGnu @tonyhoo
> Add release notes for v1.4.0

- tabular/setup.py
*Description of changes:* Add einops in mitra install, same version range as tabpfnmix
> Add einops in mitra install

- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
> Minor logging fix

- tabular/src/autogluon/tabular/predictor/predictor.py
Resolves #5283
- Clarify `tuning_data` documentation
> [doc] Clarify `tuning_data` documentation

- common/src/autogluon/common/utils/try_import.py
- core/setup.py
- core/tests/unittests/hpo/test_ray_hpo.py
> [Test] Fix CI + Upgrade Ray

- timeseries/src/autogluon/timeseries/metrics/abstract.py
- timeseries/src/autogluon/timeseries/models/multi_window/multi_window_model.py
- timeseries/src/autogluon/timeseries/utils/features.py
> [timeseries] typing improvements to multiwindow model
