- eda/src/autogluon/eda/analysis/interaction.py
- eda/src/autogluon/eda/analysis/model.py
- eda/src/autogluon/eda/auto/simple.py
- eda/src/autogluon/eda/state.py
- eda/src/autogluon/eda/visualization/__init__.py
- eda/src/autogluon/eda/visualization/layouts.py
- eda/src/autogluon/eda/visualization/model.py
- eda/tests/unittests/auto/test_simple.py
- eda/tests/unittests/visualization/test_layouts.py
- Added `PropertyRendererComponent` to enable simplified properties rendering stored in `state`:
- The following component apply `transform_fn` to an object stored in `state.model_evaluation.highest_error` then render it (if the object present):
```python
PropertyRendererComponent("model_evaluation.highest_error", transform_fn=(lambda df: df.head(10))),
```
- `MarkdownSectionComponent` now supports `condition_fn` argument to enable conditional rendering:
```python
MarkdownSectionComponent(
condition_fn=(lambda state: is_key_present_in_state(state, "model_evaluation.undecided")),
markdown="Text to render",
),
```
- samples with the highest prediction error - candidates for inspection
- smaples with the least distance from the other class - candidates for labeling …
> [eda] Updates for quick-fit to include samples display

- timeseries/src/autogluon/timeseries/evaluator.py
- timeseries/src/autogluon/timeseries/models/ensemble/__init__.py
- timeseries/src/autogluon/timeseries/models/ensemble/abstract_timeseries_ensemble.py
- timeseries/src/autogluon/timeseries/models/ensemble/greedy_ensemble.py
- timeseries/src/autogluon/timeseries/trainer/abstract_trainer.py
- timeseries/tests/unittests/models/test_ensemble.py
- timeseries/tests/unittests/test_trainer.py
This PR lays the groundwork for the implementation of more sophisticated ensembling strategies for time series.
- Introduce `AbstractTimeSeriesEnsembleModel` - base class implementing different ensembling strategies for time series models.
- Refactor and simplify the logic for fitting the simple greedy ensemble for time series.
- Combine `SimpleTimeSeriesWeightedEnsemble` and `TimeSeriesEnsembleWrapper` into a single class -> `TimeSeriesGreedyEnsemble`
- Simplify the logic in `AbstractTimeSeriesTrainer.fit_ensemble`.
- Save ensemble to disk as a usual model instead of storing it inside the `model_graph`.
- Minor change: 10x speedup for `mean_wQuantileLoss` calculation using vectorization.
By submitting this pull request, I confirm that you can use, modify, copy, …
> [timeseries] Create an abstract class for time series ensembles

- timeseries/src/autogluon/timeseries/configs/presets_configs.py
- timeseries/src/autogluon/timeseries/dataset/ts_dataframe.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/tests/unittests/test_ts_dataset.py
- Remove deprecated methods & presets from `autogluon.timeseries`.
> [timeseries] Remove deprecations scheduled for v0.7

- multimodal/src/autogluon/multimodal/predictor.py
Performing prediction on an image classification task wasted most of the time on preprocessing. See a complete breakdown below :
```
elapsed (preprocess): 42.2 ms
> elapsed (data_to_df): 0.3 ms
> elapsed (infer_column_types): 1.2 ms
> elapsed (deepcopy): 40.5 ms
elapsed (compute_xxx): 0.3 ms
elapsed (realtime_predict): 36.1 ms
```
, while total prediction time is 78.8 ms
* avoid deepcopy of data_preprocessors in predict() function
* preprocess time reduced from 42.2 ms to 1.9 ms
* overall prediction time (image classification task) reduced from 78.8 ms to 39.7 ms
To reproduce
```python
import time
from autogluon.multimodal.utils.misc import shopee_dataset
from autogluon.multimodal import MultiModalPredictor
def main():
download_dir = …
```
> [multimodal] avoid deepcopy of data_processors

- eda/src/autogluon/eda/analysis/__init__.py
- eda/src/autogluon/eda/analysis/dataset.py
- eda/src/autogluon/eda/auto/simple.py
- eda/src/autogluon/eda/visualization/__init__.py
- eda/src/autogluon/eda/visualization/dataset.py
- eda/tests/unittests/analysis/test_dataset.py
- eda/tests/unittests/analysis/test_model.py
- eda/tests/unittests/auto/test_simple.py
- eda/tests/unittests/visualization/test_dataset.py
Analyze label for insights:
- classification: low cardinality classes detection
- classification: classes present in test data, but not in the train data
- regression: out-of-domain labels detection
**Example**
```python
import autogluon.eda.analysis as eda
import autogluon.eda.visualization as viz
auto.analyze(
auto.analyze(train_data=..., test_data=..., label=..., anlz_facets=[
eda.dataset.ProblemTypeControl(),
eda.dataset.LabelInsightsAnalysis(low_cardinality_classes_threshold=50, regression_ood_threshold=0.01),
], viz_facets=[
viz.dataset.LabelInsightsVisualization()
])
```
**Classification outputs:**
**Regression outputs:**
Helper component to control problem type. Autodetect if `problem_type = 'auto'`. See example of use …
> [eda] LabelInsightsAnalysis/LabelInsightsVisualization - label column insights for classification and regression

- core/src/autogluon/core/trainer/abstract_trainer.py
- tabular/tests/unittests/test_tabular.py
Currently unit test will not fail as long as there's at least one model being trained. We would like to capture any failures in our unit test instead
* Added a variable recording failed models and check it during unit tests
> Add model failed to train check

- multimodal/src/autogluon/multimodal/data/process_text.py
- multimodal/src/autogluon/multimodal/data/utils.py
- multimodal/tests/unittests/predictor/test_predictor.py
#2741 
Fix computing the max length. Checkpoint `CLTL/MedRoBERTa.nl`'s max length in tokenizer is incorrect. Use the `max_position_embeddings` instead.
> [AutoMM] Fix token max length

- docs/tutorials/multimodal/advanced_topics/customization.md
- multimodal/src/autogluon/multimodal/configs/data/default.yaml
- multimodal/src/autogluon/multimodal/data/process_image.py
- multimodal/src/autogluon/multimodal/data/process_mmlab/process_mmdet.py
- multimodal/src/autogluon/multimodal/data/process_mmlab/process_mmlab_base.py
- multimodal/src/autogluon/multimodal/data/process_mmlab/process_mmocr.py
- multimodal/src/autogluon/multimodal/predictor.py
1. Fallback to original column type when `infer_type` on image was not successful during inference;
2. Update default `missing_value_strategy` to `zero`
> Fix image type fallback

- multimodal/src/autogluon/multimodal/data/utils.py
- multimodal/tests/unittests/others/test_utils.py
Allow partial overlapping between custom annotations and the words from pre-tokenization. Previous version only labels words that are within the custom annotations offset and skips all other words.
Add unit test.
> [NER] Allow noisy annotations

- timeseries/src/autogluon/timeseries/learner.py
- timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
- timeseries/src/autogluon/timeseries/models/autogluon_tabular/tabular_model.py
- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- timeseries/src/autogluon/timeseries/models/gluonts/mx/models.py
- timeseries/src/autogluon/timeseries/models/gluonts/torch/models.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/src/autogluon/timeseries/utils/features.py
- timeseries/tests/smoketests/test_features_and_covariates.py
- timeseries/tests/unittests/common.py
- timeseries/tests/unittests/models/test_autogluon_tabular.py
- timeseries/tests/unittests/models/test_models.py
- timeseries/tests/unittests/test_features.py
- timeseries/tests/unittests/test_learner.py
- Fix several bugs related to `past_covariates` handling
- Include documentation for `past_covariates`
- Add support for `past_covariates` and `known_covariates` to `AutoGluonTabular` model
- Add support for `past_covariates` to `TemporalFusionTransformerMXNet` model
- Add tests
> [timeseries] Add support for past_covariates to Predictor & models

- timeseries/src/autogluon/timeseries/models/sktime/abstract_sktime.py
- We switched to the `StatsForecast` implementation of `AutoETS` and `AutoARIMA` (instead of `sktime` and `pmdarima`), so these dependencies will be removed in a future release.
> [timeseries] Add deprecation warning for Sktime models

- eda/src/autogluon/eda/auto/simple.py
- eda/src/autogluon/eda/utils/defaults.py
- eda/tests/unittests/auto/test_simple.py
By default quick fit is using `RF` model if no hyperparameters are provided. Switched default to use Extra Trees LightGBM if LightGBM is available.
> [eda] use LightGBM in quick_fit if available

- docs/tutorials/multimodal/text_prediction/ner.md
- multimodal/src/autogluon/multimodal/data/labelencoder_ner.py
- multimodal/src/autogluon/multimodal/data/preprocess_dataframe.py
- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/utils/inference.py
- multimodal/tests/unittests/others/test_ner.py
Now, we can get the detailed probabilities for NER output, using
predictions = `predictor.predict_proba(data)`
> [NER] add support for predict_proba 

- multimodal/src/autogluon/multimodal/data/datamodule.py
- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/tests/unittests/others/test_save_path.py
#2756 
1. persistent_workers=True if num_workers > 0.
2. reload_dataloaders_every_n_epochs=0.
3. Remove the additional evaluation in top_k_average. Use the best validation score from training instead to reduce overhead.
This PR can substantially reduce the time overhead of multi-gpu training introduced by 0.6.2. Specifically, for 60s time limit, it even uses less training time compared to 0.5.2.
**Environment**
g4dn.12xlarge, pytorch-lightning 1.8.6
**time_limit=30**
* best
* PR's time: 76.5s
* 0.5.2 time: 75.6s
* greedy soup
* PR's time: 87.3s
* 0.5.2 time: 82.2s
* uniform soup
* PR's time: 77.1s
* 0.5.2 time: 75.9s
**time_limit=60**
* best
* PR's time: 104.7s
* 0.5.2 time: 110.8s
* greedy soup
* PR's time: 116.7s
* 0.5.2 time: 120.0s
* …
> [AutoMM] Speed up training

- multimodal/src/autogluon/multimodal/models/huggingface_text.py
- multimodal/tests/hf_model_list.yaml
- multimodal/tests/unittests/others_2/test_predictor_with_bart.py
BART models won't support `token_type_ids`. This is identified via:
```python3
from transformers import AutoTokenizer
tokenizer_bart = AutoTokenizer.from_pretrained("facebook/bart-base")
print("BART: ", tokenizer_bart.model_input_names)
tokenizer_electra = AutoTokenizer.from_pretrained("google/electra-base-discriminator")
print("ELECTRA:", tokenizer_electra.model_input_names)
```
Output:
```
BART:  ['input_ids', 'attention_mask']
ELECTRA: ['input_ids', 'token_type_ids', 'attention_mask']
```
> [BugFix] Fix usage of BART in HF_Text

- docs/tutorials/timeseries/forecasting-indepth.md
This PR removes an old TODO item from the Timeseries In-depth tutorial.
I am making this change because the AppSec review of our content requested that our docs contain no TODO items.
> Remove "TODO" comment from forecasting in-depth tutorial

- multimodal/src/autogluon/multimodal/configs/data/default.yaml
- multimodal/src/autogluon/multimodal/data/process_categorical.py
- multimodal/src/autogluon/multimodal/data/process_image.py
- multimodal/src/autogluon/multimodal/data/process_label.py
- multimodal/src/autogluon/multimodal/data/process_mmlab/process_mmdet.py
- multimodal/src/autogluon/multimodal/data/process_mmlab/process_mmocr.py
- multimodal/src/autogluon/multimodal/data/process_ner.py
- multimodal/src/autogluon/multimodal/data/process_numerical.py
- multimodal/src/autogluon/multimodal/data/process_text.py
1. Align `missing_value_strategy `'s default with comments.
2. Fix/remove some docstrings in data processors.
3. Clean up some unused variables in ner processor.
> [AutoMM] Fix some comments and docstrings

- multimodal/src/autogluon/multimodal/utils/model.py
- multimodal/tests/unittests/predictor/test_predictor.py
Some unused model configs still exist in the saved config, which can confuse users.
Filter out the unused model configs and only keep the used ones.
> [AutoMM] Filter out unused model configs

- docs/tutorials/timeseries/forecasting-indepth.md
- docs/tutorials/timeseries/forecasting-model-zoo.rst
- timeseries/src/autogluon/timeseries/models/__init__.py
- timeseries/src/autogluon/timeseries/models/local/__init__.py
- timeseries/src/autogluon/timeseries/models/local/statsforecast.py
- timeseries/src/autogluon/timeseries/models/presets.py
- timeseries/tests/unittests/models/test_local.py
- Discuss `past_covariates` in the in-depth tutorial
- Add the missing `Model` suffix to StatsForecast models
- Add StatsForecast models to the model zoo
- Remove GluonTS MXNet models from the model zoo
> [timeseries] Update documentation for timeseries

- docs/tutorials/timeseries/forecasting-quickstart.md
- Use first 200 items from the M4 hourly dataset for faster results.
> [timeseries] Speed up the time series quickstart tutorial by using a smaller dataset

- .github/workflow_scripts/build_multimodal_tutorial.sh
- .github/workflow_scripts/build_text_prediction_tutorial.sh
- .github/workflow_scripts/env_setup.sh
- .github/workflow_scripts/setup_hf_model_mirror.py
- .github/workflow_scripts/test_multimodal.sh
- CI/hf_mirror/Dockerfile
- CI/hf_mirror/deploy.sh
- CI/hf_mirror/download_hf_models.py
- CI/hf_mirror/download_hf_models.sh
- multimodal/tests/hf_model_list.yaml
* Have setup an AWS Batch job running chronically to sync up our models stored in S3 with HF. An EFS was used as a cache so we don't re-download the model each time.
* List of models will be fetched dynamically from our repo with `hf_model_list.yaml`
* All models in the list will be downloaded and synced to our S3, no matter which subfolder it belongs to
* CI job will use `setup_hf_model_mirror.py` to download the corresponding models to `~/.cache/huggingface/hub` for the specific subfolder to test.
* Updated the structure of the model list.
* A follow-up PR to enforce model list updating will be sent
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
> [CI] Enable HF model caching

- .github/workflows/check_hf_model_list.yml
* This workflow will fail whenever the commit modified multimodal unit tests/doc to ensure people remember updating the model list file if necessary. Can be passed by adding the label `model list checked`
* Have tested on my fork: https://github.com/yinweisu/autogluon/pull/20
> [MERGE AFTER HF CACHE ENABLED] Enforce model list check

- common/src/autogluon/common/savers/save_pkl.py
- core/src/autogluon/core/trainer/abstract_trainer.py
- core/src/autogluon/core/utils/utils.py
- tabular/src/autogluon/tabular/learner/abstract_learner.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/tests/unittests/test_tabular.py
- Add predictor.predict_dict and predictor.predict_proba_dict
- This is an optimized way to get predictions for a list of models, faster than looping through predictor.predict or predictor.predict_proba
- Also serves as a clean way to vend per-model out-of-fold predictions, validation predictions, and test predictions for the purposes of more advanced logic (Meta-learning / Zero-shot HPO)
- Fixed inconsistency with predictions, now will round pred_proba ties to 0 instead of 1 always when converting proba to pred, previously if object was pandas DF we would round to 0 and if it was a pandas Series we would round to 1.
- Fixed bug in save_pkl where it would crash if saving file to working directory root.
By submitting this pull request, I …
> Add predictor.predict_multi and predictor.predict_proba_multi

- core/setup.py
- docs/requirements_doc.txt
- multimodal/setup.py
- Remove dask and distributed dependencies
- This is to check if they are actually needed
> Remove dask and distributed dependencies

- timeseries/setup.py
- timeseries/src/autogluon/timeseries/models/gluonts/__init__.py
- The new GluonTS version seems to overcome our method for silencing the JSON warning, so it's probably easier to just add `ujson` as a dependency. The library is actively developed and actually isn't use in our code, so it should be safe.
> [timeseries] Add ujson dependency to silence the GluonTS warning

- timeseries/src/autogluon/timeseries/models/autogluon_tabular/tabular_model.py
- When training `AutoGluonTabular` model with both past & known covariates, the following warning is raised by pandas
> /local/home/shchuro/workspace/autogluon/timeseries/src/autogluon/timeseries/models/autogluon_tabular/tabular_model.py:230: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
This happens at line
```
features[self.target] = time_series[self.target]
```
This PR replaces column insertion with a concatenation, which fixes this warning.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …
> [timeseries] Fix PerformanceWarning in AutoGluonTabularModel

- docs/api/autogluon.predictor.rst
- docs/tutorials/timeseries/forecasting-indepth.md
- timeseries/src/autogluon/timeseries/dataset/ts_dataframe.py
- timeseries/tests/unittests/common.py
- timeseries/tests/unittests/test_ts_dataset.py
- Two new methods for imputing the missing values. These should be called before passing the data to the `TimeSeriesPredictor`.
- `to_regular_index(freq)` - fills gaps in an irregularly-sampled time series with NaNs
- `fill_missing_values(method)`  - drop leading NaNs & replace other NaNs (middle/trailing) using the chosen method (forward fill or interpolation)
> [timeseries] Implement missing value imputation for TimeSeriesDataFrame

- core/src/autogluon/core/trainer/abstract_trainer.py
- core/src/autogluon/core/utils/utils.py
- Refactor AbstractTrainer.get_inputs_to_stacker
- This resolves a long-standing code hack that depended on creating a dummy stack ensemble model to preprocess stack features. With this refactor, we no longer create a dummy stack ensemble and Trainer no longer depends on StackerEnsembleModel, greatly simplifying the code.
- Tested for equivalence by first having the tests run and succeed end-to-end with both old and new variant running with assert equals of their values. (Refer to [this version of the code](https://github.com/autogluon/autogluon/pull/2744/commits/bf6e2edce022b4538a2509c1960a5df0f974d3d9) for the successful CI run with both variants active and checked for equivalence)
By submitting this pull request, I confirm that you can …
> Refactor AbstractTrainer.get_inputs_to_stacker

- common/setup.py
- core/src/autogluon/core/_setup_utils.py
- docs/README.md
- docs/ReleaseInstructions.md
- features/setup.py
- multimodal/setup.py
- tabular/setup.py
- timeseries/setup.py
- Add versioning release instructions
- add boto3 version range
- add requests version range
- add inline comments for where version ranges are defined
> Add versioning release instructions, add boto3 version range

- tabular/src/autogluon/tabular/configs/hyperparameter_configs.py
- Fix Tabular multimodal preset, previously text model crashed due to 'medium_quality_faster_train' being an invalid preset.
> Fix Tabular multimodal preset

- .github/workflows/continuous_integration.yml
- core/src/autogluon/core/_setup_utils.py
- eda/tests/unittests/auto/test_simple.py
#2813
- Expand numpy, scipy, and scikit-learn version ranges to include latest release.
- Version cap tqdm to `<5` (Current latest is `4.x`)
> Expand numpy,scipy,scikit-learn version ranges

- multimodal/src/autogluon/multimodal/utils/inference.py
I think we don't have a DictCollator in case of realtime prediction, therefore DataParallel here isn't actually functional.
Log warning for multi-gpu realtime prediction
> [multimodal] Log warning for multi-gpu realtime prediction

- CI/docker/full_install_image.sh
- CONTRIBUTING.md
- core/src/autogluon/core/_setup_utils.py
#2694 
Remove remaining existence of `autogluon.vision`, `ImagePredictor`, `ObjectDetector` and `gluoncv`
> Remove gluoncv

- multimodal/src/autogluon/multimodal/configs/environment/default.yaml
- multimodal/src/autogluon/multimodal/presets.py
The recent package updates make the previous cuda error disappear for deberta, num_workers>0, and muti-gpu. For fast training, we'd better use num_workers>0 by default.
> [AutoMM] Set num_workers>0 by default

- docs/tutorials/multimodal/document/document_classification.md
- multimodal/src/autogluon/multimodal/configs/data/default.yaml
- multimodal/src/autogluon/multimodal/data/infer_types.py
- multimodal/src/autogluon/multimodal/data/process_document.py
- multimodal/src/autogluon/multimodal/utils/checkpoint.py
- multimodal/src/autogluon/multimodal/utils/cloud_io.py
- multimodal/src/autogluon/multimodal/utils/data.py
- Support missing documents.
- exception handling for opening images.
- change top_k_average_method to best in tutorial.
- move dependence on lightning cloud_io.
> [DocClassifier] add missing documents support and exception handling

- docs/tutorials/tabular_prediction/tabular-deployment.md
This PR updates the tabular model deployment tutorial with some context on `persist_models` and `compile_models` for efficient real-time prediction.
> [tabular] mention persist and compile in deploy tutorial

- multimodal/src/autogluon/multimodal/utils/map.py
torchmetrics changed from pycocotool based mAP to torch based and has significant speed drop.
Here we change back to their implementation in 0.6.0 which is pycocotool based and gain 10x+ faster mAP validation speed.
> [multimodal] Change to pycocotool based mAP

- timeseries/setup.py
https://github.com/autogluon/autogluon/issues/2830
> Update version cap of lightning in timeseries

- timeseries/setup.py
#2831 
Fixing dependency version ranges in line with #2831, getting rid of the `~=` notation. Note that we install `ujson` just to silence GluonTS warnings, but we cap the version to <6 nevertheless. Changes were tested with regression tests.
> [timeseries] Fix dependency version ranges

- timeseries/setup.py
- timeseries/src/autogluon/timeseries/__init__.py
#2841 
As of v0.7, we are deprecating sktime in AG-TS, due to instability and efficiency issues. Nevertheless, we update the version ranges for conda compatibility. There are no regressions or additional faults in regression tests with v0.14 or v0.15, we cap at 0.16 as we will deprecate in the next release.
> [timeseries] update sktime dependency range

- docs/tutorials/multimodal/advanced_topics/customization.md
- multimodal/src/autogluon/multimodal/configs/optimization/adamw.yaml
- multimodal/src/autogluon/multimodal/optimization/lit_module.py
- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/tests/unittests/others_2/test_predictor_advanced.py
By default, a final validation is run after the training is signaled to stop, and as a result, AutoPilot team's 10min quick build on large dataset overshoots by quite a long time.
By passing in a `skip_final_val` flag, we disable the final validation by setting the `trainer.val_dataloaders = []` to stop the validation.
By setting:
```
"optimization.top_k_average_method": "best",
"optimization.val_check_interval": 1.0,
"optimization.skip_final_val" = True,
}
```
we were able to reduce the `.fit()` time from 30-40min down to 10min.
> Skip validation

- core/src/autogluon/core/utils/try_import.py
- tabular/setup.py
- tabular/src/autogluon/tabular/models/vowpalwabbit/vowpalwabbit_model.py
#2686 
- Update vowpalwabbit version
- This should hopefully fix Py310 MacOS install
- Note: Bug in vowpalwabbit>=9.5 : Model is not saved correctly, so avoiding that version for now.
This PR is low risk: vowpalwabbit is an optional dependency not installed by default, and it is not imported unless the user specifies vowpalwabbit to be trained.
> Update vowpalwabbit version

- multimodal/src/autogluon/multimodal/constants.py
#2878 
`automm` is not a recognized name space for AutoGluon, and thus is not part of the overall namespace log formatting that is done in `autogluon.common.utils.log_utils._add_stream_handler()` called during initialization of `autogluon.core`.
Change the logger name to start with `autogluon` to make verbosity work correctly.
> [AutoMM] Fix logger

- tabular/src/autogluon/tabular/configs/hyperparameter_configs.py
- tabular/tests/unittests/models/test_automm.py
- Switch Tabular's `'multimodal'` hyperparameter preset to use 1 AutoMM model rather than 2 models (one for text+tabular and one for vision).
- This leverages the benefits of AutoMM's multimodal fusion accuracy enhancements when text, tabular, and images are present in a single dataset.
> Tabular: Switch to use multimodal fusion

- multimodal/src/autogluon/multimodal/configs/environment/default.yaml
- multimodal/src/autogluon/multimodal/data/datamodule.py
- multimodal/src/autogluon/multimodal/matcher.py
- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/utils/__init__.py
- multimodal/src/autogluon/multimodal/utils/config.py
- multimodal/src/autogluon/multimodal/utils/inference.py
- multimodal/src/autogluon/multimodal/utils/object_detection.py
- multimodal/tests/unittests/predictor/test_predictor.py
- https://github.com/autogluon/autogluon/issues/2898
*Update, @zhiqiangdon noticed that we can simply set persistent_worker to False in the evaluation dataloader.
After setting `persistent_worker`, there seems to be an additional overhead in creating the prediction / evaluation dataloader. I thus compared the speed of `num_worders_evaluation` set to 0 and 2, and noticed that `num_workers_evaluation=0` will be 10x faster:
```python
import time
from autogluon.multimodal import MultiModalPredictor
from autogluon.multimodal.utils.misc import shopee_dataset
def test_num_workers_evaluation(num_workers=0, nrepeat=20):
download_dir = "./"
train_data_1, test_data_1 = shopee_dataset(download_dir=download_dir)
train_data_2, test_data_2 = …
```
> [Performance]Set persistent_worker in prediction dataloader to False + Remove seed in inference

- common/src/autogluon/common/__init__.py
- Currently, all AutoGluon modules except common will call `_add_stream_handler()` during init.
- This meant that AutoGluon logging would not log correctly if only `autogluon.common` was imported. For example, changing log level would be ignored.
- Note that `_add_stream_handler()` only performs operations the first time it is called in a session, so multiple calls will not change behavior, and are safe to do.
Example:
```python3
from autogluon.common.utils.log_utils import set_logger_verbosity
from autogluon.common.loaders.load_pd import logger
logger.warning('before verbosity 4')
logger.debug("should not see debug")
set_logger_verbosity(verbosity=4, logger=logger)
logger.warning('after verbosity 4')
logger.debug("should see debug")
``` …
> Add `_add_stream_handler()` call to common init

- eda/tests/test_check_style.py
B028: No explicit stacklevel keyword argument found. The warn method from the warnings module uses a stacklevel of 1 by default. This will only show a stack trace for the line on which the warn method is called. It is therefore recommended to use a stacklevel of 2 or greater to provide more information to the user.
> Lint error fix

- common/src/autogluon/common/loaders/load_s3.py
- tabular/src/autogluon/tabular/learner/abstract_learner.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/tests/unittests/test_tabular.py
#2820 (Part of the process to make the benchmark throughput easy for users to do on their own datasets)
- When skip_score=True and extra_metrics=None during a `predictor.leaderboard(data)` call, this PR allows `data` to not have the label column, since it isn't required (no scoring being done). This enables easier usage of inference speed analysis code that doesn't unnecessarily require the label column.
- Also deleted old unused code from `load_s3.py`, the same code but updated already exists in `load_pd.py`. Removing this code eliminates a circular import that causes ray to error in certain situations (Note: Error situation is outside of normal usage and did not effect users, only occurred when trying to parallelize boto3 calls using …
> Allow no y in leaderboard

- tabular/setup.py
resolves #2902
- Update to use latest scikit-learn-intelex version (latest release 2023.0.1 tested on linux, worked correctly)
> Update scikit-learn-intelex version

- tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
- tabular/src/autogluon/tabular/models/tabular_nn/torch/tabular_nn_torch.py
- Accelerate FastAI Preprocessing
- For datasets with many columns (>1000), this speeds up FastAI preprocessing by **>300**x when using `pandas==1.5.3`
- While the speedup is most large using `pandas==1.5.3` due to pandas having major slowdowns in several functions, it is also major using older pandas versions that are not as slow (instead of 300x faster, it is 30x faster).
- This speedup can result in training time going from 1000 seconds -> 25 seconds, and inference time from 70 seconds -> 0.13 seconds. (robert dataset)
- This PR additionally fixes another major bug: TabularNN time estimates were off by a factor of 128x, causing many situations where TabularNN will skip training due to thinking it will run out of time when time_limit is …
> Accelerate FastAI Preprocessing + Fix TabularNN time_limit

- tabular/setup.py
- tabular/src/autogluon/tabular/models/rf/compilers/onnx.py
#2922
* fix onnxruntime installation in setup.py
* fix compile_models error when onnxruntime is missing
> [tabular] fix compile_models error when onnxruntime is missing

- features/src/autogluon/features/generators/abstract.py
- features/src/autogluon/features/generators/astype.py
- features/tests/features/conftest.py
- features/tests/features/generators/test_auto_ml_pipeline.py
- features/tests/features/generators/test_bulk.py
Fix bug introduced in #2944 
- Fix bug when useless features are present (aka categorical with each value only appearing once) and boolean features >= 15, causing crash during inference in some cases.
- Technically this slows down preprocessing in this situation, but avoiding the slow down is massively complicated and not worth implementing.
- Added unit test
> Fix AsTypeFeatureGenerator Edge-case Crash

- multimodal/src/autogluon/multimodal/data/utils.py
- multimodal/src/autogluon/multimodal/utils/misc.py
- multimodal/tests/unittests/others/test_utils.py
The backend pretokenizer will not split punctuation, so we switch it to BertPreTokenizer which will consider both space and punctuation when doing pre-tokenization.
> [NER] Use BertPreTokenizer for pre-tokenization

- core/src/autogluon/core/utils/utils.py
- When the label column is dtype categorical, and a category exists that is present in 0 rows of the training data, an exception would be raised `'NoneType' object has no attribute 'reset_index'`. This PR fixes this issue by returning early in the function call.
- Note that this bug would only appear in very specific situations, and only if the user somehow had their dtype be category for the label column.
- Additionally fixes FutureWarnings from usage of deprecated functions `.append` and `.iteritems`
This bug was found while expanding the tabular benchmark suite to 300 datasets (from 100), as it caused 2 datasets to crash.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …
> Fix crash when 0 rows of class

- multimodal/src/autogluon/multimodal/utils/checkpoint.py
#3000
AutoMM can redundantly evaluate and checkpoint, leading to a doubling of training time, due to not updating `self._last_global_step_saved` in the checkpointing callback. Specifically when an epoch is a single step, this doubles training time.
This fixes that issue by updating `self._last_global_step_saved` in the callback's `_save_checkpoint` method to align with the parent method's logic.
Code to reproduce:
```python3
from autogluon.core.utils.loaders import load_pd
train_data = load_pd.load('https://autogluon-text.s3-accelerate.amazonaws.com/glue/sst/train.parquet')
test_data = load_pd.load('https://autogluon-text.s3-accelerate.amazonaws.com/glue/sst/dev.parquet')
subsample_size = 100  # subsample data for faster demo, try setting …
```
> AutoMM: Avoid redundant checkpointing and evaluation (2x training speedup)

- docs/tutorials/tabular/advanced/tabular-custom-metric.ipynb
- docs/tutorials/tabular/advanced/tabular-custom-model-advanced.ipynb
- docs/tutorials/tabular/advanced/tabular-custom-model.ipynb
- docs/tutorials/tabular/advanced/tabular-deployment.ipynb
- docs/tutorials/tabular/advanced/tabular-gpu.ipynb
- docs/tutorials/tabular/advanced/tabular-multilabel.ipynb
- docs/tutorials/tabular/tabular-essentials.ipynb
- docs/tutorials/tabular/tabular-feature-engineering.ipynb
- docs/tutorials/tabular/tabular-indepth.ipynb
- docs/tutorials/tabular/tabular-multimodal.ipynb
The `pip install` cell for the tabular tutorials should be `autogluon.tabular[all]` for all the notebooks except `tabular-multimodal` which should be `pip install autogluon` since AutoMM is needed as well.
> Update tabular tutorial pip installs

- .github/workflow_scripts/build_all_docs.sh
- .github/workflow_scripts/copy_docs.sh
The old AutoGluon website used the `root_index.html` file to add a header with links to every page. The new website handles this natively during the Sphinx build process.
There were steps in the AutoGluon CI related to copying this file under certain conditions. These steps failed after merge to `master` because the file no longer exists. This issue was not uncovered during development of the new website because the logic is only executed when the `master` branch is being built.
All lines referencing this vestigial file need to be removed.
> [CI] Remove vestigial root_index.html operations from doc build steps

- multimodal/src/autogluon/multimodal/matcher.py
- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/utils/__init__.py
- multimodal/src/autogluon/multimodal/utils/data.py
- multimodal/tests/unittests/predictor/test_predictor.py
Support passing path of training data in fit().
```
predictor = MultiModalPredictor(label="label")
predictor.fit(train_data=train_data_path)
```
> [AutoMM] Support using data path in fit()

- .github/workflow_scripts/build_all_docs.sh
- .github/workflow_scripts/build_doc.sh
I was cleaning up our `dev/` website S3 resources and observed that the S3 folder is ~70MBs, and ~28MBs of it is a directory called `.doctrees`. This directory is full of binary files names `*.doctree`. I determined that these files are created and used during the Sphinx build process but are not required for serving or viewing the generated webpage. See this [StackOverflow answer](https://stackoverflow.com/questions/33904042/is-doctrees-folder-required-for-displaying-html-docs-with-sphinx) and the related [Sphinx Docs](https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-d).
In this change, I delete these files from our CI build steps before doing `aws s3 cp` so that we don't waste S3 space, which will become more important when we …
> Remove .doctrees build artifacts before s3 upload

- multimodal/src/autogluon/multimodal/cli/prepare_detection_dataset.py
- multimodal/src/autogluon/multimodal/utils/download.py
Bandit requires to set timeout when calling `requests.get()`.
> Fix lint check

- multimodal/src/autogluon/multimodal/data/utils.py
Avoid negative index when padding
> [NER] Fix Negative Index Issue

- docs/ReleaseInstructions.md
During release, the repository notebook paths for Colab and Studio lab links need to be updated in the AutoGluon tutorials. This one line change adds instructions to do this.
Testing:
I tested the command on macOS because I believe that is the OS most developers will be using during release preparation.
> Add release instructions for modifying notebook paths

- docs/tutorials/eda/eda-auto-quick-fit.ipynb
- docs/tutorials/eda/eda-auto-target-analysis.ipynb
- eda/setup.py
- eda/src/autogluon/eda/analysis/__init__.py
- eda/src/autogluon/eda/analysis/explain.py
- eda/src/autogluon/eda/analysis/model.py
- eda/src/autogluon/eda/auto/__init__.py
- eda/src/autogluon/eda/auto/simple.py
- eda/src/autogluon/eda/visualization/__init__.py
- eda/src/autogluon/eda/visualization/explain.py
- eda/src/autogluon/eda/visualization/interaction.py
- eda/tests/unittests/analysis/test_explain.py
- eda/tests/unittests/analysis/test_model.py
- eda/tests/unittests/auto/test_simple.py
- eda/tests/unittests/visualization/test_explain.py
- added `explain_rows` method to `autogluon.eda.auto`; the methods performs Kernel SHAP values analysis and visualization
- `quick_fit`: fixes for highest_error and undecided rows calculations
```python
import numpy as np
df_train = pd.read_csv('https://autogluon.s3.amazonaws.com/datasets/titanic/train.csv')
df_test = pd.read_csv('https://autogluon.s3.amazonaws.com/datasets/titanic/test.csv')
label='Survived'
state = auto.quick_fit(
train_data=df_train,
label=label,
save_model_to_state=True,
return_state=True,
render_analysis=False,  # Don't render analysis
)
auto.explain_rows(
train_data=df_train,
model=state.model,
backend='shap',  # default | shap/fastshap
plot='force',  # default | force/waterfall …
```
> [eda] added `explain_rows` method to `autogluon.eda.auto` - Kernel SHAP visualization

- tabular/src/autogluon/tabular/predictor/predictor.py
- `predictor.evaluate(...)` would warn the user for using `predict_proba` unnecessarily when problem_type was regression.
- This has been resolved by checking if predict_proba is supported based on the problem type, and calling `predict` if it is not. The logic is identical from the users perspective, but without the warning.
> Tabular: Fix evaluate warning in regression

- eda/setup.py
- eda/src/autogluon/eda/analysis/model.py
- eda/src/autogluon/eda/auto/simple.py
- eda/src/autogluon/eda/visualization/__init__.py
- eda/src/autogluon/eda/visualization/model.py
- eda/tests/unittests/analysis/test_model.py
- eda/tests/unittests/visualization/test_model.py
Regression: switched prediction analysis from diagonal `y` vs `y^` to residuals plot with option to add Q-Q analysis (default) or histogram.
```python
df_train = pd.read_csv('https://autogluon.s3.amazonaws.com/datasets/AmesHousingPriceRegression/train_data.csv')
df_test = pd.read_csv('https://autogluon.s3.amazonaws.com/datasets/AmesHousingPriceRegression/test_data.csv')
target_col = 'SalePrice'
keep_cols = [
'Overall.Qual', 'Gr.Liv.Area', 'Neighborhood', 'Total.Bsmt.SF', 'BsmtFin.SF.1',
'X1st.Flr.SF', 'Bsmt.Qual', 'Garage.Cars', 'Half.Bath', 'Year.Remod.Add', target_col
]
auto.quick_fit(
train_data=df_train[keep_cols],
test_data=df_test[keep_cols],
label=target_col,
)
```
...
Customizing residuals outputs …
> [eda] switch regression analysis in `quick_fit` to use residuals plot

- core/src/autogluon/core/constants.py
- core/src/autogluon/core/models/abstract/abstract_model.py
- core/tests/unittests/models/abstract_model/test_init_user_params.py
- tabular/src/autogluon/tabular/models/catboost/catboost_model.py
- tabular/src/autogluon/tabular/models/knn/knn_model.py
- tabular/src/autogluon/tabular/models/lgb/lgb_model.py
- tabular/src/autogluon/tabular/models/rf/rf_model.py
- tabular/src/autogluon/tabular/models/xgboost/xgboost_model.py
resolves #3031 
- Previously it was very confusing how to specify aux hyperparameters of a model.
- Now, we simply prefix the hyperparameter with `ag.` to indicate it as an aux hyperparameter, which is much easier.
- Prior API functionality remains in-tact, this is purely an extra way to pass the arguments.
- Added unit tests for this logic.
- I've added a TODO to expand upon this long term for improved ease of use and extensibility by enabling aux hyperparameters to be part of HPO search spaces. This should be made available by v1.0 release, but is too complicated to make sense including in this PR.
Mainline:
```
'GBM': {'ag_args_fit': {'max_memory_usage_ratio': 2.5}},
}
```
This PR:
```
'GBM': …
```
> Tabular: Refactor params_aux & memory checks

- multimodal/src/autogluon/multimodal/utils/config.py
- multimodal/tests/unittests/others_2/test_predictor_advanced.py
Fix customizing hyperparameters through terminal commands.
> [AutoMM] Fix terminal input hyperparameters

- core/src/autogluon/core/metrics/__init__.py
- core/tests/unittests/metrics/test_metrics.py
- Supporting weighted RMSE for evaluation metric - if user specifies kwargs, it will use scikit learn's RMSE function, or else it will use the existing accelerated RMSE computation
- [tested] test-run with the example dataset
> Support sample_weight in RMSE

- multimodal/src/autogluon/multimodal/data/infer_types.py
- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/tests/unittests/others/test_utils.py
`filter_hyperparameters ` requires column type `text_ner` to keep the `ner_text` model. Post-process the `column_types` from `infer_column_types` to replace column type `text` with `text_ner`.
> [AutoMM] Fix NER HPO

- docs/tutorials/eda/components/autogluon.eda.explain.md
- docs/tutorials/eda/components/index.md
- docs/tutorials/eda/eda-auto-quick-fit.ipynb
- eda/src/autogluon/eda/analysis/explain.py
- eda/src/autogluon/eda/analysis/model.py
- eda/src/autogluon/eda/auto/simple.py
- eda/src/autogluon/eda/state.py
- eda/src/autogluon/eda/visualization/interaction.py
- eda/src/autogluon/eda/visualization/shift.py
- eda/tests/unittests/analysis/test_explain.py
- eda/tests/unittests/auto/test_simple.py
- eda/tests/unittests/test_state.py
- added support for dot-notation config to pass `fig_args` and `chart_args`; updated docs to document supported properties
- updated `quick_fit` to save model to state by default
- `covariate_shift` doesn't render categorical variables to highlight shift since they are not helpful
- updated docs to include `explain` modules
- [bugfix] `explain`: fixed columns handling when `rows` have different column order than the originally trained model so that `shap` doesn't complain
Dot notation for composite components now is more compact:
```python
auto.target_analysis(
train_data=df_train, 
label=target_col,
fig_args={
f'chart.{target_col}.figsize': (4,4),
'chart.Sex.figsize': (4,4),
'correlation.figsize': (1,1),
},
chart_args={
f'chart.{target_col}.color': 'orange', …
```
> [eda][api][docs] Introduced dot notation for properties to simplify components customization UX

- tabular/src/autogluon/tabular/models/tabular_nn/hyperparameters/parameters.py
Minor update: Adjust indentation for return statement of get_param_regression(), such that it conforms with rest of the code
> Remove extra indent

- tabular/src/autogluon/tabular/models/tabular_nn/hyperparameters/parameters.py
Fix typo, add options in description for `proc.skew_threshold` based on options defined in hyperparameters search spaces config: https://github.com/autogluon/autogluon/blob/19f4db7195559a8c48cfafb898ac2eb0a46fb383/tabular/src/autogluon/tabular/models/tabular_nn/hyperparameters/searchspaces.py#L20
> Fix typo, add parameter options

- common/src/autogluon/common/utils/resource_utils.py
- tabular/src/autogluon/tabular/learner/default_learner.py
- Add available disk logging + warning to TabularPredictor.fit call.
- This will highlight to the user when they have small amounts of disk space available.
- If logic errors for whatever reason due to a strange env, it will fallback to a warning message that we were unable to calculating available disk space and asks to submit a GitHub issue and continue.
- Note that the current threshold is 10 GB. This is too high for small datasets, and too low for large datasets, but properly calculating the expected disk space requirement is complex. 10 GB is a good initial value, however it depends on how many models are being trained and what presets are being used. I've added a TODO to improve this estimate in future.
Example:
Low Available Disk: …
> Tabular: Add available disk logging + warning

- multimodal/src/autogluon/multimodal/predictor.py
#3003
- Previously AutoMM would split the same data differently even with the same seed when calling fit multiple times. Now it will use the same split if called with same data and same seed.
- Changed default seed to 0 to align with Tabular
- Changed splitting logic to be identical to Tabular, including adding stratification and other guardrails such as ensuring at least 1 sample per class exists in train data after split. Stratification should help improve AutoMM's test scores, especially when train_data has a small amount of rows.
Now the following code produces identical results for Tabular and AutoMM (previously did not due to (1) seed difference, (2) data split logic difference:
```python3
from autogluon.core.utils.loaders import …
```
> AutoMM: Add consistent seed, stratification, alignment with tabular for train-val split

- timeseries/src/autogluon/timeseries/dataset/ts_dataframe.py
- timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
- timeseries/src/autogluon/timeseries/models/abstract/model_trial.py
- timeseries/src/autogluon/timeseries/models/autogluon_tabular/tabular_model.py
- timeseries/src/autogluon/timeseries/models/ensemble/greedy_ensemble.py
- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- timeseries/src/autogluon/timeseries/trainer/abstract_trainer.py
- timeseries/tests/unittests/models/gluonts/test_gluonts.py
- timeseries/tests/unittests/models/test_models.py
- timeseries/tests/unittests/test_trainer.py
This is part 1 of the improved multi-window backtesting for time series (part 2: #3051).
- Cache the predictions on the validation set for all time series models (as a model attribute + saved to disk). This ensures that we only call `predict` on the `val_data` once for all models. This saves training time and deals with the fact that predictions are non-deterministic for some models.
- Ensure that the reported prediction time for the test/val sets corresponds to the actual **prediction** time (before it included the time spent slicing the data / computing the metric).
- Simplify scoring logic in `AbstractTimeSeriesModel` and `AbstractTimeSeriesTrainer`
- Fix the bug where `AutoGluonTabularModel` would create an empty directory at initialization.
By submitting …
> [timeseries] Implement OOF prediction caching

- docs/tutorials/eda/components/autogluon.eda.interaction.md
- docs/tutorials/eda/eda-auto-analyze-interaction.ipynb
- docs/tutorials/eda/references/autogluon.eda.auto.md
- docs/tutorials/eda/references/autogluon.eda.base-apis.md
- eda/src/autogluon/eda/analysis/base.py
- eda/src/autogluon/eda/analysis/explain.py
- eda/src/autogluon/eda/auto/__init__.py
- eda/src/autogluon/eda/auto/simple.py
- eda/src/autogluon/eda/visualization/__init__.py
- eda/src/autogluon/eda/visualization/base.py
- eda/src/autogluon/eda/visualization/explain.py
- eda/src/autogluon/eda/visualization/interaction.py
- eda/src/autogluon/eda/visualization/shift.py
- eda/tests/unittests/analysis/test_base.py
- eda/tests/unittests/auto/test_simple.py
- eda/tests/unittests/visualization/test_explain.py
- **Partial Dependence Plots**: Individual Conditional Expectation (ICE) plots complement Partial Dependence Plots (PDP) by showing the relationship between a feature and the model's output for each individual instance in the dataset. ICE lines (blue) can be overlaid on PDPs (red) to provide a more detailed view of how the model behaves for specific instances
- Migrated `explain_rows` from legacy APIs to the new ones
- Updated docs/tutorials to include new functionality
```python
df_train = pd.read_csv('https://autogluon.s3.amazonaws.com/datasets/AmesHousingPriceRegression/train_data.csv')
target_col = 'SalePrice'
keep_cols = [
'Overall.Qual', 'Gr.Liv.Area', 'Neighborhood', 'Total.Bsmt.SF', 'BsmtFin.SF.1', …
```
> [eda] Partial Dependence Plots support

- common/LICENSE
- common/NOTICE
- common/src/autogluon/common/loaders/load_s3.py
- common/src/autogluon/common/utils/distribute_utils.py
- common/src/autogluon/common/utils/resource_utils.py
- common/src/autogluon/common/utils/s3_utils.py
- common/src/autogluon/common/utils/try_import.py
- common/tests/unittests/test_s3_utils.py
- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- core/src/autogluon/core/models/ensemble/fold_fitting_strategy.py
* This PR enables distributed training in AG tabular by implementing `RayResourceManager` and `ParallelLocalFoldFittingStrategy`
* `RayResourceManager` will report total resources of the cluster instead of a single hardware. 
* The functionality requires import of ray. The `try_import` function cannot be used here because it's being defined within `autogluon.core`, which has a dependency on `autogluon.common`. Using it would result in a circular dependency. Here, we only instantiate `RayResourceManager` when a env var `AG_DISTRIBUTED_MODE` is set. This variable is supposed to be set by the `cloud` module
* `ParallelLocalFoldFittingStrategy` will have a different ray init args and requires a s3 bucket for model synchronization between head …
> RayResourceManager and ParallelLocalFoldFittingStrategy

- docs/tutorials/eda/eda-auto-analyze-interaction.ipynb
- eda/src/autogluon/eda/auto/simple.py
- eda/src/autogluon/eda/visualization/interaction.py
- eda/tests/unittests/visualization/test_interaction.py
- Partial Dependence Plots now support two modes:
- regular PDP + ICE plots - this is the default mode of operation
- two-way PDP plots - this mode can be selected via passing two `features` and setting `two_way = True`
Two-way PDP can visualize potential interactions between any two features. Here are a few cases when two-way PDP can give good results:
- `Suspected interactions`: Even if two features are not highly correlated, they may still interact in the context of the model.
If you suspect that there might be interactions between any two features, two-way PDP can help to verify the hypotheses.
- `Moderate to high correlation`: If two features have a moderate to high correlation,
a two-way PDP can show how the combined effect of these features influences the …
> [eda] Partial Dependence Plots - Two-Way Interactions

- tabular/tests/unittests/models/test_automm.py
https://github.com/autogluon/autogluon/actions/runs/4545834564/jobs/8013765308
Some dataloader workers are killed accidentally. I have run the test locally and didn't see any issue. I suspect some recent updates in our CI environment may cause the issue.
Set `num_workers` and `num_workers_evaluation` to 0 in tests, which follows the practices of unit tests in AutoMM.
> [AutoMM] Fix tests

- multimodal/src/autogluon/multimodal/utils/inference.py
num_gpus always become 1 when calling predictor.evaluate after fit, therefore prevent us from supporting multi-gpu.
> [multimodal] fix num_gpus

- multimodal/src/autogluon/multimodal/models/utils.py
- multimodal/src/autogluon/multimodal/utils/export.py
- multimodal/src/autogluon/multimodal/utils/onnx.py
- multimodal/tests/unittests/others/test_deployment_onnx.py
the /opt/ml/model directory on sagemaker endpoint is on a read-only file system
1. write onnx model file and tensorrt cache on /tmp directory
> [multimodal] compile without saving to disk

- eda/src/autogluon/eda/auto/simple.py
- eda/tests/unittests/analysis/test_dataset.py
- eda/tests/unittests/analysis/test_interaction.py
- eda/tests/unittests/auto/test_simple.py
- eda/tests/unittests/visualization/test_interaction.py
Set default sample to 10k for `eda.auto` functions. This is to cap time needed to run the analysis and encourage fast iterations. The sample can be set to a higher value via `sample` parameter or removed via setting to `None`.
> [eda] set default sample to 10k for eda.auto functions

- multimodal/tests/unittests/others/test_deployment_onnx.py
https://github.com/autogluon/autogluon/actions/runs/4580188062/jobs/8088687808
manually add a small subset of the sts-benchmark dataset
> [multimodal] fix sts benchmark dataset missing problem

- .github/workflows/pypi_release.yml
- .github/workflows/pythonpublish.yml
Pre-release workflow fails without detailed error message. Found another failure couple days ago mentioning `ubuntu-18.04` will be deprecated on April 1st.
> Update platform of release workflow

- docs/tutorials/eda/eda-auto-quick-fit.ipynb
- eda/src/autogluon/eda/analysis/model.py
- eda/src/autogluon/eda/auto/simple.py
- eda/src/autogluon/eda/visualization/model.py
- eda/tests/unittests/analysis/test_model.py
- eda/tests/unittests/auto/test_simple.py
- eda/tests/unittests/visualization/test_model.py
- fix `quick_fit` residuals plot to use unseen data for Train
- added `fit_bagging_folds` argument to support baging in `quick_fit` and allow OOF usage in regression residuals
- Added information what part of the dataset is used for Test points
The updated code will use `test_data` true/predicted values if available to render Test points. If these not available, but `quick_fit` is called with `fit_bagging_folds` to enable OOF predictions, then Train wil use OOF predictions and Test will be validation data hold-off (automated within `quick_fit`). If no OOF available then only validation data points will be rendered.
```python
state = auto.quick_fit(
train_data=df_train,
label=target_col, 
fit_bagging_folds=3,  # enable OOF predictions
return_state=True
)
```
By …
> [eda][bugfixes] fix `quick_fit` residuals plot to use unseen data for Train

- common/src/autogluon/common/utils/resource_utils.py
- common/src/autogluon/common/utils/s3_utils.py
- common/tests/unittests/test_s3_utils.py
- core/src/autogluon/core/models/ensemble/fold_fitting_strategy.py
During full testing of distributed training, noticed that xgboost model cannot be saved to s3 bucket directly unless being compiled with a special flag, i.e.
```bash
Fitting model: XGBoost_BAG_L1 ...
Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelDistributedFoldFittingStrategy
Warning: Exception caused XGBoost_BAG_L1 to fail during training... Skipping this model.
ray::_ray_fit() (pid=1426, ip=172.31.66.143)
File "/opt/conda/lib/python3.9/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py", line 395, in _ray_fit
fold_model.save(path=model_save_path)
File "/opt/conda/lib/python3.9/site-packages/autogluon/tabular/models/xgboost/xgboost_model.py", line 215, in save
_model.save_model(path + 'xgb.ubj')
File …
```
> Tabular distributed training artifact upload update

- common/src/autogluon/common/utils/s3_utils.py
- Add suffix arg to download_s3_folder args
- This allows filtering of the files to download based on suffix, which is useful for ZS-HPO project.
- Follow-up PR should include the remaining args from list_bucket_prefix_suffix_contains_s3, as well as add unit tests for list_bucket_prefix_suffix_contains_s3.
> Add suffix to download_s3_folder args

- timeseries/src/autogluon/timeseries/configs/presets_configs.py
- timeseries/src/autogluon/timeseries/models/autogluon_tabular/tabular_model.py
- timeseries/src/autogluon/timeseries/models/local/abstract_local_model.py
- timeseries/src/autogluon/timeseries/models/local/statsforecast.py
- timeseries/src/autogluon/timeseries/models/local/statsmodels.py
- timeseries/src/autogluon/timeseries/models/presets.py
- Several minor optimizations done to speed up the training time of `high_quality` presets
- Remove XGBoost model from AutoGluonTabular model
- Remove HPO for Theta
- Cap maximum time series length for ARIMA
> [timeseries] Update high_quality presets

- docs/update-conda-recipies.md
This PR adds step-by-step instructions for updating conda-forge recipes for AutoGluon. You can preview the markdown file [here](https://github.com/giswqs/autogluon-conda/tree/master).
> Add instructions for updating conda-forge recipies

- core/src/autogluon/core/models/ensemble/fold_fitting_strategy.py
* Add logic to check if the ray task is executed on the head node. If so, avoid uploading/downloading it cause it's already present in the local disk
* Sync on fold level instead of bag level to 1. avoid download duplicate models when training with repeats 2. sync model artifacts when the head is waiting worker nodes to finish
Example run with some logs enabled:
```bash
Fitting 1 L1 models ...
Fitting model: LightGBM_BAG_L1 ... Training model for up to 599.77s of the 599.77s of remaining time.
Fitting 2 child models (S1F1 - S1F2) | Fitting with ParallelDistributedFoldFittingStrategy
Will download 0 objects from s3://weisy-personal/test_distributed/utils/LightGBM_BAG_L1/S1F1/ to AutogluonModels/ag-20230411_204255/models/LightGBM_BAG_L1/S1F1 …
```
> Optimize distributed model sync

- eda/src/autogluon/eda/analysis/shift.py
- eda/src/autogluon/eda/auto/simple.py
- eda/tests/unittests/test_shift.py
https://github.com/autogluon/autogluon/issues/3133
- `XShiftDetector` now produces `xshift_results.shift_features` which contain a list of features whose contribution is statistically significant; only present if `xshift_results.detection_status = True`. Please note, unlike visualization, this property is not trimmed to max number of elements to display; it contains only statistically significant features in the decreasing order of importance.
- docs improvements
> [eda] Add shift analysis descriptive information to state object

- core/src/autogluon/core/models/abstract/abstract_model.py
- tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
- tabular/src/autogluon/tabular/models/knn/knn_model.py
- tabular/src/autogluon/tabular/models/tabular_nn/torch/tabular_nn_torch.py
torch models training will be slowed by the usage of virtual cores.
* Add maximum resources check when in distributed mode
Example run output with a newly launched cluster of 8 m5.24xlarge machine:
The training time matches a local run and appear to be normal now
```bash
Fitting 1 L1 models ...
Fitting model: NeuralNetFastAI_BAG_L1 ...
Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelDistributedFoldFittingStrategy
0.9224   = Validation score   (accuracy)
286.06s  = Training   runtime
3.44s    = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
0.9224   = Validation score   (accuracy)
0.08s    = Training   runtime
0.04s    = Validation runtime
AutoGluon training complete, total runtime = 298.45s ... Best model: …
```
> Maximum resources

- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- core/src/autogluon/core/models/ensemble/fold_fitting_strategy.py
- core/src/autogluon/core/trainer/abstract_trainer.py
- Optimize refit_folds logic
- This is an updated version of this PR: #1351
- Currently does not enable `refit_folds=True` for any model, but a follow-up PR will test enabling for KNN.
- `refit_folds=True` will fit a bagged ensemble of a given model and then immediately call refit_full, replacing the bag with a single model in a similar manner to `use_child_oof=True`, but supported for any model rather than only models that have `use_child_oof=True` supported.
- Fixed a bug where ParallelBagging ignored `save_folds` (SequentialBagging and ParallelBagging now produce the same result instead of different results when `save_folds=False`, which is relevant to reduce disk usage).
- Removed a redundant predict call on all of the data during …
> Optimize refit_folds logic

- timeseries/src/autogluon/timeseries/models/multi_window/multi_window_model.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/tests/unittests/models/test_multi_window_model.py
- Fix a bug, where `MultiWindowModel` tries to load the base model from the original path, where the model was saved initially, even if the model got moved.
- Make sure that `TimeSeriesPredictor.path` is correctly updated when loading from disk.
> [timeseries] Fix incorrect path used by MultiWindowModel

- tabular/setup.py
- tabular/src/autogluon/tabular/models/catboost/callbacks.py
- tabular/src/autogluon/tabular/models/catboost/catboost_model.py
- tabular/src/autogluon/tabular/models/catboost/catboost_utils.py
- tabular/src/autogluon/tabular/trainer/model_presets/presets.py
- tabular/tests/unittests/models/test_catboost.py
- Add support for `problem_type=QUANTILE` for CatBoost using the [`MultiQuantile` metric](https://catboost.ai/en/docs/concepts/loss-functions-regression#MultiQuantile) added in [v1.1](https://github.com/catboost/catboost/releases/tag/v1.1).
*To Do:*
> [tabular] Add quantile regression support for CatBoost

- common/src/autogluon/common/utils/s3_utils.py
- common/tests/unittests/test_s3_utils.py
- Added logic to download a list of files, and generally added flexibility to our s3 download logic.
- Removed folder creation tracking logic and replaced with calling `mkdir` prior to downloading a given file.
TODO:
> Add s3_download utils

- tabular/src/autogluon/tabular/models/lgb/hyperparameters/parameters.py
- tabular/src/autogluon/tabular/models/lgb/lgb_model.py
- tabular/src/autogluon/tabular/models/lgb/lgb_utils.py
- tabular/src/autogluon/tabular/trainer/model_presets/presets.py
- tabular/tests/unittests/models/test_lightgbm.py
- Add support for `problem_type=QUANTILE` for `LGBModel`. The current implementation trains a separate LGBM `Booster` for each quantile level and concatenates their outputs at prediction time.
> [tabular] Implement quantile regression for LGBModel

- common/src/autogluon/common/utils/distribute_utils.py
- common/src/autogluon/common/utils/resource_utils.py
- core/src/autogluon/core/hpo/executors.py
- core/src/autogluon/core/hpo/ray_hpo.py
- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- core/src/autogluon/core/models/ensemble/fold_fitting_strategy.py
- core/src/autogluon/core/ray/resources_calculator.py
* Enable distributed HPO and Distributed HPO + bagging for Tabular
Log from example run with 8 trials, each being a bagged model consists of 8 folds, training in parallel in a cluster of 8 m5.2xlarge machine.
```bash
Fitting 1 L1 models ...
Hyperparameter tuning model: NeuralNetFastAI_BAG_L1 ...
== Status ==
Current time: 2023-04-26 21:33:53 (running for 00:00:02.87)
Memory usage on this node: 1.6/30.9 GiB 
Using FIFO scheduling algorithm.
Resources requested: 8.0/64 CPUs, 0/0 GPUs, 0.0/174.34 GiB heap, 0.0/70.76 GiB objects
Result logdir: /tmp/ray/session_2023-04-26_21-30-34_117853_27096/runtime_resources/working_dir_files/_ray_pkg_8885f3ae4fb837d6/AutogluonModels/ag-20230426_213349/models/NeuralNetFastAI_BAG_L1
Number of trials: 1/8 (1 …
```
> Tabular Distributed HPO, and Distributed HPO + bagging

- tabular/src/autogluon/tabular/models/rf/rf_quantile.py
*Issue #, if available:* #3176
- Change kwarg to positional argument in `ExtraTreesQuantileRegressor` and `RandomForestQuantileRegressor` to support the API change in sklearn >= 1.2.0.
> [tabular] Fix RandomForestQuantileRegressor failing if sklearn >= 1.2.0

- eda/setup.py
Pinning ipython version only to the ranges supported by the project's python versions
> pin ipython to only supported by project's python version range

- multimodal/src/autogluon/multimodal/data/dataset_mmlab/multi_image_mix_dataset.py
Error message that guide user to install mmcv won't print before this fix.
> [multimodal] Fix mmcv reference if import failed

- timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
- timeseries/src/autogluon/timeseries/models/autogluon_tabular/tabular_model.py
- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- timeseries/src/autogluon/timeseries/models/gluonts/torch/models.py
- timeseries/src/autogluon/timeseries/models/local/abstract_local_model.py
- timeseries/src/autogluon/timeseries/models/presets.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/tests/unittests/test_trainer.py
- Allow training multiple configurations of the same model using the `hyperparameters` kwarg, similar to how this is done in the `TabularPredictor`. For example, the following code will train 3 models `[ETS, ETS_2, ETS_seasonal]`:
```python
TimeSeriesPredictor().fit(
data,
hyperparameters={
"ETS": [
{"seasonal": None},  # ETS
{},  # ETS_2 -> suffix added to avoid name collision
{"seasonal": "mul", "ag_args": {"name_suffix": "_mul"}},  # ETS_mul -> custom suffix
]
}
)
```
By default, a suffix `_2`, `_3`, .. is added to avoid name collisions, but custom names/suffixes/prefixes can also be specified using the `ag_args` hyperparameter (just like in Tabular). Currently, only following `ag_args` are supported: `name`, `name_suffix`, `name_prefix`.
This change will be …
> [timeseries] Allow creating multiple configurations of the same model using `hyperparameters`

- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/tests/unittests/test_predictor.py
- Add deprecation warning for the `quantiles` argument to `TimeSeriesPredictor`
- Fix a potential bug that prevented users from setting `quantile_levels = []`
- Fix typo
> [timeseries] Deprecate quantiles argument to TimeSeriesPredictor

- eda/tests/unittests/analysis/test_anomaly.py
- eda/tests/unittests/analysis/test_explain.py
- eda/tests/unittests/auto/test_simple.py
- [mac] mypy and coverage have conflicts with lightgbm when running coverage stage during the build process; switching to use Random Forest for SHAP tests.
- [win] np.int64 conversion is required for test on Windows box (Windows unlike Linux is frequently using int32 even on 64-bit machines).
> [eda] improve stability of flaky platform tests

- multimodal/src/autogluon/multimodal/predictor.py
https://github.com/autogluon/autogluon/issues/3219
* The issue above can be reproduced by providing a fixed HPO search space, i.e. `learning_rate = tune.choice([1])` and running multiple runs will give different results.
* The root cause should be because the current `seed_everything` call happens in `fit` while this seed setting is not affecting hpo trials. This behavior can be verified by printing torch seed inside `_fit` via `torch.random.initial_seed()`. Different runs will give different seed value.
* This PR moves the `seed_everything` call to `_fit`, which happens inside forked process created by ray and should fix the issue …
> [Multimodal] Fix seed

- eda/setup.py
- tabular/src/autogluon/tabular/models/tabular_nn/torch/tabular_nn_torch.py
#2954
Updated `save`/`load` procedures in `TabularNeuralNetTorchModel`; Unfortunately we don't have an option to control torch loading directly as recommended in [this doc](https://pytorch.org/tutorials/recipes/recipes/save_load_across_devices.html) because pickle automatically calling `torch.load` without a way to add a hook and inject additional device parameters.
Loading trained model on GPU box:
Loading the same model on CPU:
> [BUG] Cannot load TabularNeuralNetTorchModel trained on GPU on a CPU

- common/src/autogluon/common/utils/utils.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- timeseries/src/autogluon/timeseries/predictor.py
*Issue #, if available:* #2808
- Move logic for checking if the current AG version matches the saved version of the predictor to `autogluon.common.utils.utils`
- Use this logic inside `TimeSeriesPredictor` to keep track of the version used to train the model.
> [timeseries] Check AG-TS version when loading TimeSeriesPredictor

- autogluon/src/autogluon/__init__.py
- autogluon/src/autogluon/_internal_/__init__.py
- common/src/autogluon/__init__.py
- core/src/autogluon/__init__.py
- core/src/autogluon/core/_setup_utils.py
- core/src/autogluon/core/utils/version_utils.py
- eda/src/autogluon/__init__.py
- features/src/autogluon/__init__.py
- multimodal/src/autogluon/__init__.py
- tabular/src/autogluon/__init__.py
- timeseries/src/autogluon/__init__.py
Building the project generates deprecation warnings and suggests transitioning to the use of implicit namespace packages (refer to [native namespace packages](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#native-namespace-packages) and [PEP420](https://peps.python.org/pep-0420/)):
```
../../venv-ag-310/lib/python3.10/site-packages/pkg_resources/__init__.py:2870
/Users/user/Projects/venv-ag-310/lib/python3.10/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('autogluon')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespa …
```
> Update namespace packages for PEP420 compatibility

- timeseries/src/autogluon/timeseries/learner.py
- timeseries/src/autogluon/timeseries/models/abstract/__init__.py
- timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
- timeseries/src/autogluon/timeseries/models/gluonts/mx/models.py
- timeseries/src/autogluon/timeseries/models/presets.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/src/autogluon/timeseries/trainer/abstract_trainer.py
- timeseries/src/autogluon/timeseries/trainer/auto_trainer.py
- timeseries/tests/unittests/models/gluonts/mx/test_mx.py
- timeseries/tests/unittests/test_predictor.py
- timeseries/tests/unittests/test_trainer.py
*Issue number*: #2600
- Gracefully handle the case when users incorrectly add the `Model` suffix to the model name (e.g., specify `DeepARModel` instead of `DeepAR`). This is a common pain point for users since models are listed with the `Model` suffix in the [documentation](https://auto.gluon.ai/stable/tutorials/timeseries/forecasting-model-zoo.html) because of Sphinx.
- New argument `excluded_model_types` for `TimeSeriesPredictor.fit` that allows users to exclude certain models from the presets, replicating the API of `TabularPredictor`.
- Remove some untested/undocumented/probably unsupported functionality for `AbstractTimeSeriesModelFactory` & `GenericGluonTSMXNetModelFactory`. …
> [timeseries] Add excluded_model_types and simplify preset generation logic

- common/src/autogluon/common/utils/deprecated_utils.py
- common/tests/unittests/test_deprecated_utils.py
* Add wrapper to generate deprecated decorator so the util can be used by modules like cloud
> Add wrapper to generate deprecated decorator

- timeseries/src/autogluon/timeseries/dataset/ts_dataframe.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/tests/smoketests/test_features_and_covariates.py
- timeseries/tests/unittests/test_predictor.py
- timeseries/tests/unittests/test_ts_dataset.py
*Issue #, if available:* #3036, #2995
- Raise exception if provided data contains a column `item_id` that is not used as `item_id` / `timestamp` that is not used as `timestamp` - fixes #2995
- Automatically sort data by `['item_id', 'timestamp']`, if data provided by user isn't sorted - fixes #3036
> [timeseries] Bugfixes for TimeSeriesDataFrame

- multimodal/src/autogluon/multimodal/data/infer_types.py
- multimodal/src/autogluon/multimodal/matcher.py
- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/tests/unittests/others/test_deployment_onnx.py
- multimodal/tests/unittests/others/test_matcher.py
- multimodal/tests/unittests/others/test_utils.py
#3017 #3004
- Decouple problem type and output shape inference
- Reuse core utils `infer_problem_type`. 
> [AutoMM] refactor inferring problem type and output shape

- core/src/autogluon/core/problem_type.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/tests/conftest.py
- tabular/tests/unittests/test_tabular.py
Resolves #2685 
Update `TabularPredictor` to raise an AssertionError when `predict_proba` and `predict_proba_multi` are called when the problem type is `regression` or `quantile`. This aligns the logic with `MultimodalPredictor`.
> Tabular: Raise regression pred_proba

- common/src/autogluon/common/utils/log_utils.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/tests/unittests/test_tabular.py
https://github.com/autogluon/autogluon/issues/3127
https://github.com/autogluon/autogluon/issues/3221
* Add `add_log_to_file `, which could be used by any predictor to add support for log to file
* Add `log_to_file` and `log_file_path` in TabularPredictor
> Log to file

- timeseries/src/autogluon/timeseries/models/local/abstract_local_model.py
- timeseries/src/autogluon/timeseries/models/local/statsforecast.py
- timeseries/src/autogluon/timeseries/models/local/statsmodels.py
- timeseries/tests/unittests/models/test_local.py
- timeseries/tests/unittests/models/test_models.py
- Expose `use_fallback_model` as an optional hyperparameter for all local models (default `True`). When set to `False`, fallback model will be disabled, and any exception in the underlying model will propagate. This is important for testing - currently, we had one model that always failed because of a bug, but this wasn't caught by the CI because of the fallback model. 
- Fix typos in docstrings
- All local models are now trained using at most the last 2500 entries of each time series. This allows to significantly reduce the training time without degrading the accuracy:
> [timeseries] Minor bugfixes & improvements for local forecasting models

- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- core/src/autogluon/core/models/ensemble/weighted_ensemble_model.py
-  Fix incorrect warning log when fitting WeightedEnsembleModel.
> Tabular: Fix incorrect warning log

- timeseries/tests/unittests/test_predictor.py
- Catch another potential bug not handled by #3255. The old test would fail in the rare case that `Naive` had the best validation score & was the only model used by the ensemble.
> [timeseries] Fix non-deterministic bug in tests (update of #3255)

- tabular/setup.py
Update CatBoost to 1.2
- CatBoost 1.2 has 8% faster training speed in multiclass classification with the log loss metric.
- Will plan to benchmark after merge on mainline during code freeze instead of benchmarking this PR individually, as it will be easy to isolate the root cause of regressions in case this PR is the cause.
TODO:
> Update CatBoost to 1.2

- tabular/src/autogluon/tabular/models/xgboost/xgboost_model.py
- tabular/tests/unittests/models/test_xgboost.py
Resolves #2429 
- Added support for XGBoost's new (as of XGBoost 1.6) support for categorical features via `enable_categorical=True`.
- Currently not enabled by default, will benchmark to consider enabling by default.
> Add enable_categorical=True support to XGBoost

- .github/workflows/build_latest_image.yml
* Nightly image building is failing recently because of the increase of the image size leading to out of disk space for github runners. Adding a step to cleanup the machine to squeeze more space.
* Has been tested [here](https://github.com/yinweisu/autogluon/actions/runs/5191861673)
* To be noticed, if our image size continue to grow, it's likely that we'll need to move away from github hosted runners...
> Cleanup diskspace for docker image build

- .github/workflow_scripts/env_setup.sh
- .github/workflow_scripts/test_tabular.sh
- CI/batch/docker/Dockerfile.cpu
- CI/batch/docker/Dockerfile.gpu
- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/tests/unittests/test_tabular.py
https://github.com/autogluon/autogluon/issues/1065
* path attributes already being stored in the node is causing some weird issue to pygraphviz on Windows likely because it somehow treat `\\` separator on Windows as escape character.
* This PR removes all unneeded attributes from the nodes
> Fix plot ensemble model on Windows

- common/src/autogluon/common/model_filter/_model_filter.py
- tabular/src/autogluon/tabular/trainer/auto_trainer.py
Resolves #3057 
- Add logging of the hyperparameter dictionary
- The logging is copy-paste-able by the user so they can edit it and pass into a new fit call.
- Also enhanced the included/excluded models logging to use list instead of set (looks cleaner), and added additional info to the logs so the user understands why the log occurred.
Example:
Mainline:
```
Data preprocessing and feature engineering runtime = 0.1s ...
AutoGluon will gauge predictive performance using evaluation metric: 'log_loss'
This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
This metric expects predicted probabilities rather than predicted class labels, so you'll need to use …
```
> Tabular: Log hyperparameters

- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/utils/__init__.py
- multimodal/src/autogluon/multimodal/utils/model.py
- multimodal/tests/unittests/others_2/test_predictor_advanced.py
Support calling `predictor.total_parameters `, `predictor.trainable_parameters `, and `predictor.model_size `.
> [AutoMM] Support model parameter number statistics

- common/src/autogluon/common/utils/path_converter.py
- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/models/ensemble/stacker_ensemble_model.py
- core/src/autogluon/core/trainer/abstract_trainer.py
- tabular/tests/conftest.py
- tabular/tests/unittests/models/test_dummy.py
- If using an absolute path in predictor init, will crash upon load.
This PR fixes the obvious error so that the below script works, however the current fix is not a good idea long-term, as I have no idea if there will be edge-cases where it fails. I also don't know if it will work when using multiple disk drives in a single process.
The root of the issue is that `StackerEnsembleModel` does something it shouldn't: It has the absolute paths of both itself and its base models stored as variables. Therefore, in order to figure out where the base models are upon loading in a new location, it isn't sufficient to look at the old absolute paths, instead they need to be regenerated based on 1. the old absolute path, 2. the new path.
For example: …
> Tabular: Fix crash when save path is absolute

- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/utils/__init__.py
- multimodal/src/autogluon/multimodal/utils/environment.py
- multimodal/src/autogluon/multimodal/utils/log.py
- multimodal/tests/unittests/others_2/test_predictor_advanced.py
#3284 
Log AG version, torch version, and GPU info.
> [AutoMM] Log GPU info

- .github/workflow_scripts/env_setup.sh
- .github/workflow_scripts/test_install.sh
- .github/workflow_scripts/test_install_windows.sh
- .github/workflow_scripts/test_tabular.sh
- .github/workflows/platform_tests-command.yml
- common/tests/unittests/test_hash_pandas_df.py
* install fail because of setup_mmcv.sh not being found. Change to use install_all.sh now as we don't need mxnet anymore
* fix tempfile path. `str(tempfile)` doesn't give a string but still the object itself for some reason causing issue on Windows. Tried to use `tempfile.name` instead but the underlying issue with `TemporaryFile` is that it opens the file automatically, while our saving logic tries to open it again. This will fail on Windows. Change to create a tempdir instead
> Fix platform tests

- timeseries/src/autogluon/timeseries/models/autogluon_tabular/mlforecast.py
- timeseries/tests/unittests/models/test_mlforecast.py
- timeseries/tests/unittests/test_trainer.py
- An ad-hoc solution the OOM problems caused by `RecursiveTabular` model on large datasets (>50M rows). We subsample time series to ensure that there are at most ~30M rows in the dataset.
- The previously considered solution considered #3272 turned out to not generalize to different machines. We can try designing a better strategy in the future (or eliminating the root cause of the excessive memory consumption) after the v0.8 release.
> [timeseries] Subsample time series to avoid high memory usage of the RecursiveTabular model 

- core/src/autogluon/core/utils/utils.py
- tabular/src/autogluon/tabular/learner/abstract_learner.py
- tabular/tests/unittests/test_tabular.py
- Fix `predict_multi` crashing when `inverse_transform=False, as_pandas=True`
- Fix `predict_proba_multi` crashing when `inverse_transform=False, as_pandas=True` and dropped classes exist.
- Unified post-processing code between `predict` and `predict_multi`.
- Unified post-processing code between `predict_proba` and `predict_proba_multi`.
- Added additional unit tests for `predict_multi` and `predict_proba_multi`
> Fix `predict_multi` crashing when `inverse_transform=False`

- docs/tutorials/multimodal/advanced_topics/continuous_training.ipynb
> continuous training tutorial update

- core/src/autogluon/core/calibrate/__init__.py
- core/src/autogluon/core/calibrate/_decision_threshold.py
- core/src/autogluon/core/trainer/abstract_trainer.py
- core/src/autogluon/core/utils/utils.py
- core/tests/unittests/calibrate/test_decision_threshold.py
- tabular/src/autogluon/tabular/learner/abstract_learner.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/tests/unittests/models/test_lightgbm.py
resolves #1038, #1515 
pre-req for #3112 
Add `TabularPredictor.calibrate_decision_threshold` which allows to optimize a given metric's decision threshold for predictions to strongly enhance the metric score.
The below code and output showcase how this logic can reliably improve metric scores on a variety of metrics, particularly `f1` and `balanced_accuracy`.
<details>
<summary>Example Code</summary>
```python
from autogluon.tabular import TabularPredictor, TabularDataset
path_prefix = 'https://autogluon.s3.amazonaws.com/datasets/Inc/'
path_train = path_prefix + 'train.csv'
path_test = path_prefix + 'test.csv'
train_data = TabularDataset(path_train)
train_data = train_data.sample(25000, …
```
> Add calibrate_decision_threshold

- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/tests/unittests/test_tabular.py
* tempfile behaves weird on Windows: if you create a file within the TemporaryDirectory, the directory will fail to clean up itself. Minimal reproducible example
```python
def test_foo():
with tempfile.TemporaryDirectory() as tempdir:
temp = os.path.join(tempdir, "abc")
with open(temp, "r") as f:
pass
```
pytest running test above will fail^^^
* Removed usage of tempfile
> Fix log to file Windows tests

- docs/tutorials/tabular/tabular-indepth.ipynb
- tabular/src/autogluon/tabular/predictor/predictor.py
* https://github.com/autogluon/autogluon/issues/1485
* Added docstring for `hyperparameter_tune_kwargs`. Tutorial for search space will be added in a separate PR to speed up building process
> Add docstring for hyperparameter_tune_kwargs

- docs/install-mac-cpu-source.md
- docs/install-mac-cpu.md
- docs/install-mac-libomp.md
- docs/install.md
A user in the autogluon-interest slack channel pointed out `there is no wheel for the 1.13.1+cpu for OSx` for `torch`. It also appears there is no `1.14.1+cpu` for `torch-vision` on macOS. We need to use the non-CPU versions .
Reference to existing issue: https://auto.gluon.ai/stable/install.html -> Mac/Pip/CPU
Install options: https://download.pytorch.org/whl/cpu/torch_stable.html
> Update mac cpu install instructions

- .github/workflow_scripts/env_setup.sh
- CI/batch/docker/Dockerfile.gpu
- docs/install-gpu-pip.md
- docs/install-gpu-source.md
- docs/install-windows-gpu.md
[Issue 2885](https://github.com/autogluon/autogluon/issues/2885)
Update GPU installation guide to use CUDA 11.7
* Log (from Linux with GPU)
```
dev-dsk-tonyhu-2c-77435e3d % pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117
pip install autogluon
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com, https://download.pytorch.org/whl/cu117
Collecting torch==1.13.1+cu117
Downloading https://download.pytorch.org/whl/cu117/torch-1.13.1%2Bcu117-cp39-cp39-linux_x86_64.whl (1801.8 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 GB 61.5 MB/s eta 0:00:00
Collecting torchvision==0.14.1+cu117
Downloading https://download.pytorch.org/whl/cu117/torchvision-0.14.1%2Bc …
```
> Update GPU installation guide to use CUDA 11.7

- tabular/src/autogluon/tabular/configs/hyperparameter_configs.py
- tabular/src/autogluon/tabular/configs/presets_configs.py
- Add Experimental Zeroshot HPO
Shown to perform well on small datasets <5000 rows, but currently struggles to outperform best quality when facing larger datasets, due to the limitations of the current benchmark suite that the simulations are generated from that will be resolved in a future update.
> Add Experimental Zeroshot HPO

- docs/conf.py
We need to update AutoGluon's Google analytics identifier by July 1st. The dev team agreed to wait for the 0.8 release, and then test this change on `dev`. We will make a similar change to `stable` once we have verified the change works on `dev`.
> Update google analytics property

- tabular/src/autogluon/tabular/predictor/predictor.py
Update persist_models max_memory 0.1 -> 0.4
0.4 is a safe memory amount to persist with, as confirmed on AMLB.
This results in an average 2x batch_size=1 inference speedup for best_quality preset with no drawbacks.
```
(06_11is with `max_memory=0.1` , 06_19 is with `max_memory=0.4`)
AutoGluon_bq_1h8c_2023_06_11 | rows_per_s_mean=0.22 | rows_per_s_median=0.39
AutoGluon_bq_1h8c_2023_06_19 | rows_per_s_mean=0.35 | rows_per_s_median=0.65
AutoGluon_hq_1h8c_2023_06_11 | rows_per_s_mean=3.56 | rows_per_s_median=10.08
AutoGluon_hq_1h8c_2023_06_19 | rows_per_s_mean=5.61 | rows_per_s_median=9.84
AutoGluon_hq_il001_1h8c_2023_06_11 | rows_per_s_mean=6.9 | rows_per_s_median=37.52
AutoGluon_hq_il001_1h8c_2023_06_19 | rows_per_s_mean=12.13 | …
```
> Update persist_models max_memory 0.1 -> 0.4

- core/src/autogluon/core/_setup_utils.py
- Remove TIMM in core setup, the versions did not align with multimodal, and multimodal is the only module that uses TIMM.
> Remove TIMM in core setup

- docs/tutorials/multimodal/document/pdf_classification.ipynb
- multimodal/setup.py
- multimodal/src/autogluon/multimodal/data/process_document.py
- Move PyMuPDF to optional
Since PyMuPDF isn't available in Conda, better to move to an optional dependency as it is only used in a specific scenario for PDF file reading.
TODO:
> Move PyMuPDF to optional

- multimodal/setup.py
Remove fairescale as lightning has deprecated using it since v1.9.0.
> [AutoMM] Remove fairscale

- docs/conf.py
This change updates the Google Analytics identifier for the stable branch docs as described [here](https://github.com/autogluon/autogluon/pull/3330). We already did this to `master` in [this commit](https://github.com/autogluon/autogluon/commit/8af509a6a1f1249fb8d63d8c033fd5370c91143b) and verified that analytics are still working for the `/dev` web docs.
> Stable GA4 update

- core/src/autogluon/core/trainer/abstract_trainer.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- Fix edge-case crash in `.refit_full('best')` when "best" differs between trainer and predictor (for example, when `WeightedEnsemble` only has 1 base model, and when predictor was fit with `_save_bag_folds=False`. Now the `"best"` model refit will be the predictor's "best" model to avoid an exception during `.predict(data)`
- Fix edge-case crash when `.fit(..., _save_bag_folds=False, calibrate=True, refit_full=False)` where no models can infer and calibration is called, resulting in an exception. Now models that can't infer can be calibrated, which after refit_full results in calibrated refit models.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
> Fix refit crash

- timeseries/src/autogluon/timeseries/models/autogluon_tabular/direct_tabular.py
- timeseries/src/autogluon/timeseries/utils/warning_filters.py
- timeseries/tests/smoketests/test_features_and_covariates.py
- timeseries/tests/unittests/models/test_direct_tabular.py
*Issue #, if available:* #3341
This PR addresses two bugs related to the `DirectTabularModel` introduced in v0.8.
1. `DirectTabular` model fails for non-default values of `eval_metric`.
- **Reason** 
Under the hood, `TabularPredictor` is used differently depending on the `eval_metric`. 
- If `eval_metric="mean_wQuantileLoss"`: we use `problem_type="quantile"`, predictor returns a `pd.DataFrame`.
- If `eval_metric!="mean_wQuantileLoss"`: we use `problem_type="regression"`, predictor returns a `pd.Series`. Unlike DataFrame, Series has no method `set_index`, which leads to an exception. 
- **Why didn't we catch this bug before?**
Our smoke tests did not consider the non-default values for `eval_metric`. When doing a sanity check of the leaderboards produced during …
> [timeseries] Fix bugs in DirectTabularModel

- docs/tutorials/multimodal/advanced_topics/continuous_training.ipynb
- docs/tutorials/multimodal/advanced_topics/presets.ipynb
The "Open in Colab" type buttons are missing in these two tutorials:
- https://auto.gluon.ai/stable/tutorials/multimodal/advanced_topics/presets.html
- https://auto.gluon.ai/stable/tutorials/multimodal/advanced_topics/continuous_training.html
These PR adds buttons to open the notebooks in Colab and Studio Lab.
> Add missing colab buttons to advanced AutoMM tutorials

- multimodal/src/autogluon/multimodal/utils/hpo.py
* Fix `reuse_actor` causing ray tune to crash
> [Multimodal] Fix hpo crashing on reuse_actor

- common/src/autogluon/common/utils/try_import.py
- tabular/setup.py
bump vw version to 9.8
I've just increased allowed version of wovpal wabbit to 9.8 in file:
https://github.com/autogluon/autogluon/blob/master/common/src/autogluon/common/utils/try_import.py
I've tested it locally.
> vw version bump

- multimodal/src/autogluon/multimodal/configs/model/fusion_mlp_image_text_tabular.yaml
- multimodal/src/autogluon/multimodal/data/process_text.py
- multimodal/src/autogluon/multimodal/utils/data.py
- multimodal/tests/hf_model_list.yaml
- multimodal/tests/unittests/others_2/test_data_processors.py
Through customizing `hf_text.use_fast`, users can choose whether to use fast tokenizer for hf_text models. If not set, we use the same default as the AutoTokenizer.
> [AutoMM] Support customizing use_fast for AutoTokenizer

- eda/src/autogluon/eda/analysis/anomaly.py
- eda/tests/unittests/analysis/test_anomaly.py
Don't use `bps_flag=True` - it's using pre-trained models which aren't loading in newer versions of sklearn
> [fix][eda] Anomaly Detection - disable bps_flag for SUOD

- core/src/autogluon/core/models/abstract/abstract_model.py
- Add log for fit time adjustments
Previously, if user specified per-model time limit arguments, this would not be logged and thus it was not clear why a model was stopped or trained for a certain duration.
This PR:
```
'GBM': {},
'CAT': {'ag.max_time_limit': 5},
}
predictor = predictor.fit(train_data, hyperparameters=hyperparameters, time_limit=120)
```
```
User-specified model hyperparameters to be fit:
{
'GBM': {},
'CAT': {'ag.max_time_limit': 5},
}
Fitting 2 L1 models ...
Fitting model: LightGBM ... Training model for up to 119.82s of the 119.82s of remaining time.
0.9383	 = Validation score   (roc_auc)
2.27s	 = Training   runtime
0.01s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to …
```
> Add log for fit time adjustments

- tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
- Fixed extremely rare crash when the batch time estimate was so fast that `batch_time_tracker_callback.batch_measured_time` returns None, causing downstream numerical operations to crash.
- Added type hints
Bug found when fitting on the `visualizing_soil` OpenML dataset.
> Fix FastAI crash edge-case

- core/src/autogluon/core/models/abstract/abstract_model.py
- Fix crash when `time_limit` is None and overwritten via `max_time_limit`
> Fix crash when `time_limit` is None and overwritten via `max_time_limit`

- .github/workflow_scripts/build_all_docs.sh
- .github/workflows/continuous_integration.yml
- .github/workflows/platform_tests-command.yml
- .github/workflows/pypi_release.yml
- .github/workflows/pythonpublish.yml
- .github/workflows/pythonpublish_testpypi.yml
- docs/index.md
> [EDA] Disable EDA tests and doc build temporarily

- multimodal/src/autogluon/multimodal/data/process_document.py
- multimodal/src/autogluon/multimodal/data/process_ner.py
- multimodal/src/autogluon/multimodal/data/process_text.py
- multimodal/src/autogluon/multimodal/models/clip.py
- multimodal/src/autogluon/multimodal/models/document_transformer.py
- multimodal/src/autogluon/multimodal/models/huggingface_text.py
- multimodal/src/autogluon/multimodal/models/ner_text.py
- multimodal/src/autogluon/multimodal/models/t_few.py
- multimodal/src/autogluon/multimodal/models/utils.py
- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/utils/data.py
- multimodal/src/autogluon/multimodal/utils/export.py
- multimodal/src/autogluon/multimodal/utils/load.py
- multimodal/src/autogluon/multimodal/utils/model.py
- multimodal/tests/unittests/others/test_ner.py
- Previously, tokenizers were created in both model and data processor, which is difficult to maintain. This PR is to unify creating tokenizers for all models. Now tokenizers are created in the model initializations and then passed to data processors.
- Fixed the slow loading issue of M5 tokenizer. `use_fast` is only needed in one place.
> [AutoMM] Unify creating tokenizers for all models

- README.md
* https://github.com/autogluon/autogluon-brokenlinks holds a github action to check for broken links in our website. Add a badge to reflect the status in our main repo
> Add broken link checker badge

- multimodal/src/autogluon/multimodal/utils/environment.py
The default strategy is `ddp_spawn_find_unused_parameters_true`. Make sure training in an interactive env with multi-gpus doesn't fail.
> [AutoMM] Fix training in notebook

- common/src/autogluon/common/utils/deprecated_utils.py
The deprecation warnings generated by the `Deprecated` decorator are currently silenced. This happens because Python silences all `DeprecationWarning`s by default, except those that occur inside the `if __name__ = "__main__:"` idiom ([PEP565](https://peps.python.org/pep-0565/)).
<details>
<summary>Minimal working example</summary>
```python
from autogluon.common.utils.deprecated_utils import Deprecated
@Deprecated(min_version_to_warn="0.8", min_version_to_error="1.0")
def f(x):
return x
if __name__ == "__main__":
f(1)  # this does not produce a warning
```
</details>
With the current value `stacklevel=2` the warnings are attributed to the decorator inside `common/src/autogluon/common/utils/deprecated_utils.py`, so they are silenced.
- Set `stacklevel=3` to …
> [common] Fix deprecation warnings

- core/src/autogluon/core/trainer/abstract_trainer.py
- tabular/src/autogluon/tabular/predictor/predictor.py
Fixes infer_limit being incorrectly calculated when bagging
The fix involves using the post-refit (expected) infer time of models in all scenarios involving refit full and selecting the best model when `infer_limit` is specified.
With this fix, infer_limit should work as intended in all scenarios. For users who were already using `infer_limit` combined with bagging, it is recommended to lower the `infer_limit` value by a factor of 10 to maintain similar inference speed.
Specifically, the inference time values used were incorrect when 1. choosing the best model, and 2. choosing the best model during refit full with bagging enabled.
If a bagged model had 8 folds, it would use the infer time of all 8 fold models, rather than the expected …
> [Tabular] Fix infer_limit being incorrectly calculated when bagging

- .github/workflow_scripts/test_core.sh
- .github/workflows/platform_tests-command.yml
- core/tests/conftest.py
- core/tests/unittests/hpo/test_ray_hpo.py
Core tests fail on Windows platform after ray upgrade PR - https://github.com/autogluon/autogluon/pull/3468
Was not reproducible on Windows EC2, hence adding checks to skip it only on Windows Platforms.
Test run - https://github.com/prateekdesai04/autogluon/actions/runs/5968708969
> Adding Windows platform fix for Core test failure

- README.md
- Add bibtex for the AutoGluon-TimeSeries AutoML Conf 2023 paper to README.md
> Add reference to the AGTS paper to README.md

- core/src/autogluon/core/utils/utils.py
- core/tests/unittests/utils/test_utils.py
In cases where there are an extreme number of classes compared to data samples and the data is large, AutoGluon can crash during train test split due to a bug in scikit-learn's `train_test_split` function.
Example:
```
Train Data Rows:    1528329
Train Data Class Count: 27000
```
Because the test split would be 1% of the total data based on AutoGluon's split logic, it results in the test data having fewer rows than the number of classes, triggering the error:
```
ValueError: The test_size = 14915 should be greater or equal to the number of classes = 27000
```
While scikit-learn claims that test_size must be greater than the number of classes, this isn't technically required fundamentally. This PR adds a work-around for this limitation by …
> Tabular: Fix train_test split edge-case

- core/src/autogluon/core/_setup_utils.py
- multimodal/src/autogluon/multimodal/configs/environment/default.yaml
- multimodal/src/autogluon/multimodal/constants.py
- multimodal/src/autogluon/multimodal/models/utils.py
- multimodal/src/autogluon/multimodal/optimization/utils.py
- multimodal/src/autogluon/multimodal/predictor.py
Users can turn on compiling their models through `predictor.fit(hyperparameters={"env.compile.turn_on", True})`.
Limitations
- Doesn't work for multi-gpu training.
- Needs pytorch version >= `2.2.0.dev20230908`
> [AutoMM] Support torch.compile()

- docs/tutorials/timeseries/forecasting-indepth.ipynb
- docs/tutorials/timeseries/forecasting-quick-start.ipynb
- Currently time series tutorials fail on Colab because of an incompatible version of `torchaudio` pre-installed in the Colab Python environment (Colab expects torch 2.0 while autogluon v0.8.2 installs torch 1.13, which breaks torchaudio). This PR uninstalls torchaudio to fix this problem.
> [timeseries] Fix timeseries tutorial on Colab

- core/src/autogluon/core/_setup_utils.py
- docs/tutorials/multimodal/advanced_topics/customization.ipynb
- multimodal/setup.py
- multimodal/src/autogluon/multimodal/configs/environment/default.yaml
- multimodal/src/autogluon/multimodal/data/datamodule.py
- multimodal/src/autogluon/multimodal/matcher.py
- multimodal/src/autogluon/multimodal/optimization/deepspeed.py
- multimodal/src/autogluon/multimodal/optimization/lit_distiller.py
- multimodal/src/autogluon/multimodal/optimization/lit_matcher.py
- multimodal/src/autogluon/multimodal/optimization/lit_mmdet.py
- multimodal/src/autogluon/multimodal/optimization/lit_module.py
- multimodal/src/autogluon/multimodal/optimization/lit_ner.py
- multimodal/src/autogluon/multimodal/predictor.py
- multimodal/src/autogluon/multimodal/utils/cache.py
- multimodal/src/autogluon/multimodal/utils/checkpoint.py
- multimodal/src/autogluon/multimodal/utils/cloud_io.py
- multimodal/src/autogluon/multimodal/utils/environment.py
- multimodal/src/autogluon/multimodal/utils/hpo.py
- multimodal/src/autogluon/multimodal/utils/log.py
- pyproject.toml
- timeseries/setup.py
- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- timeseries/src/autogluon/timeseries/predictor.py
- Install the new `lightning` package and use the new import style. See the discussion: https://lightning.ai/forums/t/using-pytorch-lightning-from-lightning-import/2182/2
- Update lightning doc links
- Remove `env.auto_select_gpus` from the doc since it's no longer used.
- Resolve one issue of using ray tune with new `lightning` (https://github.com/optuna/optuna/issues/4689 and https://github.com/ray-project/ray/issues/33426)
> [Lightning] Update lightning import

- common/src/autogluon/common/utils/utils.py
- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- timeseries/src/autogluon/timeseries/models/gluonts/torch/models.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/tests/smoketests/test_features_and_covariates.py
- timeseries/tests/unittests/models/gluonts/test_gluonts.py
A recent update to `pytorch_lightning` has potential to introduce a massive performance regression to forecasting models in AutoGluon that rely on multiprocessing / joblib. As of `v2.0.8` of `pytorch_lightning`, a multiprocessing lock is created whenever the module is imported. This increased the process initialization time significantly.
For example, total runtime of the above code snippet
```python
import pytorch_lightning as pl
from autogluon.timeseries import TimeSeriesPredictor, TimeSeriesDataFrame
data = TimeSeriesDataFrame('https://autogluon.s3.amazonaws.com/datasets/timeseries/m4_hourly/train.csv')
predictor = TimeSeriesPredictor()
predictor.fit(data, hyperparameters={"Naive": {}})
```
- current `master` branch: 1m 42s
- with this PR: 36s.
- Hide all …
> [timeseries] Avoid importing pytorch_lightning at top level

- timeseries/src/autogluon/timeseries/models/local/statsforecast.py
- timeseries/tests/smoketests/test_features_and_covariates.py
- Gracefully handle the case when `ETSModel` and `AutoETSModel` fail if time series length < 2 * `season_length`.
- Disable damped trend for `ETSModel` (for compatibility with the `ETSModel` from statsmodels that was replaced in #3513).
> [timeseries] Fix smoketests for time series

- docs/tutorials/timeseries/forecasting-indepth.ipynb
- timeseries/src/autogluon/timeseries/evaluator.py
- timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
- timeseries/src/autogluon/timeseries/models/autogluon_tabular/direct_tabular.py
- timeseries/src/autogluon/timeseries/models/autogluon_tabular/mlforecast.py
- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/tests/smoketests/test_features_and_covariates.py
- timeseries/tests/unittests/models/test_direct_tabular.py
- timeseries/tests/unittests/test_evaluator.py
- Replace all occurrences of `mean_wQuantileLoss` with `WQL`
- If user sets `eval_metric="mean_wQuantileLoss"`, log a warning and automatically change the metric name to `WQL`.
> [timeseries] Rename mean_wQuantileLoss metric to WQL

- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/models/dummy/dummy_model.py
- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- core/src/autogluon/core/trainer/abstract_trainer.py
- tabular/src/autogluon/tabular/learner/default_learner.py
- tabular/src/autogluon/tabular/models/automm/automm_model.py
- tabular/src/autogluon/tabular/models/catboost/catboost_model.py
- tabular/src/autogluon/tabular/models/fasttext/fasttext_model.py
- tabular/src/autogluon/tabular/models/lgb/callbacks.py
- tabular/src/autogluon/tabular/models/lgb/lgb_model.py
- tabular/src/autogluon/tabular/models/vowpalwabbit/vowpalwabbit_model.py
- tabular/src/autogluon/tabular/models/xgboost/xgboost_model.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/tests/unittests/models/test_dummy.py
- tabular/tests/unittests/test_tabular.py
- Add model failures tracking support via `predictor.get_model_failures()`
- Improve LightGBM, CatBoost, and XGBoost memory estimate by estimating the histogram memory usage.
- Improve stability of refit full when memory usage is high by increasing the memory usage cap by 25% for refit models to avoid fitting the original model successfully and then having the refit model cause a NotEnoughMemoryError exception due to requiring slightly more memory.
- PR has been tested extensively across 244 datasets with 1416 model configs. It works well, eliminating all cases of OOM due to incorrect memory estimates for GBM models, and the model failures logic works in all cases.
TODO:
By submitting this pull request, I confirm that you can use, modify, …
> Tabular: Add model failures tracking support

- docs/index.md
- Ensure versions link in website always links to dev documentation. This way it doesn't become outdated over time.
> Force versions link to always go to stable versions file

- core/src/autogluon/core/metrics/__init__.py
- core/tests/unittests/metrics/test_metrics.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- timeseries/src/autogluon/timeseries/models/autogluon_tabular/mlforecast.py
- Add `symmetric_mean_absolute_percentage_error` regression metric. This metric corresponds to one of the metrics used in TimeSeries module, and it would be helpful to use this metric inside `DirectTabular` and `RecursiveTabular` forecasting models.
> [core] Add symmetric_mean_absolute_percentage error

- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- timeseries/src/autogluon/timeseries/models/gluonts/torch/models.py
- timeseries/tests/unittests/models/test_gluonts.py
- timeseries/tests/unittests/models/test_multi_window_model.py
- timeseries/tests/unittests/test_evaluator.py
- Enable early stopping to GluonTS models using `early_stopping_patience` hyperparameter
- Allow passing custom trainer arguments using `trainer_kwargs` hyperparameter
- Log whether GPU is used at DEBUG level (fixes #3309)
- Speed up inference for GluonTS models (fixes #3564)
- Instead of using pandas DataFrames + `loc` accessing, we use numpy arrays + indptr accessing.
- Use larger batch size during inference (32->500).
- Speed up the conversion of GluonTS forecast objects to a predictions DataFrame in AutoGluon.
Here is an ablation that demonstrates the effect of each change. We compare master branch (top row), this PR with all changes (bottom row), and this PR with each of the 3 changes removed. Results are for the M4-Monthly dataset with 48000 time series.
| …
> [timeseries] Enhancements for GluonTS models

- docs/install-cpu-pip.md
- docs/install-cpu-source.md
- docs/install-gpu-pip.md
- docs/install-gpu-source.md
* Follow-up PR of https://github.com/autogluon/autogluon/pull/3190 to update torch installation instruction to 2.0
> Update torch install

- core/src/autogluon/core/_setup_utils.py
- timeseries/setup.py
- The new release of `lightning` v2.1.0 introduces a backwards-incompatible change that breaks all GluonTS models. We have capped `lightning<2.1`, but for some reason that doesn't prevent the installation of `pytorch_lightning==2.1.0`, where the breaking change is introduced. This PR caps the version of `pytorch_lightning`.
> Add version cap for pytorch_lightning

- docs/tutorials/multimodal/object_detection/data_preparation/convert_data_to_coco_format.ipynb
- multimodal/src/autogluon/multimodal/utils/object_detection.py
- multimodal/tests/unittests/others/test_object_detection.py
Fix object detection prediction on COCO json files without annotations.
Also add a test case for this issue.
> [AutoMM] Fix object detection prediction on COCO json files without annotations.

- multimodal/src/autogluon/multimodal/predictor.py
*Reference Issue*
#3589 
This PR makes sure, the inference of `problem_type` happens before the dataset splitting and stratification, fixing #3589. 
> [AutoMM] fix stratification based on problem_type

- tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
This PR adds clipping to FastAI neural networks for regression. The PR adjust the code such that it now clips the y values before training the model by default. Moreover, the predictions of the model are also clipped. This was done by replacing the scaler with a pipeline that includes a function transformer for clipping and the scaler (if available). The code follows the TorchNN model to determine the range for clipping. 
The following code compares clipping vs. no clipping on a dataset with extreme outliers. 
<details>
<summary>
Script
</summary>
```python
import numpy as np
import openml
import sklearn
def get_data(tid: int, fold: int):
oml_task = openml.tasks.get_task(tid, download_splits=True, download_data=True, …
```
> FastAI Neural Network Clipping for Regression

- core/src/autogluon/core/trainer/abstract_trainer.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/tests/unittests/edgecases/test_edgecases.py
This PR adds code to enable and make it the default that the final weighted ensemble (post hoc ensemble) uses all models from **all** previous stacking layers. Previous, the final weighted ensemble used only the models from the last layer. 
Thus, now AutoGluon by default mirrors the behavior of calling `TabularPredictor.fit_weighted_ensemble` after a fit.
This change can be manually controlled via `fit_full_last_level_weighted_ensemble` at `fit` or `fit_extra`.
Moreover, the PR adds the options to set `full_weighted_ensemble_additionally` at `fit` or `fit_extra`. If this and  `fit_full_last_level_weighted_ensemble` are set to True, then AutoGluon will fit two ensembles post hoc: one only for the models from the last level and one with all trained models. By default …
> Make the Last Layer's Post Hoc Ensemble (Weighted Ensemble) Use all Models

- timeseries/setup.py
- timeseries/src/autogluon/timeseries/metrics/point.py
- timeseries/src/autogluon/timeseries/models/autogluon_tabular/mlforecast.py
- Bump `mlforecast` dependency to v0.10.0 as it includes an important bugfix
- Fix a bug because of which `RecursiveTabular` model did not use the covariates
- Fix typos in docstrings
> [timeseries] Bump mlforecast dependency + fix covariates usage

- core/src/autogluon/core/_setup_utils.py
- docs/tutorials/timeseries/forecasting-model-zoo.md
- timeseries/setup.py
- timeseries/src/autogluon/timeseries/models/__init__.py
- timeseries/src/autogluon/timeseries/models/gluonts/__init__.py
- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- timeseries/src/autogluon/timeseries/models/gluonts/torch/__init__.py
- timeseries/src/autogluon/timeseries/models/gluonts/torch/models.py
- timeseries/src/autogluon/timeseries/models/local/npts.py
- timeseries/src/autogluon/timeseries/models/presets.py
- timeseries/tests/smoketests/test_all_models.py
- timeseries/tests/unittests/models/test_gluonts.py
- timeseries/tests/unittests/models/test_local.py
- Bump GluonTS to v0.14.0.
- Change all `pytorch_lightning` references to `lightning.pytorch`.
- Add wrapper for the `WaveNet` model.
- Rename old MXNet argument names `learning_rate` / `epochs` to `lr` / `max_epochs` for compatibility with PyTorch-Lightning naming (both versions are still supported, only docstrings are updated).
------
**To Do:**
> [timeseries] Update GluonTS to v0.14.0

- timeseries/tests/smoketests/test_all_models.py
- Fix failing platform tests. These were caused by some versions of pandas (<2.1) failing to correctly infer some frequencies from timestamps.
> [timeseries] Fix platform tests

- common/setup.py
- common/src/autogluon/common/loaders/load_pd.py
- common/src/autogluon/common/utils/s3_utils.py
- Add tqdm to common
- Use tqdm when downloading a list of S3 files for better progress tracking
- fix incorrect function name in load_pd.py (Logic would have crashed due to undefined function name before)
> Add tqdm to common, fix incorrect function name in load_pd.py

- common/src/autogluon/common/utils/pandas_utils.py
- Currently, the method `get_approximate_df_mem_usage` produces the following warning with `pandas` `v2.1`:
```
/local/home/shchuro/workspace/autogluon/common/src/autogluon/common/utils/pandas_utils.py:50: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '1283.3714285714286' has dtype incompatible with int64, please explicitly cast to a compatible dtyp
e first.
```
This PR fixes this warning.
> [common] Fix FutureWarning in get_approximate_df_mem_usage

- core/src/autogluon/core/metrics/__init__.py
- core/src/autogluon/core/models/greedy_ensemble/ensemble_selection.py
- Address warnings from log_loss metric
- `eps` arg is deprecated in sklearn.metrics.log_loss
- Have to renormalize during weighted ensemble fit to avoid warnings in the log_loss metric.
Mainline:
```
Fitting model: LightGBM ...
/opt/conda/envs/code310new/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2851: FutureWarning: Setting the eps parameter is deprecated and will be removed in 1.5. Instead eps will always havea default value of `np.finfo(y_pred.dtype).eps`.
warnings.warn(
/opt/conda/envs/code310new/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2922: UserWarning: The y_pred values do not sum to one. Starting from 1.5 thiswill result in an error.
warnings.warn(
-1.1347	 = Validation score …
```
> Address warnings from log_loss metric

- timeseries/src/autogluon/timeseries/learner.py
- timeseries/src/autogluon/timeseries/metrics/__init__.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/src/autogluon/timeseries/trainer/abstract_trainer.py
- timeseries/tests/smoketests/test_all_models.py
- timeseries/tests/unittests/test_predictor.py
-  The behavior of `TimeSeriesPredictor.evaluate` now aligns with Tabular/Multimodal predictors:
- it now returns a dictionary where keys = metric names, values = scores along each metric
- user can now pass multiple metrics to `evaluate`
- Deprecate the method  `TimeSeriesPredictor.score` as it's just an alias for `TimeSeriesPredictor.evaluate`.
- Do not log a warning if user provides the old name for the `mean_wQuantileLoss` metric. 
> [timeseries] Support passing multiple evaluation metrics to TimeSeriesPredictor.evaluate

- core/src/autogluon/core/learner/abstract_learner.py
- core/src/autogluon/core/stacked_overfitting/utils.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/tests/conftest.py
- tabular/tests/unittests/dynamic_stacking/test_dynamic_stacking.py
Rel.: #2779 
This PR adds support for dynamic stacking. The idea of dynamic stacking is to avoid stacked overfitting (a.k.a. stacked information leakage) by fitting AutoGluon at least twice. All but the last fits are done on a subset of the training data whereby a holdout set is used to determine if stacked overfitting occurs for the provided data. Afterwards, we run the last fit with or without  multi-layer stacking depending on whether stacked overfitting has not occurred in a previous fit.
We understand dynamic stacking as a baseline solution to avoid stacked overfitting. Nevertheless, so far, it is the best solution we have benchmarked due to it being most consistent (which is very important for AutoML systems). Moreover, due to having a holdout set as a result of this approach, we …
> Support Dynamic Stacking to Avoid Stacked Overfitting

- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/src/autogluon/timeseries/utils/features.py
- timeseries/tests/unittests/models/test_mlforecast.py
- If user provides `known_covariates_names` as a `np.ndarray` or `pd.Index` instead of `List`, this causes a bug for [MLForecsat models](https://github.com/autogluon/autogluon/blob/master/timeseries/src/autogluon/timeseries/models/autogluon_tabular/mlforecast.py#L212C7-L212C7). Instead of concatenating two lists like `["1", "2"] + ["B"] = ["1", "2", "B"]`, we accidentally append to each entry in the first list as `np.array(["1", "2"]) + ["B"] = ["1B", "2B"]`. Then, the model fails because it cannot find these columns if the dataframe.
- Fix the test that is supposed to catch this bug.
> [timeseries] Fix bug caused by `known_covariates_names` provided as a pd.Index instead of list

- docs/tutorials/timeseries/forecasting-indepth.ipynb
- timeseries/src/autogluon/timeseries/dataset/ts_dataframe.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/tests/unittests/test_predictor.py
- timeseries/tests/unittests/test_ts_dataset.py
Currently, there are only two ways for the user to create a `TimeSeriesDataFrame` with `static_features`.
1. After creating a TSDF in any way (e.g., using `from_data_frame`, `from_path`), we attach the static features as
```python
tsdf = TimeSeriesDataFrame.from_data_frame(...)
tsdf.static_features = static_df
```
2. Set at creation time (this approach is not documented)
```python
tsdf = TimeSeriesDataFrame(..., static_features=static_df)
```
In both of these cases, `static_df` must be a `pd.DataFrame` with `item_id` **set as index**. This is rather restrictive and is not compatible with other methods for TSDF creation such as `TimeSeriesDataFrame.from_data_frame`:
- What if `item_id` is a column and not the index?
- What if the item ID column is not called `item_id`?
This PR adds support …
> [timeseries] Improve handling of static_features by TimeSeriesDataFrame

- tabular/src/autogluon/tabular/models/automm/automm_model.py
- Fix memory size estimate after AutoMM refactor
- Mainline crashes if training an AutoMM model via tabular and then calling `predictor.persist_models()` because `self.model._model` does not exist anymore.
> Fix memory size estimate after AutoMM refactor

- multimodal/src/autogluon/multimodal/models/ft_transformer.py
- multimodal/src/autogluon/multimodal/models/fusion/fusion_mlp.py
- multimodal/tests/unittests/predictor/test_predictor.py
- Add input_keys property in ft_transformer for late fusion.
- Fixed the bug in fusion_mlp when getting outputs from single models.
- Add ft_transformer in test_predictor.
> [AutoMM] Add input_keys property in ft_transformer for late fusion

- core/src/autogluon/core/_setup_utils.py
Pillow `10.0.1` addresses [CVE-2023-4863](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-4863), see: https://pillow.readthedocs.io/en/stable/releasenotes/10.0.1.html
> Update Pillow to v10.

- multimodal/setup.py
- multimodal/src/autogluon/multimodal/utils/log.py
Using `subprocess` + `nvidia-smi` command caused both free and total GPU mem returns 0 in `log_gpu_info`.
> [AutoMM] Fix log gpu info

- common/setup.py
- common/src/autogluon/common/loaders/load_json.py
- common/src/autogluon/common/savers/save_json.py
- common/src/autogluon/common/utils/simulation_utils.py
- core/src/autogluon/core/_setup_utils.py
- core/src/autogluon/core/trainer/abstract_trainer.py
- tabular/src/autogluon/tabular/learner/abstract_learner.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/tests/unittests/test_tabular.py
- Add get_simulation_artifact for zeroshot HPO
- Added s3 save/load support to `save_json` and `load_json`
- Added s3fs to default dependencies as it is lightweight and is needed to access s3 files via pandas.
- Added eval_metric column to leaderboard output
- Added stopping_metric column to leaderboard output when `extra_info=True`.
- Added `score_format` argument to leaderboard to add the option to return the error instead of the score.
> Add get_simulation_artifact

- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- Fix bug introduced in #3575 that led to incorrect `start` timestamp provided to GluonTS models.
> [timeseries] Fix starting timestamp bug for GluonTS models

- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/tests/unittests/test_metrics.py
- timeseries/tests/unittests/test_predictor.py
- Automatically reduce `num_val_windows` so that median time series length in `train_data` is sufficient to perform `num_val_windows` backtests.
If `num_val_windows` provided by the user is too high, the log message looks as follows:
```
Provided train_data has 6244 rows, 72 time series. Median time series length is 108 (min=16, max=108).
Time series in train_data are too short for chosen num_val_windows=100. Reducing num_val_windows to 7.
Removing 24 short time series from train_data. Only series with length >= 97 will be used for training.
After removing short series, train_data has 5184 rows, 48 time series. Median time series length is 108 (min=108, max=108).
```
- Fix typo in docstring to `fit`
- Remove `pytest.skip` in metric tests since the new release of …
> [timeseries] Automatically reduce num_val_windows if training data is too short

- multimodal/tests/unittests/predictor/test_predictor.py
- multimodal/tests/unittests/utils/unittest_datasets.py
- Categorical MLP is not used in unit test test_predictor because categorical data is filtered out when dataset is too small. Fixed it by using larger subset of `petfinder` dataset.
> [AutoMM] Fix test_predictor coverage of categorical mlp

- common/src/autogluon/common/utils/utils.py
- docs/tutorials/timeseries/forecasting-quick-start.ipynb
- timeseries/src/autogluon/timeseries/learner.py
- timeseries/src/autogluon/timeseries/models/ensemble/greedy_ensemble.py
- timeseries/src/autogluon/timeseries/predictor.py
*Issue #, if available:* #3707
- Make output of `TimeSeriesPredictor.fit` more aligned with `TabularPredictor.fit`
- Print learned ensemble weights
- Fix outdated `silent=True` flag in docs
Example output of `TimeSeriesPredictor.fit`:
```
Beginning AutoGluon training... Time limit = 60s
AutoGluon will save models to 'AutogluonModels/ag-20231116_111814'
=================== System Info ===================
AutoGluon Version:  0.8.3b20231107
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Wed Oct 11 23:53:22 UTC 2023
CPU Count:          32
GPU Count:          4
Memory Avail:       230.66 GB / 239.87 GB (96.2%)
Disk Space Avail:   139.34 GB / 984.21 GB (14.2%) …
```
> [timeseries] Align time series logs with Tabular

- timeseries/setup.py
- timeseries/src/autogluon/timeseries/models/autogluon_tabular/mlforecast.py
- timeseries/src/autogluon/timeseries/models/local/abstract_local_model.py
- timeseries/src/autogluon/timeseries/models/local/statsforecast.py
- timeseries/tests/unittests/models/test_mlforecast.py
- Avoid high memory usage by shortening time series before calling `MLForecast.preprocess`
- Increase default `num_items` to 20K because we don't suffer from OOM problems anymore with the above change
- Generate dummy forecast for time series that are shorter than `sum(differences)` (before we used to get NaN predictions for these series)
- Add dummy quantiles to predictions of `DirectTabular` model if point forecast metric is provided (before there was a bug, where mean forecast was just repeated for all quantiles)
- Expose `damped` parameter of `AutoETS` model from StatsForecast
> [timeseries] Bugfixes for MLForecast models

- tabular/src/autogluon/tabular/models/lgb/callbacks.py
- Fix LightGBM callback crash with v4.0+
- In v4.0+, `show_stdv` was changed from having a default value to being required to specify by the user in `_format_eval_results`. Because we weren't specifying it before, it started causing crashes when we upgraded to LightGBM v4.0+.
> Fix LightGBM callback crash with v4.0+

- timeseries/src/autogluon/timeseries/models/gluonts/torch/models.py
- Inference is extremely slow for WaveNet model on CPU. Reducing `num_samples` used in GluonTS SampleForecast for this model from 250 to to its default value of 100 reduces the inference time by a factor of 2.5x.
> [timeseries] Speed up inference for WaveNet model

- timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
- timeseries/src/autogluon/timeseries/models/multi_window/multi_window_model.py
- timeseries/src/autogluon/timeseries/trainer/abstract_trainer.py
- timeseries/tests/unittests/test_predictor.py
- Do not allocate more than 600 seconds for fitting ensemble
- Evenly split the time limit across all validation windows in MultiWindowBacktestingModel
- Fix a bug where incorrect model suffix was saved if no refit happened in the most recent window
> [timeseries] Adjust how time limit is split across models

- multimodal/src/autogluon/multimodal/optimization/losses.py
https://github.com/autogluon/autogluon/issues/3441
In `FocalLoss`, the expected `alpha` is a tensor or an iterable type, e.g. `[0.1, 0.3, 0.5, 0.1]`. However, when `ray.tune` is used for HPO, the sampled hyperparameter per trial converts `alpha` to a `tuple` in `str`, e.g.: `"(0.1, 0.3, 0.5, 0.1)"`.
We are patching this bug by parsing the erroneous `str` type sampled hyperparameters from `ray.tune` to be a list so that the logic doesn't break during HPO.
> handle str type in sampled ray.tune hyperparameter

- timeseries/src/autogluon/timeseries/models/ensemble/greedy_ensemble.py
- timeseries/src/autogluon/timeseries/trainer/abstract_trainer.py
- Make sure that correct verbosity is set for the logger in ensemble. Currently, incorrect logger configuration leads to the ensemble weights not being printed to the console.
> [timeseries] Fix logger verbosity for ensemble

- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- timeseries/src/autogluon/timeseries/models/gluonts/torch/models.py
- timeseries/tests/unittests/models/test_gluonts.py
- Currently, if user provides a very large `prediction_length` (more than 1000), it will result in extremely high `context_length` used by GluonTS models. This may lead to OOM errors (e.g., for TemporalFusionTransformer model that scales quadratically with sequence length).
- We clip the `context_length` to be at most 512 to avoid these issues.
> [timeseries] Fix GluonTS models using high context_length

- timeseries/src/autogluon/timeseries/models/autogluon_tabular/mlforecast.py
- timeseries/tests/unittests/models/test_mlforecast.py
- timeseries/tests/unittests/models/test_models.py
- Estimate the standard deviation of the residuals separately for each item in `DirectTabular` model (with point forecast metric) and `RecursiveTabular` model. Before, we used to estimate a single standard deviation across all items.
- Fix typo in docstring.
> [timeseries] Use per-item residuals in MLForecast models

- docs/tutorials/timeseries/forecasting-faq.md
- docs/tutorials/timeseries/forecasting-indepth.ipynb
- docs/tutorials/timeseries/forecasting-metrics.md
- docs/tutorials/timeseries/forecasting-model-zoo.md
- docs/tutorials/timeseries/index.md
- timeseries/src/autogluon/timeseries/metrics/__init__.py
- timeseries/src/autogluon/timeseries/metrics/point.py
- timeseries/src/autogluon/timeseries/metrics/quantile.py
- timeseries/src/autogluon/timeseries/predictor.py
- Add documentation for evaluation metrics available in AutoGluon.
> [timeseries] Add documentation for forecasting metrics

- timeseries/setup.py
*Issue #, if available:* #3612
- Pin tensorboard version range to avoid potential installation problems (matches range defined in https://github.com/autogluon/autogluon/blob/master/multimodal/setup.py#L54)
> [timeseries] Pin tensorboard version range

- timeseries/src/autogluon/timeseries/dataset/ts_dataframe.py
- timeseries/tests/unittests/test_ts_dataset.py
- `tsdf.convert_frequency` can be extremely slow for large datasets. In this PR, we parallelize resampling using joblib. 
- This results in a noticeable speedup. For example, for M4 Monthly dataset (48000 items):
- Current sequential implementation based on `df.groupby(...).resample(...)` - `4m11s`.
- This PR (32 cores, chunk_size=100) -`31s`.
Note that chunking critical for the speedup. If we don't use chunking, runtime for M4 Monthly goes up to `4m30s`, which is comparable to the sequential version.
I have considered [other methods](https://stackoverflow.com/questions/15799162/resampling-within-a-pandas-multiindex) for speeding up resampling, however:
- `pd.Grouper` isn't applicable in case original data has irregular timestamps that are a subset of …
> [timeseries] Speed up TimeSeriesDataFrame.convert_frequency using joblib

- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- Ensure that # of validation batches is still limited in case `Cached` issue is fixed in GluonTS v0.14.x.
> [timeseries] Limit number of GluonTS validation batches

- multimodal/src/autogluon/multimodal/utils/environment.py
*Description of changes:* Avoid crash when model `config.yaml` contains integer `precision: 16`
```pytb
File "/usr/share/python3/app/lib/python3.11/site-packages/autogluon/multimodal/predictor.py", line 644, in predict_proba
return self._learner.predict_proba(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/share/python3/app/lib/python3.11/site-packages/autogluon/multimodal/learners/base.py", line 2000, in predict_proba
outputs = self.predict_per_run(
^^^^^^^^^^^^^^^^^^^^^
File "/usr/share/python3/app/lib/python3.11/site-packages/autogluon/multimodal/learners/base.py", line 1724, in predict_per_run
outputs = self.realtime_predict(
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/share/python3/app/lib/python3.11/site-packages/autogluon/multimodal/learners/base.py", line 1631, in …
```
> Fix get_precision_context

- timeseries/src/autogluon/timeseries/models/autogluon_tabular/mlforecast.py
- timeseries/src/autogluon/timeseries/trainer/abstract_trainer.py
- timeseries/tests/unittests/test_trainer.py
*Issue #, if available:* #3814
- Fix bugs when calling `predictor.refit_full()` multiple times
- Add test that verifies correctness of repeated calls to `refit_full()`
- Add `can_refit_full` tag to `DirectTabular` and `RecursiveTabular` models that was incorrectly removed in v1.0
> [timeseries] Fix refit_full bug

- multimodal/src/autogluon/multimodal/optimization/lit_module.py
https://github.com/autogluon/autogluon/issues/3414
This PR fixes the bug when using `f1`, `f1_macro`, `f1_micro` for binary classification problems.
> handle binary classification for f1 metrics

- .github/workflow_scripts/env_setup.sh
- .github/workflow_scripts/test_common.sh
- .github/workflow_scripts/test_core.sh
- .github/workflow_scripts/test_eda.sh
- .github/workflow_scripts/test_features.sh
- .github/workflow_scripts/test_multimodal.sh
- .github/workflow_scripts/test_tabular.sh
- .github/workflow_scripts/test_timeseries.sh
*Issue #:* https://github.com/autogluon/autogluon/issues/3807
(**NOTE**: This PR does not solve the issue linked above but just detects it, which was not the case earlier)
This fix is to detect the error on Windows runners when we run platform tests. 
Currently the platform tests pass for Python 3.11 on Windows runners but this should not happen as AG installation should error out as `ray` does not support Python 3.11 on Windows (https://github.com/autogluon/autogluon/issues/3807#issuecomment-1851644976).
The platform tests pass on Github Windows runners because an incorrect version of python is used (3.9) when we use `python3` to install packages. Windows runners pick up the correct version only when we use `python` instead of `python3`.
This problem is not …
> [Fix] Using correct Python version on Windows runners for Platform tests

- eda/setup.py
- eda/src/autogluon/eda/analysis/explain.py
- eda/src/autogluon/eda/auto/simple.py
- eda/src/autogluon/eda/visualization/explain.py
- eda/tests/unittests/visualization/test_explain.py
*Issue #, if available:* #3497
- Added positive class selection - see #3497
- binary classification will use `model.positive_class`
- multiclass uses the last column in prediction probabilities
```python
auto.explain_rows(
train_data=df_train,
model=state.model,
display_rows=True,
return_state=True,
positive_class='banana', # specify positive class
rows=state.model_evaluation.highest_error[:1]
)
```
- Libraries updates: bumped versions for shap and pyod; updated changed shap API calls.
> [eda] added positive class parameters and autodetection

- timeseries/src/autogluon/timeseries/trainer/abstract_trainer.py
- timeseries/tests/unittests/test_trainer.py
- Currently, if all models failed during `fit()`, calling `predictor.leaderobard()` crashes with a `KeyError`. With this PR, we will return an empty leaderboard instead.
> [timeseries] Return empty leaderboard if no models were trained during fit

- tabular/src/autogluon/tabular/predictor/predictor.py
While searching for another issue, I realized that the current implementation of memory-safe fits will not do memory-safe fits in the edge case where Ray was never initialized on the current system (e.g., in a fresh container).
Due to using `address="auto"`, this would fail and then be silently handled by except without informing the user. 
This PR is a short, straightforward fix for this and provides a warning now if save memory fits should have been used but were not. 
---
> [FIX] Imporve Error Handling and Init for Ray for Memory Save Sub-fits in Dynamic Stacking 

- tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
Autogluon 1.0 emits the following warning since pandas 2.2 [depreacated downcast arg](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html) in `pd.fillna`.
```
autogluon/tabular/models/fastainn/tabular_nn_fastai.py:200: FutureWarning: The 'downcast' keyword in fillna is deprecated and will be removed in a future version. Use res.infer_objects(copy=False) to infer non-object dtype, or pd.to_numeric with the 'downcast' keyword to downcast numeric results.
```
It was partially resolved in #3734 
This PR also adds the warning filter to tabular_nn_fastai.py.
> Ignore pandas downcast warning

- core/src/autogluon/core/_setup_utils.py
- features/src/autogluon/features/generators/one_hot_encoder.py
- tabular/src/autogluon/tabular/models/rf/rf_quantile.py
Upgrading to scikit-learn 1.4.0 has brought on some changes in the API. PR to address the same.
> [Fix] Fix tests on scikit-learn upgrade

- timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
- timeseries/src/autogluon/timeseries/models/autogluon_tabular/mlforecast.py
- timeseries/src/autogluon/timeseries/models/ensemble/greedy_ensemble.py
- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- timeseries/src/autogluon/timeseries/models/local/abstract_local_model.py
- timeseries/src/autogluon/timeseries/models/multi_window/multi_window_model.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/src/autogluon/timeseries/trainer/abstract_trainer.py
- timeseries/tests/unittests/test_predictor.py
#3766 
- Enable logging to file, including a custom log file name following the API of `TabularPredictor`.
- Clean up unused verbosity arguments and set_logger_verbosity calls throughout the library. 
Note: Previously, timeseries model objects (`AbstractTimeSeriesModel`) had their own verbosity levels provided in the call to `fit`, which was propagated from the Trainer `fit` call to individual models. While this created clutter, it also afforded the flexibility of models potentially using the verbosity level to set dependency log output levels (e.g., GluonTS). We keep this as is: GluonTS models still receive `verbosity` as a fit argument.
However, logger verbosity is now only controlled by the Predictor, which sets the verbosity (either …
> [timeseries] enable logging to file, clean up set_logger_verbosity calls

- docs/tutorials/multimodal/advanced_topics/customization.ipynb
- multimodal/src/autogluon/multimodal/configs/model/default.yaml
- multimodal/src/autogluon/multimodal/models/ft_transformer.py
- multimodal/src/autogluon/multimodal/models/utils.py
- multimodal/src/autogluon/multimodal/utils/model.py
- multimodal/tests/unittests/predictor/test_predictor.py
Resolves #3847
- Add `checkpoint_name` argument in ft_transformer so that users could load pre-trained ft_transformer weights.
- Fixed a bug in setting `layer_id` when `model_prefix` is `None`.
> [AutoMM] Add support for loading pre-trained weights in ft_transformer

- docs/install.md
Mention availability of AutoGluon in SageMaker Distribution images. Added a few sentences at the top of the Install section.
> Mention availability of AutoGluon in SageMaker Distribution images

- tabular/tests/unittests/test_tabular.py
**_test_tabular.py:test_pseduolabeling.py_** fails as there is a deadlock due to Ray.
refer issue for more info: https://github.com/autogluon/autogluon/issues/3870
This PR fixes a test showing this behavior by disabling dynamic stacking, which in turn fixes the CI
> [CI Fix][Tabular]Disable dynamic stacking for pseudolabeling

- multimodal/src/autogluon/multimodal/constants.py
- multimodal/src/autogluon/multimodal/data/infer_types.py
- multimodal/src/autogluon/multimodal/data/preprocess_dataframe.py
- multimodal/src/autogluon/multimodal/data/process_image.py
- multimodal/src/autogluon/multimodal/learners/base.py
- multimodal/src/autogluon/multimodal/problem_types.py
- multimodal/src/autogluon/multimodal/utils/misc.py
- multimodal/tests/unittests/predictor/test_predictor.py
> [AutoMM] add a new column type 'image_base64_str'

- timeseries/tests/conftest.py
- Skip deleting directory created by` temp_model_path` on Windows if logs are saved to it.
> [timeseries] Fix platform tests failing on Windows

- .github/workflows/continuous_integration.yml
- .github/workflows/continuous_integration_multigpu.yaml
This change adds concurrency control to our CI.
If a same PR has multiple commits within a short span of time then the older CI runs are cancelled and the latest one is only run. The same thing would happen for synchronization as well.
This would massively bring down the cost incurred by the AG Team for using AWS Batch for the CI.
It would also free up the vCPUs that are used unnecessarily for old runs, which we can then dedicate to new runs, thus increasing the capacity of our CI.
> [Feature][CI] Add Concurrency control to increase efficiency, save resources and bring down cost

- tabular/setup.py
There is a new version of LightGBM: https://github.com/microsoft/LightGBM/releases/tag/v4.0.0
I think the most important part is quantization that promises 2x speed-up in training (https://arxiv.org/pdf/2207.09682.pdf)
It could be enabled by parameter `use_quantized_grad`  (https://lightgbm.readthedocs.io/en/latest/Parameters.html)
> Update setup.py - LightGBM version bump

- tabular/src/autogluon/tabular/models/fastainn/hyperparameters/searchspaces.py
- tabular/src/autogluon/tabular/models/tab_transformer/utils.py
- tabular/src/autogluon/tabular/models/tabular_nn/compilers/onnx.py
- tabular/src/autogluon/tabular/predictor/predictor.py
Resolves #3884
Related: #3882
- Fixes paths to use `os.path.sep` instead of `/` in dynamic stacking to avoid errors on Windows.
> Tabular: Fix dynamic_stacking on Windows

- timeseries/src/autogluon/timeseries/learner.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/src/autogluon/timeseries/trainer/abstract_trainer.py
- timeseries/src/autogluon/timeseries/trainer/auto_trainer.py
- timeseries/tests/unittests/test_predictor.py
#3896 
#3923
Previously, `seed_everything` was called once at the beginning of `TimeSeriesPredictor` `fit` and `predict` methods which led to two undesirable side effects:
- if any of the models reset the seeds in their internal logic, they could effectively cancel the `random_seed` provided by the user. This was done, e.g., in `RecursiveTabular`'s `NN_TORCH` affecting `high_quality` presets.
- The fitting order of models could affect the outcomes of individual models. i.e., the random state at the beginning of each model depended on previous models.
With this change, we propagate the random seed to the learner and trainer both at training and prediction time. We set the seed again, per model, when fitting single models or predicting with …
> [timeseries] fix random seed, reset seed for every model

- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- timeseries/src/autogluon/timeseries/models/gluonts/torch/models.py
- timeseries/tests/unittests/models/test_gluonts.py
*Issue #, if available:* Fixes #3853
- Add hyperparameter `keep_lightning_logs` to GluonTS models. If set to `True`, `lightning_logs` directory won't be removed after training.
> [timeseries] Add option to keep lightning_logs after training

- docs/tutorials/timeseries/forecasting-metrics.md
- timeseries/src/autogluon/timeseries/metrics/__init__.py
- timeseries/src/autogluon/timeseries/metrics/point.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/tests/unittests/test_metrics.py
#3878
RMSLE is a forecast error metric popular with some Kaggle competitions, that is specifically insensitive to effects of scale and trends and has an asymmetric penalty for overprediction. For example, the "getting started" Sales Prediction competition uses RMSLE. This PR includes RMSLE to AG-TS.
Discussion points: 
> [timeseries] add RMSLE to metrics

- core/src/autogluon/core/_setup_utils.py
Recently `scikit-learn` released a new version 1.4.1.post1 on 16th Feb 2024.
This release somehow interferes with Ray and causes a failure of all tests under `test_hpo.py`.
The fix for now is to cap the version of `scikit-learn` that is installed until further investigation.
> [AutoMM][CI] Capping scikit-learn to avoid HPO test failure

- core/src/autogluon/core/models/abstract/abstract_model.py
- tabular/src/autogluon/tabular/models/catboost/catboost_model.py
- tabular/src/autogluon/tabular/models/lgb/lgb_model.py
- tabular/src/autogluon/tabular/models/xgboost/xgboost_model.py
Resolves #3928 
- Fixes crash during HPO if the user specified in their search space a hyperparameter which is used to estimate memory usage of a model. Now we use the default value within the search space for the memory check.
> Fix HPO crash in memory check

- docs/conf.py
**This change ensures the copyright information in conf.py accurately displays the current year (2024).**
> Update conf.py copyright to reflect current year

- timeseries/src/autogluon/timeseries/models/autogluon_tabular/mlforecast.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/src/autogluon/timeseries/utils/features.py
- timeseries/tests/unittests/models/test_gluonts.py
- timeseries/tests/unittests/test_features.py
- timeseries/tests/unittests/test_learner.py
- Add support for known and past **categorical** covariates to `autogluon.timeseries.utils.features.TimeSeriesFeatureGenerator`.
- Improve log messages about the inferred column types
- Convert all continuous covariates, features, and target to float32
Example log for a dataset with various covariates:
```
Provided data contains following columns:
target: 'target'
known_covariates:
categorical:        ['feat1']
continuous (float): ['feat3']
past_covariates:
categorical:        ['feat2', 'feat_bool']
continuous (float): ['feat4']
static_features:
categorical:        ['a', 'c']
continuous (float): ['b']
AutoGluon will ignore following non-numeric/non-informative columns:
ignored covariates:      ['feat_dt', 'feat_repeat']
ignored static_features: ['d']
To learn how …
```
> [timeseries] Add support for categorical covariates

- core/setup.py
To fix AutoGluon installation [issue](https://github.com/autogluon/autogluon/issues/3807) on windows with Python 3.11
Currently the workaround is not to install ray till ray release a version which support windows installation
> Fix windows python 3.11 issue by removing ray

- docs/install-modules.md
Resolves #3965
- Mention skex does not support ARM.
- Mention EDA is deprecated.
> [Docs] Update install modules content

- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/tests/unittests/test_predictor.py
- Fix a bug, where GluonTS models trained on GPU could not be loaded on a CPU-only machine
- Fix a bug, where passing path to data as a `str` raised an exception
- Fix the respective test that was supposed to catch this bug
- Allow passing the path to data as a `pathlib.Path` when using `TimeSeriesPredictor`
> [timeseries] Fix path and device bugs

- timeseries/src/autogluon/timeseries/metrics/abstract.py
- timeseries/src/autogluon/timeseries/metrics/point.py
- timeseries/src/autogluon/timeseries/metrics/quantile.py
- timeseries/tests/unittests/common.py
- timeseries/tests/unittests/models/test_models.py
- timeseries/tests/unittests/test_metrics.py
*Issue #, if available:* #3886
- Raise exception in `TimeSeriesScorer` if predictions contain NaN values
- Update implementation of WQL metric to handle NaN values in target column
- Update our implementation of MASE and SQL metrics to align with GluonTS in case missing values are present
- As part of this update, we moved from `pandas + groupby` to `numpy + reshape`, which results in faster metric computations & lower fit time for WeightedEnsemble (for M4 Monthly with 48K time series, ensemble fit time decreases 200s -> 160s)
- Update the RMSSE implementation to follow the same missing values handling logic
- Add new tests & update some old tests to use dataframes with missing values …
> [timeseries] Ensure that all metrics handle missing values in the target

- core/src/autogluon/core/_setup_utils.py
- multimodal/setup.py
- multimodal/src/autogluon/multimodal/data/process_image.py
- timeseries/setup.py
Chronos implementation (cf #3978) requires `transformers>=4.36`. This PR moves transformers and accelerate version ranges to `_setup_utils.py` and bumps the version. 
> [core] move transformers to setup_utils, bump dependency version

- timeseries/src/autogluon/timeseries/configs/presets_configs.py
- timeseries/src/autogluon/timeseries/learner.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/src/autogluon/timeseries/trainer/abstract_trainer.py
- timeseries/src/autogluon/timeseries/trainer/auto_trainer.py
- timeseries/tests/unittests/test_predictor.py
- timeseries/tests/unittests/test_trainer.py
- Add kwarg `skip_model_selection` to `TimeSeriesPredictor.fit`. It can be used if only a single model is to be trained. If set to True, model will skip computing the validation score, thereby reducing the overall fit time.
> [timeseries] Add option to skip model selection if only 1 model is trained

- timeseries/tests/conftest.py
- timeseries/tests/unittests/test_predictor.py
Fixes a bug that causes a FileNotFoundError from ray using the current temporary path fixture in predictor tests. This PR replaces predictor path fixtures with the pytest fixtures.
> [timeseries] fix predictor tests temporary path issue

- timeseries/src/autogluon/timeseries/learner.py
- timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
- timeseries/src/autogluon/timeseries/models/chronos/model.py
- timeseries/src/autogluon/timeseries/models/multi_window/multi_window_model.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/src/autogluon/timeseries/trainer/abstract_trainer.py
- timeseries/tests/unittests/models/test_chronos.py
- timeseries/tests/unittests/test_predictor.py
Adds methods to `persist` predictor, learner, trainer and model objects, bringing the ability to persist models in memory like in `TabularPredictor`
> [timeseries] add persist logic to TimeSeriesPredictor

- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- core/src/autogluon/core/models/ensemble/fold_fitting_strategy.py
- core/src/autogluon/core/pseudolabeling/pseudolabeling.py
- core/src/autogluon/core/trainer/abstract_trainer.py
- tabular/src/autogluon/tabular/learner/abstract_learner.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/tests/unittests/test_tabular.py
> Tabular: Refactor and fix `fit_pseudolabel` logic

- examples/automm/Conv-LoRA/README.md
- examples/automm/Conv-LoRA/run_semantic_segmentation.py
1. Install from source to improve the flexibility of users.
2. Remove fixed model path to avoid errors when running different datasets.
3. Support customizing per_gpu_batch_size and batch_size.
> [AutoMM] Fix conv-lora example

- core/src/autogluon/core/models/abstract/abstract_model.py
Quadratic Kappa is an important evaluation metric used in lots of kaggle competitions. This was added in https://github.com/autogluon/autogluon/pull/1104 but the documentation [doesn't](https://auto.gluon.ai/stable/api/autogluon.tabular.TabularPredictor.html#autogluon-tabular-tabularpredictor) mention its availability as one of the `eval_metric` options inside AutoGluon.
Add `quadratic_kappa` to the doc list of `eval_metric` options for classification.
> DOC: Mention quadratic_kappa metric in eval_metric docs

- tabular/tests/conftest.py
Fix the path matching logics in tabular conftest.py to accommodate windows
On windows machine, the path matching logics failed due to directory separator used is not consistent
Adding link to working platform tests: https://github.com/autogluon/autogluon/actions/runs/8546584824
> Fix the path matching logics in tabular conftest.py to accommodate windows

- timeseries/tests/unittests/models/test_models.py
- Platform 3.8 raises a SyntaxError if context managers are used within parentheses, so we need to adjust the line breaks
> [timeseries] Fix platform tests for time series on Python 3.8

- timeseries/tests/unittests/test_predictor.py
[Windows platform tests](https://github.com/autogluon/autogluon/actions/runs/8539963097/job/23395948812) for `timeseries` are failing due to a permission error on removing a logfile that is being used by another process.
This was introduced due to changes made in #3934 specifically these two lines were added to clean up the test directory (see comment: https://github.com/autogluon/autogluon/pull/3934/files#r1495459186). So this is a test specific fix for windows, and we skip removing the custom_log file in windows tests.:
https://github.com/autogluon/autogluon/blob/4de305651abe621aeab92d4a950cfc6fc1f6c3b9/timeseries/tests/unittests/test_predictor.py#L1090-L1091
Thanks @shchur for helping setup the machine and sharing some context on the …
> [timeseries] Fix windows platform tests logfile permission error

- timeseries/src/autogluon/timeseries/learner.py
- timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
- timeseries/src/autogluon/timeseries/models/autogluon_tabular/mlforecast.py
- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- timeseries/src/autogluon/timeseries/models/gluonts/torch/models.py
- timeseries/src/autogluon/timeseries/models/multi_window/multi_window_model.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/src/autogluon/timeseries/trainer/abstract_trainer.py
- timeseries/src/autogluon/timeseries/utils/features.py
- timeseries/tests/unittests/test_features.py
- timeseries/tests/unittests/test_predictor.py
- timeseries/tests/unittests/test_trainer.py
#3924 
This draft PR introduces the high level design for `TimeSeriesPredictor.feature_importance`. 
Additional to-dos:
- ~(stretch) Revisit prediction caching logic to prevent models that don't use features from re-inferring~
> [timeseries] add feature importance to TimeSeriesPredictor

- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- timeseries/tests/unittests/models/test_gluonts.py
- Preprocess real-valued columns in known, past & static covariates for GluonTS models. We use the same logic as used by `TORCH_NN` model in AG-Tabular:
- Boolean features are kept as-is
- Skewed features (skewness > 0.99) are transformed with `QuantileTransform`
- Remaining features are transformed with `StandardScaler`
To do:
> [timeseries] Preprocess real-valued features for neural network models

- common/src/autogluon/common/utils/try_import.py
- core/src/autogluon/core/_setup_utils.py
- tabular/setup.py
- Upgrade Dependency Ranges for 1.1
- Update pandas to 2.2.x has been moved to a future PR.
> Upgrade Dependency Ranges for 1.1

- core/src/autogluon/core/trainer/abstract_trainer.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- Improve AbstractTrainer Docs
> Improve AbstractTrainer Docs

- timeseries/src/autogluon/timeseries/models/chronos/model.py
Previously, models saved to long local pathnames caused test failures due to Windows' MAX_PATH. Our path names are now safe for both Windows' `os.path.sep` and also truncates the names of models loaded locally to increase readability and avoid MAX_PATH issues.
> [timeseries] Fix long path name issue on Windows for Chronos

- timeseries/tests/smoketests/test_all_models.py
- timeseries/tests/unittests/models/test_local.py
- timeseries/tests/unittests/test_features.py
- Supersedes #4049 
- Fix failing tests caused by capped `numpy` / `pandas` versions available for Python 3.8
> [timeseries] Fix timeseries platform tests on ubuntu/mac with Python 3.8

- timeseries/tests/conftest.py
- timeseries/tests/smoketests/test_all_models.py
- timeseries/tests/unittests/models/test_models.py
Previously time series smoke tests and model tests did not reuse the `hf_model_path` test fixture, leading to about ~250 downloads on Hugging Face for each CI run. This PR brings the number to about ~10~ 40. 
> [timeseries] use chronos test fixture in smoke tests

- timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
- timeseries/src/autogluon/timeseries/models/chronos/model.py
- timeseries/src/autogluon/timeseries/models/chronos/utils.py
- timeseries/src/autogluon/timeseries/models/local/abstract_local_model.py
- timeseries/src/autogluon/timeseries/models/multi_window/multi_window_model.py
- timeseries/tests/unittests/models/test_chronos.py
- timeseries/tests/unittests/models/test_models.py
- Ensure that Chronos does not have an extremely long inference time during model selection (e.g., if huge dataset is provided on bad hardware) by adding a callback to the Chronos dataloader that checks if the time_limit is not exceeded
- Unify design of inference time limits between local models & Chronos
> [timeseries] Ensure that Chronos respects time_limit during score_and_cache_oof

- timeseries/src/autogluon/timeseries/dataset/ts_dataframe.py
- timeseries/src/autogluon/timeseries/models/local/abstract_local_model.py
- Avoid printing the following error message when dummy forecast is used for all-NaN series
```
Warning: SeasonalNaive/W0 failed for 1 time series (50%). Fallback model SeasonalNaive was used for these time series
```
> [timeseries] Fix logger messages if series are all NaN

- tabular/tests/unittests/test_tabular.py
*Description:*
This pull request addresses a test failure observed on Windows environments within the tabular.The root cause of this issue has been identified as a discrepancy in pandas' default integer data type across different operating systems. Specifically, while pandas defaults to using `int64` on Windows, it utilizes `int32` on Linux platforms. This inconsistency leads to test failures when running platform-specific tests on Windows.
A detailed overview of the encountered test failure can be found here: [Test Failure Details](https://github.com/autogluon/autogluon/actions/runs/8570605165/job/23488891713).
*Changes Proposed:*
Implement a solution to ensure consistent behavior across platforms by explicitly managing the data type used in tests, thereby resolving the failure on …
> Fix Platform-Specific Test Failures in Tabular Module on Windows

- timeseries/src/autogluon/timeseries/models/autogluon_tabular/mlforecast.py
- timeseries/tests/unittests/models/test_mlforecast.py
- Some lightweight feature engineering for MLForecast-based models:
- Add two static features, encoding mean & std of the target time series for each item
- For each continuous real-valued covariate, add a copy of this covariate that is mean-abs-scaled per item
> [timeseries] Add scale feature and normalize covariates for MLForecast models

- timeseries/src/autogluon/timeseries/dataset/ts_dataframe.py
- timeseries/src/autogluon/timeseries/learner.py
- timeseries/src/autogluon/timeseries/models/autogluon_tabular/mlforecast.py
- timeseries/src/autogluon/timeseries/models/chronos/model.py
- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- timeseries/src/autogluon/timeseries/models/local/abstract_local_model.py
- timeseries/src/autogluon/timeseries/utils/forecast.py
- timeseries/tests/unittests/models/test_gluonts.py
- timeseries/tests/unittests/models/test_local.py
- timeseries/tests/unittests/models/test_models.py
- Many models currently rely on `data.freq` of the data passed to `model.predict(data)` when generating the forecast. It may happen that some time series in `data` passed to `predict` contain just a single observation. In this case, `freq` inference is impossible and the model fails.
- With this PR, we
1. Rely on `self.freq` attribute of the model instead of `data.freq` whenever frequency is required
2. Make sure that `data.fill_missing_values()` works even no `freq` is available (as this is too strong of a requirement for this method)
> [timeseries] Fix prediction failing if context contains < 3 observations

- core/src/autogluon/core/hpo/executors.py
- core/src/autogluon/core/hpo/ray_hpo.py
- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
Fixes #4075 
Use the environment variable `RAY_CHDIR_TO_TRIAL_DIR` instead of the argument `chdir_to_trial_dir`.
> [FIX] Avoid `chdir_to_trial_dir` causing silent `DeprecationWarning` Error

- timeseries/src/autogluon/timeseries/learner.py
- If there are duplicate column names in static features & covariates, `predictor.feature_importance()` will fail 100% of the time with an uninformative error message. This PR raises an informative exception in this case.
> [timeseries] Raise ValueError if duplicate feature names are provided for feature importance

- timeseries/src/autogluon/timeseries/models/autogluon_tabular/mlforecast.py
- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- timeseries/src/autogluon/timeseries/models/gluonts/torch/models.py
> [timeseries] Always pass dummy frequency to GluonTS models

- timeseries/setup.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/src/autogluon/timeseries/utils/warning_filters.py
#4062 
Two housekeeping items
- Drop unused `statsmodels` dependency
- Improve docs and raise warning for `refit_every_n_windows`
> [timeseries] drop statsmodels, improve refit_every_n_windows

- timeseries/src/autogluon/timeseries/trainer/abstract_trainer.py
- timeseries/tests/unittests/test_predictor.py
- Increment the random seed used to train each consecutive model by 1. This fixes a weird regression for GluonTS models: when we use the same seed for all GluonTS models, their performance becomes correlated and sometimes leads to an overall performance regression. This likely happens because, when the seed is fixed, the GluonTS dataloaders returns batches in the same order.
> [timeseries] Use different random seed for each model

- docs/tutorials/multimodal/document_prediction/pdf_classification.ipynb
- multimodal/setup.py
- multimodal/src/autogluon/multimodal/data/process_document.py
[3800](https://github.com/autogluon/autogluon/issues/3800)
Check if poppler is installed and in PATH. If so, get the DPI and convert the PDF with pdf2image.
Adds an optional dependency pdf2image, which can be installed in place of PyMuPDF.
> Optionally use Poppler/Pdf2Image for PDF Image Conversion

- multimodal/src/autogluon/multimodal/data/process_text.py
- After text augmentation, the text may become a list. TypeError will be raised when calling "tokenizer.encode".
> [AutoMM] Fix a bug of text augmentation.

- multimodal/src/autogluon/multimodal/models/clip.py
- Fix the bug which results in returning a tensor with NaN values when image data is absent.
> [AutoMM] Fix a bug of CLIP model's image feature normalization.

- core/src/autogluon/core/calibrate/_decision_threshold.py
- core/src/autogluon/core/trainer/abstract_trainer.py
- core/tests/unittests/calibrate/test_decision_threshold.py
- tabular/src/autogluon/tabular/learner/abstract_learner.py
- tabular/src/autogluon/tabular/predictor/predictor.py
Adds `secondary_decision_thresholds` argument to decision threshold calibration.
This enables a 2nd-round fine-grained search of the optimal threshold.
In total this is 25% faster with 10x finer granularity than the previous implementation.
> [tabular] Add secondary_decision_thresholds to calibrate_decision_threshold

- core/src/autogluon/core/metrics/__init__.py
- core/tests/unittests/metrics/test_metric_kwargs.py
- core/tests/unittests/metrics/test_metrics.py
- docs/tutorials/tabular/advanced/tabular-custom-metric.ipynb
- tabular/src/autogluon/tabular/predictor/predictor.py
- Add "auto" option for calibrate_decision_threshold that sets to True for valid metrics in Binary Classification, otherwise False.
- Improve Scorer information on knowing if metrics are for regression or classification tasks (via the new `needs_class` property). This is important because while we technically can run metrics like root_mean_squared_error through decision_threshold_calibration and not crash, it would not lead to the intended functionality. With `needs_class`, we know that RMSE is not valid for threshold calibration and avoid it when `calibrate_decision_threshold="auto"`.
- In a future PR I intend to switch `calibrate_decision_threshold` to `"auto"` as the new default in TabularPredictor.
By submitting this pull request, I …
> [tabular] Add "auto" option for calibrate_decision_threshold

- tabular/src/autogluon/tabular/predictor/predictor.py
- We are validating the `calibrate_decision_threshold` inside `fit` (L974). And then calling the validation function again inside `_post_fit`.
- Since `fit` calls `_post_fit`, there's no need to call the validation function again.
- This won't improve much, but the duplicated call is unnecessary.
> [tabular] Remove unnecessary duplicate call to `_validate_calibrate_decision_threshold`

- timeseries/src/autogluon/timeseries/predictor.py
*Issue #, if available:* Fixes #4012
- Currently, predictor.fit() fails is `prediction_length` is provided as a `float` instead of `int`. This PR ensures that `prediction_length` is always stored as an `int`.
> [timeseries] Ensure that prediction_length is stored as an integer

- multimodal/src/autogluon/multimodal/configs/data/default.yaml
- multimodal/src/autogluon/multimodal/configs/model/default.yaml
- multimodal/src/autogluon/multimodal/configs/optimization/default.yaml
- multimodal/src/autogluon/multimodal/learners/ner.py
- Not to convert the categorical features to text.
- Use text augmentation.
- Increase the number of training epochs.
> [AutoMM] Modify the default of basic fine-tuning tricks

- timeseries/src/autogluon/timeseries/models/autogluon_tabular/mlforecast.py
Tabular forecasting models would occasionally fail when a non-boolean known real covariate was mistakenly interpreted as a boolean covariate.
MWE:
```python
from autogluon.timeseries import TimeSeriesPredictor
N = 30
df = pd.DataFrame(
{
"item_id": ["A"] * N,
"timestamp": pd.date_range("2020-01-01", freq="D", periods=N),
"target": np.random.normal(size=N),
"feat": np.tile([5, 0, 0], int(N/3)),
}
)
predictor = TimeSeriesPredictor(known_covariates_names=["feat"]).fit(df, hyperparameters={"RecursiveTabular": {}})
```
This code will fail with the following exception
```
Warning: Exception caused RecursiveTabular to fail during training... Skipping this model.
"['__scaled_feat'] not in index"
```
This happens because during `fit()`, the feature `feat` is interpreted as …
> [timeseries] Fix tabular models sometimes failing because of a bug in preprocessing logic

- timeseries/src/autogluon/timeseries/models/autogluon_tabular/mlforecast.py
- timeseries/tests/unittests/models/test_mlforecast.py
*Issue #, if available:* Fixes #4133
- Fix loading of Tabular models failing if predictor moved to a different directory. Now the path of the Tabular predictor is generated at runtime based on the model path.
> [timeseries] Fix loading of Tabular models failing if predictor moved to a different directory

- timeseries/src/autogluon/timeseries/trainer/abstract_trainer.py
- timeseries/tests/unittests/test_predictor.py
*Issue #, if available:* Fixes #4183 #4195
- Currently there is a bug in cached prediction logic that occurs if we re-use a directory where a predictor has been trained before. Specifically, the trainer tries to load some metadata for each model mentioned in the `cached_predictions.pkl` dictionary. However, if the model was trained by the old predictor (but isn't trained by the new predictor), this will result in an error.
- We fix this problem by making sure that the cached predictions are deleted whenever a new trainer is created.
> [timeseries] Fix cached predictions error when predictor saved to directory with an existing predictor

- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/models/abstract/model_trial.py
- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- core/src/autogluon/core/models/ensemble/fold_fitting_strategy.py
- core/src/autogluon/core/trainer/abstract_trainer.py
- core/src/autogluon/core/utils/utils.py
- tabular/src/autogluon/tabular/learner/default_learner.py
Resolves #4162 
- add infer throughput logging, this implementation specifically introduces no overheads by avoiding calling predict separately, instead calculating the throughput at the same time as the score is being calculated for efficiency.
- code cleanup / code dedupe
- added additional method documentation
Mainline:
```
AutoGluon training complete, total runtime = 21.17s ... Best model: WeightedEnsemble_L2
```
This PR:
```
AutoGluon training complete, total runtime = 21.17s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 23766.6 rows/s (1500 batch size)
```
> [tabular] add infer throughput logging

- timeseries/src/autogluon/timeseries/models/chronos/model.py
- timeseries/tests/conftest.py
- Use `autogluon/chronos-t5-*` path to load Chronos models
> [timeseries] Use AutoGluon forks of Chronos models

- timeseries/src/autogluon/timeseries/models/chronos/pipeline.py
Fixes off by one error: https://github.com/amazon-science/chronos-forecasting/pull/73/files
> [timeseries] fix off-by-one bug in Chronos inference

- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/tests/unittests/test_tabular.py
- timeseries/src/autogluon/timeseries/predictor.py
Resolves #4161 
- Previously AutoGluon's TabularPredictor and TimeSeriesPredictor would save a file named `__version__` that contained the AutoGluon version as a string at the time of saving. However, Kaggle doesn't allow files named `__version__` to be uploaded for an unknown reason.
- This PR renames the file to `version.txt`, while keeping backwards compatibility.
> [tabular, timeseries] Rename cached version file to `version.txt` from `__version__`

- tabular/src/autogluon/tabular/learner/default_learner.py
- tabular/src/autogluon/tabular/predictor/predictor.py
Resolves #4148
- Overhauled the logging for Dynamic Stacking to provide more useful information.
- Added option to show ray logs during dynamic stacking: `force_ray_logging=True`.
- Added extra type hints.
- Moved system info logging to earlier in `fit` so it is logged prior to Dynamic Stacking.
- Added exception handling if dynamic stacking errors (for example, having negative time remaining after preprocessing).
This PR:
```
DyStack is enabled (dynamic_stacking=True). AutoGluon will try to determine whether the input data is affected by stacked overfitting and enable or disable stacking as a consequence.
This is used to identify the optimal `num_stack_levels` value. Copies of AutoGluon will be fit on subsets of the data. Then holdout …
```
> [tabular] Dynamic Stacking Logging Enhancement

- tabular/src/autogluon/tabular/predictor/predictor.py
Resolves #4196 
Resolves #3870
- Fix dynamic_stacking hanging with num_gpus>0
- Refer to the root cause here: https://docs.ray.io/en/latest/ray-core/tasks/nested-tasks.html#yielding-resources-while-blocked
TODO in follow-up PR: #4214 
Details:
Seems like nested ray jobs don't properly handle `num_gpus`.
For example:
```
sub_fit_caller = _ds_ray.remote(max_calls=1)(_sub_fit)
sub_fit_caller.options(num_cpus=num_cpus, num_gpus=1).remote(...)
```
Inside this `_sub_fit` call in ray, if we try to launch nested ray jobs, such as using `num_gpus=1` to fit a fold model, it will deadlock.
This is because the parent call already reserved the `num_gpus=1`, and thus there are no more GPU resources available to launch the nested job that requires GPU …
> Fix dynamic_stacking hanging with num_gpus>0

- tabular/src/autogluon/tabular/models/lr/lr_model.py
- Disable sklearnex for LR models due to performance degradation
- Unsure what version of sklearnex started causing this, but it is better to disable by default until we find a fix.
Version: scikit-learn-intelex-2024.4.0
Dataset: AdultIncome
```
model  score_test  score_val eval_metric
0            LinearModel    0.902293   0.904318     roc_auc
1  LinearModel_SKLEARNEX    0.863535   0.873544     roc_auc
```
> [tabular] Disable sklearnex for LR models due to performance degradation

- tabular/src/autogluon/tabular/models/lr/lr_model.py
- When `can_refit_full` tag was added, I forgot to add the tag to linear models. This meant we were skipping refit and using the first fold model, which gives slightly worse results that doing a proper refit.
- This PR enables LinearModels to do the refit.
- Because we don't yet use LinearModels in default portfolios, this doesn't impact the normal user experience.
Example on AdultIncome dataset:
Mainline:
```
model  score_test  score_val eval_metric
0          LinearModel_FULL   -0.352494  -0.326698    log_loss
1               LinearModel   -0.352494  -0.326698    log_loss
```
This PR:
```
model  score_test  score_val eval_metric
0          LinearModel_FULL   -0.351792        NaN    log_loss
1               LinearModel   -0.352380 …
```
> [tabular] Add refit_full support for LinearRegression

- timeseries/src/autogluon/timeseries/models/autogluon_tabular/mlforecast.py
- Make sure that the fallback model uses the correct values for `target` and `quantile_levels`.
> [timeseries] Use correct target and quantile_levels in fallback model for MLForecast

- pyproject.toml
- Ignore "SME" in codespell, false positive, was causing codespell to fail for timeseries.
> [codespell] Ignore "SME"

- common/src/autogluon/common/utils/utils.py
- core/src/autogluon/core/hpo/ray_hpo.py
- docs/whats_new/index.md
- docs/whats_new/v1.1.1.md
- tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
Resolves #4186 
- Fix HPO crash NN_TORCH, FASTAI
- Ray 2.7+ requires absolute path for `storage_path`, so I've updated the code to do so.
- Also fixed incorrect save location for `model-internals.pkl` in FastAI model, which previously was saved outside of the intended directory of the model artifact (`"FastAImodel-internals.pkl"` -> `"FastAI/model-internals.pkl"`).
- Added extra logging for incompatible version loading, to make it even more explicit that users should not do this.
- Added note in v1.1.1 release notes on backwards incompatibility: The FastAI change is backwards incompatible, if users try to load an old artifact, it will fail to find `model-internals.pkl`.
By submitting this pull request, I confirm that you can use, modify, …
> [tabular] Fix HPO crash NN_TORCH, FASTAI

- core/src/autogluon/core/trainer/abstract_trainer.py
- Fix logging verbosity of inference throughput
- It was accidentally set to 30 (verbosity>=1) instead of 15 (verbosity>=3)
> [tabular] Fix logging verbosity of inference throughput

- docs/tutorials/timeseries/forecasting-model-zoo.md
- timeseries/setup.py
- timeseries/src/autogluon/timeseries/models/__init__.py
- timeseries/src/autogluon/timeseries/models/gluonts/__init__.py
- timeseries/src/autogluon/timeseries/models/gluonts/torch/models.py
- timeseries/src/autogluon/timeseries/models/presets.py
- timeseries/tests/smoketests/test_all_models.py
- timeseries/tests/unittests/models/test_gluonts.py
- Bump GluonTS dependency to v0.15.1
- Add wrapper for the `TiDE` model
> [timeseries] Upgrade GluonTS to v0.15.1

- features/src/autogluon/features/generators/astype.py
- Add detailed exception logging to AsTypeFeatureGenerator if the data at test time cannot be successfully converted to the expected dtype.
Example output when switching `age` column from int to a string column at test time in AdultIncome:
```
Exception encountered in AsTypeFeatureGenerator ... Please check if feature data types differ between train and test (via df.dtypes).
Exception breakdown by feature:
feature      status dtype_input   dtype_to_convert_to                                          exception
0              age  ValueError      object                 int64  invalid literal for int() with base 10: ' Priv...
1        workclass     Success      object                object                                               None
2 …
```
> [features] Add AsType detailed exception logging

- features/src/autogluon/features/generators/astype.py
- Make AsType exception logging handle all exception types, instead of just ValueError. For example, NaNs can lead to exceptions types such as `IntCastingNaNError`, which previously wouldn't benefit from the improved exception logging. 
> [features] Make AsType exception logging handle all exception types

- tabular/src/autogluon/tabular/models/lgb/lgb_utils.py
- Fix LightGBM multiclass custom metrics
- Previously they either crashed or computed the metric incorrectly.
- This is likely because the code that does this is >4 years old, and LightGBM probably changed how their internal logic worked at some point.
> [tabular] Fix LightGBM multiclass custom metrics

- CI/docker/Dockerfile.cpu-inference
- CI/docker/Dockerfile.cpu-training
- CI/docker/Dockerfile.gpu-inference
- CI/docker/Dockerfile.gpu-training
- CI/docker/full_install_image.sh
The original pytorch2.1 sagemaker base images installs `torchaudio` 2.1.x, however,  AutoGluon master installs `torch` 2.2.x will introduce incompatibility issues. Updating the sagemaker base image version would resolve this issue.
> update sagemaker base images to use pytorch 2.2

- core/src/autogluon/core/calibrate/conformity_score.py
*Issue #, if available:* Fixes #4268
- Ensure that `y_pred_val` is a `np.ndarray` instead of a `pd.DataFrame`.
> [tabular] Fix indexing error in compute_conformity_score

- tabular/src/autogluon/tabular/models/lgb/lgb_model.py
- tabular/tests/conftest.py
- tabular/tests/unittests/models/test_lightgbm.py
Resolves #4270 
- Fix LightGBM quantile predict_proba dtype from pd.DataFrame to np.ndarray
- Add unit test assertion that return types are np.ndarray for model.predict and model.predict_proba
> [tabular] Fix LightGBM quantile predict_proba dtype

- features/src/autogluon/features/generators/one_hot_encoder.py
- Fix RuntimeWarning in LinearModel
- From what I can tell the RuntimeWarning is harmless, I can't find a situation where it is doing something incorrectly.
- @LennartPurucker's explanation below provides a good hypothesis for what is going on. Because of this, I will opt to silence the warning instead of reimplementing the logic.
RuntimeWarning:
```
/opt/conda/envs/ag-111-310/lib/python3.10/site-packages/pandas/core/arrays/categorical.py:1664: RuntimeWarning: invalid value encountered in cast
return np.asarray(ret, dtype)
```
> [tabular] Fix RuntimeWarning in LinearModel

- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/models/ensemble/fold_fitting_strategy.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/tests/conftest.py
- tabular/tests/unittests/edgecases/test_edgecases.py
Adds additional checks to ensure CPU and GPU settings are valid.
- raise TypeError if num_cpus and num_gpus are invalid types.
- raise ValueError if num_cpus<1
- raise ValueError if num_gpus<0
- Fixes a cryptic failure caused when passing `num_cpus` as a float that could be converted to an int such as `12.0`, which will fail the process but not provide a useful error message to understand the root cause. Now it will fail immediately stating that `num_cpus` must be an int.
> [tabular] Validate CPU/GPU settings

- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/tests/unittests/test_tabular.py
- Add readable error message for invalid models in persist
```
train_data = pd.read_csv('https://autogluon.s3.amazonaws.com/datasets/Inc/train.csv')
"GBM": {},
}
predictor = TabularPredictor(
label=label,
)
predictor = predictor.fit(
train_data=train_data,
hyperparameters=hyperparameters,
)
predictor.persist(["abc"])
```
```
ValueError: Invalid models specified. The following models do not exist:
['abc']
Valid models:
['LightGBM', 'WeightedEnsemble_L2']
```
```
networkx.exception.NetworkXError: The node abc is not in the digraph.
``` …
> [tabular] Add readable error message for invalid models in persist

- core/src/autogluon/core/data/label_cleaner.py
- core/src/autogluon/core/metrics/__init__.py
- core/src/autogluon/core/models/abstract/abstract_model.py
- core/tests/unittests/metrics/test_metrics.py
- docs/tutorials/tabular/advanced/tabular-custom-metric.ipynb
- tabular/src/autogluon/tabular/learner/abstract_learner.py
- tabular/src/autogluon/tabular/learner/default_learner.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/tests/unittests/data/test_label_cleaner.py
- Add roc_auc_ovo metrics
- Add roc_auc_ovr metrics
- Remove roc_auc_ovo_macro from binary metrics (not a binary metric) 
- Raise exception if inferred problem_type mismatches eval_metric.
- Improve logging when metric related errors occur (invalid metric specified)  
- Fix edge-case crash / incorrect metric calculation in multiclass when rare classes are dropped at fit time and then leaderboard is called with those rare classes and extra_metrics specified.
TODO:
> [tabular] Add roc_auc_ovo / ovr

- tabular/src/autogluon/tabular/learner/abstract_learner.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- Improve logging for invalid label when problem_type is not specified by user
```
KeyError: "Label column 'target' is missing from training data. Training data columns: ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country', 'class']"
```
```
KeyError: 'target'
```
> [tabular] Improve logging for invalid label

- timeseries/src/autogluon/timeseries/predictor.py
*Issue #, if available:* Fixes: #4297
- Fix typo in dataset statistics reporting in `TimeSeriesPredictor.fit`
> [timeseries] Fix incorrectly logged tuning data size

- timeseries/setup.py
- timeseries/src/autogluon/timeseries/models/local/statsforecast.py
- timeseries/src/autogluon/timeseries/models/presets.py
- timeseries/tests/unittests/models/test_local.py
**Do not merge until after v1.1.1 release**
Bump StatsForecast version to v1.7. 
> [timeseries] bump statsforecast version

- common/src/autogluon/common/features/feature_metadata.py
- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/models/ensemble/stacker_ensemble_model.py
- core/src/autogluon/core/trainer/abstract_trainer.py
- features/tests/features/test_feature_metadata.py
- tabular/tests/unittests/models/advanced/test_stack_feature_usage.py
- Fix a long standing major bug where L2+ stacker models that are not weighted ensembles will not respect the `max_models` and `max_models_per_type` parameters, and will instead use all base models during fit.
- This bug has been present forever, since the original code was written, but only started majorly impacting AutoGluon in v1.0+ with the introduction of Zeroshot-HPO.
- Fixing this should lead to faster training and inference times for stack layers, and a potential quality improvement.
Results: 3x inference speedup with no noticeable model quality drop:
TODO:
Follow-up PRs:
> [tabular] Fix Stacker max_models logic

- multimodal/src/autogluon/multimodal/data/infer_types.py
According to the documentation (https://auto.gluon.ai/stable/tutorials/multimodal/advanced_topics/customization.html#data-image-missing-value-strategy) and process_image.py (autogluon/multimodal/src/autogluon/multimodal/data
/process_image.py), Autogluon uses an image with zero pixels if an image is missing. There is a warning in infer_types.py (multimodal/src/autogluon/multimodal/data/infer_types.py) that says the default behavior is to skip samples, which I updated.
> Update infer_types.py to say the default handling is zero

- core/src/autogluon/core/trainer/abstract_trainer.py
- tabular/src/autogluon/tabular/learner/default_learner.py
This is a minimal change to the code to avoid a divide-by-zero error that occurs when a tiny test dataset is used with a high-speed prediction model. 
This edge case occurs in some of my tests for an AutoGluon integration. 
The PR provides a simple workaround for the bug. This also depends highly on the machine. 
Here is the exact error that I run into very often with CatBoost in my tests:
```bash
self.save_trainer(trainer=trainer)
time_end = time.time()
self._time_fit_training = time_end - time_preprocessing_end
self._time_fit_total = time_end - time_preprocessing_start
log_throughput = ""
if trainer.model_best is not None:
predict_n_time_per_row = trainer.get_model_attribute_full(model=trainer.model_best, attribute="predict_n_time_per_row")
predict_n_size = …
```
> [Tabular] Avoid Edge Case Divison By Zero Error

- timeseries/src/autogluon/timeseries/models/local/statsforecast.py
- Since we upgraded to StatsForecast 1.7.0, we can remove the cap `season_length <= 24` that was necessary for older version (fixed by https://github.com/Nixtla/statsforecast/pull/384)
> [timeseries Enable season_length > 24 in ETS models

- tabular/src/autogluon/tabular/models/rf/rf_model.py
- Remove sklearnex RF logic that raises exception
- Previously this code worked and halved the disk usage / memory usage of the RandomForest model.
- Now the code crashes, due to a change at some point in sklearnex. Therefore, we have to remove the code.
> [tabular] Remove sklearnex RF logic that raises exception

- tabular/src/autogluon/tabular/models/rf/compilers/onnx.py
Previously, the ONNX compilation code would crash if RandomForest's model directory was not yet created. This didn't trigger in normal usage, but it does if we want to compile prior to saving the original model. This PR fixes this by ensuring the parent directory is created.
> [tabular] Fix file path for RF ONNX

- core/setup.py
Tests in `core` failed due to a missing `flake8` dependency.
I added `flake8` to the test requirements in `core/setup.py`.
> [core] Add `flake8` to the `[test]` requirements in `core/setup.py`

- core/src/autogluon/core/models/abstract/abstract_model.py
- tabular/tests/unittests/models/test_tabular_nn.py
- Add `ag.compile` parameter to models
- This allows the user to specify model compilation to occur directly after the model is fit, rather than in a separate `predictor.compile` call.
> [tabular] Add `ag.compile` parameter to models

- tabular/src/autogluon/tabular/trainer/auto_trainer.py
-  Fix exception when >20 configs present in medium quality preset
- The old hyperparameters configs had single models be in a special format where they aren't in a list, such as:
```
{
'XGB': {},
}
```
This will cause an exception if logged in an edge-case where there are more than 20 configs in the hyperparameters dict.
This impacts medium and good quality presets.
This PR fixes this issue by converting to list before logging.
> [tabular] Fix exception when >20 configs present in medium quality preset

- core/src/autogluon/core/models/greedy_ensemble/ensemble_selection.py
The current implementation of the greedy ensembling is unnecessarily slowed down, especially for large ensemble_sizes, as the `weighted_ensemble_prediction` computation here
https://github.com/autogluon/autogluon/blob/f5c7b7400596e1449fad2b4107fde55809a09bac/core/src/autogluon/core/models/greedy_ensemble/ensemble_selection.py#L113-L125
is done in every iteration of the loop from scratch. This could be done on a rolling basis instead, which would reduce the complexity of this function from quadratic in the ensemble size to linear.
This PR changes the current implementation to instead accumulate into the `ensemble_prediction` at each iteration. On a small local example I see a decrease in the ensembling time from 1.4s to 0.9s for the …
> [core] Speed up `EnsembleSelection._fit`

- core/src/autogluon/core/hpo/executors.py
- core/src/autogluon/core/hpo/ray_hpo.py
- core/src/autogluon/core/ray/resources_calculator.py
Resolves #4375
- Fix exception in HPO when only specifying one of `num_cpus` or `num_gpus` in `ag_args_fit`.
- Fix exception in HPO for FASTAI and NN_TORCH when `num_cpus` specified in `ag_args_fit`, caused by RayTune converting int to float for `num_cpus`, which leads to a failure in a downstream type assertion as reported in #4375.
For example, in mainline the following with raise an exception:
```python
train_data = pd.read_csv('https://autogluon.s3.amazonaws.com/datasets/Inc/train.csv')
subsample_size = 1000  # subsample subset of data for faster demo, try setting this to much larger values
if subsample_size is not None and …
```
> [tabular] Fix exception in HPO when only specifying one of `num_cpus`/`num_gpus`

- core/src/autogluon/core/calibrate/temperature_scaling.py
- core/src/autogluon/core/trainer/abstract_trainer.py
Heyho,
I have noticed that the predictions of my best model were often quite suboptimal compared to other models for metrics that were affected by temperature scaling. 
After looking more into it, I believe I found a bug and two crucial improvements to the temperature scaling logic. 
The proposed PR now does the following:
1. We take the best-found temperature instead of the last temperature when tuning temperature. 
2. We double-check that temperature improves performance on the target metric.
I am certain that 1. is very important, although it might overfit more.
For 2. it is a bit more complicated, as it is sometimes beneficial to even accept better calibration if it does not improve the target metric on validation data. Moreover, I am not too sure that my code works in all cases of …
> [Tabular,Core] Fix Temperature Scaling

- tabular/src/autogluon/tabular/predictor/predictor.py
This PR enables users to make AutoGluon raise an error if no models are trained successfully during `fit`. 
Without this, people sometimes write their own code to catch this or ignore it and then believe AutoGluon is broken, although it is most likely a result of a broken environment or their memory being insufficient. 
So far, this defaults to False, but I would argue this should default to True in the future. 
> [Tabular] Support for Raising an Error When No Models Were Trained Successfully During fit()

- core/src/autogluon/core/calibrate/temperature_scaling.py
- core/src/autogluon/core/trainer/abstract_trainer.py
- Skip temperature scaling if zero or negative temperature. A negative temperature could be selected if the model has a worse validation score than a model that predicts a constant `0.5` value. This can happen when there are very few rows of validation data and is an artifact of validation overfitting.
- increase learning rate by 10x to make convergence faster, reduce max iters by 5x to compensate. We can afford a more aggressive learning rate now that we pick the best iteration instead of the final iteration, so divergence is less problematic.
> Skip temperature scaling if negative temperature, increase learning rate

- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/tests/unittests/models/test_dummy.py
- Switch the default behavior of TabularPredictor to raise a RuntimeError if no models were successfully fit in a fit call. Most users would prefer an error to be raised in this scenario, as not having an error raise may confuse them into thinking a model was fit successfully.
> [tabular] raise_on_no_models_fitted=True

- timeseries/src/autogluon/timeseries/models/autogluon_tabular/mlforecast.py
*Issue #, if available:* Fixes #4369
- Fixed the off-by-one error in the length check for DirectTabular when determining if a fallback model should be used.
> [timeseries] Fix off-by-one error in DirectTabular length check

- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/tests/unittests/test_predictor.py
*Issue #, if available:* Fixed #4291
- Raise an informative error message if an invalid path is provided to `TimeSeriesPredictor.load`
> [timeseries] Fix exception raised when invalid path provided

- core/src/autogluon/core/metrics/__init__.py
Unfortunately, so far in AutoGluon, when using the multiclass ROC AUC metric via the string key, the call to sklearn has been misconfigured. 
Instead of using `macro`, `weighted` has been passed to sklearn's `average` argument of ROC AUC.
This is unexpected by default and also occurs when explicitly using the `macro` string key for the metric.
This bug resulted from re-using a previously initialized loop variable, which was set to `weighted` after a prior loop had finished.
I replaced the variable with an explicit statement, as there is no need for a variable. 
> [Tabular] Fix ROC AUC Average for Macro is Macro

- tabular/src/autogluon/tabular/predictor/predictor.py
- Add `mcc` metric to eval_metric docstring. It was previously missing.
> [tabular] Add `mcc` metric to eval_metric docstring

- core/src/autogluon/core/utils/feature_selection.py
- docs/tutorials/tabular/tabular-quick-start.ipynb
Resolves #4390
- Fix crash on Windows when feature pruning is enabled due to numpy random integer generator returning a different dtype int on Windows compared to Linux/MacOS. Now it is consistently converted to Python int.
> [tabular] Fix feature pruning crash on Windows

- core/src/autogluon/core/callbacks/__init__.py
- core/src/autogluon/core/callbacks/_abstract_callback.py
- core/src/autogluon/core/callbacks/_early_stopping_callback.py
- core/src/autogluon/core/callbacks/_early_stopping_ensemble_callback.py
- core/src/autogluon/core/callbacks/_example_callback.py
- core/src/autogluon/core/trainer/abstract_trainer.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/src/autogluon/tabular/trainer/auto_trainer.py
- tabular/tests/unittests/callbacks/test_callbacks.py
- Add initial callbacks support to TabularPredictor
- Callbacks allow users to inject custom logic into the training process, and theoretically allow the user to completely override the training logic with their own custom logic.
Example Code:
```
from autogluon.core.callbacks import EarlyStoppingCallback
train_data = pd.read_csv('https://autogluon.s3.amazonaws.com/datasets/Inc/train.csv')
callbacks = [EarlyStoppingCallback(patience=3)]
predictor = TabularPredictor(label=label).fit(train_data=train_data, callbacks=callbacks)
```
Example Output:
```
...
User-specified callbacks (1): ['EarlyStoppingCallback']
Fitting 13 L1 models …
```
> [tabular] Add initial callbacks support

- core/src/autogluon/core/_setup_utils.py
- multimodal/src/autogluon/multimodal/data/preprocess_dataframe.py
*Issue #, if available:* https://github.com/autogluon/autogluon/issues/4331
Creating deep copy of the DataFrame, which allows writable buffer to be created.
This is needed for `1.4.1 < scikit-learn < 1.5.0`, the versions `1.4.0` and `1.5.1` do not need a writable buffer.
If there is no writeable buffer, the function - `_is_pandas_df_or_series()` in `scikit-learn` breaks, note that this function is present in `scikit_learn` versions ranging from `1.4.1` to `1.5.0`, but is fixed by the maintainers in the `1.5.1` release - https://github.com/scikit-learn/scikit-learn/pull/29018.
Hence, the deep copy solution is to fix **AutoMM HPO + respective tests** for `scikit-learn` versions ranging from `1.4.1` to `1.5.0` and is not needed for `1.5.1`. We still need this …
> Upgrade scikit-learn to 1.5.1

- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/models/ensemble/stacker_ensemble_model.py
- core/src/autogluon/core/trainer/abstract_trainer.py
- core/src/autogluon/core/utils/exceptions.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- Add `valid_stacker` and `use_orig_features` options
- `valid_stacker` allows to disable model in L2+ layers
- `use_orig_features="never"` allows to disable model in L1 layer.
- Improved exception logging in HPO
- Added docstrings
> [tabular] Add `valid_stacker` and `use_orig_features` options

- tabular/src/autogluon/tabular/learner/abstract_learner.py
- Fix incorrect return type in `predict_multi` for regression
- Previously would return np.ndarray when `as_pandas=True` when it should return `pd.Series`.
> [tabular] Fix incorrect return type in `predict_multi` for regression

- multimodal/src/autogluon/multimodal/learners/base.py
Not able to reproduce the bug in https://github.com/autogluon/autogluon/issues/4428.
But this should fix it.
> [AutoMM] Fix Missing Validation Metric While Resuming A Model Failed At Checkpoint Fusing Stage

- .github/workflows/benchmark-command.yml
- .github/workflows/continuous_integration.yml
- .github/workflows/platform_tests-command.yml
- .github/workflows/slash_command_dispatch.yml
Update the PAT to have the correct scopes for runners from command triggered CICD tests such as `/platform_tests`
> Updated the PAT secrets used for CICD

- tabular/src/autogluon/tabular/predictor/predictor.py
- Make num_bag_sets == 1 by default.
- Ever since v1.0, we did not use num_bag_sets > 1 in any of the presets, however if the user specified bagging manually and set a time limit, it would actually be set to 5 which most users would not want since it would 5x the runtime for minimal gain.
- This change has no impact when presets are used.
> [tabular] Set num_bag_sets to 1 by default

- core/src/autogluon/core/trainer/abstract_trainer.py
- Fix crash when refit_full is specified and no cloned refit models exist and there is no weighted ensemble.
- Bug first introduced in #4327 
For example, the following would crash:
```
predictor = TabularPredictor(...).fit(
..., presets="high_quality", hyperparameters={"GBM": {}}, fit_weighted_ensemble=False,
)
```
> [tabular] Fix refit crash

- core/src/autogluon/core/utils/utils.py
- core/tests/unittests/utils/test_utils.py
- Add `train_size` argument to `generate_train_test_split`. This allows the user to specify the train size directly, akin to the argument `train_size` in sklearn's `train_test_split`.
- Add `stratify` argument to `generate_train_test_split`. This allows the user to specify the stratification logic, akin to the argument `stratify` in sklearn's `train_test_split`.
- Made `problem_type` argument optional. Defaults to the equivalent of `regression`.
- Added extensive unit tests
- This logic is partly preparation for resolving #4453 in a future PR, as we need the `stratify` argument.
> [core] Enhance generate_train_test_split

- core/src/autogluon/core/utils/utils.py
A recent merged commit leads to a import error with Python 3.8 due to the usage of `|` type hints, which were introduced in Python 3.9. This PR fixes this by adding `from __future__ import annotations` for backwards compatibility.
> Fix py38 import

- .github/workflow_scripts/lint_check.sh
- timeseries/src/autogluon/timeseries/learner.py
- timeseries/src/autogluon/timeseries/models/presets.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/src/autogluon/timeseries/trainer/abstract_trainer.py
- timeseries/tests/unittests/test_predictor.py
*Issue #, if available:* #4152
- Two new arguments to `TimeSeriesPredictor.leaderboard()`:
- `extra_metrics` allows computing additional metrics on the test set
- `extra_info` returns hyperparameters selected by hyperparameter tuning for each model
> [timeseries] Align TimeSeriesPredictor.leaderboard API with TabularPredictor

- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/trainer/abstract_trainer.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/tests/unittests/models/test_advanced.py
Resolves #3871
Follow-up #4496 
- Make refit_full respect user `num_cpus` and `num_gpus`.
- Make WeightedEnsemble respect user `num_cpus` and `num_gpus`.
- User can now check the resources used to fit each model via `predictor.info()`
Now when the user specifies refit_full along with resource constraints, those resource constraints are respected during refit_full:
```python
predictor = TabularPredictor(label='class').fit(
train_data=train_data, num_cpus=17, num_gpus=0, refit_full=True
)
```
The above code would previously fit the original models with the constraints, and then during refit_full it would ignore the constraints. For example, if you had a GPU, it would forcibly use the GPU during refit.
With this PR, this is no longer the …
> [tabular] Make refit_full respect user `num_cpus` and `num_gpus`

- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/utils/utils.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- Various doc cleanup and improved type hinting.
- Made it easier for user to specify `positive_class` by making it a init arg in TabularPredictor rather than requiring it to be specified as a learner kwarg, which was hard to find.
> [tabular] Doc cleanup, add positive_class init arg

- .github/workflow_scripts/lint_check.sh
- examples/automm/memory_bank/memory_bank.py
- multimodal/src/autogluon/multimodal/learners/base.py
- multimodal/src/autogluon/multimodal/learners/matching.py
- multimodal/src/autogluon/multimodal/models/ft_transformer.py
- multimodal/src/autogluon/multimodal/models/mmdet_image.py
- multimodal/src/autogluon/multimodal/models/timm_image.py
- multimodal/src/autogluon/multimodal/utils/cache.py
- multimodal/src/autogluon/multimodal/utils/checkpoint.py
- multimodal/src/autogluon/multimodal/utils/cloud_io.py
- tabular/src/autogluon/tabular/models/fastainn/fastai_helpers.py
- tabular/src/autogluon/tabular/models/tab_transformer/tab_transformer_model.py
- tabular/src/autogluon/tabular/models/tabular_nn/torch/tabular_nn_torch.py
- tabular/src/autogluon/tabular/models/tabular_nn/torch/tabular_torch_dataset.py
This PR addresses the need for safe usage of `torch.save` and `torch.load` within the internal codebase. The main changes include:
1. **Inline Warning Mitigation**: Added `# nosec B614` comments to mitigate Bandit warnings for `torch.save` and `torch.load` usage in internal functions. This ensures that these functions are used safely and intentionally within the codebase.
2. **Remove Repo-Level Mitigation**: Removed the repo-level Bandit warning mitigation (`--skip B614`) to prevent accidental usage of `torch.save` and `torch.load` in external-facing APIs. This change ensures that any new usage of these functions will be flagged by Bandit, promoting safer coding practices.
> Add Bandit Warning Mitigation for Internal `torch.save` and `torch.load` Usage

- docs/install-cpu-pip.md
- docs/install-gpu-pip.md
- docs/install-mac-cpu.md
- docs/install.md
- full_install.sh
This change is a temporary measure to mitigate pip installation issues.
*Issue #, if available:* #4515
- Updated installation instructions to use uv instead of pip
- Added uv installation step in all installation documentation
- Replaced pip install commands with uv pip install
- Updated full_install.sh to check for uv and install it if not present
- Used uv for installing AutoGluon and its dependencies
This change addresses the recent installation failures reported in issue #4515, where users are encountering problems with onnx and optimum dependencies. By using uv, we aim to provide a more stable installation process until a permanent solution can be implemented. …
> [Master] Update installation instructions to use uv temporarily

- .github/workflow_scripts/lint_check.sh
- core/setup.py
- docs/install-cpu-pip.md
- docs/install-gpu-pip.md
- docs/install-mac-cpu.md
- docs/install.md
- full_install.sh
This change is a temporary measure to mitigate pip installation issues.
*Issue #, if available:* #4515
- Updated installation instructions to use uv instead of pip
- Added uv installation step in all installation documentation
- Replaced pip install commands with uv pip install
- Updated full_install.sh to check for uv and install it if not present
- Used uv for installing AutoGluon and its dependencies
This change addresses the recent installation failures reported in issue #4515, where users are encountering problems with onnx and optimum dependencies. By using uv, we aim to provide a more stable installation process until a permanent solution can be implemented. …
> [Stable] Update installation instructions to use uv temporarily

- core/setup.py
https://github.com/autogluon/autogluon/issues/4519
Source installation now works on every supported version of Python - 3.9, 3.10, 3.11.
> [Bug] Cap pyarrow to fix source installation issue

- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/tests/unittests/test_predictor.py
- Currently, calling `predictor.fit(..., num_val_windows=1, refit_every_n_windows=None)` raises an exception. This PR fixes the bug.
> [timeseries] Fix refit_every_n_windows=None raising an exception if num_val_windows=1

- features/src/autogluon/features/generators/drop_duplicates.py
- Speed up fitting time & reduce memory usage for `DropDuplicatesFeatureGenerator`
Benchmark results for a dataset with 47M rows, 7 features
```python
import time
from autogluon.features.generators import DropDuplicatesFeatureGenerator
df = pd.read_parquet("http://m5-benchmarks.s3.amazonaws.com/data/train/temporal.parquet")
print(len(df))
print(df.dtypes)
start = time.time()
gen = DropDuplicatesFeatureGenerator()
out = gen.fit_transform(df)
print(f"duration: {time.time() - start:.1f} s")
```
> [features] Speed up DropDuplicatesFeatureGenerator

- core/src/autogluon/core/trainer/abstract_trainer.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/tests/unittests/edgecases/test_edgecases.py
> [!CAUTION]
> This PR changes the default behavior **if** a user manually has set `num_bag_sets != 1`
This PR enables support for controlling when bagging is repeated in cross-validation.
I also suggest changing the default behavior for two reasons:
- it is very unintuitive that if a user increases the number of bag sets (i.e., repeats) under a time limit, they might not even see a change in the results due to the entire portfolio being fit first;
- if we have enabled repeats, it is likely more important to do more repeats than evaluate more models to avoid overfitting, especially for small data;
- the current default AutoGluon behavior does not change, as we have  `num_bag_sets == 1` since AutoGluon 1.0.
Happy to discuss this in more detail. 
---
By submitting this pull request, I …
> [tabular] Add support for controlling AutoGluon's repeated cross-validation behavior

- docs/install-cpu-pip.md
https://github.com/autogluon/autogluon/issues/4541
Fix the installation issue for CPU by adding `+cpu` tag
> add +cpu tag for cpu installation guide

- timeseries/src/autogluon/timeseries/models/chronos/model.py
#4544 
The MPS backend leads to bugs for Chronos in PyTorch 2.2 and 2.3. This PR disables all non-CUDA backends for Chronos.
> [timeseries] disable non-CUDA backends for chronos

- core/src/autogluon/core/utils/utils.py
- Fix rare crash that occurs when the label column is a categorical with categories defined that have 0 rows with that value. AutoGluon treats it as a missing label and crashes. This PR fixes this to ignore such categories.
- Added type hints
> Fix edgecase label crash

- tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
Fix FASTAI edge-case crash when a column contains only a single unique value + NaNs. This would lead to imputing NaNs as the single unique value, resulting in an undefined std deviation. When normalizing, if an unseen value is present in validation data, the loss will be NaN, causing an exception.
This crash occurred on two AMLB datasets: `KDDCup09_appetency` and `KDDCup09-Upselling` which contained many NaN values.
> [tabular] Fix FASTAI edgecase crash with NaN

- full_install.sh
- Fix full_install.sh to be editable
- Previously only `common` was editable.
- Added `--refresh` to ensure that the install still works across different days due to the date suffix in the version name.
> [install] Fix full_install.sh to be editable

- .github/actions/submit-job/action.yml
https://github.com/autogluon/autogluon/issues/4578
Broke by change https://github.com/autogluon/autogluon/pull/4462
Arg ($SOURCE_REF) submitted to AWS Batch containers is interpreted as string literal during CI `push` action - when commits getting merged into `master` or `stable` branch. 
```
[2024-09-16T22:38:57.563Z] jobId: fe2e76f5-8edc-466a-893b-d33b7b6550a6
[2024-09-16T22:38:57.563Z] jobQueue: CI-GPU
[2024-09-16T22:38:57.563Z] computeEnvironment: CI-GPU-3
[2024-09-16T22:38:57.566Z] Cloning into 'autogluon'...
[2024-09-16T22:38:59.370Z] fatal: couldn't find remote ref $SOURCE_REF
[2024-09-16T22:38:59.374Z] error: pathspec 'working' did not match any file(s) known to git
```
This does not materially affect `master` merge action but …
> [CI] Fix container checkouts incorrect branch

- .github/workflows/platform_tests-command.yml
- core/src/autogluon/core/_setup_utils.py
- docs/install.md
- multimodal/setup.py
- tabular/setup.py
- timeseries/setup.py
1. adds support for Python3.12
2. updated `pip install` to `uv pip install` for tests in order to speed up the installation and avoid the installation [issue](https://github.com/autogluon/autogluon/issues/4515) at the moment 
3. fixed platform tests (most of them except for TimeSeries tests that fail on MacOS)
> Support python3.12

- .github/workflows/benchmark_master.yml
Scheduling benchmark daily until v1.2. 
Will merge post AMLB and AG-Bench fixes.
Pending PRs to merge before his PR is merged - 
1. https://github.com/autogluon/autogluon-bench/pull/108
2. https://github.com/openml/automlbenchmark/pull/643
3. Until [2] is merged we are using https://github.com/autogluon/autogluon/pull/4603
> [CI] Schedule benchmark everday

- .github/workflow_scripts/env_setup.sh
New version of AG Bench requires s3fs to be installed otherwise CI Benchmark fails.
> [CI Benchmark] Add dependencies for AG Bench 0.4.4

- common/src/autogluon/common/utils/s3_utils.py
- Fix specifying None in upload_file prefix causing crash
> Fix specifying None in upload_file prefix

- common/src/autogluon/common/__init__.py
- common/src/autogluon/common/dataset.py
- common/src/autogluon/common/loaders/load_pd.py
- common/tests/unittests/test_dataset.py
- core/src/autogluon/core/__init__.py
- core/src/autogluon/core/dataset.py
- core/src/autogluon/core/utils/infer_utils.py
- docs/tutorials/tabular/advanced/tabular-multilabel.ipynb
- tabular/src/autogluon/tabular/__init__.py
- tabular/src/autogluon/tabular/predictor/interpretable_predictor.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- refactor TabularDataset so that it no longer is a subclass of a pandas DataFrame, but rather *is* a pandas DataFrame.
- This simplifies a lot of logic, such that we only need to consider input types for pandas DataFrame rather than for TabularDataset.
- This also fixes IDE visualizers such as PyCharm which wouldn't properly display TabularDataset because it didn't recognize it as a pandas DataFrame.
- The extra attribute that TabularDataset used to have was never used, so this change is backwards compatible.
- Updated docstrings and type hints in TabularPredictor to remove mention of TabularDataset and cleanup / improve existing type hints.
- Moved TabularDataset from `core` to `common`, since it only depends on pandas and …
> Refactor TabularDataset

- timeseries/src/autogluon/timeseries/dataset/ts_dataframe.py
*Issue #, if available:* Fixes #4257
- Make sure that the `TimeSeriesDataFrame` index is sorted before generating the train/test split.
> [timeseries] Ensure that TimeSeriesDataFrame index is sorted before train_test_split

- docs/tutorials/timeseries/forecasting-model-zoo.md
- timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
- timeseries/src/autogluon/timeseries/models/chronos/model.py
- timeseries/src/autogluon/timeseries/models/local/abstract_local_model.py
- timeseries/src/autogluon/timeseries/models/multi_window/multi_window_model.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/src/autogluon/timeseries/regressor.py
- timeseries/src/autogluon/timeseries/transforms/scaler.py
- timeseries/tests/conftest.py
- timeseries/tests/unittests/common.py
- timeseries/tests/unittests/models/test_models.py
- timeseries/tests/unittests/test_predictor.py
- timeseries/tests/unittests/test_regressor.py
Fixes #3508
- Add an option to fit a tabular regression model on the covariates & forecasting on the residuals of the tabular models. The relevant logic is incapsulated into the `CovariateRegressor` object.
> [timeseries] Add CovariatesRegressor for forecasting models

- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- timeseries/src/autogluon/timeseries/models/local/statsforecast.py
- Fix the bug where GluonTS models would modify known_covariates inplace, affecting other models
- Remove the initialization time for AutoARIMA, AutoETS and ARIMA models
> [timeseries] Fix inplace data modification by GluonTS models

- core/src/autogluon/core/metrics/__init__.py
- core/src/autogluon/core/metrics/score_func.py
- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/models/greedy_ensemble/ensemble_selection.py
- core/src/autogluon/core/trainer/abstract_trainer.py
- core/src/autogluon/core/utils/utils.py
- tabular/src/autogluon/tabular/learner/abstract_learner.py
Add `compute_metric` to replace `compute_weighted_metric`.
- Added docstring
- `compute_metric` is easier to use and less likely to be misused than `compute_weighted_metric`.
- Added `as_error` support
- Added `silent` support
- Added type hints
- Refactored AbstractModel and AbstractTrainer scorer methods to use `compute_metric`
- Refactored AbstractLearner to use `compute_metric`
- Refactored EnsembleSelection to use `compute_metric`
> Add `compute_metric`

- tabular/src/autogluon/tabular/models/tabular_nn/torch/tabular_nn_torch.py
- Fix Torch accidentally being imported immediately on `import autogluon.tabular`
> Fix Torch accidentally being imported immediately

- .github/workflow_scripts/env_setup.sh
AG-Bench does not install pyarrow by default which breaks the cleaning scripts.
Hence, adding the dependency.
> [Benchmark] Add PyArrow required by clean scripts

- core/src/autogluon/core/trainer/abstract_trainer.py
- docs/tutorials/tabular/tabular-indepth.ipynb
- tabular/src/autogluon/tabular/models/tabular_nn/utils/data_preprocessor.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- Set `calibrate_decision_threshold="auto"` by default in TabularPredictor, previously `False`.
- This massively improves results on `f1` and `balanced_accuracy` metrics for binary classification.
- Only enable calibrate_decision_threshold for accuracy if >=10000 validation rows, to avoid overfitting
- Only enable calibrate_decision_threshold if >=50 validation rows, to minimize the risk of picking extreme thresholds due to overfitting.
- [Major] Update `calibrate="auto"` to also have minimum validation row requirement.
- `calibrate` min val row for binary = 3000, multiclass = 500, quantile = 1000
- Huge improvements on small datasets for `log_loss` metric, refer to 2nd and 3rd benchmark.
- Update in-depth tutorial
- Fix sklearn warning …
>  [tabular] Set calibrate_decision_threshold="auto"

- timeseries/src/autogluon/timeseries/metrics/__init__.py
- timeseries/src/autogluon/timeseries/metrics/point.py
- timeseries/tests/unittests/test_metrics.py
- Add experimental `WCD` (Weighted Cumulative Discrepancy) forecasting metric
> [timeseries] Add weighted cumulative error forecasting metric

- docs/tutorials/multimodal/advanced_topics/index.md
Current Bug: Can't open metric tutorial in this page: https://auto.gluon.ai/dev/tutorials/multimodal/advanced_topics/index.html
> [AutoMM] Fix Index Typo in Tutorial

- timeseries/src/autogluon/timeseries/dataset/ts_dataframe.py
- timeseries/tests/unittests/test_ts_dataset.py
- Add method to convert a TimeSeriesDataFrame to a regular pd.DataFrame
> [timeseries] Add method to convert a TimeSeriesDataFrame to a regular pd.DataFrame

- timeseries/src/autogluon/timeseries/models/chronos/model.py
*Description of changes:* This PR fixes a problem that occurs on `torch <= 2.3` when fine-tuning Chronos models on CPU. Since the default optimizer is `adamw_torch_fused`, fine-tuning fails because the fused AdamW optimizer is not supported on `torch <= 2.3`. I tested this using the following snippet. 
```py
import torch
a = torch.rand(42, requires_grad=True)
b = ((a - 1) ** 2).mean()
optim = torch.optim.AdamW([a], fused=True)
optim.zero_grad()
b.backward()
optim.step()
```
It fails with the following error on `torch <= 2.3` but succeeds on `torch >= 2.4`. 
> RuntimeError: `fused=True` requires all the params to be floating point Tensors of supported devices: ['cuda', 'xpu', 'privateuseone'].
The fix in this PR is to default to `adamw_torch` instead of …
> [timeseries] Fix `fused=True` failure in Chronos fine-tuning on CPU

- docs/tutorials/timeseries/forecasting-model-zoo.md
- timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
- timeseries/src/autogluon/timeseries/models/autogluon_tabular/mlforecast.py
- timeseries/src/autogluon/timeseries/models/autogluon_tabular/transforms.py
- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- timeseries/src/autogluon/timeseries/models/local/abstract_local_model.py
- timeseries/src/autogluon/timeseries/models/multi_window/multi_window_model.py
- timeseries/src/autogluon/timeseries/transforms/__init__.py
- timeseries/src/autogluon/timeseries/transforms/covariate_scaler.py
- timeseries/src/autogluon/timeseries/transforms/target_scaler.py
- timeseries/tests/unittests/models/test_gluonts.py
- timeseries/tests/unittests/models/test_mlforecast.py
- timeseries/tests/unittests/models/test_models.py
- timeseries/tests/unittests/test_transforms.py
- Combine methods `preprocess` and `preprocess_known_covariates` into a single method. This simplifies certain types of preprocessing such as converting past_covariates into known_covariates using lags.
- Move GluonTS preprocessing logic into a standalone class `CovariateScaler` that can be used by any `AbstractTimeSeriesModel`
- Extend test coverage for the covariate scaling logic
> [timeseries] Move covariate scaling logic into a separate class

- timeseries/src/autogluon/timeseries/models/chronos/pipeline/chronos.py
*Description of changes:* This PR fixes incorrect use of `axis` and `keepdims` in `torch.Tensor.mean`.
> [timeseries] Fix `torch.Tensor.mean` use with incorrect kwargs

- timeseries/src/autogluon/timeseries/metrics/point.py
- timeseries/src/autogluon/timeseries/metrics/quantile.py
- timeseries/src/autogluon/timeseries/metrics/utils.py
- timeseries/src/autogluon/timeseries/models/autogluon_tabular/mlforecast.py
- timeseries/tests/unittests/test_metrics.py
- Fix a regression caused by the new scaler logic in `RecursiveTabularModel` introduced in #4460
- Make `_in_sample_abs_seasonal_error` and `_in_sample_squared_seasonal_error` public methods
> [timeseries] Fix incorrect scale of the quantile forecast for RecursiveTabular

- timeseries/tests/smoketests/test_all_models.py
- timeseries/tests/unittests/models/chronos/test_model.py
- timeseries/tests/unittests/models/test_local.py
- timeseries/tests/unittests/models/test_mlforecast.py
This PR reduces overall test time by ~30%, primarily by 
- reducing the test case grid in smoke tests
- removing expensive but unused local models from smoke and model tests
- removing some Chronos hyperparameter configs
> [timeseries] prune timeseries unit and smoke tests

- timeseries/src/autogluon/timeseries/models/chronos/model.py
*Description of changes:* This PR removes the evaluation logic from Chronos fine-tuning. When evaluation during fine-tuning is enabled, all evaluation-related decisions will be handled by `transformers`. 
> [timeseries] Remove eval logic from Chronos fit

- core/src/autogluon/core/models/abstract/model_trial.py
When skipping hpo, validation data was not used in the call to the model's fit method, which affected the printing during the training process and the evaluation of the trained model. I have corrected this issue.
> add val operation when skip hpo

- timeseries/src/autogluon/timeseries/configs/presets_configs.py
- timeseries/src/autogluon/timeseries/models/chronos/model.py
- timeseries/src/autogluon/timeseries/models/presets.py
- Currently, there is an inconsistency between the preset names (e.g., `bolt_small`) and model aliases (e.g., `"Chronos": {"model_path": "bolt-small"}`. This PR changes the aliases for bolt models to `bolt_size` instead of `bolt-size` to be consistent with the preset names. 
> [timeseries] Change Chronos-Bolt model aliases

- docs/install-cpu-pip.md
- docs/install-cpu-source.md
- docs/install-cpu-uv.md
- docs/install-gpu-pip.md
- docs/install-gpu-source.md
- docs/install-gpu-uv.md
- docs/install-mac-cpu.md
- docs/install.md
Issue #4593
1. Added dedicated UV installation tabs for all platforms (Linux/Mac/Windows)
2. Fixed virtual environment installation issues by:
- Using `python -m uv pip install` instead of `uv pip install`
- Creating separate UV-specific installation files
3. Cleaned up installation files:
- Removed UV installer from non-UV installation methods (pip, source)
- Created dedicated install-cpu-uv.md and install-gpu-uv.md
- Updated nightly build instructions to use correct UV command format
> [Install] Update UV installation instructions and add dedicated UV tabs

- tabular/src/autogluon/tabular/models/lgb/lgb_model.py
- Fix the warning produced by LightGBM on Colab. To reproduce, run this on Colab:
```
!pip install uv && uv pip install autogluon=="1.1.2b20241122" --pre
import lightgbm
```
Output:
```
/usr/local/lib/python3.10/dist-packages/dask/dataframe/__init__.py:42: FutureWarning: 
Dask dataframe query planning is disabled because dask-expr is not installed.
You can install it with `pip install dask[dataframe]` or `conda install dask`.
This will raise in a future version.
warnings.warn(msg, FutureWarning)
```
> [tabular] Fix lightgbm import warning

- core/src/autogluon/core/_setup_utils.py
- Currently, Chronos fine-tuning fails for `accelerate<0.34` with error `'AdamW' has no attribute 'train'` (see https://github.com/huggingface/transformers/issues/33620#issuecomment-2375857846). This error was fixed in `accelerate-0.34.0`, so we need to raise the lower bound.
> [core] Bump accelerate version to >=0.34,<1.0

- common/src/autogluon/common/utils/try_import.py
- tabular/setup.py
*Issue*
Related to failing tests on macOS Python >= 3.11
See https://github.com/autogluon/autogluon/actions/runs/12000876469/job/33494689238 and
https://github.com/autogluon/autogluon/actions/runs/12000876469/job/33494690159
- Remove outdated Python 3.11 + macOS compatibility check as CatBoost now supports this configuration
- Add minimum version requirement for CatBoost (>= 1.2)
- Improve error messages and exception handling:
- Add proper exception chaining using `from e`
- Include version requirements in error messages
- Maintain existing numpy-related error handling
- Fix empty ImportError being raised without message …
> [timeseries] Update try_import.py by update CatBoost requirement

- tabular/tests/unittests/test_tabular.py
*Issue *
Follow-up to [PR#4685](https://github.com/autogluon/autogluon/pull/4685)
- Remove platform-specific CatBoost restriction from test_tabular.py
- Previously, CatBoost was disabled for macOS + Python >= 3.11 combinations
- This restriction is no longer needed since CatBoost >= 1.2 now supports these environments
The change improves test consistency by:
- Allowing CatBoost to run on all supported platforms
- Relying on version checks rather than platform-specific restrictions
cc @Innixma @shchur @zhiqiangdon @gradientsky @yinweisu @sxjscience @FANGAreNotGnu @canerturkmen @jwmueller @prateekdesai04 @tonyhoo
> [tabular] Remove outdated macOS Python 3.11 CatBoost restriction for test_tabular.py

- multimodal/setup.py
- tabular/setup.py
**Issue:** Build fails on aarch64 due to onnxruntime-gpu dependency
**Fix**: Exclude onnxruntime-gpu on aarch64 platforms to fix build issues
The autogluon build process was failing on aarch64 platforms due to onnxruntime-gpu package incompatibility. 
This PR:
- Modified platform-specific ONNX dependencies by updates tabular/setup.py & multimodal/setup.py
- Falls back to CPU-only onnxruntime on aarch64 and Darwin platforms
- Maintains GPU support on compatible platforms (x86_64/Windows/Linux)
This change allows autogluon to build successfully on aarch64 while maintaining existing functionality on other platforms.
cc @Innixma @shchur @zhiqiangdon …
> fix: enable autogluon build on aarch64 platforms

- core/src/autogluon/core/trainer/abstract_trainer.py
- Disable callbacks for parallel fit_strategy
- This ensures that callbacks aren't used when parallel mode is enabled, as callback support in parallel mode is not implemented.
> Disable callbacks for parallel fit_strategy

- timeseries/tests/unittests/test_metrics.py
**Issue**
The Timeseries Platform test is failing.
***Description of changes**:*
Replace deprecated score() with evaluate() in experimental metric test
- Update **test_when_experimental_metric_name_used_then_predictor_can_score** to use evaluate() instead of score()
- Fix test failures caused by deprecated method usage
**Note :** The change addresses ValueError raised when using deprecated score() method that will be removed in version 1.2.
cc @Innixma @shchur @zhiqiangdon @gradientsky @yinweisu @sxjscience @FANGAreNotGnu @canerturkmen @jwmueller @prateekdesai04 @tonyhoo
> [timeseries] fix timeseries test_metrics.py failure

- timeseries/src/autogluon/timeseries/predictor.py
When setting `refit_full=True`, compatible models are re-trained on the full dataset, and the resulting models are saved with a `"_FULL"` suffix in the list of base models. This creates an issue in `predictor._simulation_artifact`, where we simply retrieve the already-computed OOF evaluations of each available model from disk, to be then stored in the `simulation_artifact` dict. These are not available for the `"_FULL"` models, and thus currently the code fails with an error of the form
```
FileNotFoundError: [Errno 2] No such file or directory: '/local/home/user/autogluon/AutogluonModels/ag-20241211_105202/models/DeepAR/DeepAR_FULL/utils/oof.pkl'
```
This PR fixes this issue by skipping any `"_FULL"` model in this step.
By submitting this pull request, I confirm …
> [timeseries] Do not try to compute OOF evaluations for "_FULL" models

- .github/workflows/slash_command_dispatch.yml
This PR fixes a security concern that /platform_tests might pick up a malicious commit sent within the very brief timing gap between when a maintainer sends out `/platform_tests` comment, and when the action dequeues and picks up the new malicious commit sha because it currently checks out the PR sha automatically. With this PR, it requires the maintainer to supply the commit sha in the slash command, and avoids the potential risk of running a malicious commit.
> use slash command arg for pr-sha

- docs/tutorials/tabular/tabular-indepth.ipynb
Resolves #3542
Fixes wording in tutorial to not mention commenting out train_data.head
> Update tabular tutorial wording

- core/src/autogluon/core/models/abstract/_tags.py
- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
Resolves #3913 
Improved the logging to better communicate what is going on when `num_folds=0` (exception) and `num_folds=1` (warning). 
> [tabular] Improve logging/error messages for use_child_oof

- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- core/src/autogluon/core/utils/utils.py
- core/tests/unittests/models/test_bagged_ensemble_model.py
- tabular/src/autogluon/tabular/predictor/predictor.py
Resolves #4453
Resolves #4771
- Stratify regression and quantile tasks via binning when doing cross-validation (such as during bagging)
- Fix bug in dynamic stacking cross-validation mode where stratification was not being done on binary/multiclass, but was being done on other problem_types (opposite of intention).
- Added type hints
> [tabular] Stratify regression tasks via binning

- tabular/setup.py
Increase tabpfn version min as lower versions are broken after the TabPFN v2 release.
> Increase tabpfn version min

- docs/tutorials/multimodal/advanced_topics/customization.ipynb
Update the documentation to reflect that the default value of `data.categorical.convert_to_text` is set to `False`.
see [4678](https://github.com/autogluon/autogluon/issues/4678)
> [Tutorial] categorical convert_to_text default value

- timeseries/setup.py
- Bump version ranges to StatsForecast, MLForecast and coreforecast
These contain no breaking changes so we can safely upgrade.
> [timeseries] Update version ranges for statsforecast & coreforecast

- tabular/src/autogluon/tabular/models/tabular_nn/torch/tabular_nn_torch.py
Fixes crash that occurs when the number of training samples is < 8 for NeuralNetTorch.
If the number of samples is <8, then NeuralNetTorch will skip doing any training at all because the data loader will only load exactly N samples, where the lowest batch size N is 8. Because N = 8 is greater than the number of training samples, no training occurs.
This PR fixes this by ensuring that batch_size is no larger than len(X), allowing it to be lower than 8.
Additionally, I did logic cleanup and added type hints.
Example code that fails in mainline but works in this PR:
```
from autogluon_benchmark.tasks.task_wrapper import OpenMLTaskWrapper
task = …
```
> [tabular] Fix NN_TORCH batch_size < 8

- common/tests/unittests/test_version.py
- core/src/autogluon/core/_setup_utils.py
- Add `test_version.py` to ensure that we don't accidentally do a release with a version that doesn't include an explicit micro / minor version. For example, we released `1.2` instead of `1.2.0`. While `1.2` is technically valid, it causes issues with some AWS logic such as docker builds that expect an explicit micro version.
- Update the way we create our `version.py` file so the content aligns with the ruff formater. Previously it complained that the version file lacked a newline and should use `"` instead of `'` for string values. This would lead to unnecessary clutter and confusing when users would perform automated linting prior to submitting a PR.
Example of the previous confusing lint message:
```
ruff format --diff "timeseries/" …
```
> Add `test_version.py`

- timeseries/src/autogluon/timeseries/dataset/ts_dataframe.py
- timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
- timeseries/src/autogluon/timeseries/models/autogluon_tabular/mlforecast.py
- timeseries/src/autogluon/timeseries/models/chronos/model.py
- timeseries/src/autogluon/timeseries/models/chronos/pipeline/utils.py
- timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
- timeseries/src/autogluon/timeseries/models/gluonts/torch/models.py
- timeseries/src/autogluon/timeseries/models/local/abstract_local_model.py
- timeseries/src/autogluon/timeseries/models/local/statsforecast.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/src/autogluon/timeseries/utils/forecast.py
- timeseries/tests/unittests/common.py
- timeseries/tests/unittests/models/test_local.py
- timeseries/tests/unittests/test_splitter.py
- timeseries/tests/unittests/test_ts_dataset.py
- timeseries/tests/unittests/utils/test_features.py
- The frequency caching mechanism sometimes results in very weird and hard-to-debug situations when an incorrect data frequency is cached even when resampling is applied.
- Originally, we used `data.freq` to infer the data frequency throughout the codebase, so caching this computation made sense. We can safely remove the caching mechanism now since
1. Currently, we only infer the frequency once when data is passed to the predictor with `data.infer_frequency()`. In the rest of the code, we pass around the `freq` as a string (e.g., setting it as a model attribute).
2. The new implementation of `data.freq` is much faster than before, so there is minimal overhead.
- Always use all items when inferring the data frequency inside the …
> [timeseries] Remove _cached_freq attribute for TimeSeriesDataFrame

- timeseries/src/autogluon/timeseries/regressor.py
- timeseries/tests/unittests/test_regressor.py
- Fixes #4832
- Fixes #4846
- Add optional arguments `include_static_features` and `include_item_id` to CovariateRegressor that control whether these features are used by the regressor.
- Fix a bug where an empty folder was created during creation of the regression model by the covariate regressor
- Fix a bug where the regressor would fail if all features it receives are constant
> [timeseries] Fix minor CovariateRegressor bugs

- timeseries/src/autogluon/timeseries/models/chronos/model.py
- timeseries/tests/unittests/models/chronos/test_model.py
*Issue #, if available:* #4776
*Description of changes:* This PR fixes a bug which prevented tuning of the `context_length` hyperparameter in Chronos models. Attributes are moved from `__init__` to another helper function which is called inside `_fit`. 
> [timeseries] Bugfix to allow tuning of `context_length` in Chronos

- core/src/autogluon/core/models/abstract/abstract_model.py
- timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
- timeseries/src/autogluon/timeseries/models/multi_window/multi_window_model.py
- This is the first in a line of PRs refactoring the `AbstractModel`. In this first PR we take care of typing in the `AbstractTimeSeriesModel` and pull in some of the methods that depend on their `super()` implementations. We also mark some methods where signatures do not align with `AbstractModel`, as TODO, for refactoring later. 
- The PR also touches `core` for harmless typing corrections.
> [timeseries] refactor dependencies on AbstractModel

- .github/workflow_scripts/test_timeseries.sh
- .github/workflows/platform_tests-command.yml
#4828 started causing time series platform tests to fail. This disables xdist in platform tests.
> [CI] fix timeseries platform tests

- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- tabular/src/autogluon/tabular/trainer/abstract_trainer.py
- tabular/tests/conftest.py
- tabular/tests/unittests/models/test_lightgbm.py
- tabular/tests/unittests/models/test_rf.py
Resolves #4869 
For the 1.2 release, I refactored the sanity checks in BaggedEnsembleModel, and as part of it, I made it raise an exception if called with `k_fold=0`, as previously we passed both `k_fold=0` and `k_fold=1` to mean the same thing (doing refit_full). However, this actually made refit_full fail to work for models anymore. This wasn't caught in our unit tests because the fallback mechanism which uses the first fold model in case of an error made the unit tests continue to pass.
I've fixed the issue by passing `k_fold=1` instead of `k_fold=0` during refit_full.
I've also added a docstring to clarify this behavior in BaggedEnsembleModel, and a unit test to verify that it is working correctly.
By submitting this pull request, I …
> [tabular] Fix refit_full crash

- timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
- timeseries/tests/conftest.py
#4773 broke time series platform tests because of how multiprocessing handles function pickling. This fixes that.
> [timeseries] fix in conftest

- timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
- timeseries/src/autogluon/timeseries/models/presets.py
- timeseries/tests/unittests/models/test_abstract.py
- increase test coverage of AbstractTimeSeriesModel to ~100%
- fix another type annotation issue
- remove "min_time_limit" from model aux params. i.e., a model may not decide to increase its time limit by itself.
> [timeseries] add tests for concrete methods in AbstractTimeSeriesModel

- .github/workflows/benchmark_master.yml
- .github/workflows/build_latest_image.yml
In #3466 the free-disk-space action was changed to use a fork to work around some issues, but fixes have since been merged (https://github.com/jlumbroso/free-disk-space/pull/8, https://github.com/jlumbroso/free-disk-space/pull/11).
Changes have been made entirely based on the old comments left in the workflow and the state of the linked issues. I am not familiar with the AutoGluon code base nor the free-disk-space GH action.
Sorry for the git history, did this from the web UI. I assume you squash anyway.
> Revert to use jlumbroso/free-disk-space@v1.3.1

- timeseries/src/autogluon/timeseries/models/gluonts/torch/models.py
- timeseries/tests/unittests/models/test_gluonts.py
- Make it possible to pass custom `distr_output` to the TFT model. Currently, passing the custom value leads to an exception because specifying both `quantiles` and `distr_output` triggers an assertion during initialization of the TFT model.
- Remove stale TODOs for GluonTS models
> [timeseries] Allow using custom distr_output with the TFT model

- common/src/autogluon/common/utils/utils.py
Fix setup_outputdir
- Force path_suffix to always result in a new directory if specified and `path=None`. Previously it could result in appending a str to `ag-{timestamp}` without making a new directory. For example, initializing CatBoostModel with `path=None` would create `AutogluonModels/ag-{...}CatBoost`, instead of `AutogluonModels/ag-{...}/CatBoost`
- Fix unnecessary warning logged when `path=None` is the input.
> Fix setup_outputdir

- common/src/autogluon/common/utils/resource_utils.py
Improvement to first check if cuda is available before trying to get GPU count. On a CPU machine, trying to get GPU count when cuda isn't available leads to warning messages. Better to avoid the warning messages.
> check cuda.is_available() before cuda.device_count()

- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- core/src/autogluon/core/models/ensemble/stacker_ensemble_model.py
- core/src/autogluon/core/models/greedy_ensemble/greedy_weighted_ensemble_model.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/tests/unittests/test_tabular.py
Adding extra features to better support TabRepo 2.0:
- Add `predictor.model_hyperparameters(model)`
- Add `predictor.model_info(model)`
- Add `include_feature_metadata` boolean to `model.get_info()`, as `feature_metadata` is dependent on AutoGluon unlike all other outputs of `get_info` which are python native types.
TODO:
> [tabular] Add predictor.model_hyperparameters()

- common/src/autogluon/common/utils/utils.py
- core/src/autogluon/core/hpo/executors.py
- core/src/autogluon/core/models/__init__.py
- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/trainer/abstract_trainer.py
- timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
- timeseries/tests/unittests/models/test_abstract.py
This PR contains all the key design choices for removing `AbstractTimeSeriesModel`'s tight coupling to core / AbstractModel.
Initially, `AbstractTimeSeriesModel` was tightly coupled to `AbstractModel` as both a quick solution to ensure the rest of core development does not break timeseries + to force us to replicate most of AG's core patterns in time series. It was also evident at the time that inheritance was not the correct path since the subtyping relation `AbstractTimeSeriesModel <: AbstractModel` was broken in most cases--starting from the type of data they operated on. In time, this coupling continued to cause problems and has recently made timeseries increasingly hard to develop (cf. the Chronos and Chronos-Bolt experiences, new …
> [timeseries] decouple AbstractTimeSeriesModel from core

- full_install.sh
Fixes #4934
Adds Jupyter/Colab environment detection to the full_install.sh script. When running in Colab or other Jupyter environments, the script automatically adds the `--system` flag to all `uv pip install` commands.
This addresses the issue where AutoGluon installation with `uv pip` was failing in Colab because packages were being installed in a virtual environment not accessible from the notebook's Python kernel. The `--system` flag ensures packages are installed in the system Python path, making them importable in notebook environments.
Colab testing [link](https://colab.research.google.com/drive/16zmGdMylUbLYYVuEgOcEkip8-ah3GH5b?usp=sharing) …
> add notebook env check for colab and fix the source installation issue

- full_install.sh
Resolves #4932 
Make `full_install.sh` work when called outside of autogluon's directory.
This works in mainline:
```
git clone https://github.com/autogluon/autogluon.git
cd autogluon && ./full_install.sh
```
This fails in mainline but succeeds in this PR:
```
git clone https://github.com/autogluon/autogluon.git
./autogluon/full_install.sh
```
> Make full_install.sh working dir -> script dir

- tabular/setup.py
- tabular/src/autogluon/tabular/models/xgboost/xgboost_model.py
#4859
Gets rid of deprecation warnings when using GPU with XGBoost, as the arguments changed in the XGBoost 2.0 release.
This will also remove support for XGBoost 1.x. We could consider keeping it by having an `if version<2:` logic, but unless XGB 1.x is important for some reason, I'll plan to just drop it for simplicity.
Note that I haven't tested this PR yet, so I don't know if it works properly. Would be good for someone with a GPU machine to sanity check it.
> Fix XGBoost GPU warnings

- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- tabular/src/autogluon/tabular/trainer/abstract_trainer.py
- tabular/tests/unittests/models/advanced/test_refit_full.py
Related: #4941
Fix a bug where refit_full(train_data_extra) fails when categorical features are present. This is because when concating two dataframes with identical dtypes, the dtypes for category features are changed to float/int. This causes downstream errors in models. This PR fixes this by doing `.astype(X.dtypes)` after the concat.
> [tabular] Fix .refit_full(train_data_extra)

- common/src/autogluon/common/utils/try_import.py
- tabular/setup.py
Resolves #4987 
- Add FastAI 2.8 support
- Removed upper hard cap on FastAI so users who upgrade in future won't automatically get failures.
> Add FastAI 2.8 support

- multimodal/src/autogluon/multimodal/data/trivial_augmenter.py
*Issue #, if available:* fix #4967
fix typo in download_nltk function. Which always caused downloading of averaged_perceptron_tagger
> Fix NLTK tagger path in download function

- timeseries/src/autogluon/timeseries/trainer.py
- timeseries/tests/unittests/test_predictor.py
*Issue #, if available:* Fixes #4973
- Raise an informative error message if a model not present in the trainer is used for prediction. Currently, the error message is very confusing: `networkx.exception.NetworkXError: The node Chronos is not in the digraph`.
> [timeseries] Raise informative error message if invalid model name is provided

- multimodal/src/autogluon/multimodal/optim/lit_module.py
#4966 
When using multiple GPUs, the learning rate schedule was incorrectly calculated because `max_steps` didn't account for distributed training. This caused: 
- Warmup period to be longer than intended 
- Learning rate to not decay to 0 as expected
The fix divides `max_steps` by `num_devices` to properly scale the schedule for distributed training. 
This ensures: 
- Correct warmup period (e.g. 10% of actual total steps) 
- Proper cosine decay reaching 0 at the end of training
Learning Rate Prior to the fix with 4 GPUs:
Learning Rate Post to the fix with 4 GPUs:
> fix: account for distributed training in learning rate schedule

- timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
- timeseries/src/autogluon/timeseries/models/multi_window/multi_window_model.py
- timeseries/tests/unittests/models/common.py
*Issue #, if available:* Fixes #4999
- The method `_initialize_covariate_regressor_scaler` in `MultiWindowBacktestingModel` did not actually overload the method `_initialize_transforms_and_regressor` in `AbstractTimeSeriesModel`. Because of this, the scaler / regressor object was created twice in multi window models. 
- This bug went unnoticed because of another bug in the `get_multi_window_deepar` method in the tests. The initialization was done differently from what actually happened when we trained a `MultiWindowBacktestingModel` during training.
> [timeseries] Fix redundant scaler and regressor initialization for MultiWindowBacktestingModel

- timeseries/src/autogluon/timeseries/models/chronos/model.py
- timeseries/tests/unittests/models/chronos/test_model.py
*Issue #, if available:* fixes #5018
*Description of changes:* This PR changes the `evaluation_strategy` training argument to `eval_strategy`, if the `transformers` version is greater than or equal to `4.46`.
> [timeseries] Change `evaluation_strategy` to `eval_strategy`

- common/src/autogluon/common/utils/simulation_utils.py
- Add mem opt simulation artifact support, necessary for upcoming TabArena
- Mem opt simulation artifact is up to 4x smaller than non-optimized artifact.
- Tests pass locally
> [Tabular] Add mem opt simulation artifact support

- tabular/tests/unittests/test_tabular.py
- Fix platform tests failing on Python 3.9 because of the new style of type annotations ([logs](https://github.com/autogluon/autogluon/actions/runs/14375314317/job/40306242490))
> [tabular] Fix platform tests for tabular

- core/src/autogluon/core/_setup_utils.py
- tabular/src/autogluon/tabular/models/tabular_nn/utils/categorical_encoders.py
- Fix sklearn<1.6 compatibility
- With recent PR #5029, it breaks sklearn<1.6 support. It is important we continue to work on older sklearn versions, as many environments or packages might not support sklearn 1.6+ yet.
> Fix sklearn<1.6 compatibility

- .github/workflows/platform_tests-command.yml
N/A
Fix "No space left on device" [errors](https://github.com/autogluon/autogluon/actions/runs/14440463375/job/40489263110) in platform tests CI for tabular modules on Ubuntu runners with python 3.10.
- Added disk cleanup steps before dependency installation for Ubuntu runners
- Removes unnecessary large directories (/usr/share/dotnet, Android libraries, etc.)
- Cleans apt-get cache
- Removes Docker images if present
- Added to both tabular and timeseries workflow jobs
- Frees up ~14GB of disk space (from 67% to 47% disk usage)
* Testing
Successful [run](https://github.com/tonyhoo/autogluon/actions/runs/14455066679)
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …
> Platform tests

- common/src/autogluon/common/loaders/load_json.py
- tabular/src/autogluon/tabular/trainer/abstract_trainer.py
- Raise on NaN val if raise_on_model_failure=True
- Improve return type hint for load_json which can return a list or a dict.
> [Tabular] Raise on NaN val if raise_on_model_failure=True

- timeseries/src/autogluon/timeseries/trainer.py
- timeseries/tests/smoketests/test_all_models.py
- timeseries/tests/unittests/test_trainer.py
*Issue #, if available:* Fixes #5046
- Fix the bug introduced in [#4653](https://github.com/autogluon/autogluon/pull/4653/files#diff-d2a9d7490bd4601b8f3613cfea6c5e37455fb05cc4a025420240a6d47e45de0fR523) that incorrectly set the `time_limit` if `tuning_data` was provided to `predictor.fit()`.
> [timeseries] Fix time_limit when val_data is provided #5046

- tabular/src/autogluon/tabular/configs/config_helper.py
- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/src/autogluon/tabular/trainer/auto_trainer.py
- tabular/src/autogluon/tabular/trainer/model_presets/presets.py
- tabular/tests/unittests/data/test_learning_curves.py
- timeseries/src/autogluon/timeseries/regressor.py
- Adopt ag_model_register in all places to avoid using multiple derivative global variables to track model class metadata.
@shchur I made one edit in timeseries as one of the global variables was used in timeseries. The change should have no impact.
> Adopt ag_model_register

- core/src/autogluon/core/models/abstract/abstract_model.py
- Enforce max model resources
- Previously, max model resources was only respected during bagging, but not during holdout. This ensures that max model resources is respected.
> Enforce max model resources

- timeseries/src/autogluon/timeseries/learner.py
- timeseries/src/autogluon/timeseries/metrics/__init__.py
- timeseries/src/autogluon/timeseries/metrics/abstract.py
- timeseries/src/autogluon/timeseries/metrics/point.py
- timeseries/src/autogluon/timeseries/metrics/quantile.py
- timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
- timeseries/src/autogluon/timeseries/models/ensemble/greedy_ensemble.py
- timeseries/src/autogluon/timeseries/models/presets.py
- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/src/autogluon/timeseries/trainer.py
- timeseries/tests/unittests/test_metrics.py
- timeseries/tests/unittests/test_predictor.py
*Issue #, if available:* #4852
- Add an optional argument `horizon_weight: list[float] | None` to the `TimeSeriesPredictor` and all forecasting metrics that allows assigning custom weights to each time step in the forecast horizon when computing the metric. 
- When computing all metrics, we create an array of raw error values of shape `[num_items, prediction_length]`. We then multiply this array with `horizon_weight.reshape[1, prediction_length]`, before applying the final aggregation step. 
> [timeseries] Add support for `horizon_weight` in time series forecasting metrics

- timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
- timeseries/src/autogluon/timeseries/models/chronos/model.py
- timeseries/tests/unittests/models/chronos/test_model.py
*Issue #, if available:* Among other things, fixes #4876
On the current `master` branch, the HPO is broken for Chronos models (both with and without `tuning_data` provided to `predictor.fit`). This is caused by two issues:
1. Problems with the model name and path described in #4876 (this only kicks in if `tuning_data` is provided to `predictor.fit`)
2. Bug in `AbstractTimeSeriesModel.get_params` that returned all HP values during cloning (including the instantiated default hyperparameter values), instead of just returning the user-provided HPs.
This PR fixes both of these issues.
> [timeseries] Fix HPO for Chronos models

- timeseries/src/autogluon/timeseries/dataset/ts_dataframe.py
- timeseries/tests/unittests/test_ts_dataset.py
*Issue #, if available:* Fixes #4917
- Ensure that the `timestamp` index level has `datetime64[ns]` dtype before resampling. Other dtypes (e.g., `datetime64[ms]` may result in NaT values appearing in the index).
> [timeseries] Fix NaT timestamp values during resampling

- common/src/autogluon/common/utils/pandas_utils.py
- timeseries/tests/unittests/utils/test_features.py
*Issue #, if available:* Fixes #4315
- Currently, if a feature of type `category` contains all-NaN values, `PipelineFeatureGenerator.fit_transform` will raise a `ZeroDivisionError` when trying to estimate the `post_memory_usage`. This PR fixes this issue.
> [features] Fix ZeroDivisionError inside get_approximate_df_mem_usage

- timeseries/src/autogluon/timeseries/predictor.py
- timeseries/tests/unittests/test_predictor.py
*Issue #, if available:* fixes #4356 
*Description of changes:* This PR adds support for `cutoff` in `TimeSeriesPredictor.evaluate` and `TimeSeriesPredictor.leaderboard`. 
TODOs:
> [timeseries] Add cutoff support in evaluate and leaderboard

- timeseries/src/autogluon/timeseries/predictor.py
*Issue #, if available:* Fixes #4212
- Log a warning of an S3 `path` is provided to `TimeSeriesPredictor`.
> [timeseries] Warn if an S3 path is provided to the TimeSeriesPredictor

- docs/tutorials/timeseries/forecasting-metrics.md
Issue #5043 
I was bored and had nothing to do, so I decided to add a bit to the documentation. :)
Description of changes:
- Add a new “Customizing Model Training Loss via `distr_output`” section to the Forecasting Time Series guide.
- Show how to swap in a built‑in distribution (e.g. `NormalOutput`) to change the training loss.
- Provide a complete example of a custom `TildeQOutput` subclass implementing multi‑quantile (pinball) loss.
> Update docs for custom `distr_output`

- pyproject.toml
- timeseries/src/autogluon/timeseries/metrics/__init__.py
- timeseries/src/autogluon/timeseries/models/chronos/pipeline/__init__.py
- timeseries/src/autogluon/timeseries/models/ensemble/__init__.py
- timeseries/src/autogluon/timeseries/transforms/__init__.py
*Issue #, if available:* Related to #5097
There are a few arguably incorrect configuration options in our `pyproject.toml` that resulted in issues such as #5097. This PR fixes this misconfiguration.
- Set target Python version to 3.9 for `ruff` and `pyright`.
- Do not completely ignore `__init__.py` files with ruff. Only remove complaints about the unused imports (F401) and perform the other checks.
> [timeseries] Do not ignore __init__ files with ruff

- timeseries/src/autogluon/timeseries/metrics/abstract.py
- timeseries/src/autogluon/timeseries/models/chronos/pipeline/utils.py
- timeseries/src/autogluon/timeseries/models/gluonts/__init__.py
- timeseries/src/autogluon/timeseries/models/gluonts/abstract.py
- timeseries/src/autogluon/timeseries/models/gluonts/dataset.py
- timeseries/src/autogluon/timeseries/models/gluonts/models.py
- timeseries/tests/unittests/models/common.py
- timeseries/tests/unittests/models/test_gluonts.py
- timeseries/tests/unittests/test_metrics.py
- Reorganizes `gluonts` namespace, separating out `dataset` and removing the redundant `torch.*` namespace.
- Fixes minor typing issue (use of pipe instead of Union) in `metrics`.
> [timeseries] reorganize gluonts namespace, fix minor typing issue

- tabular/setup.py
- tabular/src/autogluon/tabular/models/tabular_nn/utils/categorical_encoders.py
https://github.com/catboost/catboost/issues/2671
With the release of catboost 1.2.8 and resolution of the [issue](https://github.com/catboost/catboost/issues/2671), update numpy support on autogluon side
> upgrade numpy to 2.x with latest catboost release

- timeseries/src/autogluon/timeseries/trainer.py
- Fix `FutureWarnings` produced by `leaderboard` and `evaluate` methods in the `TimeSeriesPredictor` (see e.g., https://auto.gluon.ai/stable/tutorials/timeseries/forecasting-quick-start.html#evaluating-the-performance-of-different-models). This happens because we forgot to update the code in light of a deprecation introduced in #5084.
> [timeseries] Fix FutureWarning in leaderboard and evaluate methods

- tabular/src/autogluon/tabular/predictor/predictor.py
Fixes #5114 
This PR fixes a bug in the TabularPredictor constructor where `positive_class` was incorrectly accessed from `kwargs`, causing a KeyError when passed as a named argument. The line:
```python
learner_kwargs["positive_class"] = kwargs["positive_class"]
```
has been corrected to:
```python
learner_kwargs["positive_class"] = positive_class
```
> Fix incorrect reference to positive_class in TabularPredictor constructor

- timeseries/src/autogluon/timeseries/models/ensemble/greedy.py
- With `numpy>2.0` the ensemble weights are printed as follows:
```
Ensemble weights: {'Chronos[bolt_small]': np.float64(0.74), 'DirectTabular': np.float64(0.04), 'ETS': np.float64(0.02), 'RecursiveTabular': np.float64(0.19)}
```
This PR ensures that the weights are displayed as floats (and not np.float64 dtype).
> [timeseries] Fix ensemble weights format for printing

- common/src/autogluon/common/utils/resource_utils.py
- multimodal/src/autogluon/multimodal/utils/log.py
- tabular/src/autogluon/tabular/models/tabular_nn/torch/tabular_nn_torch.py
#4984 
#3126 
It looks like with the recent upgrade of torch and lightning, we're now utilizing MPS on Apple Silicon devices! I've confirmed it through GPU memory and usage. I've also added this information to the system log to prevent any confusion for users on Apple devices.
```
=================== System Info ===================
AutoGluon Version:  1.3.1b20250527
Python Version:     3.10.16
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 24.5.0: Tue Apr 22 19:54:49 PDT 2025; root:xnu-11417.121.6~2/RELEASE_ARM64_T6000
CPU Count:          10
Pytorch Version:    2.6.0
CUDA Version:       CUDA is not available
GPU Count:          1
Memory Avail:       20.19 GB / 32.00 GB (63.1%)
Disk Space …
```
> fix: Support Apple Silicon and log it in the system info

- tabular/src/autogluon/tabular/models/_utils/rapids_utils.py
- tabular/src/autogluon/tabular/models/lr/lr_model.py
- tabular/src/autogluon/tabular/models/lr/lr_rapids_model.py
N/A
RAPIDS cuML linear models (LinearRapidsModel) fail during training with an `AttributeError: n_iter_` because they don't expose the `n_iter_` attribute that scikit-learn models provide. This causes the LinearModel base class to crash when trying to access `model.n_iter_` for iteration tracking.
- RAPIDS cuML models use GPU-optimized algorithms that don't track iterations the same way as scikit-learn
- The `n_iter_` attribute is not available in cuML implementations
- AutoGluon's LinearModel base class assumes all linear models have this attribute
Replace direct attribute access with safe `getattr()` calls:
- Use `getattr(model, 'n_iter_', None)` instead of `model.n_iter_`
- Verified with RAPIDS cuML lr models
- Confirmed scikit-learn …
> [Fix] Resolve AttributeError in LinearModel when using RAPIDS cuML models

- docs/tutorials/timeseries/forecasting-indepth.ipynb
- docs/tutorials/timeseries/forecasting-metrics.md
- docs/tutorials/timeseries/forecasting-quick-start.ipynb
- timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
- timeseries/src/autogluon/timeseries/models/ensemble/greedy.py
- timeseries/src/autogluon/timeseries/trainer.py
- timeseries/tests/unittests/models/test_abstract.py
- timeseries/tests/unittests/test_trainer.py
- Currently, exceptions occurring during model fitting are reported as
https://github.com/autogluon/autogluon/blob/0ee849fc6dc2c44aa0f3e086317e4d11d16955fa/timeseries/src/autogluon/timeseries/trainer.py#L373-L376
So the log message at default `verbosity=2` may look like
```
...
Training timeseries model DirectTabular. 
Warning: Exception caused DirectTabular to fail during training... Skipping this model.
'int' object is not iterable
...
```
The only way to see the entire stack trace is to re-run the entire fit process with `verbosity=4`, in which case the logs look like
```
Training timeseries model DirectTabular. 
Window 0
Warning: Exception caused DirectTabular to fail during training... Skipping this model.
'int' object is not …
```
> [timeseries] Fix exception logging in case of model failures + minor fixes

- docs/api/autogluon.tabular.models.rst
- Currently, the model aliases and names are not displayed in the [documentation](https://auto.gluon.ai/dev/api/autogluon.tabular.models.html#lgbmodel):
With this PR:
> [docs] Show tabular model aliases in the documentation

- timeseries/setup.py
- timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
- timeseries/src/autogluon/timeseries/models/autogluon_tabular/mlforecast.py
- timeseries/src/autogluon/timeseries/models/chronos/model.py
- timeseries/src/autogluon/timeseries/models/local/abstract_local_model.py
- timeseries/src/autogluon/timeseries/regressor.py
- timeseries/tests/unittests/models/common.py
- timeseries/tests/unittests/models/test_mlforecast.py
- timeseries/tests/unittests/test_predictor.py
- timeseries/tests/unittests/test_trainer.py
- Update version range for `mlforecast`, `coreforecast`, `utilsforecast`
- Log a warning if unsupported hyperparameters are provided to `DirectTabular`, `RecursiveTabular`, or `Chronos` models.
- Instead of creating a `TabularPredictor` inside `DirectTabular` and `RecursiveTabular` models, create a single tabular model (instance of `autogluon.core.models.AbstractModel`). This simplifies our internal logic and makes the API of the model compatible with the upcoming PerStepTabular model.
- Allow passing `lag_transforms` to `RecursiveTabular` model.
*To do:*
> [timeseries] Update hyperparameter handling in MLForecast models

- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- tabular/tests/unittests/models/test_dummy.py
-  Add support for max_rows, max_features, max_classes, problem_types
- This is useful for foundation models which focus on small data and don't work effectively on large data, so that we can dynamically disable these methods based on the data properties.
For example:
```python
"CAT": [{"ag.max_rows": 1000}],  # will raise an AssertionError if train data > 1000 samples
}
predictor = TabularPredictor(...).fit(..., hyperparameters=hyperparameters)
```
> [tabular] Add support for max_rows, max_features, max_classes, problem_types

- core/src/autogluon/core/_setup_utils.py
update numpy cap, thus 2.3.0 is allowed
> update numpy cap, thus 2.3.0 is allowed

- core/src/autogluon/core/models/abstract/abstract_model.py
- tabular/src/autogluon/tabular/models/catboost/callbacks.py
- tabular/src/autogluon/tabular/models/catboost/catboost_utils.py
- tabular/src/autogluon/tabular/testing/fit_helper.py
- tabular/src/autogluon/tabular/testing/generate_datasets.py
Currently CatBoost fails for problem_type="quantile" if len(quantile_levels) == 1. This PR fixes this problem.
MWE
```python
train_data = 'https://autogluon.s3.amazonaws.com/datasets/Inc/train.csv'
predictor = TabularPredictor(label='age', problem_type='quantile', quantile_levels=[0.5]).fit(train_data=train_data, time_limit=30)
```
Leads to
```
Fitting model: CatBoost ... Training model for up to 19.61s of the 19.61s of remaining time.
Warning: Exception caused CatBoost to fail during training... Skipping this model.
catboost/private/libs/algo/tensor_search_helpers.cpp:200: Parameter alpha should contain at least two quantiles separated by comma
Detailed Traceback:
File …
```
> [tabular] Fix CatBoost crashing for problem_type="quantile" if len(quantile_levels) == 1

- tabular/src/autogluon/tabular/predictor/predictor.py
- tabular/src/autogluon/tabular/testing/fit_helper.py
- tabular/src/autogluon/tabular/trainer/model_presets/presets.py
- tabular/tests/unittests/models/test_dummy.py
Add `ag.ens.` shortcut for ag_args_ensemble
TODO:
> Add `ag.ens.` shortcut for ag_args_ensemble

- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- core/src/autogluon/core/models/ensemble/fold_fitting_strategy.py
- tabular/tests/unittests/resource_allocation/test_bagging_resource_allocation.py
- tabular/tests/unittests/resource_allocation/test_resource_allocation_combined.py
Related: #5180 
**Major bug fix**
- Previously if the model is fit in bagged mode with `fold_fitting_strategy="sequential_local"`, the system level CPU and GPU arguments from `predictor.fit(num_cpus=..., num_gpus=...)` were ignored.
- This led to major problems, such as GPUs being used when they shouldn't be, or far more CPUs being used than the user expected.
- Now the system level CPU and GPU arguments are respected.
- Additionally fixed an issue in `fold_fitting_strategy="sequential_local"` where if the user specified `ag_args_fit` with only one of `num_cpus` or `num_gpus`, the other unspecified value would be set to an incorrect value, ignoring the model's default resource suggestion.
- Added logging in the bagged model to clearly …
> [tabular] Respect num_cpus/num_gpus in sequential_local fit

- common/src/autogluon/common/utils/cpu_utils.py
- common/src/autogluon/common/utils/resource_utils.py
- core/src/autogluon/core/hpo/ray_hpo.py
- tabular/src/autogluon/tabular/models/catboost/catboost_model.py
- tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
- tabular/src/autogluon/tabular/models/lgb/lgb_model.py
- tabular/src/autogluon/tabular/models/tabpfnmix/tabpfnmix_model.py
- tabular/src/autogluon/tabular/models/tabular_nn/torch/tabular_nn_torch.py
- tabular/src/autogluon/tabular/models/xgboost/xgboost_model.py
- tabular/src/autogluon/tabular/trainer/abstract_trainer.py
Follow-up to #5197
- Switch from psutil to loky for get_cpu_count in all places
- This should improve AutoGluon's compatibility with docker / slurm clusters.
> [tabular] Switch to loky for get_cpu_count in all places

- timeseries/src/autogluon/timeseries/models/autogluon_tabular/mlforecast.py
- timeseries/tests/unittests/models/test_mlforecast.py
- This PR adds an `AutoMLPipelineFeatureGenerator` to DirectTabular and RecursiveTabular models. This fixes a regression on some datasets with categorical features that was introduced in #5184. 
This object ensures that the features received by model during fit and predict have the same dtypes and category ordering. For some reason, removing this check led to worse performance of LightGBM on two datasets.
> [timeseries] Add AutoMLPipelineFeatureGenerator to MLForecast-based models

- common/setup.py
- common/src/autogluon/common/utils/cpu_utils.py
- common/tests/unittests/utils/test_cpu_detection.py
- core/src/autogluon/core/_setup_utils.py
- timeseries/setup.py
For some unexplainable reason, the statement `import loky` that was added in #5197 results in weird and verbose error messages printed by the `PerStepTabularModel` in the TS module.
MWE:
```python
from autogluon.timeseries import TimeSeriesPredictor
if __name__ == "__main__":
predictor = TimeSeriesPredictor(prediction_length=2).fit(
"https://autogluon.s3.amazonaws.com/datasets/timeseries/m4_hourly_subset/train.csv",
hyperparameters={"PerStepTabular": {}},
time_limit=15,
)
```
Predictor log after #5197:
```
...
Provided data contains following columns:
target: 'target'
AutoGluon will gauge predictive performance using evaluation metric: 'WQL'
This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the …
```
> [common] Use joblib instead of loky for cpu detection

- tabular/src/autogluon/tabular/models/catboost/catboost_model.py
- timeseries/src/autogluon/timeseries/models/autogluon_tabular/mlforecast.py
- timeseries/src/autogluon/timeseries/models/autogluon_tabular/per_step.py
- timeseries/tests/unittests/models/test_per_step_tabular.py
- Fix docstrings for `DirectTabular` and `RecursiveTabular` models
- Change the `PerStepTabular` model to adjust the tabular `problem_type` / `eval_metric` based on the forecasting metric. This behavior matches the current behavior of `DirectTabular` model:
- For quantile metrics like WQL/SQL, the model will be fit in quantile regression mode.
- For point metrics like MASE/RMSE, the model will be fit in regression mode, and prediction intervals will be obtained from the zero-mean normal distribution fitted to the residuals on the training set.
Since the model is not included in the default presets for v1.4.0, this is a very low-risk change. …
> [timeseries] Add regression mode support to PerStepTabularModel

- tabular/src/autogluon/tabular/models/catboost/catboost_model.py
- tabular/src/autogluon/tabular/models/catboost/catboost_utils.py
- tabular/src/autogluon/tabular/testing/fit_helper.py
- tabular/tests/unittests/models/test_catboost.py
- Currently, the `CatBoostModel` in AutoGluon always uses the default `loss_function` [(RMSE)](https://catboost.ai/docs/en/concepts/python-reference_catboostregressor) when `problem_type="regression"` is used. This means, the model always tries to estimate the conditional mean, which can lead to poor results for datasets with skewed targets if the user actually cares about the conditional median (e.g., cares about the metric like MAE).
This PR updates the default value of the `loss_function` used by CatBoostRegressor to match the user-defined `eval_metric`. 
On a small benchmark of 31 time series forecasting tasks, the `PerStepTabular` model (based on CatBoost) achieves 77% win rate and up to 30% error reduction (median: 4% reduction) …
> [tabular] Fix default loss_function for CatBoostModel with problem_type='regression'

- common/src/autogluon/common/utils/resource_utils.py
- tabular/src/autogluon/tabular/models/mitra/mitra_model.py
- tabular/src/autogluon/tabular/models/realmlp/realmlp_model.py
- tabular/src/autogluon/tabular/models/tabicl/tabicl_model.py
- tabular/src/autogluon/tabular/models/tabm/tabm_model.py
- tabular/src/autogluon/tabular/models/tabpfnv2/tabpfnv2_model.py
This PR addresses a issue identified in the previous PR (#5221) where `torch` was being imported directly in the `_get_default_resources()` method across several foundational tabular models (RealMLP, TabPFNv2, TabM, TabICL, and Mitra).
The `_get_default_resources()` method is called very early in the AutoGluon workflow - during model initialization and resource calculation phases, before proper error handling mechanisms are established. When torch import fails at this stage, it can:
* Bypass error handling logic - The failure occurs before AutoGluon's try/catch mechanisms are set up
* Crash the entire AutoGluon process - Instead of gracefully falling back to CPU-only mode
* Prevent proper user feedback - Users don't get helpful error …
> [tabular] Enhance GPU resource handling across foundational tab models with error logging

- timeseries/src/autogluon/timeseries/models/autogluon_tabular/per_step.py
- timeseries/src/autogluon/timeseries/utils/warning_filters.py
- Currently `PerStepTabularModel` may produce lots of `PerformanceWarning` if the users provides a large list of lags, which results in a fragmented dataframe. This PR silences these warnings.
> [timeseries] Silence performance warnings in PerStepTabularModel

- core/src/autogluon/core/metrics/score_func.py
Fixes #5185.
Pass `predictions` (i.e., `y_pred` or `y_pred_proba`) to eval metric. `y_pred` is `None` for metrics like `roc_auc`.
> [Fix] Pass predictions to eval metric when weight_evaluation=True

- multimodal/setup.py
Currently when we run `pip install --pre autogluon` or `uv pip install --pre autogluon`, the dependency resolution process does a lot of backtracking and ends up installing an ancient version of `datasets`.
```
INFO: pip is looking at multiple versions of datasets to determine which version is compatible with other requirements. This could take a while.
Collecting datasets>=2.0.0 (from evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.4.0b20250724->autogluon)
Downloading datasets-3.6.0-py3-none-any.whl.metadata (19 kB)
Downloading datasets-3.5.1-py3-none-any.whl.metadata (19 kB)
Downloading datasets-3.5.0-py3-none-any.whl.metadata (19 kB)
Downloading datasets-3.4.1-py3-none-any.whl.metadata (19 kB)
Downloading datasets-3.4.0-py3-none-any.whl.metadata (19 kB) …
```
> [multimodal] Cap fsspec version to avoid backtracking during pip version resolution

- core/src/autogluon/core/learning_curves/plot_curves.py
**Problem:** Inconsistent method signature types in plot_curves.py (see issue #5155)
**Solution:** Updated the [plot_curves ](https://github.com/autogluon/autogluon/blob/b1ab1acc5503320df39e40f33ad6be8d88a4fe5c/core/src/autogluon/core/learning_curves/plot_curves.py#L8-L17) method signature type for the learning_curves parameter to align with the current implementation. Switched from `dict` to `tuple[dict, dict]` and updated documentation.
> [Fix] Changed Plot Curves Method Signature Type

- timeseries/src/autogluon/timeseries/models/autogluon_tabular/mlforecast.py
Currently, if user imports anything from `autogluon.common` before training DirectTabular or RecursiveTabular model in AutoGluon, they will see the following log messages
```
Training timeseries model RecursiveTabular. Training for up to 21.6s of the 43.1s of remaining time.
('float', []) : 44 | ['lag1', 'lag2', 'lag3', 'lag4', 'lag5', ...]
('float', []) : 44 | ['lag1', 'lag2', 'lag3', 'lag4', 'lag5', ...]
-231.1598     = Validation score (-MAE)
20.02   s     = Training runtime
0.32    s     = Validation (prediction) runtime
```
that are produced by https://github.com/autogluon/autogluon/blob/master/features/src/autogluon/features/generators/abstract.py#L806
- Set verbosity of the `AutoMLPipelineFeatureGenerator` to 0 to silence these …
> [timeseries] Silence log messages produced by autogluon.common

- core/src/autogluon/core/models/abstract/abstract_model.py
- core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
- core/src/autogluon/core/models/ensemble/fold_fitting_strategy.py
- core/tests/unittests/models/test_bagged_ensemble_model.py
- tabular/src/autogluon/tabular/models/catboost/catboost_model.py
- tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
- tabular/src/autogluon/tabular/models/knn/knn_model.py
- tabular/src/autogluon/tabular/models/lgb/lgb_model.py
- tabular/src/autogluon/tabular/models/lr/lr_model.py
- tabular/src/autogluon/tabular/models/mitra/mitra_model.py
- tabular/src/autogluon/tabular/models/realmlp/realmlp_model.py
- tabular/src/autogluon/tabular/models/rf/rf_model.py
- tabular/src/autogluon/tabular/models/tabicl/tabicl_model.py
- tabular/src/autogluon/tabular/models/tabm/tabm_model.py
- tabular/src/autogluon/tabular/models/tabpfnmix/tabpfnmix_model.py
- tabular/src/autogluon/tabular/models/tabpfnv2/tabpfnv2_model.py
- tabular/src/autogluon/tabular/models/tabular_nn/hyperparameters/parameters.py
- tabular/src/autogluon/tabular/models/tabular_nn/torch/tabular_nn_torch.py
- tabular/src/autogluon/tabular/models/xgboost/xgboost_model.py
- tabular/tests/unittests/models/advanced/test_model_random_seed.py
This PR ensures that each fold gets a different random seed. I implemented it as part of the kwargs to avoid users setting random seeds as a hyperparameter. 
> By default, we keep a static seed of 0 to ensure reproducibility. When using a bagged model, a static seed of 0 to n_splits-1 is used to ensure that each fold has a different seed that is consistent across different models.
Note, one can disable this behavior and use a static seed across all folds (similar to the prior implementation via):
TODO:
--- 
One can control the seed behavior via `ag_args_ensemble`:
```python
predictor = TabularPredictor(label="class", path=str("./ag_path")).fit(
train_data=train_data,
hyperparameters={'GBM':{"num_boost_round": 10}},
ag_args_ensemble={"fold_fitting_strategy": 'sequential_local', …
```
> [Tabular] Support different random seeds per fold

- core/tests/unittests/hpo/test_ray_hpo.py
For older versions of `tune` -` tune.report(score=score)` was acceptable but with newer versions params in report need to be wrapped in a dict like:`tune.report({"score": score})`
> Fix usage of report API due to tune upgrade

- docs/install-modules.md
- docs/install.md
- full_install.sh
If the user doesn't have `pip` installed, the current `full_install.sh` source install script will fail even if the user has `uv` installed standalone:
```
$ ./autogluon/full_install.sh
uv could not be found. Installing uv...
/usr/bin/python: No module named pip
```
This PR fixes this by checking if a standalone uv install exists, and if so it will use it without requiring `pip` to be installed.
[Colab example](https://colab.research.google.com/drive/124DXEjBffUCDA9L7L6oq_Tfx31GoiTkp?usp=sharing) of this PR's install script: 
> [install] Use standalone uv in full_install.sh

- docs/tutorials/timeseries/forecasting-model-zoo.md
- timeseries/setup.py
- timeseries/src/autogluon/timeseries/models/__init__.py
- timeseries/src/autogluon/timeseries/models/toto/__init__.py
- timeseries/src/autogluon/timeseries/models/toto/_internal/LICENSE
- timeseries/src/autogluon/timeseries/models/toto/_internal/README.txt
- timeseries/src/autogluon/timeseries/models/toto/_internal/__init__.py
- timeseries/src/autogluon/timeseries/models/toto/_internal/backbone/__init__.py
- timeseries/src/autogluon/timeseries/models/toto/_internal/backbone/attention.py
- timeseries/src/autogluon/timeseries/models/toto/_internal/backbone/backbone.py
- timeseries/src/autogluon/timeseries/models/toto/_internal/backbone/distribution.py
- timeseries/src/autogluon/timeseries/models/toto/_internal/backbone/kvcache.py
- timeseries/src/autogluon/timeseries/models/toto/_internal/backbone/rope.py
- timeseries/src/autogluon/timeseries/models/toto/_internal/backbone/scaler.py
- timeseries/src/autogluon/timeseries/models/toto/_internal/backbone/transformer.py
- timeseries/src/autogluon/timeseries/models/toto/_internal/dataset.py
- timeseries/src/autogluon/timeseries/models/toto/_internal/forecaster.py
- timeseries/src/autogluon/timeseries/models/toto/_internal/model.py
- timeseries/src/autogluon/timeseries/models/toto/dataloader.py
- timeseries/src/autogluon/timeseries/models/toto/hf_pretrained_model.py
- timeseries/src/autogluon/timeseries/models/toto/model.py
- timeseries/tests/smoketests/test_all_models.py
- timeseries/tests/unittests/models/conftest.py
- timeseries/tests/unittests/models/test_toto.py
Add Toto to the model zoo. Apart from very minor changes the code in `_internal/` is from the original [repository](https://github.com/DataDog/toto).
TODOS:
> [timeseries] add Toto model
